<?php
namespace HoseinMomeni\MahexWoo\V36;

use HoseinMomeni\MahexWoo\V33\Access;
use HoseinMomeni\MahexWoo\V33\BoardTools;
use HoseinMomeni\MahexWoo\V34\DispatchWorkbench;
use HoseinMomeni\MahexWoo\V35\LocalHandover;
use HoseinMomeni\MahexWoo\V35\OrderQuality;
use HoseinMomeni\MahexWoo\Shipments\OptionOperationLock;

/** Internal, offline dispatch planning. A wave is not a route, label, carrier status or physical handover. */
final class OfflineDispatchWaves {
 const META='_hm_mahex_v36_waves'; const OPTION='hm_mahex_v36_waves'; const SLUG='hm-mahex-v36-waves';
 const STATES=['draft'=>'پیش‌نویس','published'=>'منتشرشده','in_progress'=>'در اجرا','completed'=>'تکمیل برنامه','cancelled'=>'لغو'];
 const ACTIVE=['draft','published','in_progress']; const LIMIT=200; const HISTORY_LIMIT=250; const SNAPSHOT_LIMIT=20;
 public static function register(): void {add_action('admin_menu',[self::class,'menu'],48);add_action('admin_enqueue_scripts',[self::class,'assets']);add_action('wp_ajax_hm_mahex_v36_waves',[self::class,'ajax']);add_action('admin_post_hm_mahex_v36_wave_export',[self::class,'download']);}
 public static function menu(): void {add_submenu_page('hm-mahex','موج‌های آفلاین ارسال','موج‌های آفلاین',Access::OPERATIONS,self::SLUG,[self::class,'page']);}
 public static function assets(string $hook): void {if(strpos($hook,self::SLUG)===false)return;wp_enqueue_style('hm-mahex-v36-waves',plugins_url('assets/admin/v36-waves.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_enqueue_script('hm-mahex-v36-waves',plugins_url('assets/admin/v36-waves.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_localize_script('hm-mahex-v36-waves','hmWaves',['url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('hm_mahex_v36_waves')]);}
 public static function catalog(): array {$v=get_option(self::OPTION,[]);return is_array($v)?$v:[];}
 public static function meta($order): array {$v=$order->get_meta(self::META,true);return array_merge(['refs'=>[],'waves'=>[]],is_array($v)?$v:[]);}
 public static function text($v,int $min=0,int $max=120): string {if(!is_scalar($v))throw new \InvalidArgumentException('متن معتبر نیست.');$v=trim(strip_tags((string)$v));if(mb_strlen($v)<$min||mb_strlen($v)>$max)throw new \InvalidArgumentException('طول متن خارج از محدوده است.');return $v;}
 public static function integer($v,int $min,int $max): int {if((!is_int($v)&&(!is_string($v)||!ctype_digit($v)))||(int)$v<$min||(int)$v>$max)throw new \InvalidArgumentException('عدد صحیح خارج از محدوده است.');return (int)$v;}
 public static function localDate($v,bool $day=false): string {$format=$day?'Y-m-d':'Y-m-d\TH:i';$v=self::text($v,$day?10:16,$day?10:16);$d=\DateTimeImmutable::createFromFormat('!'.$format,$v,wp_timezone());$e=\DateTimeImmutable::getLastErrors();if(!$d||($e&&($e['warning_count']||$e['error_count']))||$d->format($format)!==$v)throw new \InvalidArgumentException('تاریخ محلی معتبر نیست.');return $d->format('c');}
 public static function id(string $id): string {if(!preg_match('/^[a-f0-9]{24}$/',$id))throw new \InvalidArgumentException('شناسه موج معتبر نیست.');return $id;}
 private static function order(int $id){if(!Access::can('operations',$id)||!($o=wc_get_order($id)))throw new \RuntimeException('سفارش موجود یا قابل دسترسی نیست.');$o->read_meta_data(true);return $o;}
 private static function locked(array $ids,callable $fn){sort($ids,SORT_NUMERIC);$l=new OptionOperationLock();$held=[];try{foreach(array_unique($ids) as $id){if(!$l->acquire($id,120))throw new \RuntimeException('موج یا سفارش در حال ویرایش است.');$held[]=$id;if($id>0)BoardTools::guardOtherEditor($id);}return $fn();}finally{foreach(array_reverse($held) as $id)$l->release($id);}}
 public static function details(array $w): ?array {$o=wc_get_order((int)$w['anchor']);if(!$o)return null;$m=self::meta($o);return isset($m['waves'][$w['id']])&&is_array($m['waves'][$w['id']])?$m['waves'][$w['id']]:null;}
 private static function authorized(array $w): void {if(!Access::can('operations'))throw new \RuntimeException('دسترسی عملیات مجاز نیست.');foreach(array_unique(array_merge([(int)$w['anchor']],array_map('intval',array_keys($w['members'])))) as $id)self::order($id);}
 private static function normalizeCity(string $s): string {$s=str_replace(['ي','ك'],['ی','ک'],$s);$s=preg_replace('/[\x{200c}\x{200d}\s]+/u',' ',trim($s))??trim($s);return mb_strtolower($s);}
 private static function shippingMethod($order): string {$items=$order->get_items('shipping');foreach($items as $item){if(method_exists($item,'get_method_id'))return (string)$item->get_method_id();}return '';}
 private static function qualityBlocked($order): bool {foreach(OrderQuality::scan($order,false)['findings']??[] as $f)if(($f['severity']??'')==='critical'&&($f['state']??'open')==='open')return true;return false;}
 public static function row($order): array {
  $id=(int)$order->get_id();$cargo=LocalHandover::shipment($order);$state=self::text($order->get_shipping_state(),0,80);$city=self::normalizeCity(self::text($order->get_shipping_city(),0,120));$postcode=preg_replace('/\D+/u','',(string)$order->get_shipping_postcode())??'';$prefix=strlen($postcode)>=3?substr($postcode,0,3).'•••••••':'';$status=(string)$order->get_status();$dispatch=DispatchWorkbench::data($order);$items=0;foreach($order->get_items('line_item') as $item)$items+=max(0,(int)$item->get_quantity());$minutes=max(1,min(1440,$items*3+$cargo['parcels']*5));$unknown=[];if(!$cargo['measured'])$unknown[]='weight';if($cargo['parcels']<1)$unknown[]='parcels';if($items<1)$unknown[]='minutes';$cluster=$state.'|'.$city.'|'.substr($postcode,0,3);
	  $created=$order->get_date_created()?$order->get_date_created()->getTimestamp():0;$priority=$dispatch['priority']??'normal';$factors=['priority'=>$priority==='vip'?30:($priority==='urgent'?20:0),'age_days'=>max(0,(int)floor((time()-$created)/86400)),'cluster_complete'=>($state!==''&&$city!=='')?10:0];$score=array_sum($factors);
  $row=['id'=>$id,'number'=>(string)$order->get_order_number(),'status'=>$status,'state'=>$state,'city'=>$city,'postcode_prefix'=>$prefix,'cluster_hash'=>hash('sha256',$cluster),'shipping_method'=>self::shippingMethod($order),'priority'=>$priority,'created'=>$created,'parcels'=>(int)$cargo['parcels'],'weight_g'=>$cargo['measured']?(float)$cargo['weight_g']:null,'minutes'=>$items?$minutes:null,'unknown'=>$unknown,'recommendation'=>['score'=>$score,'factors'=>$factors],'hold'=>!empty($dispatch['hold']),'quality_blocked'=>self::qualityBlocked($order)];$row['fingerprint']=hash('sha256',wp_json_encode(array_diff_key($row,['number'=>1,'postcode_prefix'=>1,'recommendation'=>1])));return $row;
 }
 private static function handoverActive(int $id): bool {return LocalHandover::active(LocalHandover::catalog(),$id);}
 public static function active(array $all,int $oid,string $except=''): bool {foreach($all as $id=>$w)if($id!==$except&&in_array($w['state'],self::ACTIVE,true)&&isset($w['members'][$oid])&&self::details($w)!==null)return true;return false;}
 private static function eligible(array $row,array $all,string $except=''): void {if($row['hold'])throw new \RuntimeException('سفارش توقف داخلی فعال دارد.');if($row['quality_blocked'])throw new \RuntimeException('سفارش یافته کیفیت بحرانی باز دارد.');if(self::handoverActive($row['id']))throw new \RuntimeException('سفارش عضو دفتر تحویل فعال است.');if(self::active($all,$row['id'],$except))throw new \RuntimeException('سفارش عضو موج فعال دیگری است.');}
 public static function totals(array $w): array {$t=['orders'=>count($w['members']),'parcels'=>0,'weight_g'=>0.0,'minutes'=>0,'unknown_orders'=>0];foreach($w['members'] as $r){$t['parcels']+=(int)$r['parcels'];if($r['weight_g']!==null)$t['weight_g']+=(float)$r['weight_g'];if($r['minutes']!==null)$t['minutes']+=(int)$r['minutes'];if($r['unknown'])$t['unknown_orders']++;}$t['weight_g']=round($t['weight_g'],3);return $t;}
 private static function assertCapacity(array $w): void {$t=self::totals($w);if($t['orders']>$w['limits']['orders']||$t['parcels']>$w['limits']['parcels']||$t['weight_g']>$w['limits']['weight_g']||$t['minutes']>$w['limits']['minutes'])throw new \RuntimeException('ظرفیت تعریف‌شده موج کافی نیست.');}
 public static function digest(array $w): string {$rows=[];foreach($w['order'] as $id)$rows[]=['id'=>(int)$id,'fingerprint'=>$w['members'][$id]['fingerprint']];return hash('sha256',wp_json_encode($rows));}
 private static function event(array &$d,string $intent,array $detail=[]): void {if(count($d['history']??[])>=self::HISTORY_LIMIT)throw new \RuntimeException('ظرفیت رویدادهای موج پر شده؛ شواهد قبلی حذف نمی‌شود.');$d['history'][]=['intent'=>$intent,'detail'=>$detail,'actor'=>get_current_user_id(),'at'=>gmdate('c')];}
 private static function persist(array $all,array $w,array $d,array $affected): void {$old=[];$saved=[];try{foreach(array_unique(array_merge([(int)$w['anchor']],array_map('intval',$affected))) as $id){$o=self::order($id);$old[$id]=$o->get_meta(self::META,true);$m=self::meta($o);$m['refs'][$w['id']]=['code'=>$w['code'],'state'=>$w['state'],'revision'=>$w['revision'],'member'=>isset($w['members'][$id])];if(count($m['refs'])>50)throw new \RuntimeException('ظرفیت ۵۰ ارتباط موج سفارش پر شده است.');if($id===$w['anchor'])$m['waves'][$w['id']]=$d;$o->update_meta_data(self::META,$m);if(!$o->save())throw new \RuntimeException('ذخیره سفارش موفق نشد.');$saved[]=$id;}$all[$w['id']]=$w;if(!update_option(self::OPTION,$all,false))throw new \RuntimeException('ذخیره فهرست موج‌ها موفق نشد.');}catch(\Throwable $e){foreach($saved as $id){$o=wc_get_order($id);if(!$o)continue;if($old[$id]==='')$o->delete_meta_data(self::META);else $o->update_meta_data(self::META,$old[$id]);$o->save();}throw $e;}}
 public static function create(array $p): array {if(!Access::can('operations'))throw new \RuntimeException('دسترسی مجاز نیست.');$oid=self::integer($p['order_id']??0,1,PHP_INT_MAX);return self::locked([-3601,$oid],static function()use($p,$oid){$all=self::catalog();if(count($all)>=self::LIMIT)throw new \RuntimeException('ظرفیت ۲۰۰ موج پر شده است.');$o=self::order($oid);$r=self::row($o);self::eligible($r,$all);$start=self::localDate($p['start']??'');$end=self::localDate($p['end']??'');if(strtotime($end)<=strtotime($start))throw new \InvalidArgumentException('پایان باید بعد از شروع باشد.');$id=bin2hex(random_bytes(12));$w=['id'=>$id,'code'=>'MW36-'.strtoupper(substr($id,0,12)),'anchor'=>$oid,'state'=>'draft','revision'=>1,'created_at'=>gmdate('c'),'updated_at'=>gmdate('c'),'members'=>[$oid=>$r],'order'=>[$oid],'limits'=>['orders'=>self::integer($p['orders']??50,1,200),'parcels'=>self::integer($p['parcels']??100,1,500),'weight_g'=>self::integer($p['weight_g']??100000,1,5000000),'minutes'=>self::integer($p['minutes']??480,1,1440)],'threshold'=>self::integer($p['threshold']??85,70,100),'snapshot_version'=>0];self::assertCapacity($w);$d=['title'=>self::text($p['title']??'',3,120),'day'=>self::localDate($p['day']??'',true),'start'=>$start,'end'=>$end,'origin_id'=>self::text($p['origin_id']??'',1,40),'origin_label'=>self::text($p['origin_label']??'',3,120),'note'=>self::text($p['note']??'',0,1000),'unknown_ack'=>[],'history'=>[],'snapshots'=>[]];self::event($d,'create',['order_id'=>$oid]);self::persist($all,$w,$d,[$oid]);return self::get($id);});}
 public static function drifts(array $w): array {$out=[];foreach($w['order'] as $id){try{$now=self::row(self::order((int)$id));if(!hash_equals($w['members'][$id]['fingerprint'],$now['fingerprint']))$out[$id]=['before'=>$w['members'][$id]['fingerprint'],'after'=>$now['fingerprint']];}catch(\Throwable $e){$out[$id]=['error'=>$e->getMessage()];}}return $out;}
 public static function get(string $id): array {$id=self::id($id);$w=self::catalog()[$id]??null;if(!$w)throw new \RuntimeException('موج وجود ندارد.');self::authorized($w);$d=self::details($w);$rows=[];foreach($w['order'] as $oid){$r=$w['members'][$oid];$r['changed']=isset(self::drifts($w)[$oid]);$rows[]=$r;}return array_merge($w,['details'=>$d,'redacted'=>$d===null,'rows'=>$rows,'totals'=>self::totals($w),'digest'=>self::digest($w),'drifts'=>self::drifts($w)]);}
 public static function listing(): array {$out=[];foreach(self::catalog() as $id=>$w)try{$g=self::get($id);$out[]=['id'=>$id,'code'=>$w['code'],'state'=>$w['state'],'revision'=>$w['revision'],'title'=>$g['details']['title']??'اطلاعات پاک‌شده','day'=>$g['details']['day']??'','totals'=>$g['totals']];}catch(\Throwable $e){}return array_reverse($out);}
 public static function candidates(array $filters=[]): array {if(!Access::can('operations'))throw new \RuntimeException('دسترسی مجاز نیست.');$statuses=$filters['statuses']??['processing','on-hold'];if(!is_array($statuses)||!$statuses)$statuses=['processing'];$allowed=['pending','processing','on-hold','completed'];$statuses=array_values(array_intersect(array_map('sanitize_key',$statuses),$allowed));$after=!empty($filters['after'])?strtotime(self::localDate($filters['after'])):0;$before=!empty($filters['before'])?strtotime(self::localDate($filters['before'])):PHP_INT_MAX;$rows=[];foreach(wc_get_orders(['limit'=>100,'status'=>$statuses,'orderby'=>'date','order'=>'DESC']) as $o){if(!Access::can('operations',$o->get_id()))continue;try{$r=self::row($o);$r['eligible']=true;$r['blockers']=[];try{self::eligible($r,self::catalog());}catch(\Throwable $e){$r['eligible']=false;$r['blockers'][]=$e->getMessage();}if($r['created']<$after||$r['created']>$before)continue;if(!empty($filters['shipping_method'])&&$r['shipping_method']!==$filters['shipping_method'])continue;if(!empty($filters['priority'])&&$r['priority']!==$filters['priority'])continue;$rows[]=$r;}catch(\Throwable $e){}}usort($rows,static function($a,$b){$p=['vip'=>0,'urgent'=>1,'normal'=>2];return [$p[$a['priority']]??3,$a['created'],$a['cluster_hash'],$a['id']]<=>[$p[$b['priority']]??3,$b['created'],$b['cluster_hash'],$b['id']];});return $rows;}
 public static function mutate(string $id,int $revision,string $intent,array $p=[]): array {$id=self::id($id);$old=self::catalog()[$id]??null;if(!$old)throw new \RuntimeException('موج وجود ندارد.');self::authorized($old);$ids=array_merge([-3601],array_map('intval',array_keys($old['members'])));if(isset($p['order_id']))$ids[]=self::integer($p['order_id'],1,PHP_INT_MAX);return self::locked($ids,static function()use($id,$revision,$intent,$p){$all=self::catalog();$w=$all[$id]??null;if(!$w||(int)$w['revision']!==$revision)throw new \RuntimeException('نسخه موج تغییر کرده؛ تازه‌سازی کنید.');$d=self::details($w);if(!$d)throw new \RuntimeException('داده خصوصی پاک شده؛ موج فقط خواندنی است.');if(in_array($w['state'],['completed','cancelled'],true))throw new \RuntimeException('موج نهایی فقط خواندنی است.');$affected=array_keys($w['members']);$detail=[];
 if(in_array($intent,['add','remove','reorder'],true)){if($w['state']!=='draft')throw new \RuntimeException('عضویت فقط در پیش‌نویس تغییر می‌کند.');if($intent==='reorder'){$order=$p['order']??[];if(!is_array($order)||count($order)!==count($w['members']))throw new \InvalidArgumentException('ترتیب معتبر نیست.');$order=array_map('intval',$order);if(count(array_unique($order))!==count($order)||array_diff($order,array_keys($w['members'])))throw new \InvalidArgumentException('ترتیب باید همه اعضا را یک‌بار داشته باشد.');$w['order']=$order;$detail=['order'=>$order];}else{$oid=self::integer($p['order_id']??0,1,PHP_INT_MAX);$affected[]=$oid;if($intent==='remove'){if(!isset($w['members'][$oid]))throw new \InvalidArgumentException('سفارش عضو نیست.');$note=self::text($p['note']??'',3,200);unset($w['members'][$oid],$d['unknown_ack'][$oid]);$w['order']=array_values(array_diff($w['order'],[$oid]));$detail=['order_id'=>$oid,'note'=>$note];}else{if(isset($w['members'][$oid]))throw new \InvalidArgumentException('سفارش قبلاً عضو است.');$r=self::row(self::order($oid));self::eligible($r,$all,$id);$w['members'][$oid]=$r;$w['order'][]=$oid;self::assertCapacity($w);$detail=['order_id'=>$oid];}}}
 elseif($intent==='ack_unknown'){if($w['state']!=='draft')throw new \RuntimeException('تأیید داده فقط در پیش‌نویس است.');$oid=self::integer($p['order_id']??0,1,PHP_INT_MAX);if(empty($w['members'][$oid]['unknown']))throw new \InvalidArgumentException('داده نامعلومی وجود ندارد.');$reason=self::text($p['note']??'',3,300);$d['unknown_ack'][$oid]=['reason'=>$reason,'actor'=>get_current_user_id(),'at'=>gmdate('c')];$detail=['order_id'=>$oid,'note'=>$reason];}
 elseif($intent==='publish'){if($w['state']!=='draft'||!$w['members'])throw new \RuntimeException('فقط پیش‌نویس دارای عضو منتشر می‌شود.');self::assertCapacity($w);foreach($w['members'] as $oid=>$r){self::eligible(self::row(self::order((int)$oid)),$all,$id);if($r['unknown']&&empty($d['unknown_ack'][$oid]))throw new \RuntimeException('داده نامعلوم تأیید نشده است.');}if(count($d['snapshots'])>=self::SNAPSHOT_LIMIT)throw new \RuntimeException('سقف ۲۰ نسخه snapshot پر شده است.');$w['state']='published';$w['snapshot_version']++;$d['snapshots'][]=['version'=>$w['snapshot_version'],'digest'=>self::digest($w),'totals'=>self::totals($w),'order'=>$w['order'],'at'=>gmdate('c'),'actor'=>get_current_user_id()];$detail=['snapshot_version'=>$w['snapshot_version'],'digest'=>self::digest($w)];}
 elseif($intent==='refresh'){if(!in_array($w['state'],['published'],true))throw new \RuntimeException('بازبینی رانش فقط برای موج منتشرشده است.');$note=self::text($p['note']??'',3,300);if(!self::drifts($w))throw new \RuntimeException('رانشی برای پذیرش نیست.');if(count($d['snapshots'])>=self::SNAPSHOT_LIMIT)throw new \RuntimeException('سقف snapshot پر شده است.');foreach(array_keys($w['members']) as $oid){$r=self::row(self::order((int)$oid));self::eligible($r,$all,$id);$w['members'][$oid]=$r;}$w['snapshot_version']++;$d['snapshots'][]=['version'=>$w['snapshot_version'],'digest'=>self::digest($w),'totals'=>self::totals($w),'order'=>$w['order'],'at'=>gmdate('c'),'actor'=>get_current_user_id(),'reason'=>$note];$detail=['note'=>$note,'snapshot_version'=>$w['snapshot_version']];}
 elseif($intent==='start'){if($w['state']!=='published'||self::drifts($w))throw new \RuntimeException('موج منتشرشده بدون رانش برای اجرا لازم است.');$w['state']='in_progress';}
 elseif($intent==='complete'){if($w['state']!=='in_progress'||self::drifts($w))throw new \RuntimeException('موج در اجرا و بدون رانش لازم است.');$w['state']='completed';}
 elseif($intent==='cancel'){$note=self::text($p['note']??'',3,300);$w['state']='cancelled';$detail=['note'=>$note];}
 elseif($intent==='note'){$d['note']=self::text($p['note']??'',0,1000);$detail=['note'=>$d['note']];}
 else throw new \InvalidArgumentException('عملیات موج مجاز نیست.');self::event($d,$intent,$detail);$w['revision']++;$w['updated_at']=gmdate('c');self::persist($all,$w,$d,$affected);return self::get($id);});}
 public static function export(string $id): array {$g=self::get($id);return ['schema'=>'mahex-offline-dispatch-wave/1','carrier_route_verified'=>false,'physical_execution_verified'=>false,'code'=>$g['code'],'state'=>$g['state'],'revision'=>$g['revision'],'snapshot_version'=>$g['snapshot_version'],'snapshot_hash'=>$g['digest'],'title'=>$g['details']['title']??'','day'=>$g['details']['day']??'','origin'=>$g['details']['origin_label']??'','members'=>array_map(static fn($r)=>['order_id'=>$r['id'],'order_number'=>$r['number'],'parcels'=>$r['parcels'],'weight_g'=>$r['weight_g'],'minutes'=>$r['minutes'],'cluster_hash'=>$r['cluster_hash']],$g['rows']),'totals'=>$g['totals']];}
 public static function privacy($order): array {$id=(int)$order->get_id();$m=self::meta($order);$out=['refs'=>$m['refs'],'waves'=>[]];foreach($m['refs'] as $wid=>$ref){$w=self::catalog()[$wid]??null;if(!$w)continue;$d=self::details($w);if(!$d)continue;$events=[];foreach($d['history'] as $e)if((int)($e['detail']['order_id']??0)===$id)$events[]=$e;$out['waves'][$wid]=['code'=>$w['code'],'state'=>$w['state'],'member'=>$w['members'][$id]??null,'events'=>$events];}return $out;}
 public static function eraseOrder(int $oid): int {return self::locked([-3601],static function()use($oid){$all=self::catalog();$ids=[];$anchors=[];foreach($all as $id=>$w)if($w['anchor']===$oid||isset($w['members'][$oid])){$ids[]=$id;$anchors[]=$w['anchor'];}foreach(array_unique($anchors) as $anchor){$o=wc_get_order($anchor);if(!$o)continue;$m=self::meta($o);foreach($ids as $id)unset($m['waves'][$id]);$o->update_meta_data(self::META,$m);$o->save();}return count($ids);});}
 public static function ajax(): void {if(!check_ajax_referer('hm_mahex_v36_waves','nonce',false)||!Access::can('operations'))wp_send_json_error(['message'=>'دسترسی مجاز نیست.'],403);try{$intent=sanitize_key(wp_unslash($_POST['intent']??''));$raw=wp_unslash($_POST['payload']??'{}');if(!is_string($raw)||strlen($raw)>32000)throw new \InvalidArgumentException('داده بیش از حد بزرگ است.');$p=json_decode($raw,true);if(!is_array($p))throw new \InvalidArgumentException('JSON معتبر نیست.');if($intent==='list')$r=['waves'=>self::listing(),'candidates'=>self::candidates($p)];elseif($intent==='get')$r=['wave'=>self::get((string)($p['id']??''))];elseif($intent==='create')$r=['wave'=>self::create($p),'waves'=>self::listing()];elseif($intent==='mutate')$r=['wave'=>self::mutate((string)($p['id']??''),(int)($p['revision']??0),(string)($p['operation']??''),(array)($p['values']??[])),'waves'=>self::listing()];else throw new \InvalidArgumentException('عملیات ناشناخته است.');wp_send_json_success($r);}catch(\Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],409);}}
 public static function download(): void {if(!Access::can('operations'))wp_die('دسترسی مجاز نیست.','',['response'=>403]);check_admin_referer('hm_mahex_v36_wave_export');$id=self::id((string)($_GET['wave']??''));$format=sanitize_key((string)($_GET['format']??'json'));$data=self::export($id);nocache_headers();if($format==='csv'){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$data['code'].'.csv"');$f=fopen('php://output','w');fwrite($f,"\xEF\xBB\xBF");fputcsv($f,['order_id','order_number','parcels','weight_g','minutes','cluster_hash']);foreach($data['members'] as $r)fputcsv($f,$r);fclose($f);}else{header('Content-Type: application/json; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$data['code'].'.json"');echo wp_json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);}exit;}
 public static function page(): void {if(!Access::can('operations'))return;$initial=['waves'=>self::listing(),'candidates'=>self::candidates(),'states'=>self::STATES,'export_nonce'=>wp_create_nonce('hm_mahex_v36_wave_export')];echo '<div class="wrap hmx-waves" dir="rtl"><h1>برنامه‌ریز آفلاین موج‌های ارسال</h1><p class="hmx-waves-note">ابزار برنامه‌ریزی داخلی با داده واقعی سفارش؛ ترتیب پیشنهادی مسیر واقعی، زمان سفر، بارنامه یا تأیید شرکت حمل نیست و هیچ API بیرونی فراخوانی نمی‌شود.</p><p data-wave-status role="status" aria-live="polite"></p><form data-wave-create><input name="order_id" type="number" min="1" required placeholder="شناسه سفارش آغازگر"><input name="title" minlength="3" maxlength="120" required placeholder="عنوان موج"><input name="day" type="date" required><input name="start" type="datetime-local" required><input name="end" type="datetime-local" required><input name="origin_id" maxlength="40" required placeholder="کد مبدا داخلی"><input name="origin_label" minlength="3" maxlength="120" required placeholder="عنوان مبدا"><input name="orders" type="number" min="1" max="200" value="50" required><input name="parcels" type="number" min="1" max="500" value="100" required><input name="weight_g" type="number" min="1" max="5000000" value="100000" required><input name="minutes" type="number" min="1" max="1440" value="480" required><input name="threshold" type="number" min="70" max="100" value="85" required><button class="button button-primary">ساخت موج</button></form><div class="hmx-wave-toolbar"><input data-wave-search type="search" placeholder="جست‌وجوی شماره سفارش"><button type="button" class="button" data-wave-refresh>تازه‌سازی</button></div><div class="hmx-wave-layout"><nav data-wave-list aria-label="موج‌ها"></nav><main data-wave-detail></main><aside><h2>نامزدها</h2><div data-wave-candidates aria-label="نامزدهای قابل کشیدن"></div></aside></div><script type="application/json" data-wave-data>'.wp_json_encode($initial,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP).'</script></div>';}
}
