<?php
namespace HoseinMomeni\MahexWoo\V36;

use HoseinMomeni\MahexWoo\V33\Access;

/** Local QA sampling. All inspection results are explicit human observations. */
final class QualitySampling {
 const OPTION='hm_mahex_v36_quality_campaigns';
 const SLUG='hm-mahex-v36-sampling';
 const NONCE='hm_mahex_v36_sampling';
 const STATES=['draft','active','review','closed','cancelled'];
 const LANES=['pending','inspecting','rework','review','released'];
 const DISPOSITIONS=['pass','rework','quarantine','escalate'];
 const ANSWERS=['pass','fail','not_applicable'];
 const SAMPLE_MODES=['fixed','percent','interval','risk'];
 const DEFAULT_TEMPLATE=[
  ['code'=>'identity','title'=>'تطبیق شناسه سفارش با برگه بسته','severity'=>'critical','weight'=>5],
  ['code'=>'contents','title'=>'تطبیق دستی محتویات و تعداد','severity'=>'critical','weight'=>5],
  ['code'=>'closure','title'=>'سلامت بست و درزهای بسته','severity'=>'warning','weight'=>3],
  ['code'=>'protection','title'=>'کفایت محافظ و پرکننده','severity'=>'warning','weight'=>2],
  ['code'=>'label','title'=>'خوانایی برچسب محلی','severity'=>'warning','weight'=>2],
 ];
 const DEFAULT_DEFECTS=[
  'wrong_item'=>['title'=>'قلم یا تعداد نادرست','severity'=>'critical','active'=>true],
  'open_seam'=>['title'=>'بست یا درز نامطمئن','severity'=>'warning','active'=>true],
  'weak_protection'=>['title'=>'محافظ ناکافی','severity'=>'warning','active'=>true],
  'unreadable_label'=>['title'=>'برچسب ناخوانا','severity'=>'warning','active'=>true],
 ];

 public static function register(): void {add_action('admin_menu',[self::class,'menu'],49);add_action('admin_enqueue_scripts',[self::class,'assets']);add_action('wp_ajax_hm_mahex_v36_sampling',[self::class,'ajax']);add_action('admin_post_hm_mahex_v36_sampling_export',[self::class,'download']);add_action('admin_post_hm_mahex_v36_sampling_print',[self::class,'printSheet']);}
 public static function menu(): void {add_submenu_page('hm-mahex','نمونه‌برداری کیفیت بسته‌بندی','نمونه‌برداری کیفیت',Access::OPERATIONS,self::SLUG,[self::class,'page']);}
 public static function assets(string $hook): void {if(strpos($hook,self::SLUG)===false)return;wp_enqueue_style('hm-v36-sampling',plugins_url('assets/admin/v36-sampling.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_enqueue_script('hm-v36-sampling',plugins_url('assets/admin/v36-sampling.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_localize_script('hm-v36-sampling','hmSampling',['url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce(self::NONCE)]);}
 public static function catalog(): array {$v=get_option(self::OPTION,[]);return is_array($v)?$v:[];}
 public static function canView(int $orderId=0): bool {return Access::can('operations',$orderId)||Access::can('packing',$orderId);}
 public static function canInspect(int $orderId=0): bool {return Access::can('packing',$orderId)||current_user_can('manage_woocommerce');}
 public static function canManage(): bool {return current_user_can('manage_woocommerce');}
 public static function text($v,int $min=0,int $max=1000): string {if(!is_scalar($v))throw new \InvalidArgumentException('متن معتبر نیست.');$v=trim(strip_tags((string)$v));if(mb_strlen($v)<$min||mb_strlen($v)>$max)throw new \InvalidArgumentException('طول متن معتبر نیست.');return $v;}
 public static function integer($v,int $min,int $max): int {if((!is_int($v)&&(!is_string($v)||!ctype_digit($v)))||(int)$v<$min||(int)$v>$max)throw new \InvalidArgumentException('عدد صحیح معتبر نیست.');return (int)$v;}
 public static function id(string $v): string {if(!preg_match('/^[a-f0-9]{24}$/',$v))throw new \InvalidArgumentException('شناسه کمپین معتبر نیست.');return $v;}
 public static function code(string $v): string {$v=strtolower(trim($v));if(!preg_match('/^[a-z][a-z0-9_-]{1,39}$/',$v))throw new \InvalidArgumentException('کد عیب معتبر نیست.');return $v;}
 public static function dateUtc($v,bool $end=false): string {$s=self::text($v,10,25);try{$d=new \DateTimeImmutable($s,new \DateTimeZone('UTC'));}catch(\Throwable $e){throw new \InvalidArgumentException('تاریخ معتبر نیست.');}return $d->setTimezone(new \DateTimeZone('UTC'))->format('c');}
 public static function hash($v): string {return hash('sha256',json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
 public static function template(array $rows): array {if(!$rows||count($rows)>30)throw new \InvalidArgumentException('الگوی بازرسی معتبر نیست.');$out=[];foreach($rows as $r){$code=self::code((string)($r['code']??''));if(isset($out[$code]))throw new \InvalidArgumentException('کد معیار تکراری است.');$severity=(string)($r['severity']??'warning');if(!in_array($severity,['info','warning','critical'],true))throw new \InvalidArgumentException('شدت معتبر نیست.');$out[$code]=['code'=>$code,'title'=>self::text($r['title']??'',3,120),'severity'=>$severity,'weight'=>self::integer($r['weight']??1,1,10)];}return array_values($out);}
 public static function defects(array $rows): array {$out=[];foreach($rows as $key=>$r){$code=self::code(is_string($key)?$key:(string)($r['code']??''));if(isset($out[$code]))throw new \InvalidArgumentException('کد عیب تکراری است.');$severity=(string)($r['severity']??'warning');if(!in_array($severity,['info','warning','critical'],true))throw new \InvalidArgumentException('شدت عیب معتبر نیست.');$out[$code]=['title'=>self::text($r['title']??'',3,120),'severity'=>$severity,'active'=>!empty($r['active'])];}if(count($out)>100)throw new \InvalidArgumentException('حداکثر ۱۰۰ کد عیب مجاز است.');return $out;}
 public static function orderSnapshot($order): array {$shipping=[];foreach($order->get_items('shipping') as $item)$shipping[]=(string)$item->get_method_id();$items=[];$virtual=true;foreach($order->get_items() as $id=>$item){$p=$item->get_product();if($p&&!$p->is_virtual())$virtual=false;$items[]=[(int)$id,(int)$item->get_product_id(),(float)$item->get_quantity()];}$created=$order->get_date_created();return ['order_id'=>(int)$order->get_id(),'version'=>(string)$order->get_version(),'status'=>(string)$order->get_status(),'created'=>$created?$created->getTimestamp():0,'shipping'=>array_values(array_unique($shipping)),'virtual'=>$virtual,'refunded'=>(float)$order->get_total()>0&&(float)$order->get_total_refunded()>=(float)$order->get_total(),'station'=>(string)$order->get_meta('_hm_mahex_station_id',true),'materials'=>(array)$order->get_meta('_hm_mahex_material_usage',true),'fingerprint'=>self::hash([$order->get_status(),$items,$shipping])];}
 public static function eligible(array $snap,array $settings): array {if($snap['virtual'])return [false,'virtual'];if(in_array($snap['status'],['cancelled','refunded','failed'],true)||$snap['refunded'])return [false,'inactive'];$from=strtotime($settings['from']);$to=strtotime($settings['to']);if($snap['created']<$from||$snap['created']>$to)return [false,'date'];if($settings['statuses']&&!in_array($snap['status'],$settings['statuses'],true))return [false,'status'];if($settings['methods']&&!array_intersect($settings['methods'],$snap['shipping']))return [false,'method'];return [true,''];}
 public static function population(array $settings): array {$ids=wc_get_orders(['limit'=>self::integer($settings['population_limit'],1,1000),'return'=>'ids','date_created'=>strtotime($settings['from']).'...'.strtotime($settings['to']),'orderby'=>'ID','order'=>'ASC']);$ok=[];$excluded=[];foreach($ids as $id){$o=wc_get_order($id);if(!$o||!self::canView((int)$id))continue;$s=self::orderSnapshot($o);[$yes,$why]=self::eligible($s,$settings);if($yes)$ok[(int)$id]=$s;else $excluded[(int)$id]=$why;}return [$ok,$excluded];}
 /** Deterministic local sampler; risk is a stored local score, never a carrier signal. */
 public static function select(array $population,string $mode,int $value,string $seed): array {if(!in_array($mode,self::SAMPLE_MODES,true))throw new \InvalidArgumentException('روش نمونه‌گیری معتبر نیست.');if(!$population)return [];$rows=array_values($population);usort($rows,static fn($a,$b)=>strcmp(self::hash([$seed,$a['order_id']]),self::hash([$seed,$b['order_id']])));$n=count($rows);if($mode==='fixed')$take=min($n,$value);elseif($mode==='percent')$take=min($n,max(1,(int)ceil($n*$value/100)));elseif($mode==='interval'){$out=[];foreach($rows as $i=>$r)if($i%$value===0)$out[]=$r;return $out;}else {usort($rows,static fn($a,$b)=>(int)($b['risk']??0)<=>(int)($a['risk']??0)?:$a['order_id']<=>$b['order_id']);$take=min($n,$value);}return array_slice($rows,0,$take);}
 public static function baseSettings(array $p): array {$statuses=array_values(array_unique(array_filter((array)($p['statuses']??[]),'is_string')));foreach($statuses as $s)if(!array_key_exists($s,wc_get_order_statuses())&&!array_key_exists('wc-'.$s,wc_get_order_statuses()))throw new \InvalidArgumentException('وضعیت سفارش ناشناخته است.');$methods=array_values(array_unique(array_map(static fn($v)=>self::text($v,1,80),(array)($p['methods']??[]))));$from=self::dateUtc($p['from']??'');$to=self::dateUtc($p['to']??'');if(strtotime($to)<strtotime($from))throw new \InvalidArgumentException('پایان بازه پیش از آغاز است.');$mode=(string)($p['mode']??'fixed');$value=self::integer($p['value']??1,1,$mode==='percent'?100:1000);return ['from'=>$from,'to'=>$to,'statuses'=>$statuses,'methods'=>$methods,'mode'=>$mode,'value'=>$value,'seed'=>self::text($p['seed']??'',3,80),'sample_cap'=>self::integer($p['sample_cap']??100,1,500),'population_limit'=>self::integer($p['population_limit']??500,1,1000),'overlap'=>in_array(($p['overlap']??''),['deny','warn'],true)?$p['overlap']:'warn','minimum_station_sample'=>self::integer($p['minimum_station_sample']??5,1,1000),'target_rate'=>min(100,max(0,(float)($p['target_rate']??5)))];}
 private static function event(array &$c,string $intent,array $detail=[]): void {if(count($c['history'])>=500)throw new \RuntimeException('ظرفیت تاریخچه کمپین پر شده است.');$c['history'][]=['intent'=>$intent,'detail'=>$detail,'actor'=>get_current_user_id(),'at'=>gmdate('c')];}
 private static function save(array $all,array $c): void {$all[$c['id']]=$c;if(!update_option(self::OPTION,$all,false))throw new \RuntimeException('ذخیره کمپین موفق نشد.');}
 public static function create(array $p,?array $suppliedPopulation=null): array {if(!self::canManage())throw new \RuntimeException('مدیریت کمپین مجاز نیست.');$all=self::catalog();if(count($all)>=100)throw new \RuntimeException('ظرفیت ۱۰۰ کمپین پر است.');$settings=self::baseSettings($p);[$population,$excluded]=$suppliedPopulation===null?self::population($settings):[$suppliedPopulation,[]];$chosen=self::select($population,$settings['mode'],$settings['value'],$settings['seed']);if(count($chosen)>$settings['sample_cap'])$chosen=array_slice($chosen,0,$settings['sample_cap']);$id=bin2hex(random_bytes(12));$members=[];foreach($chosen as $s){$oid=(int)$s['order_id'];if(self::activeMembership($oid,$all)&&$settings['overlap']==='deny')continue;$members[$oid]=['order_id'=>$oid,'snapshot'=>$s,'source'=>'sample','source_reason'=>'','lane'=>'pending','answers'=>[],'defects'=>[],'inspections'=>[],'disposition'=>'','quarantine'=>null,'revision'=>1,'updated_at'=>gmdate('c')];}$template=self::template($p['template']??self::DEFAULT_TEMPLATE);$c=['id'=>$id,'code'=>'MHQA-'.strtoupper(substr($id,0,12)),'name'=>self::text($p['name']??'',3,120),'purpose'=>self::text($p['purpose']??'',3,500),'state'=>'draft','revision'=>1,'created_at'=>gmdate('c'),'updated_at'=>gmdate('c'),'settings'=>$settings,'population_fingerprint'=>self::hash(array_map(static fn($s)=>[$s['order_id'],$s['fingerprint']],$population)),'population_count'=>count($population),'excluded'=>$excluded,'template_version'=>1,'template'=>$template,'defects'=>self::defects($p['defects']??self::DEFAULT_DEFECTS),'members'=>$members,'history'=>[]];self::event($c,'create',['members'=>count($members),'population'=>count($population)]);self::save($all,$c);return $c;}
 public static function get(string $id): array {$id=self::id($id);$c=self::catalog()[$id]??null;if(!$c)throw new \RuntimeException('کمپین وجود ندارد.');if(!self::canView())throw new \RuntimeException('دسترسی مجاز نیست.');foreach($c['members'] as $oid=>$m)if(!self::canView((int)$oid))throw new \RuntimeException('دسترسی یکی از سفارش‌ها مجاز نیست.');$c['summary']=self::summary($c);$c['drift']=self::drift($c);return $c;}
 public static function activeMembership(int $orderId,?array $all=null,string $except=''): bool {foreach($all??self::catalog() as $id=>$c)if($id!==$except&&!in_array($c['state'],['closed','cancelled'],true)&&isset($c['members'][$orderId]))return true;return false;}
 public static function drift(array $c): array {$out=[];foreach($c['members'] as $oid=>$m){$o=wc_get_order((int)$oid);if(!$o){$out[$oid]='missing';continue;}$now=self::orderSnapshot($o);if(!hash_equals($m['snapshot']['fingerprint'],$now['fingerprint'])||$m['snapshot']['status']!==$now['status'])$out[$oid]='changed';}return $out;}
 public static function mutate(string $id,int $revision,string $intent,array $p=[]): array {$all=self::catalog();$c=$all[self::id($id)]??null;if(!$c)throw new \RuntimeException('کمپین وجود ندارد.');if($c['revision']!==$revision)throw new \RuntimeException('نسخه کمپین تغییر کرده است.');if(in_array($c['state'],['closed','cancelled'],true))throw new \RuntimeException('کمپین نهایی فقط خواندنی است.');if(in_array($intent,['add','remove','regenerate','activate','cancel','close','defects'],true)&&!self::canManage())throw new \RuntimeException('مدیریت کمپین مجاز نیست.');$detail=[];
  if($intent==='activate'){if($c['state']!=='draft'||!$c['members'])throw new \RuntimeException('پیش‌نویس دارای عضو لازم است.');$c['state']='active';$c['locked_at']=gmdate('c');$c['locked_template']=self::hash($c['template']);}
  elseif($intent==='cancel'){$reason=self::text($p['reason']??'',3,500);$c['state']='cancelled';$detail=['reason'=>$reason];}
  elseif($intent==='close'){if(!in_array($c['state'],['active','review'],true))throw new \RuntimeException('کمپین فعال یا بازبینی لازم است.');foreach($c['members'] as $m)if($m['lane']!=='released')throw new \RuntimeException('همه اعضا باید تعیین تکلیف شوند.');$c['state']='closed';$detail=['summary'=>self::summary($c)];}
  elseif($intent==='add'||$intent==='remove'){if($c['state']!=='draft')throw new \RuntimeException('عضویت پس از قفل تغییر نمی‌کند.');$oid=self::integer($p['order_id']??0,1,PHP_INT_MAX);$reason=self::text($p['reason']??'',3,500);if($intent==='remove'){if(!isset($c['members'][$oid]))throw new \RuntimeException('سفارش عضو نیست.');unset($c['members'][$oid]);}else {$o=wc_get_order($oid);if(!$o||!self::canView($oid))throw new \RuntimeException('سفارش موجود یا قابل دسترسی نیست.');if(isset($c['members'][$oid]))throw new \RuntimeException('سفارش عضو است.');if(self::activeMembership($oid,$all,$id)&&$c['settings']['overlap']==='deny')throw new \RuntimeException('هم‌پوشانی کمپین ممنوع است.');$s=self::orderSnapshot($o);$c['members'][$oid]=['order_id'=>$oid,'snapshot'=>$s,'source'=>'manual','source_reason'=>$reason,'lane'=>'pending','answers'=>[],'defects'=>[],'inspections'=>[],'disposition'=>'','quarantine'=>null,'revision'=>1,'updated_at'=>gmdate('c')];}$detail=['order_id'=>$oid,'reason'=>$reason];}
  elseif($intent==='regenerate'){if($c['state']!=='draft')throw new \RuntimeException('بازنمونه‌گیری فقط در پیش‌نویس است.');$old=['population_fingerprint'=>$c['population_fingerprint'],'members'=>array_keys($c['members']),'seed'=>$c['settings']['seed']];$c['settings']['seed']=self::text($p['seed']??'',3,80);[$population,$excluded]=self::population($c['settings']);$chosen=array_slice(self::select($population,$c['settings']['mode'],$c['settings']['value'],$c['settings']['seed']),0,$c['settings']['sample_cap']);$c['members']=[];foreach($chosen as $s)$c['members'][$s['order_id']]=['order_id'=>$s['order_id'],'snapshot'=>$s,'source'=>'sample','source_reason'=>'','lane'=>'pending','answers'=>[],'defects'=>[],'inspections'=>[],'disposition'=>'','quarantine'=>null,'revision'=>1,'updated_at'=>gmdate('c')];$c['population_fingerprint']=self::hash(array_map(static fn($s)=>[$s['order_id'],$s['fingerprint']],$population));$c['population_count']=count($population);$c['excluded']=$excluded;$detail=['previous'=>$old];}
  elseif($intent==='defects'){if($c['state']!=='draft')throw new \RuntimeException('واژه‌نامه پس از قفل تغییر نمی‌کند.');$c['defects']=self::defects($p['defects']??[]);$c['template_version']++;}
  else throw new \InvalidArgumentException('عملیات کمپین معتبر نیست.');
  $c['revision']++;$c['updated_at']=gmdate('c');self::event($c,$intent,$detail);self::save($all,$c);return $c;}
 public static function inspect(string $id,int $campaignRevision,int $orderId,int $memberRevision,array $answers,array $defects,string $disposition,string $observation,bool $human,bool $blind=false): array {$all=self::catalog();$c=$all[self::id($id)]??null;if(!$c||$c['revision']!==$campaignRevision)throw new \RuntimeException('نسخه کمپین تغییر کرده است.');if($c['state']!=='active')throw new \RuntimeException('کمپین فعال نیست.');if(!self::canInspect($orderId)||!isset($c['members'][$orderId]))throw new \RuntimeException('بازرسی مجاز نیست.');$m=$c['members'][$orderId];if($m['revision']!==$memberRevision)throw new \RuntimeException('نسخه عضو تغییر کرده است.');if(!$human)throw new \InvalidArgumentException('تأیید مشاهده فیزیکی دستی لازم است.');$observation=self::text($observation,3,1000);$normalized=[];$critical=false;foreach($c['template'] as $criterion){$a=$answers[$criterion['code']]??null;if(!in_array($a,self::ANSWERS,true))throw new \InvalidArgumentException('پاسخ همه معیارها لازم است.');$note=self::text($answers[$criterion['code'].'_note']??'',0,500);if(($a==='fail'||$a==='not_applicable')&&$note==='')throw new \InvalidArgumentException('شکست و نامرتبط نیازمند توضیح است.');if($a==='fail'&&$criterion['severity']==='critical')$critical=true;$normalized[$criterion['code']]=['answer'=>$a,'note'=>$note,'severity'=>$criterion['severity'],'weight'=>$criterion['weight']];}$defectRows=[];foreach(array_unique($defects) as $code){$code=self::code($code);if(empty($c['defects'][$code]['active']))throw new \InvalidArgumentException('کد عیب فعال نیست.');$defectRows[$code]=$c['defects'][$code];if($c['defects'][$code]['severity']==='critical')$critical=true;}if(!in_array($disposition,self::DISPOSITIONS,true))throw new \InvalidArgumentException('تصمیم معتبر نیست.');if($critical&&$disposition==='pass')throw new \RuntimeException('شکست بحرانی قابل پذیرش مستقیم نیست.');$record=['id'=>bin2hex(random_bytes(8)),'actor'=>get_current_user_id(),'at'=>gmdate('c'),'human_observation'=>true,'observation'=>$observation,'answers'=>$normalized,'defects'=>$defectRows,'disposition'=>$disposition,'template_version'=>$c['template_version'],'blind'=>$blind,'second_review'=>null];$m['inspections'][]=$record;$m['answers']=$normalized;$m['defects']=$defectRows;$m['disposition']=$disposition;$m['lane']=$disposition==='pass'?'released':($disposition==='rework'?'rework':'review');$m['quarantine']=$disposition==='quarantine'?['open'=>true,'critical'=>$critical,'actor'=>$record['actor'],'at'=>$record['at'],'reason'=>$observation,'released_by'=>0]:null;$m['revision']++;$m['updated_at']=gmdate('c');$c['members'][$orderId]=$m;$c['revision']++;self::event($c,'inspect',['order_id'=>$orderId,'inspection'=>$record['id'],'disposition'=>$disposition,'critical'=>$critical]);self::save($all,$c);return $c;}
 public static function move(string $id,int $campaignRevision,int $orderId,int $memberRevision,string $lane,string $reason=''): array {$all=self::catalog();$c=$all[self::id($id)]??null;if(!$c||$c['revision']!==$campaignRevision)throw new \RuntimeException('نسخه کمپین تغییر کرده است.');if(!isset($c['members'][$orderId])||!self::canInspect($orderId))throw new \RuntimeException('جابه‌جایی مجاز نیست.');if(!in_array($lane,self::LANES,true))throw new \InvalidArgumentException('ستون معتبر نیست.');$m=$c['members'][$orderId];if($m['revision']!==$memberRevision)throw new \RuntimeException('نسخه کارت تغییر کرده است.');$allowed=['pending'=>['inspecting'],'inspecting'=>['pending','rework','review','released'],'rework'=>['inspecting','review'],'review'=>['rework','released'],'released'=>['review']];if(!in_array($lane,$allowed[$m['lane']]??[],true))throw new \RuntimeException('گذار برد مجاز نیست.');if($lane==='released'&&self::memberQuarantined($m))throw new \RuntimeException('عضو قرنطینه‌شده آزاد نمی‌شود.');if(in_array($lane,['review','released'],true)&&!$m['inspections'])throw new \RuntimeException('بازرسی ثبت‌شده لازم است.');if($reason!=='')$reason=self::text($reason,3,500);$from=$m['lane'];$m['lane']=$lane;$m['revision']++;$m['updated_at']=gmdate('c');$c['members'][$orderId]=$m;$c['revision']++;self::event($c,'move',['order_id'=>$orderId,'from'=>$from,'to'=>$lane,'reason'=>$reason]);self::save($all,$c);return $c;}
 public static function secondReview(string $id,int $revision,int $orderId,bool $release,string $reason): array {$all=self::catalog();$c=$all[self::id($id)]??null;if(!$c||$c['revision']!==$revision)throw new \RuntimeException('نسخه کمپین تغییر کرده است.');if(!self::canManage()||!isset($c['members'][$orderId]))throw new \RuntimeException('بازبینی دوم مجاز نیست.');$m=$c['members'][$orderId];$last=end($m['inspections']);if(!$last||$last['actor']===get_current_user_id())throw new \RuntimeException('بازبین دوم باید کاربر متفاوت باشد.');$reason=self::text($reason,3,500);$review=['actor'=>get_current_user_id(),'at'=>gmdate('c'),'release'=>$release,'reason'=>$reason];$m['inspections'][count($m['inspections'])-1]['second_review']=$review;if($release&&self::memberQuarantined($m)){$m['quarantine']['open']=false;$m['quarantine']['released_by']=$review['actor'];$m['quarantine']['released_at']=$review['at'];$m['quarantine']['release_reason']=$reason;$m['lane']='released';}$m['revision']++;$c['members'][$orderId]=$m;$c['revision']++;self::event($c,'second_review',['order_id'=>$orderId,'release'=>$release,'reason'=>$reason]);self::save($all,$c);return $c;}
 public static function memberQuarantined(array $m): bool {return !empty($m['quarantine']['open']);}
 public static function hasOpenQuarantine(int $orderId): bool {foreach(self::catalog() as $c)if(!in_array($c['state'],['cancelled'],true)&&isset($c['members'][$orderId])&&self::memberQuarantined($c['members'][$orderId]))return true;return false;}
 public static function assertNoQuarantine(int $orderId): void {if(self::hasOpenQuarantine($orderId))throw new \RuntimeException('این سفارش در تضمین کیفیت بسته‌بندی قرنطینه است.');}
 public static function summary(array $c): array {$s=['members'=>count($c['members']),'lanes'=>array_fill_keys(self::LANES,0),'inspected'=>0,'failed'=>0,'quarantined'=>0,'defects'=>[],'score_total'=>0,'score_denominator'=>0];foreach($c['members'] as $m){$s['lanes'][$m['lane']]++;if($m['inspections'])$s['inspected']++;if(self::memberQuarantined($m))$s['quarantined']++;foreach($m['answers'] as $a)if($a['answer']!=='not_applicable'){$s['score_denominator']+=$a['weight'];if($a['answer']==='fail'){$s['failed']++;$s['score_total']+=$a['weight'];}}foreach($m['defects'] as $code=>$d)$s['defects'][$code]=($s['defects'][$code]??0)+1;}arsort($s['defects']);$s['defect_rate']=$s['score_denominator']?round(100*$s['score_total']/$s['score_denominator'],2):0;$total=max(1,array_sum($s['defects']));$cum=0;$s['pareto']=[];foreach($s['defects'] as $code=>$count){$cum+=$count;$s['pareto'][]=['code'=>$code,'count'=>$count,'cumulative_percent'=>round(100*$cum/$total,2)];}$s['threshold_exceeded']=$s['defect_rate']>(float)$c['settings']['target_rate'];return $s;}
 public static function analytics(array $campaigns): array {$weeks=[];$stations=[];$materials=[];foreach($campaigns as $c){if($c['state']!=='closed')continue;foreach($c['members'] as $m){foreach($m['inspections'] as $inspection){$week=gmdate('o-\WW',strtotime($inspection['at']));$key=$week.':v'.$inspection['template_version'];$weeks[$key]['inspections']=($weeks[$key]['inspections']??0)+1;$fails=count(array_filter($inspection['answers'],static fn($a)=>$a['answer']==='fail'));$weeks[$key]['failures']=($weeks[$key]['failures']??0)+$fails;}$station=$m['snapshot']['station']?:'unassigned';$stations[$station]['sample']=($stations[$station]['sample']??0)+($m['inspections']?1:0);$stations[$station]['defects']=($stations[$station]['defects']??0)+count($m['defects']);foreach($m['snapshot']['materials'] as $material=>$qty)$materials[$material]['observations'][]=['quantity'=>$qty,'defects'=>count($m['defects'])];}}return ['weeks'=>$weeks,'stations'=>$stations,'materials'=>$materials,'causality_claimed'=>false];}
 public static function csv(array $c): string {$fp=fopen('php://temp','r+');fputcsv($fp,['campaign','order_id','lane','disposition','inspection_count','defect_codes','human_observation']);foreach($c['members'] as $m)fputcsv($fp,[$c['code'],$m['order_id'],$m['lane'],$m['disposition'],count($m['inspections']),implode('|',array_keys($m['defects'])),$m['inspections']?'yes':'no']);rewind($fp);$out=stream_get_contents($fp);fclose($fp);return $out;}
 public static function privacyForUser(int $userId): array {$out=[];foreach(self::catalog() as $c){$events=array_values(array_filter($c['history'],static fn($e)=>(int)$e['actor']===$userId));$inspections=[];foreach($c['members'] as $m)foreach($m['inspections'] as $i)if((int)$i['actor']===$userId||((int)($i['second_review']['actor']??0)===$userId))$inspections[]=['order_id'=>$m['order_id'],'inspection'=>$i];if($events||$inspections)$out[]=['campaign'=>$c['id'],'events'=>$events,'inspections'=>$inspections];}return $out;}
 public static function eraseUser(int $userId): int {$all=self::catalog();$changed=0;foreach($all as &$c){foreach($c['history'] as &$e)if((int)$e['actor']===$userId){$e['actor']=0;$changed++;}unset($e);foreach($c['members'] as &$m){if((int)($m['quarantine']['actor']??0)===$userId){$m['quarantine']['actor']=0;$changed++;}if((int)($m['quarantine']['released_by']??0)===$userId){$m['quarantine']['released_by']=0;$changed++;}foreach($m['inspections'] as &$i){if((int)$i['actor']===$userId){$i['actor']=0;$changed++;}if((int)($i['second_review']['actor']??0)===$userId){$i['second_review']['actor']=0;$changed++;}}unset($i);}unset($m);}unset($c);if($changed&&!update_option(self::OPTION,$all,false))throw new \RuntimeException('ناشناس‌سازی داده کاربر موفق نشد.');return $changed;}
 public static function ajax(): void {if(!check_ajax_referer(self::NONCE,'nonce',false)||!self::canView())wp_send_json_error(['message'=>'دسترسی مجاز نیست.'],403);try{$raw=$_POST['payload']??'';if(!is_string($raw)||strlen($raw)>50000)throw new \InvalidArgumentException('درخواست بیش از حد مجاز است.');$p=json_decode(wp_unslash($raw),true);if(!is_array($p))throw new \InvalidArgumentException('درخواست نامعتبر است.');$intent=(string)($p['intent']??'');if($intent==='inspect')$r=self::inspect((string)$p['id'],(int)$p['revision'],(int)$p['order_id'],(int)$p['member_revision'],(array)$p['answers'],(array)$p['defects'],(string)$p['disposition'],(string)$p['observation'],!empty($p['human']),!empty($p['blind']));elseif($intent==='move')$r=self::move((string)$p['id'],(int)$p['revision'],(int)$p['order_id'],(int)$p['member_revision'],(string)$p['lane'],(string)($p['reason']??''));elseif($intent==='second_review')$r=self::secondReview((string)$p['id'],(int)$p['revision'],(int)$p['order_id'],!empty($p['release']),(string)$p['reason']);else $r=self::mutate((string)$p['id'],(int)$p['revision'],$intent,(array)($p['data']??[]));wp_send_json_success(['revision'=>$r['revision'],'reload'=>true]);}catch(\Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],409);}}
 public static function download(): void {check_admin_referer(self::NONCE);$c=self::get((string)($_GET['campaign']??''));nocache_headers();header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="mahex-qa-'.$c['code'].'.csv"');echo "\xEF\xBB\xBF".self::csv($c);exit;}
 public static function printSheet(): void {check_admin_referer(self::NONCE);$c=self::get((string)($_GET['campaign']??''));echo '<!doctype html><html dir="rtl" lang="fa"><meta charset="utf-8"><title>'.esc_html($c['code']).'</title><style>body{font-family:Tahoma;margin:2cm}article{break-inside:avoid;border:1px solid #777;padding:12px;margin:12px}li{line-height:2}</style><h1>برگه بازرسی دستی '.esc_html($c['code']).'</h1><p><strong>این برگه تا ورود دستی در سامانه ثبت‌شده محسوب نمی‌شود.</strong></p>';foreach($c['members'] as $m){echo '<article><h2>سفارش #'.(int)$m['order_id'].'</h2><ol>';foreach($c['template'] as $criterion)echo '<li>'.esc_html($criterion['title']).' □ قبول □ رد □ نامرتبط</li>';echo '</ol><p>یادداشت: ....................................................................</p><p>نام و امضا: ........................ تاریخ: ................</p></article>';}echo '<script>window.print()</script>';exit;}
 public static function page(): void {if(!self::canView())wp_die('دسترسی مجاز نیست.','',['response'=>403]);$id=(string)($_GET['campaign']??'');echo '<div class="wrap hm-v36-sampling" dir="rtl"><h1>کمپین نمونه‌برداری کیفیت بسته‌بندی</h1><p class="notice notice-info">نتایج فقط مشاهده فیزیکی دستی کاربران مجاز است؛ هیچ دستگاه، API ماهکس، webhook یا تأیید شرکت حمل وجود ندارد.</p>';if(!$id){echo '<div class="hqs-list">';foreach(array_reverse(self::catalog()) as $c)echo '<a class="hqs-campaign" href="'.esc_url(add_query_arg(['page'=>self::SLUG,'campaign'=>$c['id']],admin_url('admin.php'))).'"><b>'.esc_html($c['name']).'</b><span>'.esc_html($c['code']).' · '.esc_html($c['state']).' · '.count($c['members']).' سفارش</span></a>';echo '</div></div>';return;}$c=self::get($id);$s=$c['summary'];echo '<header class="hqs-head"><div><h2>'.esc_html($c['name']).'</h2><p>'.esc_html($c['purpose']).'</p></div><div><b>'.esc_html($c['code']).'</b><br>نسخه '.(int)$c['revision'].' · '.esc_html($c['state']).'</div></header><nav><a class="button" href="'.esc_url(wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v36_sampling_export','campaign'=>$c['id']],admin_url('admin-post.php')),self::NONCE)).'">CSV کم‌داده</a> <a class="button" target="_blank" href="'.esc_url(wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v36_sampling_print','campaign'=>$c['id']],admin_url('admin-post.php')),self::NONCE)).'">برگه چاپ آفلاین</a></nav><section class="hqs-metrics"><b>'.$s['inspected'].' بازرسی‌شده</b><b>'.$s['quarantined'].' قرنطینه باز</b><b>'.$s['defect_rate'].'٪ نرخ وزنی</b><b>'.($s['threshold_exceeded']?'عبور از هدف داخلی':'در محدوده هدف').'</b></section><div class="hqs-filter"><label>جست‌وجوی شناسه سفارش <input type="search" data-hqs-search></label><label>ستون <select data-hqs-lane><option value="">همه</option>';foreach(self::LANES as $lane)echo '<option value="'.$lane.'">'.$lane.'</option>';echo '</select></label></div><p data-hqs-live aria-live="polite"></p><div class="hqs-board" data-campaign="'.esc_attr($c['id']).'" data-revision="'.$c['revision'].'">';foreach(self::LANES as $lane){echo '<section class="hqs-lane" data-lane="'.$lane.'"><h3>'.$lane.' <span>'.$s['lanes'][$lane].'</span></h3><div class="hqs-drop" data-drop="'.$lane.'">';foreach($c['members'] as $m)if($m['lane']===$lane){echo '<article class="hqs-card" draggable="true" tabindex="0" data-order="'.$m['order_id'].'" data-member-revision="'.$m['revision'].'" data-lane="'.$lane.'"><b>سفارش #'.$m['order_id'].'</b><small>'.esc_html($m['disposition']?:'بدون تصمیم').'</small>';if(self::memberQuarantined($m))echo '<strong class="hqs-quarantine">قرنطینه باز</strong>';echo '<label>انتقال با صفحه‌کلید <select data-hqs-move><option value="">انتخاب ستون</option>';foreach(self::LANES as $to)echo '<option value="'.$to.'">'.$to.'</option>';echo '</select></label></article>';}echo '</div></section>';}echo '</div></div>';}
}
