<?php
namespace HoseinMomeni\MahexWoo\V35;

use HoseinMomeni\MahexWoo\V33\Access;
use HoseinMomeni\MahexWoo\V33\BoardTools;
use HoseinMomeni\MahexWoo\V33\Station;
use HoseinMomeni\MahexWoo\V33\Support;
use HoseinMomeni\MahexWoo\V32\Packing;
use HoseinMomeni\MahexWoo\V34\DispatchWorkbench;
use HoseinMomeni\MahexWoo\Shipments\OptionOperationLock;

/** A local multi-order custody journal. It never changes or infers carrier status. */
final class LocalHandover {
 const META='_hm_mahex_v35_handover';
 const OPTION='hm_mahex_v35_handovers';
 const SLUG='hm-mahex-v35-handover';
 const STATES=['draft'=>'پیش‌نویس','sealed'=>'پلمب دفتر','dispatched'=>'خروج ثبت‌شده','closed'=>'بسته','cancelled'=>'لغو'];
 const CONDITIONS=['intact'=>'سالم','damaged'=>'آسیب بسته','short'=>'کسری','refused'=>'نپذیرفته'];
 const ROUTES=['branch'=>'انتقال داخلی شعبه','driver'=>'تحویل دستی راننده','pickup'=>'جمع‌آوری دستی'];
 public static function register(): void {add_action('admin_menu',[self::class,'menu'],49);add_action('admin_enqueue_scripts',[self::class,'assets']);add_action('wp_ajax_hm_mahex_v35_handover',[self::class,'ajax']);add_action('admin_post_hm_mahex_v35_handover_export',[self::class,'download']);add_action('woocommerce_admin_order_data_after_shipping_address',[self::class,'orderLink']);}
 public static function menu(): void {add_submenu_page('hm-mahex','دفتر تحویل گروهی محلی','تحویل گروهی محلی',Access::OPERATIONS,self::SLUG,[self::class,'page']);}
 public static function assets(string $hook): void {if(strpos($hook,self::SLUG)===false)return;wp_enqueue_style('hm-mahex-v35-handover',plugins_url('assets/admin/v35-handover.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_enqueue_script('hm-mahex-v35-handover',plugins_url('assets/admin/v35-handover.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_localize_script('hm-mahex-v35-handover','hmHandover',['url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('hm_mahex_v35_handover')]);}
 public static function orderLink($order): void {if(!Access::can('operations',$order->get_id()))return;$d=self::meta($order);foreach($d['refs'] as $id=>$ref)echo '<p><a href="'.esc_url(add_query_arg(['page'=>self::SLUG,'group'=>$id],admin_url('admin.php'))).'">دفتر گروهی '.esc_html($ref['code']).' — '.esc_html(self::STATES[$ref['state']]??$ref['state']).'</a></p>';}
 public static function catalog(): array {$d=get_option(self::OPTION,[]);return is_array($d)?$d:[];}
 public static function meta($order): array {$d=$order->get_meta(self::META,true);return array_merge(['refs'=>[],'groups'=>[]],is_array($d)?$d:[]);}
 public static function text($value,int $min=0,int $max=120): string {if(!is_scalar($value))throw new \InvalidArgumentException('متن معتبر نیست.');$s=trim(strip_tags((string)$value));if(mb_strlen($s)<$min||mb_strlen($s)>$max)throw new \InvalidArgumentException('طول متن باید بین '.$min.' و '.$max.' نویسه باشد.');return $s;}
 public static function integer($value,int $min,int $max): int {if((!is_int($value)&&(!is_string($value)||!ctype_digit($value)))||(int)$value<$min||(int)$value>$max)throw new \InvalidArgumentException('عدد صحیح خارج از محدوده است.');return (int)$value;}
 public static function groupId(string $id): string {if(!preg_match('/^[a-f0-9]{24}$/',$id))throw new \InvalidArgumentException('شناسه دفتر معتبر نیست.');return $id;}
 public static function localDate($raw): string {$s=self::text($raw,16,16);$d=\DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$s,wp_timezone());$e=\DateTimeImmutable::getLastErrors();if(!$d||($e&&($e['warning_count']||$e['error_count']))||$d->format('Y-m-d\TH:i')!==$s)throw new \InvalidArgumentException('تاریخ محلی معتبر نیست.');return $d->format('c');}
 public static function authorized(array $g): void {if(!Access::can('operations'))throw new \RuntimeException('دسترسی عملیات مجاز نیست.');foreach(array_unique(array_merge([$g['anchor']],array_keys($g['members']))) as $id)if(!Access::can('operations',(int)$id)||!wc_get_order((int)$id))throw new \RuntimeException('یکی از سفارش‌های دفتر موجود یا قابل دسترسی نیست.');}
 public static function details(array $g): ?array {$order=wc_get_order($g['anchor']);if(!$order)return null;$d=self::meta($order);return isset($d['groups'][$g['id']])&&is_array($d['groups'][$g['id']])?$d['groups'][$g['id']]:null;}
 /** No recipient names/phones/addresses or monetary values enter the central option. */
 public static function shipment($order): array {$plan=Packing::snapshot($order);if(!$plan||empty($plan['boxes']))throw new \RuntimeException('طرح بسته‌بندی معتبر برای سفارش لازم است.');$station=Station::data($order);$weight=0;$complete=true;$parcels=[];foreach($plan['boxes'] as $i=>$box){$p=$station['parcels'][$i]??[];$w=(float)($p['weight_g']??0);$dims=$p['dimensions_mm']??[];if(!is_array($dims)||!is_finite($w)||$w<=0||count($dims)!==3)$complete=false;else {foreach($dims as $dimension)if(!is_numeric($dimension)||!is_finite((float)$dimension)||(float)$dimension<=0)$complete=false;$weight+=$w;}$parcels[]=['weight_g'=>$w,'dimensions_mm'=>$dims];}$fp=hash('sha256',wp_json_encode(['address'=>DispatchWorkbench::address($order),'plan'=>$plan['boxes'],'items'=>Packing::fingerprint(Packing::units($order)),'parcels'=>$parcels]));return ['fingerprint'=>$fp,'parcels'=>count($plan['boxes']),'weight_g'=>round($weight,3),'measured'=>$complete];}
 public static function active(array $all,int $orderId,string $except=''): bool {foreach($all as $id=>$g)if($id!==$except&&!in_array($g['state'],['closed','cancelled'],true)&&isset($g['members'][$orderId])&&self::details($g)!==null)return true;return false;}
 /** Privacy erasure redacts the whole private journal, including non-anchor receipt copies. */
 public static function eraseOrder(int $orderId): int {return self::locked([-3501],static function()use($orderId){$all=self::catalog();$order=wc_get_order($orderId);$refs=$order?array_keys(self::meta($order)['refs']):[];$anchors=[];$groupIds=[];foreach($all as $id=>$g)if($g['anchor']===$orderId||isset($g['members'][$orderId])||in_array($id,$refs,true)){$groupIds[]=$id;$anchors[]=$g['anchor'];}if(!$groupIds)return 0;return self::locked(array_merge([$orderId],$anchors),static function()use($anchors,$groupIds){$count=0;foreach(array_unique($anchors) as $anchor){$o=wc_get_order($anchor);if(!$o)continue;$o->read_meta_data(true);$d=self::meta($o);$changed=false;foreach($groupIds as $id)if(isset($d['groups'][$id])){unset($d['groups'][$id]);$changed=true;$count++;}if($changed){$o->update_meta_data(self::META,$d);if(!$o->save())throw new \RuntimeException('پاک‌سازی اطلاعات خصوصی دفتر موفق نشد.');}}return $count;});});}
 public static function totals(array $g): array {$parcels=0;$weight=0;$received=0;$reviewed=0;$exceptions=0;$incomplete=0;foreach($g['members'] as $r){$parcels+=$r['parcels'];$weight+=$r['weight_g'];if(!$r['measured'])$incomplete++;if(isset($r['receipt'])){$reviewed++;if($r['receipt']['condition']!=='refused')$received+=$r['receipt']['accepted'];if($r['receipt']['condition']!=='intact'||$r['receipt']['accepted']!==$r['parcels'])$exceptions++;}}return ['orders'=>count($g['members']),'parcels'=>$parcels,'weight_g'=>round($weight,3),'received_parcels'=>$received,'reviewed_orders'=>$reviewed,'exceptions'=>$exceptions,'unmeasured_orders'=>$incomplete];}
 public static function digest(array $g): string {$rows=[];foreach($g['order'] as $id)$rows[]=['id'=>$id,'fingerprint'=>$g['members'][$id]['fingerprint'],'parcels'=>$g['members'][$id]['parcels'],'weight_g'=>$g['members'][$id]['weight_g']];return hash('sha256',wp_json_encode($rows));}
 public static function event(array &$d,string $intent,array $detail=[]): void {if(count($d['history']??[])>=200)throw new \RuntimeException('ظرفیت ۲۰۰ رویداد این دفتر پر شده؛ دفتر جدید ایجاد کنید.');$d['history'][]=['intent'=>$intent,'detail'=>$detail,'actor'=>get_current_user_id(),'at'=>gmdate('c')];}
 private static function order(int $id) {if(!Access::can('operations',$id)||!($o=wc_get_order($id)))throw new \RuntimeException('سفارش موجود یا قابل دسترسی نیست.');$o->read_meta_data(true);return $o;}
 private static function locked(array $ids,callable $run) {sort($ids,SORT_NUMERIC);$lock=new OptionOperationLock();$held=[];try{foreach(array_unique($ids) as $id){if(!$lock->acquire($id,120))throw new \RuntimeException('دفتر یا سفارش در حال ویرایش است.');$held[]=$id;if($id>0)BoardTools::guardOtherEditor($id);}return $run();}finally{foreach(array_reverse($held) as $id)$lock->release($id);}}
 /** Metadata is rolled back if the authoritative catalog write fails. */
 private static function persist(array $all,array $g,array $details,array $affected): void {$old=[];$saved=[];try{foreach(array_unique(array_merge([$g['anchor']],$affected)) as $id){$o=self::order((int)$id);$old[$id]=$o->get_meta(self::META,true);$d=self::meta($o);$d['refs'][$g['id']]=['code'=>$g['code'],'state'=>$g['state'],'revision'=>$g['revision'],'member'=>isset($g['members'][$id])];if(count($d['refs'])>50){foreach($d['refs'] as $k=>$r)if($k!==$g['id']&&in_array($r['state'],['closed','cancelled'],true)){unset($d['refs'][$k],$d['groups'][$k]);if(count($d['refs'])<=50)break;}if(count($d['refs'])>50)throw new \RuntimeException('ظرفیت دفترهای فعال سفارش پر شده است.');}if($id===$g['anchor'])$d['groups'][$g['id']]=$details;$o->update_meta_data(self::META,$d);if(!$o->save())throw new \RuntimeException('ذخیره ارتباط سفارش موفق نشد.');$saved[]=$id;}$all[$g['id']]=$g;if(!update_option(self::OPTION,$all,false))throw new \RuntimeException('ذخیره دفتر در پایگاه داده موفق نشد.');}catch(\Throwable $e){foreach($saved as $id){$o=wc_get_order((int)$id);if($o){if($old[$id]==='')$o->delete_meta_data(self::META);else $o->update_meta_data(self::META,$old[$id]);$o->save();}}throw $e;}}
 public static function create(array $p): array {if(!Access::can('operations'))throw new \RuntimeException('دسترسی مجاز نیست.');$orderId=self::integer($p['order_id']??0,1,PHP_INT_MAX);return self::locked([-3501,$orderId],static function()use($p,$orderId){$all=self::catalog();if(count($all)>=200)throw new \RuntimeException('ظرفیت ۲۰۰ دفتر پر شده؛ برای جلوگیری از حذف شواهد دفتر قبلی پاک نمی‌شود.');if(self::active($all,$orderId))throw new \RuntimeException('سفارش عضو دفتر فعال دیگری است.');$o=self::order($orderId);$row=self::shipment($o);$capacity=self::integer($p['capacity']??200,1,200);if($row['parcels']>$capacity)throw new \InvalidArgumentException('تعداد بسته بیش از ظرفیت دفتر است.');$route=self::text($p['route']??'branch');if(!isset(self::ROUTES[$route]))throw new \InvalidArgumentException('نوع مسیر معتبر نیست.');$start=self::localDate($p['start']??'');$end=self::localDate($p['end']??'');if(strtotime($end)<=strtotime($start))throw new \InvalidArgumentException('پایان پنجره باید بعد از شروع باشد.');$id=bin2hex(random_bytes(12));$g=['id'=>$id,'code'=>'MH35-'.strtoupper(substr($id,0,12)),'anchor'=>$orderId,'state'=>'draft','revision'=>1,'created_at'=>gmdate('c'),'updated_at'=>gmdate('c'),'members'=>[$orderId=>$row],'order'=>[$orderId],'capacity'=>$capacity];$d=['title'=>self::text($p['title']??'',3),'origin'=>self::text($p['origin']??'',3),'destination'=>self::text($p['destination']??'',3),'route'=>$route,'vehicle'=>self::text($p['vehicle']??'',0,40),'start'=>$start,'end'=>$end,'seal'=>'','custodian'=>'','receipts'=>[],'history'=>[]];self::event($d,'create',['order_id'=>$orderId]);self::persist($all,$g,$d,[$orderId]);return self::get($id);});}
 public static function get(string $id): array {$id=self::groupId($id);$g=self::catalog()[$id]??null;if(!$g)throw new \RuntimeException('دفتر وجود ندارد.');self::authorized($g);$d=self::details($g);$rows=[];foreach($g['order'] as $orderId){$o=self::order($orderId);$r=$g['members'][$orderId];try{$now=self::shipment($o);$r['changed']=!hash_equals($r['fingerprint'],$now['fingerprint']);}catch(\Throwable $e){$r['changed']=true;}$r['id']=$orderId;$r['number']=$o->get_order_number();$r['receipt_details']=$d['receipts'][$orderId]??null;$rows[]=$r;}return array_merge($g,['details'=>$d,'redacted'=>$d===null,'rows'=>$rows,'totals'=>self::totals($g),'digest'=>self::digest($g)]);}
 public static function listing(): array {if(!Access::can('operations'))throw new \RuntimeException('دسترسی مجاز نیست.');$rows=[];foreach(self::catalog() as $id=>$g){try{$v=self::get($id);$rows[]=['id'=>$id,'code'=>$g['code'],'state'=>$g['state'],'revision'=>$g['revision'],'updated_at'=>$g['updated_at'],'title'=>$v['details']['title']??'اطلاعات پاک‌شده','destination'=>$v['details']['destination']??'','totals'=>$v['totals'],'redacted'=>$v['redacted']];}catch(\Throwable $e){}}usort($rows,static fn($a,$b)=>strcmp($b['updated_at'],$a['updated_at']));return $rows;}
 public static function mutate(string $id,int $revision,string $intent,array $p=[]): array {$id=self::groupId($id);$existing=self::catalog()[$id]??null;if(!$existing)throw new \RuntimeException('دفتر وجود ندارد.');self::authorized($existing);$ids=array_merge([-3501,$existing['anchor']],array_keys($existing['members']));if(in_array($intent,['add','refresh','remove','receive'],true))$ids[]=self::integer($p['order_id']??0,1,PHP_INT_MAX);return self::locked($ids,static function()use($id,$revision,$intent,$p){$all=self::catalog();$g=$all[$id]??null;if(!$g||(int)$g['revision']!==$revision)throw new \RuntimeException('نسخه دفتر تغییر کرده؛ تازه‌سازی کنید.');self::authorized($g);$d=self::details($g);if(!$d)throw new \RuntimeException('اطلاعات شخصی دفتر پاک شده؛ دفتر فقط خواندنی است.');if(in_array($g['state'],['closed','cancelled'],true))throw new \RuntimeException('دفتر نهایی فقط خواندنی است.');$affected=array_keys($g['members']);$detail=[];$note='';
  if(in_array($intent,['add','remove','refresh','reorder'],true)){if($g['state']!=='draft')throw new \RuntimeException('عضویت فقط در پیش‌نویس قابل تغییر است.');
   if($intent==='reorder'){$order=$p['order']??[];if(!is_array($order)||count($order)!==count($g['members']))throw new \InvalidArgumentException('ترتیب اعضا معتبر نیست.');$order=array_map(static fn($v)=>self::integer($v,1,PHP_INT_MAX),$order);if(count(array_unique($order))!==count($order)||array_diff($order,array_keys($g['members'])))throw new \InvalidArgumentException('ترتیب باید همه اعضا را یک بار داشته باشد.');$g['order']=$order;$detail=['order'=>$order];}
   else {$oid=self::integer($p['order_id']??0,1,PHP_INT_MAX);$o=self::order($oid);$affected[]=$oid;if($intent==='remove'){if(!isset($g['members'][$oid]))throw new \InvalidArgumentException('سفارش عضو دفتر نیست.');$note=self::text($p['note']??'',3,1000);unset($g['members'][$oid],$d['receipts'][$oid]);$g['order']=array_values(array_diff($g['order'],[$oid]));}
    else {if($intent==='add'&&isset($g['members'][$oid]))throw new \InvalidArgumentException('سفارش قبلاً عضو است.');if($intent==='refresh'&&!isset($g['members'][$oid]))throw new \InvalidArgumentException('سفارش عضو نیست.');if(self::active($all,$oid,$id))throw new \RuntimeException('سفارش عضو دفتر فعال دیگری است.');if($intent==='refresh')$note=self::text($p['note']??'',3,1000);$g['members'][$oid]=self::shipment($o);if($intent==='add')$g['order'][]=$oid;if(self::totals($g)['parcels']>$g['capacity'])throw new \InvalidArgumentException('بسته‌ها بیش از ظرفیت دفتر هستند.');}$detail=['order_id'=>$oid,'note'=>$note];}}
  elseif($intent==='seal'){if($g['state']!=='draft'||!$g['members'])throw new \RuntimeException('فقط پیش‌نویس دارای عضو قابل پلمب است.');foreach($g['members'] as $oid=>$r){$o=self::order((int)$oid);DispatchWorkbench::assertReady($o);$now=self::shipment($o);if(!$now['measured'])throw new \RuntimeException('وزن و ابعاد تمام بسته‌ها لازم است.');if(!hash_equals($r['fingerprint'],$now['fingerprint']))throw new \RuntimeException('محموله عضو تغییر کرده؛ بازثبت با دلیل لازم است.');}$d['seal']=self::text($p['seal']??'',3,40);$g['state']='sealed';$g['sealed_digest']=self::digest($g);$g['sealed_revision']=$g['revision']+1;$detail=['seal'=>$d['seal'],'digest'=>$g['sealed_digest']];}
  elseif($intent==='unseal'){if($g['state']!=='sealed')throw new \RuntimeException('فقط دفتر پلمب شده پیش از خروج باز می‌شود.');$note=self::text($p['note']??'',3,1000);$detail=['previous_seal'=>$d['seal'],'note'=>$note];$g['state']='draft';$d['seal']='';unset($g['sealed_digest'],$g['sealed_revision']);}
  elseif($intent==='dispatch'){if($g['state']!=='sealed')throw new \RuntimeException('دفتر باید ابتدا پلمب شود.');foreach($g['members'] as $oid=>$r){$o=self::order((int)$oid);DispatchWorkbench::assertReady($o);if(!hash_equals($r['fingerprint'],self::shipment($o)['fingerprint']))throw new \RuntimeException('محموله پس از پلمب تغییر کرده؛ دفتر را باز کنید.');}$d['custodian']=self::text($p['receiver']??'',3);$reference=self::text($p['reference']??'',3,80);$g['state']='dispatched';$detail=['to'=>$d['custodian'],'reference'=>$reference,'place'=>$d['origin']];}
  elseif($intent==='transfer'){if($g['state']!=='dispatched')throw new \RuntimeException('انتقال نگهداری فقط پس از خروج است.');$to=self::text($p['receiver']??'',3);if($to===$d['custodian'])throw new \InvalidArgumentException('نگهدارنده جدید باید متفاوت باشد.');$detail=['from'=>$d['custodian'],'to'=>$to,'place'=>self::text($p['place']??'',3),'note'=>self::text($p['note']??'',3,1000)];$d['custodian']=$to;}
  elseif($intent==='receive'){if($g['state']!=='dispatched')throw new \RuntimeException('رسید عضو فقط پس از خروج ثبت می‌شود.');$oid=self::integer($p['order_id']??0,1,PHP_INT_MAX);if(!isset($g['members'][$oid]))throw new \InvalidArgumentException('سفارش عضو دفتر نیست.');$accepted=self::integer($p['accepted']??-1,0,$g['members'][$oid]['parcels']);$condition=self::text($p['condition']??'');if(!isset(self::CONDITIONS[$condition])||($condition==='refused'&&$accepted!==0))throw new \InvalidArgumentException('وضعیت یا شمار پذیرش معتبر نیست.');$note=self::text($p['note']??'',0,1000);$mismatch=$accepted!==$g['members'][$oid]['parcels']||$condition!=='intact';if($mismatch&&mb_strlen($note)<3)throw new \InvalidArgumentException('مغایرت توضیح لازم دارد.');$correction='';if(isset($g['members'][$oid]['receipt']))$correction=self::text($p['correction_reason']??'',3,1000);$receipt=['receiver'=>self::text($p['receiver']??'',3),'reference'=>self::text($p['reference']??'',3,80),'note'=>$note,'at'=>gmdate('c'),'actor'=>get_current_user_id()];$detail=['order_id'=>$oid,'accepted'=>$accepted,'condition'=>$condition,'correction_reason'=>$correction,'previous'=>$d['receipts'][$oid]??null,'previous_result'=>$g['members'][$oid]['receipt']??null,'receipt'=>$receipt];$g['members'][$oid]['receipt']=['accepted'=>$accepted,'condition'=>$condition];$d['receipts'][$oid]=$receipt;}
  elseif($intent==='close'){if($g['state']!=='dispatched'||self::totals($g)['reviewed_orders']!==count($g['members']))throw new \RuntimeException('همه اعضا باید نتیجه بررسی دریافت داشته باشند.');$note=self::text($p['note']??'',self::totals($g)['exceptions']?3:0,1000);$g['state']='closed';$detail=['note'=>$note,'exceptions'=>self::totals($g)['exceptions']];}
  elseif($intent==='cancel'){if(!in_array($g['state'],['draft','sealed'],true))throw new \RuntimeException('دفتر پس از خروج قابل لغو نیست.');$note=self::text($p['note']??'',3,1000);$g['state']='cancelled';$detail=['note'=>$note];}
  else throw new \InvalidArgumentException('عملیات ناشناخته است.');
  self::event($d,$intent,$detail);$g['revision']++;$g['updated_at']=gmdate('c');self::persist($all,$g,$d,$affected);return self::get($id);
 });}
 public static function export(string $id): array {$g=self::get($id);return ['schema'=>'mahex-local-handover/1','local_only'=>true,'carrier_delivery_verified'=>false,'group'=>$g];}
 public static function ajax(): void {if(!check_ajax_referer('hm_mahex_v35_handover','nonce',false)||!Access::can('operations'))wp_send_json_error(['message'=>'دسترسی مجاز نیست.'],403);try{$raw=Support::input('payload','{}');if(strlen($raw)>64000)throw new \InvalidArgumentException('داده بیش از حد بزرگ است.');$p=json_decode($raw,true);if(!is_array($p))throw new \InvalidArgumentException('داده معتبر نیست.');$intent=Support::input('intent');if($intent==='list')$result=['groups'=>self::listing()];elseif($intent==='get')$result=['group'=>self::get(self::text($p['id']??''))];elseif($intent==='create')$result=['group'=>self::create($p)];elseif($intent==='mutate')$result=['group'=>self::mutate(self::text($p['id']??''),self::integer($p['revision']??0,1,PHP_INT_MAX),self::text($p['operation']??''),(array)($p['values']??[]))];else throw new \InvalidArgumentException('عملیات ناشناخته است.');$result['groups']=self::listing();wp_send_json_success($result);}catch(\Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],409);}}
 public static function download(): void {Support::auth('hm_mahex_v35_handover_export','operations');try{$data=self::export(Support::input('group'));}catch(\Throwable $e){wp_die(esc_html($e->getMessage()),'',['response'=>403]);}nocache_headers();if(Support::input('format')==='json'){header('Content-Type: application/json; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$data['group']['code'].'.json"');echo wp_json_encode($data,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);exit;}$g=$data['group'];$d=$g['details']??[];header('Content-Type: text/html; charset=UTF-8');echo '<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><title>دفتر محلی '.esc_html($g['code']).'</title><style>body{font-family:Tahoma;padding:20px}table{width:100%;border-collapse:collapse}td,th{border:1px solid;padding:8px}bdi{direction:ltr}@media print{button{display:none}}</style><button onclick="window.print()">چاپ</button><h1>'.esc_html($g['code'].' — '.($d['title']??'پاک‌شده')).'</h1><p>دفتر محلی فروشگاه؛ مدرک تایید دریافت یا وضعیت شرکت حمل نیست.</p><p>'.esc_html(($d['origin']??'').' ← '.($d['destination']??'').' | پلمب: '.($d['seal']??'').' | نگهدارنده: '.($d['custodian']??'')).'</p><p>هش دفتر: <bdi>'.esc_html($g['digest']).'</bdi></p><table><thead><tr><th>سفارش</th><th>بسته</th><th>وزن گرم</th><th>نتیجه</th><th>پذیرنده دستی</th></tr></thead><tbody>';foreach($g['rows'] as $r)echo '<tr><td>'.esc_html($r['number']).'</td><td>'.(int)$r['parcels'].'</td><td>'.esc_html((string)$r['weight_g']).'</td><td>'.esc_html(isset($r['receipt'])?self::CONDITIONS[$r['receipt']['condition']].' — '.$r['receipt']['accepted']:'بررسی نشده').'</td><td>'.esc_html($r['receipt_details']['receiver']??'').'</td></tr>';echo '</tbody></table><p>جمع '.(int)$g['totals']['parcels'].' بسته — '.esc_html((string)$g['totals']['weight_g']).' گرم</p></html>';exit;}
 public static function page(): void {if(!Access::can('operations'))wp_die('دسترسی مجاز نیست.','',['response'=>403]);$group=isset($_GET['group'])&&is_string($_GET['group'])?sanitize_text_field(wp_unslash($_GET['group'])):'';echo '<div class="wrap hmx-handover" dir="rtl"><h1>دفتر تحویل گروهی محلی</h1><p class="hmx-local-note">ثبت داخلی فروشگاه، مستقل از شرکت حمل. این دفتر اثبات تحویل فیزیکی، اصالت پلمب یا وضعیت آنلاین حمل نیست. تاریخ‌ها میلادی و زمان‌ها منطقه زمانی فروشگاه هستند. ظرفیت: ۲۰۰ دفتر، ۲۰۰ بسته در دفتر و ۲۰۰ رویداد؛ شواهد قدیمی خودکار حذف نمی‌شوند.</p><div data-handover-status role="status" aria-live="polite"></div><details><summary>ایجاد دفتر جدید</summary><form data-handover-create><label>شناسه سفارش آغازین دارای طرح بسته‌بندی<input name="order_id" type="number" min="1" required></label><label>عنوان<input name="title" minlength="3" maxlength="120" required></label><label>مبدا<input name="origin" minlength="3" maxlength="120" required></label><label>مقصد عملیاتی<input name="destination" minlength="3" maxlength="120" required></label><label>نوع مسیر<select name="route">';foreach(self::ROUTES as $key=>$label)echo '<option value="'.esc_attr($key).'">'.esc_html($label).'</option>';echo '</select></label><label>شناسه خودرو اختیاری<input name="vehicle" maxlength="40"></label><label>شروع پنجره<input name="start" type="datetime-local" required></label><label>پایان پنجره<input name="end" type="datetime-local" required></label><label>ظرفیت بسته<input name="capacity" type="number" min="1" max="200" value="200" required></label><button class="button button-primary">ایجاد دفتر</button></form></details><div class="hmx-handover-toolbar"><label>جست‌وجوی کد، عنوان، مقصد<input data-handover-search type="search"></label><label>مرحله<select data-handover-filter><option value="">همه</option>';foreach(self::STATES as $key=>$label)echo '<option value="'.esc_attr($key).'">'.esc_html($label).'</option>';echo '</select></label><button class="button" data-handover-refresh>تازه‌سازی</button></div><div class="hmx-handover-layout"><nav data-handover-groups aria-label="دفترهای محلی"></nav><section data-handover-detail aria-label="دفتر انتخاب‌شده"></section></div><form data-handover-export method="post" action="'.esc_url(admin_url('admin-post.php')).'" target="_blank"><input type="hidden" name="action" value="hm_mahex_v35_handover_export"><input type="hidden" name="group" value="">';wp_nonce_field('hm_mahex_v35_handover_export');echo '<button class="button" name="format" value="sheet">برگه خصوصی قابل چاپ</button> <button class="button" name="format" value="json">خروجی خصوصی JSON</button></form><script type="application/json" data-handover-data>'.wp_json_encode(['groups'=>self::listing(),'selected'=>$group,'states'=>self::STATES,'conditions'=>self::CONDITIONS],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP).'</script></div>';}
}
