<?php
namespace HoseinMomeni\MahexWoo\V35;
use HoseinMomeni\MahexWoo\V33\Access;
use HoseinMomeni\MahexWoo\V32\Packing;
use HoseinMomeni\MahexWoo\V33\Station;
use HoseinMomeni\MahexWoo\Shipments\OptionOperationLock;
/** Local evidence review; scanning never changes order, inventory or carrier state. */
final class OrderQuality {
 const META='_hm_mahex_v35_quality'; const SLUG='hm-mahex-order-quality'; const ENGINE='3.5.0';
 public static function register(): void {add_action('admin_menu',[self::class,'menu'],49);add_action('admin_enqueue_scripts',[self::class,'assets']);add_action('wp_ajax_hm_mahex_v35_quality',[self::class,'ajax']);add_action('admin_post_hm_mahex_v35_quality_export',[self::class,'download']);}
 public static function menu(): void {add_submenu_page('hm-mahex','ممیزی کیفیت سفارش','کیفیت سفارش',Access::OPERATIONS,self::SLUG,[self::class,'page']);}
 public static function assets(string $hook): void {if(strpos($hook,self::SLUG)===false)return;wp_enqueue_style('hm-quality',plugins_url('assets/v35-quality.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_enqueue_script('hm-quality',plugins_url('assets/v35-quality.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_localize_script('hm-quality','hmQuality',['url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('hm_mahex_v35_quality')]);}
 public static function data($order): array {$d=$order->get_meta(self::META,true);return array_merge(['revision'=>0,'reviews'=>[],'history'=>[]],is_array($d)?$d:[]);}
 public static function hash($value): string {return hash('sha256',json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
 public static function snapshot($order,bool $finance): array {
  $s=['lines'=>[],'shipping'=>[],'created'=>0,'paid'=>0,'completed'=>0,'customer_missing'=>false,'status'=>$order->get_status(),'packing'=>[],'station'=>[],'units'=>[]];
  foreach(['created','paid','completed'] as $key){$method='get_date_'.$key;$date=$order->$method();$s[$key]=$date?$date->getTimestamp():0;}
  $cid=(int)$order->get_customer_id();$s['customer_missing']=$cid>0&&!get_userdata($cid);
  foreach($order->get_items() as $id=>$item){$p=$item->get_product();$line=['id'=>(int)$id,'product_id'=>$p?(int)$p->get_id():((int)$item->get_variation_id()?:(int)$item->get_product_id()),'quantity'=>$item->get_quantity(),'exists'=>(bool)$p,'virtual'=>$p?$p->is_virtual():false,'sku'=>$p?(string)$p->get_sku():''];if($finance)$line['total']=$item->get_total();$s['lines'][]=$line;}
  foreach($order->get_items('shipping') as $id=>$item)$s['shipping'][]=['id'=>(int)$id,'method'=>(string)$item->get_method_id()];
  $plan=$order->get_meta(Packing::META,true);$s['packing']=is_array($plan)?$plan:[];$s['station']=Station::data($order);
  try{$s['units']=Packing::units($order);}catch(\Throwable $e){$s['unit_error']=true;}
  if($finance){$s['total']=$order->get_total();$s['refund']=$order->get_total_refunded();$s['shipping_total']=$order->get_shipping_total();$s['currency']=$order->get_currency();$s['payment']=$order->get_payment_method();}
  return $s;
 }
 /** Pure detectors are individually testable and return no customer/product text. */
 public static function analyze(array $s,bool $finance=false,?int $now=null): array {
  $now=$now??time();$out=[];$add=static function(string $code,string $title,array $e=[],string $severity='warning',bool $money=false)use(&$out){$id=$code.(isset($e['line'])?':'.$e['line']:'');$out[$id]=['id'=>$id,'code'=>$code,'title'=>$title,'severity'=>$severity,'financial'=>$money,'evidence'=>$e,'fingerprint'=>self::hash([$code,$e])];};
  $physical=0;$skus=[];
  foreach($s['lines']??[] as $l){$e=['line'=>$l['id'],'product'=>$l['product_id']];if(!$l['exists'])$add('orphan_product','محصول این قلم دیگر قابل بازیابی نیست',$e,'critical');if(!is_numeric($l['quantity'])||!is_finite((float)$l['quantity'])||(float)$l['quantity']<=0)$add('quantity_invalid','تعداد قلم غیرمثبت یا نامعتبر است',array_merge($e,['quantity'=>(string)$l['quantity']]),'critical');elseif(floor((float)$l['quantity'])!=(float)$l['quantity'])$add('quantity_fraction','تعداد کسری نیازمند بررسی کالای شمارشی است',array_merge($e,['quantity'=>(string)$l['quantity']]));
   if(!$l['virtual']){$physical++;if($l['exists']&&trim($l['sku'])==='')$add('missing_sku','کالای فیزیکی شناسه SKU ندارد',$e,'info');}
   if($l['sku']!==''){if(isset($skus[$l['sku']])&&$skus[$l['sku']]!==$l['product_id'])$add('sku_collision','شناسه یکسان برای محصولات متفاوت',array_merge($e,['sku_hash'=>self::hash($l['sku']),'other_product'=>$skus[$l['sku']]]),'critical');$skus[$l['sku']]=$l['product_id'];}
   if($finance&&(!is_numeric($l['total'])||!is_finite((float)$l['total'])))$add('nonfinite_item','مبلغ قلم نامعتبر است',array_merge($e,['value_hash'=>self::hash((string)$l['total'])]),'critical',true);
  }
  if(!$physical)$add('no_physical','کالای فیزیکی برای ارسال وجود ندارد',[],'info');
  $ships=$s['shipping']??[];if($physical&&!$ships)$add('no_shipping_method','کالای فیزیکی بدون ردیف روش ارسال',[],'critical');if(count($ships)>1)$add('multiple_shipping','چند ردیف روش ارسال؛ تخصیص دستی را بررسی کنید',['count'=>count($ships)]);
  foreach($ships as $ship)if(trim($ship['method'])==='')$add('empty_shipping_method','روش ارسال فاقد شناسه',['line'=>$ship['id']]);
  $plan=$s['packing']??[];$station=$s['station']??[];$units=$s['units']??[];$fp=Packing::fingerprint($units);
  if(empty($s['unit_error'])&&$plan&&($plan['fingerprint']??'')!==$fp)$add('packing_drift','طرح دستی با واحدهای کنونی همخوان نیست',['saved'=>$plan['fingerprint']??'','current'=>$fp],'critical');
  if(empty($s['unit_error'])&&!empty($station['committed_fingerprint'])&&$station['committed_fingerprint']!==$fp)$add('commit_items_drift','مصرف انبار برای نسخه دیگری از اقلام ثبت شده',['saved'=>$station['committed_fingerprint'],'current'=>$fp],'critical');
  $planHash=hash('sha256',wp_json_encode($plan['boxes']??[]));if($plan&&!empty($station['committed_plan_hash'])&&$station['committed_plan_hash']!==$planHash)$add('commit_plan_drift','طرح بسته پس از مصرف انبار تغییر کرده',['saved'=>$station['committed_plan_hash'],'current'=>$planHash],'critical');
  foreach($station['scans']??[] as $id=>$_)if(empty($s['unit_error'])&&!isset($units[$id]))$add('orphan_scan','اسکن مربوط به واحد حذف‌شده',['line'=>(string)$id],'critical');
  foreach($station['parcels']??[] as $index=>$_)if(!isset($plan['boxes'][$index]))$add('orphan_parcel','اندازه‌گیری مربوط به بسته حذف‌شده',['line'=>(string)$index],'critical');
  if($finance){$moneyEvidence=['value_hash'=>self::hash([(string)($s['total']??''),(string)($s['refund']??''),(string)($s['shipping_total']??''),(string)($s['currency']??''),(string)($s['payment']??'')])];if((float)($s['total']??0)>0&&empty($s['payment']))$add('missing_payment_method','روش پرداخت برای سفارش غیررایگان ثبت نشده',$moneyEvidence,'warning',true);if((float)($s['total']??0)<0)$add('negative_total','جمع سفارش منفی است',$moneyEvidence,'critical',true);if((float)($s['refund']??0)>(float)($s['total']??0)&&($s['refund']??0)>0)$add('over_refunded','جمع بازپرداخت از مبلغ سفارش بیشتر است',$moneyEvidence,'critical',true);if((float)($s['shipping_total']??0)<0)$add('negative_shipping','جمع هزینه ارسال منفی است',$moneyEvidence,'warning',true);if(empty($s['currency']))$add('empty_currency','کد ارز سفارش خالی است',$moneyEvidence,'critical',true);if(($s['status']??'')==='processing'&&($s['total']??0)>0&&($s['refund']??0)>=($s['total']??0))$add('refunded_active','سفارش فعال کاملاً بازپرداخت شده',$moneyEvidence,'critical',true);}
  if(($s['paid']??0)>0&&$s['paid']<$s['created'])$add('paid_before_created','پرداخت پیش از زمان ایجاد سفارش',['created'=>$s['created'],'paid'=>$s['paid']],'critical');if(($s['completed']??0)>0&&$s['completed']<$s['created'])$add('completed_before_created','تکمیل پیش از زمان ایجاد سفارش',['created'=>$s['created'],'completed'=>$s['completed']],'critical');if(($s['created']??0)>$now+300)$add('future_created','زمان ایجاد بیش از پنج دقیقه در آینده است',['created'=>$s['created']]);if(!empty($s['customer_missing']))$add('missing_customer','شناسه حساب مشتری دیگر وجود ندارد',[],'info');return array_values($out);
 }
 public static function scan($order,bool $finance=false,?int $now=null): array {$now=$now??time();$d=self::data($order);$snapshot=self::snapshot($order,$finance);$findings=self::analyze($snapshot,$finance,$now);$summary=['open'=>0,'confirmed'=>0,'dismissed'=>0,'stale'=>0];foreach($findings as &$f){$r=$d['reviews'][$f['id']]??null;$f['review']=$r;$f['state']=$r?(hash_equals($r['fingerprint'],$f['fingerprint'])?$r['verdict']:'stale'):'open';$summary[$f['state']]++;}unset($f);return ['order_id'=>$order->get_id(),'engine_version'=>self::ENGINE,'unit_snapshot_incomplete'=>!empty($snapshot['unit_error']),'scanned_at'=>gmdate('c',$now),'revision'=>(int)$d['revision'],'findings'=>$findings,'summary'=>$summary];}
 public static function transition(array $d,array $finding,string $verdict,string $reason,int $actor,int $now): array {if(!in_array($verdict,['confirmed','dismissed','reset'],true))throw new \InvalidArgumentException('تصمیم نامعتبر است.');$reason=trim(strip_tags($reason));if($reason===''||mb_strlen($reason)>1000)throw new \InvalidArgumentException('توضیح ۱ تا ۱۰۰۰ نویسه لازم است.');$record=['fingerprint'=>$finding['fingerprint'],'verdict'=>$verdict,'reason'=>$reason,'actor'=>$actor,'at'=>gmdate('c',$now),'financial'=>$finding['financial']];if($verdict==='reset')unset($d['reviews'][$finding['id']]);else $d['reviews'][$finding['id']]=$record;$d['history'][]=array_merge(['finding'=>$finding['id']],$record);$d['history']=array_slice($d['history'],-50);$d['revision']++;return $d;}
 public static function review(int $id,string $finding,string $fingerprint,string $verdict,string $reason,int $revision): array {if(!Access::can('operations',$id))throw new \RuntimeException('دسترسی سفارش مجاز نیست.');$lock=new OptionOperationLock();if(!$lock->acquire($id,60))throw new \RuntimeException('سفارش در حال ویرایش است.');try{$order=wc_get_order($id);if(!$order)throw new \RuntimeException('سفارش وجود ندارد.');$order->read_meta_data(true);\HoseinMomeni\MahexWoo\V33\BoardTools::guardOtherEditor($id);$scan=self::scan($order,Access::can('finance',$id));$d=self::data($order);if($d['revision']!==$revision)throw new \RuntimeException('تصمیم در صفحه دیگری تغییر کرده است.');$match=null;foreach($scan['findings'] as $f)if($f['id']===$finding)$match=$f;if(!$match||!hash_equals($match['fingerprint'],$fingerprint))throw new \RuntimeException('شواهد تغییر کرده یا دسترسی یافته مجاز نیست.');$d=self::transition($d,$match,$verdict,$reason,get_current_user_id(),time());$order->update_meta_data(self::META,$d);$order->save_meta_data();return self::scan($order,Access::can('finance',$id));}finally{$lock->release($id);}}
 public static function exportData($order,bool $finance=false): array {$out=self::scan($order,$finance);$out['history']=array_values(array_filter(self::data($order)['history'],static fn($e)=>$finance||empty($e['financial'])));return $out;}
 public static function privacy($order): array {return self::data($order);}
 public static function erase($order): bool {if(!$order->get_meta(self::META,true))return false;$order->delete_meta_data(self::META);$order->save_meta_data();return true;}
 public static function ajax(): void {if(!check_ajax_referer('hm_mahex_v35_quality','nonce',false)||!Access::can('operations'))wp_send_json_error(['message'=>'دسترسی مجاز نیست.'],403);try{$raw=$_POST['payload']??'';if(!is_string($raw)||strlen($raw)>8000)throw new \InvalidArgumentException('داده بیش از حد مجاز است.');$p=json_decode(wp_unslash($raw),true);if(!is_array($p))throw new \InvalidArgumentException('داده نامعتبر است.');foreach(['order_id','finding','fingerprint','verdict','reason','revision'] as $key)if(!isset($p[$key])||!is_scalar($p[$key]))throw new \InvalidArgumentException('فیلد درخواست نامعتبر است.');$result=self::review(absint($p['order_id']??0),(string)($p['finding']??''),(string)($p['fingerprint']??''),(string)($p['verdict']??''),(string)($p['reason']??''),(int)($p['revision']??-1));wp_send_json_success($result);}catch(\Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],409);}}
 public static function download(): void {check_admin_referer('hm_mahex_v35_quality_export');$id=absint($_GET['order_id']??0);if(!Access::can('operations',$id)||!($order=wc_get_order($id)))wp_die('دسترسی مجاز نیست.','',['response'=>403]);nocache_headers();header('Content-Type: application/json; charset=UTF-8');header('Content-Disposition: attachment; filename="mahex-quality-'.$id.'.json"');echo wp_json_encode(self::exportData($order,Access::can('finance',$id)),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;}
 public static function page(): void {if(!Access::can('operations'))wp_die('دسترسی مجاز نیست.','',['response'=>403]);$page=max(1,min(10000,absint($_GET['paged']??1)));$id=absint($_GET['order_id']??0);$orders=$id?[wc_get_order($id)]:wc_get_orders(['limit'=>50,'page'=>$page,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap hm-quality" dir="rtl"><h1>ممیزی کیفیت سفارش</h1><p>بررسی خواندنی داده محلی فروشگاه؛ تأیید مغایرت هیچ کالا، نرخ یا وضعیت حملی را تغییر نمی‌دهد. یافته‌ها نیازمند بررسی انسانی هستند.</p><form method="get"><input type="hidden" name="page" value="'.self::SLUG.'"><label>شناسه سفارش <input name="order_id" type="number" min="1" value="'.($id?:'').'"></label><button class="button">بررسی سفارش</button></form><div class="hq-filters"><label>جست‌وجوی یافته <input data-quality-search type="search"></label><label>شدت <select data-quality-severity><option value="">همه</option><option value="critical">بحرانی</option><option value="warning">هشدار</option><option value="info">اطلاع</option></select></label><label>تصمیم <select data-quality-state><option value="">همه</option><option value="open">باز</option><option value="confirmed">تأیید</option><option value="dismissed">مثبت کاذب</option><option value="stale">شواهد تغییر کرده</option></select></label></div><p data-quality-live aria-live="polite"></p>';
  $count=0;foreach($orders as $order){if(!$order||!Access::can('operations',$order->get_id()))continue;$count++;$scan=self::scan($order,Access::can('finance',$order->get_id()));echo '<section class="hq-order" data-quality-order="'.$order->get_id().'" data-revision="'.$scan['revision'].'"><h2>سفارش #'.esc_html($order->get_order_number()).'</h2><p>یافته‌های فعلی: '.count($scan['findings']).' · باز: '.$scan['summary']['open'].' · تأیید: '.$scan['summary']['confirmed'].' · مثبت کاذب: '.$scan['summary']['dismissed'].' · تغییر شواهد: '.$scan['summary']['stale'].'</p><a class="button" href="'.esc_url($order->get_edit_order_url()).'">ویرایش سفارش</a> <a class="button" href="'.esc_url(wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v35_quality_export','order_id'=>$order->get_id()],admin_url('admin-post.php')),'hm_mahex_v35_quality_export')).'">خروجی خصوصی ممیزی</a>';if($scan['unit_snapshot_incomplete'])echo '<p>بخش تطبیق واحدهای بسته‌بندی کامل قابل ممیزی نیست؛ حد مجاز چیدمان ۵۰۰ واحد است. سایر یافته‌ها مستقل بررسی شدند.</p>';if(!$scan['findings'])echo '<p class="hq-healthy">هیچ مغایرت شناخته‌شده‌ای در این محدوده تشخیص داده نشد؛ تضمین سلامت کامل نیست.</p>';foreach($scan['findings'] as $f){echo '<article class="hq-finding" data-finding="'.esc_attr($f['id']).'" data-fingerprint="'.esc_attr($f['fingerprint']).'" data-severity="'.$f['severity'].'" data-state="'.$f['state'].'"><h3>'.esc_html($f['title']).'</h3><p><b>'.esc_html(['critical'=>'بحرانی','warning'=>'هشدار','info'=>'اطلاع'][$f['severity']]).'</b> · '.esc_html(['open'=>'باز','confirmed'=>'تأیید','dismissed'=>'مثبت کاذب','stale'=>'شواهد تغییر کرده'][$f['state']]).'</p><code dir="ltr">'.esc_html($f['id']).'</code><details><summary>شواهد حداقلی</summary><pre dir="ltr">'.esc_html(wp_json_encode($f['evidence'],JSON_PRETTY_PRINT)).'</pre></details>';if($f['review'])echo '<p>آخرین تصمیم: '.esc_html($f['review']['reason']).' · کاربر #'.(int)$f['review']['actor'].' · <time dir="ltr">'.esc_html($f['review']['at']).'</time></p>';echo '<label>توضیح تصمیم <textarea data-quality-reason maxlength="1000" rows="2"></textarea></label><div class="hq-actions"><button class="button" data-verdict="confirmed">تأیید مغایرت</button><button class="button" data-verdict="dismissed">ثبت مثبت کاذب</button><button class="button" data-verdict="reset">بازنشانی تصمیم</button></div></article>'; }echo '</section>';}
  echo '<p>محدوده بررسی: '.$count.' سفارش در صفحه '.$page.'؛ فیلترها فقط یافته‌های همین صفحه‌اند.</p>';if(!$id){if($page>1)echo '<a class="button" href="'.esc_url(add_query_arg(['page'=>self::SLUG,'paged'=>$page-1],admin_url('admin.php'))).'">صفحه قبل</a> ';echo '<a class="button" href="'.esc_url(add_query_arg(['page'=>self::SLUG,'paged'=>$page+1],admin_url('admin.php'))).'">صفحه بعد</a>';}echo '</div>';}
}
