<?php
namespace HoseinMomeni\MahexWoo\V34;

use HoseinMomeni\MahexWoo\Enterprise\AddressTools;
use HoseinMomeni\MahexWoo\V33\Access;
use HoseinMomeni\MahexWoo\V33\BoardTools;
use HoseinMomeni\MahexWoo\V33\Support;
use HoseinMomeni\MahexWoo\Shipments\OptionOperationLock;

/** Internal dispatch review. Never queries or asserts carrier delivery state. */
final class DispatchWorkbench {
 const META='_hm_mahex_v34_dispatch';
 const SLUG='hm-mahex-v34-dispatch';
 const CHECKS=['address_reviewed'=>'نشانی بازبینی شد','documents_checked'=>'اسناد همراه بررسی شد','seal_checked'=>'پلمب بسته بررسی شد','label_double_checked'=>'برچسب دوباره خوانده شد'];
 const HOLDS=['address'=>'نشانی','contact'=>'تماس','payment'=>'پرداخت','damage'=>'آسیب','customer'=>'درخواست مشتری','other'=>'سایر'];
 const PRIORITIES=['normal'=>'عادی','urgent'=>'فوری','vip'=>'ویژه'];
 public static function register(): void {add_action('admin_menu',[self::class,'menu'],48);add_action('admin_enqueue_scripts',[self::class,'assets']);add_action('wp_ajax_hm_mahex_v34_dispatch',[self::class,'ajax']);add_action('admin_post_hm_mahex_v34_dispatch_sheet',[self::class,'sheet']);}
 public static function menu(): void {add_submenu_page('hm-mahex','کارگاه بازبینی اعزام','بازبینی اعزام',Access::OPERATIONS,self::SLUG,[self::class,'page']);}
 public static function assets(string $hook): void {if(strpos($hook,self::SLUG)===false)return;wp_enqueue_style('hm-mahex-v34-dispatch',plugins_url('assets/admin/v34-dispatch.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_enqueue_script('hm-mahex-v34-dispatch',plugins_url('assets/admin/v34-dispatch.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_localize_script('hm-mahex-v34-dispatch','hmDispatch',['url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('hm_mahex_v34_dispatch')]);}
 public static function data($order): array {$d=$order->get_meta(self::META,true);return array_merge(['revision'=>0,'hold'=>null,'priority'=>'normal','priority_reason'=>'','bin'=>'','packing_instruction'=>'','contact_instruction'=>'','recipient_only'=>false,'do_not_bend'=>false,'checks'=>[],'verification'=>null,'history'=>[],'undo'=>null],is_array($d)?$d:[]);}
 public static function address($order): array {
  $out=[];$source=[];$shipping=trim((string)$order->get_shipping_address_1())!=='';
  foreach(['first_name','last_name','country','state','city','address_1','address_2','postcode','phone'] as $key){$get='get_shipping_'.$key;$ship=method_exists($order,$get)?(string)$order->$get():'';$bill='get_billing_'.$key;$billing=(string)$order->$bill();$pre=($shipping&&trim($ship)!=='')?'shipping':'billing';$out[$key]=$pre==='shipping'?$ship:$billing;$source[$key]=$pre;}
  return ['fields'=>$out,'source'=>$source,'shipping_used'=>$shipping,'shipping_phone'=>method_exists($order,'get_shipping_phone')?(string)$order->get_shipping_phone():'','billing_phone'=>(string)$order->get_billing_phone()];
 }
 public static function fingerprint(array $address): string {return hash('sha256',json_encode(['fields'=>$address['fields'],'source'=>$address['source']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
 /** Reuse established checkout normalizers. Historical correction is opt-in with a field diff. */
 public static function remediation(array $address): array {
  $diff=[];$issues=[];
  foreach($address['fields'] as $field=>$old){$new=$old;
   if($field==='phone')$new=AddressTools::normalizePhone($old);
   elseif($field==='postcode'){$digits=AddressTools::digits($old);if(preg_match('/[^0-9\s-]/u',$digits)){$issues['postcode_letters']='کدپستی حروف یا نماد دارد؛ اصلاح خودکار انجام نمی‌شود.';}else $new=preg_replace('/[\s-]/u','',$digits)??$old;}
   elseif(in_array($field,['first_name','last_name','city','address_1','address_2'],true))$new=AddressTools::cleanText($old);
   if($new!==$old)$diff[$field]=['field'=>$address['source'][$field].'_'.$field,'old'=>$old,'new'=>$new];
   if(preg_match('/[\x{200E}\x{200F}\x{202A}-\x{202E}\x{2066}-\x{2069}]/u',$old)){$issues['bidi']='نشانی کنترل نامرئی جهت متن دارد.';$clean=preg_replace('/[\x{200E}\x{200F}\x{202A}-\x{202E}\x{2066}-\x{2069}]/u','',$new)??$new;if($clean!==$old)$diff[$field]=['field'=>$address['source'][$field].'_'.$field,'old'=>$old,'new'=>$clean];}
  }
  if($address['shipping_used']&&count(array_unique($address['source']))>1)$issues['mixed']='مقصد ترکیبی از ارسال و صورتحساب است؛ تأیید گیرنده لازم است.';
  $sp=AddressTools::normalizePhone($address['shipping_phone']);$bp=AddressTools::normalizePhone($address['billing_phone']);if(AddressTools::validPhone($sp)&&AddressTools::validPhone($bp)&&$sp!==$bp)$issues['phone_conflict']='موبایل ارسال و صورتحساب متفاوت است؛ گیرنده را تأیید کنید.';
  return ['diff'=>$diff,'issues'=>$issues];
 }
 public static function reviewed(array $d,array $a): bool {return !empty($d['verification']['fingerprint'])&&hash_equals($d['verification']['fingerprint'],self::fingerprint($a));}
 public static function checklist(array $d,array $a): array {$checks=[];foreach(self::CHECKS as $key=>$label)$checks[$key]=!empty($d['checks'][$key]);if(($d['checks_address_fingerprint']??'')!==self::fingerprint($a))$checks['address_reviewed']=false;return $checks;}
 public static function readiness(array $d,array $a,int $now): array {$checks=self::checklist($d,$a);$missing=[];foreach($checks as $key=>$yes)if(!$yes)$missing[]=self::CHECKS[$key];if(!self::reviewed($d,$a))$missing[]='تأیید گیرنده برای نشانی فعلی';if(!empty($d['hold']))$missing[]='آزادسازی توقف داخلی';return ['completed'=>6-count($missing),'required'=>6,'missing'=>$missing,'ready'=>!$missing,'overdue_hold'=>!empty($d['hold']['review_at'])&&strtotime($d['hold']['review_at'])<=$now];}
 public static function assertReady($order): void {if(!empty(self::data($order)['hold']))throw new \RuntimeException('این سفارش توقف داخلی اعزام دارد؛ ابتدا در کارگاه بازبینی اعزام با دلیل آزاد کنید.');}
 public static function boundedText($value,int $max=1000): string {if(!is_scalar($value))throw new \InvalidArgumentException('متن معتبر نیست.');$text=trim(strip_tags((string)$value));if(mb_strlen($text)>$max)throw new \InvalidArgumentException('متن بیش از حد مجاز است.');return $text;}
 public static function deadline($value): string {$value=self::boundedText($value,32);if($value==='')return '';if(!preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?Z$/',$value))throw new \InvalidArgumentException('مهلت باید تاریخ UTC به شکل 2026-10-07T12:00:00Z باشد.');$date=\DateTimeImmutable::createFromFormat('!Y-m-d\TH:i:s\Z',strlen($value)===17?substr($value,0,-1).':00Z':$value,new \DateTimeZone('UTC'));$errors=\DateTimeImmutable::getLastErrors();if(!$date||($errors&&($errors['warning_count']||$errors['error_count'])))throw new \InvalidArgumentException('تاریخ مهلت معتبر نیست.');return $date->format('Y-m-d\TH:i:s\Z');}
 public static function event(array $d,string $action,array $detail,int $actor): array {$d['history'][]=['action'=>$action,'detail'=>$detail,'actor'=>$actor,'at'=>gmdate('c')];$d['history']=array_slice($d['history'],-20);return $d;}
 /** Pure review transition, validated before writing under the common order lock. */
 public static function transition(array $d,array $a,string $intent,array $p,int $actor): array {
  $detail=[];
  if($intent==='verify'){$method=self::boundedText($p['method']??'',30);if(!in_array($method,['phone','customer_message','in_person'],true))throw new \InvalidArgumentException('روش تأیید مجاز نیست.');$note=self::boundedText($p['note']??'');if($note==='')throw new \InvalidArgumentException('یادداشت تأیید گیرنده الزامی است.');$d['verification']=['method'=>$method,'note'=>$note,'actor'=>$actor,'at'=>gmdate('c'),'fingerprint'=>self::fingerprint($a)];$detail=['method'=>$method,'note'=>$note];}
  elseif($intent==='hold'){$reason=self::boundedText($p['reason']??'',30);if(!isset(self::HOLDS[$reason]))throw new \InvalidArgumentException('دلیل توقف مجاز نیست.');$note=self::boundedText($p['note']??'');if($reason==='other'&&$note==='')throw new \InvalidArgumentException('توقف سایر توضیح لازم دارد.');$d['hold']=['reason'=>$reason,'note'=>$note,'review_at'=>self::deadline($p['review_at']??''),'actor'=>$actor,'at'=>gmdate('c')];$detail=$d['hold'];}
  elseif($intent==='release'){$note=self::boundedText($p['note']??'');if($note==='')throw new \InvalidArgumentException('دلیل آزادسازی الزامی است.');if(empty($d['hold']))throw new \InvalidArgumentException('توقفی برای آزادسازی وجود ندارد.');$detail=['previous'=>$d['hold'],'release_note'=>$note];$d['hold']=null;}
  elseif($intent==='priority'){$value=self::boundedText($p['priority']??'',20);if(!isset(self::PRIORITIES[$value]))throw new \InvalidArgumentException('اولویت مجاز نیست.');$note=self::boundedText($p['note']??'');if($value!=='normal'&&$note==='')throw new \InvalidArgumentException('اولویت ویژه دلیل لازم دارد.');$detail=['from'=>$d['priority'],'to'=>$value,'note'=>$note];$d['priority']=$value;$d['priority_reason']=$note;}
  elseif($intent==='bin'){$raw=$p['bin']??'';if(!is_scalar($raw)||strip_tags((string)$raw)!==(string)$raw)throw new \InvalidArgumentException('شناسه قفسه معتبر نیست.');$value=self::boundedText($raw,40);if($value!==''&&!preg_match('/^[A-Za-z0-9_-]{1,24}$/',$value))throw new \InvalidArgumentException('شناسه قفسه باید ۱ تا ۲۴ حرف لاتین/عدد/خط تیره باشد.');$detail=['from'=>$d['bin'],'to'=>$value];$d['bin']=$value;}
  elseif($intent==='instructions'){$d['packing_instruction']=self::boundedText($p['packing_instruction']??'');$d['contact_instruction']=self::boundedText($p['contact_instruction']??'');$d['recipient_only']=!empty($p['recipient_only']);$d['do_not_bend']=!empty($p['do_not_bend']);$detail=['packing_instruction'=>$d['packing_instruction'],'contact_instruction'=>$d['contact_instruction'],'recipient_only'=>$d['recipient_only'],'do_not_bend'=>$d['do_not_bend']];}
  elseif($intent==='checklist'){$pChecks=$p['checks']??[];if(!is_array($pChecks)||array_diff(array_keys($pChecks),array_keys(self::CHECKS)))throw new \InvalidArgumentException('کلید چک‌لیست مجاز نیست.');foreach(self::CHECKS as $key=>$_)$d['checks'][$key]=!empty($pChecks[$key]);$d['checks_address_fingerprint']=self::fingerprint($a);$detail=$d['checks'];}
  else throw new \InvalidArgumentException('عملیات مجاز نیست.');
  return self::event($d,$intent,$detail,$actor);
 }
 public static function summary($order): array {$d=self::data($order);$a=self::address($order);$fix=self::remediation($a);$date=$order->get_date_created();$verification=$d['verification'];if($verification){$user=get_userdata((int)$verification['actor']);$verification['actor_name']=$user?$user->display_name:'#'.$verification['actor'];}
  return ['id'=>$order->get_id(),'number'=>$order->get_order_number(),'name'=>trim($a['fields']['first_name'].' '.$a['fields']['last_name']),'city'=>$a['fields']['city'],'created'=>$date?$date->getTimestamp():0,'status'=>$order->get_status(),'address'=>$a,'fix'=>$fix,'fingerprint'=>self::fingerprint($a),'revision'=>(int)$d['revision'],'state'=>$d,'verification'=>$verification,'verified'=>self::reviewed($d,$a),'checks'=>self::checklist($d,$a),'readiness'=>self::readiness($d,$a,time()),'station_url'=>add_query_arg(['page'=>'hm-mahex-v33-station','order_id'=>$order->get_id()],admin_url('admin.php'))];
 }
 public static function rows(int $page=1): array {$orders=wc_get_orders(['limit'=>100,'page'=>max(1,min(10000,$page)),'status'=>['pending','processing','on-hold','completed'],'orderby'=>'date','order'=>'DESC']);$rows=[];foreach($orders as $order)if(Access::can('operations',$order->get_id()))$rows[]=self::summary($order);return $rows;}
 public static function tokenKey(string $token): string {if(!preg_match('/^[a-f0-9]{48}$/',$token))throw new \InvalidArgumentException('توکن پیش‌نمایش معتبر نیست.');return 'hm_mahex_v34_preview_'.get_current_user_id().'_'.$token;}
 public static function preview(array $ids,string $intent,array $payload): array {
  if(!$ids||count($ids)>50)throw new \InvalidArgumentException('۱ تا ۵۰ سفارش انتخاب کنید.');foreach($ids as $id)if((!is_int($id)&&(!is_string($id)||!ctype_digit($id)))||(int)$id<1)throw new \InvalidArgumentException('شناسه سفارش باید عدد مثبت باشد.');$ids=array_values(array_unique(array_map('absint',$ids)));$rows=[];
  foreach($ids as $id){if(!Access::can('operations',$id))throw new \RuntimeException('دسترسی سفارش #'.$id.' مجاز نیست.');$order=wc_get_order($id);if(!$order)throw new \RuntimeException('سفارش #'.$id.' وجود ندارد.');$s=self::summary($order);$d=$s['state'];
   if($intent==='normalize'){$fields=$payload['fields']??array_keys($s['fix']['diff']);if(!is_array($fields)||count($fields)>9)throw new \InvalidArgumentException('فیلد اصلاح معتبر نیست.');$diff=[];foreach($fields as $field){if(!is_string($field)||!array_key_exists($field,$s['address']['fields']))throw new \InvalidArgumentException('فیلد اصلاح معتبر نیست.');if(isset($s['fix']['diff'][$field]))$diff[$field]=$s['fix']['diff'][$field];}$change=['diff'=>$diff];}
   elseif($intent==='undo'){$undo=$d['undo'];if(!$undo||!hash_equals($undo['after'], $s['fingerprint']))throw new \RuntimeException('نشانی پس از اصلاح تغییر کرده؛ بازگردانی مجاز نیست.');$change=['undo'=>$undo];}
   else $change=['next'=>self::transition($d,$s['address'],$intent,$payload,get_current_user_id())];
   $rows[]=['id'=>$id,'number'=>$s['number'],'revision'=>$s['revision'],'fingerprint'=>$s['fingerprint'],'change'=>$change];
  }
  $token=bin2hex(random_bytes(24));set_transient(self::tokenKey($token),['intent'=>$intent,'rows'=>$rows,'actor'=>get_current_user_id(),'created'=>time()],600);return ['token'=>$token,'intent'=>$intent,'rows'=>$rows,'expires_in'=>600];
 }
 public static function apply(string $token): array {
  $key=self::tokenKey($token);$tokenLock=new OptionOperationLock();$lockId=-340000-(int)(hexdec(substr(hash('sha256',$key),0,7))%100000000);if(!$tokenLock->acquire($lockId,60))throw new \RuntimeException('این پیش‌نمایش در حال اعمال است.');
  try{$preview=get_transient($key);if(!is_array($preview)||($preview['actor']??0)!==get_current_user_id()||time()-($preview['created']??0)>600)throw new \RuntimeException('پیش‌نمایش منقضی یا قبلاً مصرف شده است.');delete_transient($key);}finally{$tokenLock->release($lockId);}
  $done=[];$errors=[];
  foreach($preview['rows'] as $row){$id=$row['id'];$guard=new OptionOperationLock();$locked=false;try{
   if(!Access::can('operations',$id))throw new \RuntimeException('دسترسی سفارش مجاز نیست.');if(!$guard->acquire($id,60))throw new \RuntimeException('سفارش در حال ویرایش است.');$locked=true;BoardTools::guardOtherEditor($id);$order=wc_get_order($id);if(!$order)throw new \RuntimeException('سفارش وجود ندارد.');$order->read_meta_data(true);$d=self::data($order);$a=self::address($order);if((int)$d['revision']!==$row['revision']||!hash_equals(self::fingerprint($a),$row['fingerprint']))throw new \RuntimeException('داده سفارش پس از پیش‌نمایش تغییر کرده است.');
   if($preview['intent']==='normalize'){$diff=$row['change']['diff'];if(!$diff){$done[]=['id'=>$id,'unchanged'=>true];continue;}foreach($diff as $part){$set='set_'.$part['field'];$order->$set($part['new']);}$d['undo']=['before'=>$a,'after'=>self::fingerprint(self::address($order)),'diff'=>$diff];$d=self::event($d,'normalize',['diff'=>$diff],get_current_user_id());}
   elseif($preview['intent']==='undo'){$undo=$row['change']['undo'];if(!$d['undo']||!hash_equals($d['undo']['after'],$row['fingerprint']))throw new \RuntimeException('بازگردانی قبلاً تغییر کرده است.');foreach($undo['diff'] as $part){$set='set_'.$part['field'];$order->$set($part['old']);}$d['undo']=null;$d=self::event($d,'undo',['diff'=>$undo['diff']],get_current_user_id());}
   else {$d=$row['change']['next'];}
   $d['revision']=$row['revision']+1;$d['updated_at']=gmdate('c');$d['actor']=get_current_user_id();$order->update_meta_data(self::META,$d);$saved=$order->save();if(!$saved)throw new \RuntimeException('ذخیره سفارش موفق نشد.');\HoseinMomeni\MahexWoo\V1\ActivityLog::write('dispatch.'.$preview['intent'],'بازبینی داخلی اعزام ذخیره شد.',$id,['revision'=>$d['revision']]);$done[]=['id'=>$id,'revision'=>$d['revision']];
  }catch(\Throwable $e){$errors[]=['id'=>$id,'message'=>$e->getMessage()];}finally{if($locked)$guard->release($id);}}
  return ['done'=>$done,'errors'=>$errors,'rows'=>self::rows()];
 }
 public static function ajax(): void {
  if(!check_ajax_referer('hm_mahex_v34_dispatch','nonce',false)||!Access::can('operations'))wp_send_json_error(['message'=>'دسترسی مجاز نیست.'],403);
  try{$intent=isset($_POST['intent'])&&is_string($_POST['intent'])?sanitize_key(wp_unslash($_POST['intent'])):'';$raw=Support::input('payload','{}');if(strlen($raw)>32000)throw new \InvalidArgumentException('داده بیش از حد بزرگ است.');$payload=json_decode($raw,true);if(!is_array($payload))throw new \InvalidArgumentException('داده JSON معتبر نیست.');
   if($intent==='rows')$result=['rows'=>self::rows(absint($payload['page']??1))];elseif($intent==='preview'){$ids=$payload['ids']??[];if(!is_array($ids))throw new \InvalidArgumentException('شناسه‌ها معتبر نیستند.');$result=self::preview($ids,(string)($payload['operation']??''),(array)($payload['values']??[]));}elseif($intent==='apply')$result=self::apply((string)($payload['token']??''));else throw new \InvalidArgumentException('عملیات ناشناخته است.');wp_send_json_success($result);
  }catch(\Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],409);}
 }
 public static function sheet(): void {Support::auth('hm_mahex_v34_dispatch_sheet','operations');$raw=Support::input('ids');$ids=array_values(array_unique(array_filter(array_map('absint',explode(',',$raw)))));if(!$ids||count($ids)>50)wp_die('۱ تا ۵۰ سفارش انتخاب کنید.');$orders=[];foreach($ids as $id){if(!Access::can('operations',$id)||!($order=wc_get_order($id)))wp_die('دسترسی سفارش مجاز نیست.','',['response'=>403]);$orders[]=$order;}nocache_headers();header('Content-Type: text/html; charset=UTF-8');echo '<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><title>برگه کار داخلی اعزام</title><style>body{font-family:Tahoma,sans-serif;margin:20px}article{border:1px solid #777;padding:16px;break-inside:avoid;margin-bottom:20px}button{padding:12px}@media print{button{display:none}}</style><button onclick="window.print()">چاپ برگه</button><p>برگه داخلی فروشگاه؛ این برگه بارنامه یا تعهد خدمات شرکت حمل نیست.</p>';foreach($orders as $order){$s=self::summary($order);$a=$s['address']['fields'];$d=$s['state'];echo '<article><h1>سفارش '.esc_html($s['number']).' — '.esc_html($s['name']).'</h1><p>'.esc_html(implode('، ',[$a['state'],$a['city'],$a['address_1'],$a['address_2'],$a['postcode'],$a['phone']])).'</p><p>قفسه: '.esc_html($d['bin']?:'تعیین نشده').' | اولویت: '.esc_html(self::PRIORITIES[$d['priority']]??'عادی').'</p><p>بسته‌بندی: '.esc_html($d['packing_instruction']).'</p><p>تماس: '.esc_html($d['contact_instruction']).'</p><p>'.($d['recipient_only']?'فقط گیرنده — ':'').($d['do_not_bend']?'خم نشود':'').'</p><p>توقف: '.esc_html($d['hold']?(self::HOLDS[$d['hold']['reason']]??'').': '.$d['hold']['note']:'ندارد').'</p><ul>';foreach(self::CHECKS as $key=>$label)echo '<li>'.(!empty($s['checks'][$key])?'☑ ':'☐ ').esc_html($label).'</li>';echo '</ul></article>';}echo '</html>';exit;}
 public static function page(): void {
  if(!Access::can('operations'))return;$page=isset($_GET['dispatch_page'])?max(1,min(10000,absint($_GET['dispatch_page']))):1;
  echo '<div class="wrap hmx-dispatch" dir="rtl"><h1>کارگاه بازبینی اعزام</h1><p>هر صفحه آخرین ۱۰۰ سفارش قابل دسترسی را بررسی می‌کند. تأیید گیرنده، توقف و قفسه داخلی فروشگاه‌اند؛ هیچ استعلام یا تعهدی از شرکت حمل ندارند. همه تغییرها ابتدا پیش‌نمایش و سپس تأیید می‌شوند.</p><div class="hmx-dispatch-status" role="status" aria-live="polite" data-dispatch-status></div><div class="hmx-dispatch-toolbar"><label>جست‌وجو <input data-dispatch-search type="search"></label><label>صف بازبینی <select data-dispatch-filter><option value="all">همه</option><option value="unverified">مقصد تأییدنشده</option><option value="overdue_hold">توقف سررسیدشده</option><option value="fixable">دارای اصلاح پیشنهادی</option><option value="checklist">چک‌لیست ناقص</option><option value="held">توقف فعال</option></select></label><label>چینش <select data-dispatch-sort><option value="dispatch">اولویت اعزام و سررسید</option><option value="oldest">قدیمی‌تر</option><option value="newest">جدیدتر</option></select></label><button class="button" type="button" data-dispatch-refresh>تازه‌سازی</button><button class="button" type="button" data-dispatch-select>انتخاب قابل‌مشاهده‌ها</button><span data-dispatch-count>۰ انتخاب</span><button class="button" type="button" data-dispatch-bulk>پیش‌نمایش اصلاح گروهی</button></div><p class="hmx-dispatch-binbar">قفسه مقصد (لاتین/عدد) <input data-dispatch-bin maxlength="24" placeholder="QOM-A1"><button type="button" class="button" data-dispatch-addbin>افزودن محل رهاسازی</button></p><div data-dispatch-bins aria-label="محل‌های رهاسازی قفسه"></div><div data-dispatch-rows class="hmx-dispatch-grid"></div><dialog data-dispatch-dialog aria-labelledby="hmx-dispatch-preview-title"><h2 id="hmx-dispatch-preview-title">پیش‌نمایش تغییر</h2><div data-dispatch-preview></div><p>توکن ۱۰ دقیقه اعتبار دارد و یک بار مصرف می‌شود. هر سفارش مستقل ذخیره می‌شود؛ خطاهای جزئی گزارش خواهند شد.</p><button class="button button-primary" type="button" data-dispatch-apply>تأیید و اعمال</button> <button class="button" type="button" data-dispatch-cancel>انصراف</button></dialog>';
  echo '<form data-dispatch-sheet method="post" action="'.esc_url(admin_url('admin-post.php')).'" target="_blank"><input type="hidden" name="action" value="hm_mahex_v34_dispatch_sheet"><input type="hidden" name="ids" value="">';wp_nonce_field('hm_mahex_v34_dispatch_sheet');echo '<button class="button" type="submit">برگه کار انتخاب‌شده‌ها بدون مبالغ مالی</button></form><p>';if($page>1)echo '<a class="button" href="'.esc_url(add_query_arg(['page'=>self::SLUG,'dispatch_page'=>$page-1],admin_url('admin.php'))).'">صفحه قبل</a> ';echo 'صفحه '.(int)$page.' <a class="button" href="'.esc_url(add_query_arg(['page'=>self::SLUG,'dispatch_page'=>$page+1],admin_url('admin.php'))).'">صفحه بعد</a></p><script type="application/json" data-dispatch-data>'.wp_json_encode(['rows'=>self::rows($page),'checks'=>self::CHECKS,'holds'=>self::HOLDS,'priorities'=>self::PRIORITIES,'page'=>$page],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP).'</script></div>';
 }
}
