<?php
namespace HoseinMomeni\MahexWoo\V34;
use HoseinMomeni\MahexWoo\V33\Support;
use HoseinMomeni\MahexWoo\V33\Access;

/** Local promises and exception evidence. No carrier connectivity. */
final class ServicePolicies {
 const OPTION='hm_mahex_v34_service_policy'; const META='_hm_mahex_v34_service_case';
 public static function defaults(): array {return ['revision'=>0,'timezone'=>'Asia/Tehran','weekend'=>[5],'holidays'=>[],'work_start'=>'08:00','cutoff'=>'16:00','transit_days'=>2,'grace_minutes'=>60,'province_days'=>[],'city_days'=>[],'blackout_dates'=>[],'capacity'=>100,'warning_hours'=>12,'max_open'=>10,'required_close_note'=>true,'effort_minutes'=>120,'weekly_shifts'=>[],'breaks'=>[['12:00','13:00']],'date_shifts'=>[]];}
 public static function validate(array $v): array {
  $p=array_replace(self::defaults(),array_intersect_key($v,self::defaults()));
  if(!in_array($p['timezone'],\DateTimeZone::listIdentifiers(),true))throw new \InvalidArgumentException('منطقه زمانی معتبر نیست.');
  foreach(['work_start','cutoff'] as $k)if(!is_string($p[$k])||!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/D',$p[$k]))throw new \InvalidArgumentException('ساعت باید HH:MM باشد.');
  if($p['work_start']>=$p['cutoff'])throw new \InvalidArgumentException('شروع کار باید پیش از ساعت پذیرش باشد.');
  if(!is_array($p['weekend'])||count($p['weekend'])>6)throw new \InvalidArgumentException('حداقل یک روز کاری لازم است.');
  foreach($p['weekend'] as $day)if(!is_int($day)||$day<0||$day>6)throw new \InvalidArgumentException('روز هفته نامعتبر است.');$p['weekend']=array_values(array_unique($p['weekend']));
  foreach(['holidays','blackout_dates'] as $k){if(!is_array($p[$k])||count($p[$k])>366)throw new \InvalidArgumentException('حداکثر ۳۶۶ تاریخ مجاز است.');foreach($p[$k] as $d){if(!is_string($d)||!preg_match('/^(\d{4})-(\d{2})-(\d{2})$/D',$d,$m)||!checkdate((int)$m[2],(int)$m[3],(int)$m[1]))throw new \InvalidArgumentException('تاریخ میلادی معتبر لازم است.');}$p[$k]=array_values(array_unique($p[$k]));sort($p[$k]);}
  foreach(['transit_days'=>30,'grace_minutes'=>1440,'capacity'=>10000,'warning_hours'=>168,'max_open'=>50] as $k=>$max){if(!is_numeric($p[$k])||(int)$p[$k]!=(float)$p[$k]||(int)$p[$k]<($k==='capacity'||$k==='max_open'?1:0)||(int)$p[$k]>$max)throw new \InvalidArgumentException('عدد سیاست خارج از محدوده است.');$p[$k]=(int)$p[$k];}
  foreach(['province_days','city_days'] as $k){if(!is_array($p[$k])||count($p[$k])>200)throw new \InvalidArgumentException('حداکثر ۲۰۰ مسیر مجاز است.');foreach($p[$k] as $name=>$days)if(!is_string($name)||trim($name)===''||strlen($name)>120||!is_numeric($days)||(int)$days!=(float)$days||$days<0||$days>30)throw new \InvalidArgumentException('مسیر و روز نامعتبر است.');$p[$k]=array_map('intval',$p[$k]);}
  foreach(['weekly_shifts','date_shifts','breaks'] as $key){if(!is_array($p[$key])||count($p[$key])>366)throw new \InvalidArgumentException('شیفت نامعتبر است.');foreach($p[$key] as $index=>$pair){if($key==='date_shifts'&&(!preg_match('/^(\d{4})-(\d{2})-(\d{2})$/D',(string)$index,$m)||!checkdate((int)$m[2],(int)$m[3],(int)$m[1])))throw new \InvalidArgumentException('تاریخ شیفت نامعتبر است.');if($key==='weekly_shifts'&&(!is_numeric($index)||$index<0||$index>6))throw new \InvalidArgumentException('روز شیفت نامعتبر است.');if($pair===[]&&$key==='date_shifts')continue;if(!is_array($pair)||count($pair)!==2)throw new \InvalidArgumentException('بازه شیفت لازم است.');foreach($pair as $time)if(!is_string($time)||!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/D',$time))throw new \InvalidArgumentException('ساعت شیفت نامعتبر است.');if($pair[0]>=$pair[1])throw new \InvalidArgumentException('بازه شیفت معکوس است.');}}
  if(!is_numeric($p['effort_minutes'])||(int)$p['effort_minutes']!=(float)$p['effort_minutes']||$p['effort_minutes']<0||$p['effort_minutes']>14400)throw new \InvalidArgumentException('حداکثر ۱۴۴۰۰ دقیقه آماده‌سازی مجاز است.');$p['effort_minutes']=(int)$p['effort_minutes'];
  $p['required_close_note']=(bool)$p['required_close_note'];$p['revision']=max(0,(int)$p['revision']);return $p;
 }
 public static function working(\DateTimeImmutable $d,array $p): bool {if(array_key_exists($d->format('Y-m-d'),$p['date_shifts']))return $p['date_shifts'][$d->format('Y-m-d')]!==[];return !in_array((int)$d->format('w'),$p['weekend'],true)&&!in_array($d->format('Y-m-d'),$p['holidays'],true)&&!in_array($d->format('Y-m-d'),$p['blackout_dates'],true);}
 public static function effort(string $start,array $p): array {
  $d=(new \DateTimeImmutable($start))->setTimezone(new \DateTimeZone($p['timezone']));$seconds=(int)$d->format('s');$micros=(int)$d->format('u');$d=$d->setTime((int)$d->format('H'),(int)$d->format('i'),0);if($seconds>0||$micros>0)$d=$d->modify('+1 minute');$remaining=$p['effort_minutes'];$trace=[];$first=null;
  for($guard=0;$guard<1096;$guard++){
   $date=$d->format('Y-m-d');$window=$p['date_shifts'][$date]??$p['weekly_shifts'][(int)$d->format('w')]??[$p['work_start'],$p['cutoff']];
   if(self::working($d,$p)&&$window!==[]){
    $at=fn(string $t)=>$d->setTime(...array_map('intval',explode(':',$t)));$intervals=[[$at($window[0]),$at($window[1])]];
    foreach($p['breaks'] as $break){$left=$at($break[0]);$right=$at($break[1]);$next=[];foreach($intervals as [$lo,$hi]){if($right<=$lo||$left>=$hi){$next[]=[$lo,$hi];continue;}if($left>$lo)$next[]=[$lo,$left];if($right<$hi)$next[]=[$right,$hi];}$intervals=$next;}
    foreach($intervals as [$lo,$hi]){$cursor=$d>$lo?$d:$lo;if($cursor>=$hi)continue;if($first===null)$first=$cursor;if($remaining===0){$d=$cursor;break 2;}$available=(int)(($hi->getTimestamp()-$cursor->getTimestamp())/60);$used=min($remaining,$available);if($used<=0)continue;$trace[$date]=($trace[$date]??0)+$used;$remaining-=$used;$d=$cursor->modify('+'.$used.' minutes');if($remaining===0)break 2;}
   }
   $d=$d->modify('+1 day')->setTime(0,0);
  }
  if($remaining>0||$first===null)throw new \RuntimeException('آماده‌سازی در افق سه‌ساله ممکن نیست.');return ['start'=>$first->format(DATE_ATOM),'completed'=>$d->format(DATE_ATOM),'minutes'=>$p['effort_minutes'],'daily_minutes'=>$trace];
 }
 public static function summary(array $s,int $now): array {$out=['open'=>0,'critical'=>0,'overdue'=>0,'loss'=>0.0,'recovery'=>0.0,'net'=>0.0];foreach($s['incidents']??[] as $x){if($x['status']!=='closed'){$out['open']++;if($x['severity']==='critical')$out['critical']++;if($x['due_at']<$now)$out['overdue']++;}$out['loss']+=$x['cost']??0;$out['recovery']+=$x['recovery']??0;}$out['net']=$out['loss']-$out['recovery'];return $out;}
 public static function deadline(string $created,array $raw,string $province='',string $city=''): array {
  $p=self::validate($raw);$tz=new \DateTimeZone($p['timezone']);$d=(new \DateTimeImmutable($created))->setTimezone($tz);$reasons=[];
  $preparation=self::effort($d->format(DATE_ATOM),$p);if($preparation['start']!==$d->format(DATE_ATOM))$reasons[]='انتقال به بازه کاری قابل پذیرش';$d=new \DateTimeImmutable($preparation['completed']);$accepted=new \DateTimeImmutable($preparation['start']);$days=$p['transit_days'];$source='default';if(array_key_exists($province,$p['province_days'])){$days=$p['province_days'][$province];$source='province';}if(array_key_exists($city,$p['city_days'])){$days=$p['city_days'][$city];$source='city';}
  $skipped=[];for($n=0,$guard=0;$n<$days;$guard++){if($guard>1095)throw new \RuntimeException('تقویم محدود است.');$d=$d->modify('+1 day');if(self::working($d,$p))$n++;else $skipped[]=$d->format('Y-m-d');}
  $window=$p['date_shifts'][$d->format('Y-m-d')]??$p['weekly_shifts'][(int)$d->format('w')]??[$p['work_start'],$p['cutoff']];$end=$d->setTime(...array_map('intval',explode(':',$window[1])));if($end>$d)$d=$end;$d=$d->modify('+'.$p['grace_minutes'].' minutes');
  return ['accepted_at'=>$accepted->format(DATE_ATOM),'deadline'=>$d->format(DATE_ATOM),'transit_days'=>$days,'route_source'=>$source,'province'=>$province,'city'=>$city,'skipped_dates'=>$skipped,'reasons'=>$reasons,'timezone'=>$p['timezone'],'policy_revision'=>$p['revision'],'local_only'=>true,'preparation'=>$preparation,'policy_hash'=>hash('sha256',json_encode($p))];
 }
 public static function localTimestamp(string $value,string $timezone): int {
  if(!preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?$/D',$value))throw new \InvalidArgumentException('تاریخ و ساعت معتبر لازم است.');
  $format=strlen($value)===16?'!Y-m-d\\TH:i':'!Y-m-d\\TH:i:s';$date=\DateTimeImmutable::createFromFormat($format,$value,new \DateTimeZone($timezone));$errors=\DateTimeImmutable::getLastErrors();
  if(!$date||($errors&&($errors['warning_count']||$errors['error_count'])))throw new \InvalidArgumentException('تاریخ یا ساعت نامعتبر است.');return $date->getTimestamp();
 }
 public static function risk(array $promise,int $now,array $p): string {$remaining=strtotime($promise['deadline'])-$now;return $remaining<0?'overdue':($remaining<=$p['warning_hours']*3600?'warning':'normal');}
 public static function types(): array {return ['address'=>'ابهام آدرس','phone'=>'عدم پاسخ گیرنده','damage'=>'آسیب بسته','missing'=>'کسری محتوا','payment'=>'اختلاف پرداخت','capacity'=>'کمبود ظرفیت','weather'=>'اختلال جوی','delay'=>'تأخیر عملیاتی','document'=>'نقص سند','other'=>'سایر'];}
 public static function transition(array $s,string $command,array $v,int $now,int $actor,array $policy): array {
  $s=array_replace(['incidents'=>[],'history'=>[],'hold'=>false,'promise'=>[]],$s);$id=(string)($v['id']??'');$note=trim((string)($v['note']??''));if(strlen($note)>2000)throw new \InvalidArgumentException('یادداشت بیش از حد مجاز است.');
  if($command==='open'){if(!isset(self::types()[$v['type']??''])||!in_array($v['severity']??'',['low','medium','high','critical'],true)||$note==='')throw new \InvalidArgumentException('نوع، شدت و شرح الزامی است.');$open=array_filter($s['incidents'],fn($x)=>$x['status']!=='closed');if(count($open)>=$policy['max_open']||count($s['incidents'])>=200)throw new \RuntimeException('ظرفیت پرونده‌ها تکمیل است.');if($id===''||isset($s['incidents'][$id]))throw new \InvalidArgumentException('شناسه یکتا لازم است.');$s['incidents'][$id]=['type'=>$v['type'],'severity'=>$v['severity'],'note'=>$note,'status'=>'open','owner'=>$actor,'created_at'=>$now,'due_at'=>$now+86400,'ack_at'=>0,'resolved_at'=>0,'close_note'=>'','cost'=>0,'recovery'=>0,'root_cause'=>'','corrective'=>'','preventive'=>'','contact'=>'','resolution'=>''];}
  elseif(in_array($command,['hold','resume'],true)){$s['hold']=$command==='hold';if($command==='hold'){if(isset($s['paused_at'])&&$s['paused_at'])throw new \RuntimeException('توقف قبلاً ثبت شده است.');$s['paused_at']=$now;}else{if(empty($s['paused_at']))throw new \RuntimeException('توقف فعال وجود ندارد.');$elapsed=max(0,$now-$s['paused_at']);$s['pause_seconds']=($s['pause_seconds']??0)+$elapsed;if(!empty($s['promise']['deadline']))$s['promise']['deadline']=gmdate(DATE_ATOM,strtotime($s['promise']['deadline'])+$elapsed);$s['paused_at']=0;}if($note==='')throw new \InvalidArgumentException('دلیل توقف/ادامه الزامی است.');}
  elseif(in_array($command,['promise','forecast','override'],true)){
   if($command==='forecast')$s['forecast']=$v['promise'];else{if(!empty($s['promise'])){$s['promise_history'][]=$s['promise'];$s['promise_history']=array_slice($s['promise_history'],-50);}if($command==='override'){if($note==='')throw new \InvalidArgumentException('دلیل اصلاح مهلت لازم است.');if(!preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?$/D',(string)($v['deadline']??'')))throw new \InvalidArgumentException('تاریخ و ساعت مهلت الزامی است.');$t=self::localTimestamp((string)($v['deadline']??''),$policy['timezone']);if(!$t||$t<(int)($v['created_at']??0)||$t>$now+365*86400)throw new \InvalidArgumentException('مهلت اصلاح معتبر نیست.');if(empty($s['promise']))throw new \RuntimeException('ابتدا تعهد را ثبت کنید.');$s['promise']['deadline']=gmdate(DATE_ATOM,$t);$s['promise']['override_reason']=$note;}else $s['promise']=$v['promise'];if(empty($s['original_deadline']))$s['original_deadline']=$s['promise']['deadline'];}
  }
  else {if(!isset($s['incidents'][$id]))throw new \InvalidArgumentException('پرونده پیدا نشد.');$x=&$s['incidents'][$id];
   if($command==='ack'){if($x['status']!=='open')throw new \RuntimeException('فقط پرونده باز قابل پذیرش است.');$x['status']='acknowledged';$x['ack_at']=$now;}
   elseif($command==='resolve'){if(!in_array($x['status'],['open','acknowledged'],true))throw new \RuntimeException('گذار وضعیت مجاز نیست.');if($policy['required_close_note']&&$note==='')throw new \InvalidArgumentException('نتیجه رسیدگی الزامی است.');$x['status']='closed';$x['resolved_at']=$now;$x['close_note']=$note;}
   elseif($command==='reopen'){if($x['status']!=='closed'||$note==='')throw new \RuntimeException('بازگشایی با دلیل لازم است.');$x['status']='open';$x['resolved_at']=0;}
   elseif($command==='assign'){$owner=(int)($v['owner']??0);if($owner<1)throw new \InvalidArgumentException('مسئول معتبر لازم است.');$x['owner']=$owner;}
   elseif($command==='due'){ $due=(int)($v['due_at']??0);if($due<$now||$due>$now+90*86400)throw new \InvalidArgumentException('مهلت باید در ۹۰ روز آینده باشد.');$x['due_at']=$due;}
   elseif(in_array($command,['cost','recovery'],true)){$x[$command]=Support::number($v[$command]??'',1000000000);}
   elseif(in_array($command,['root_cause','corrective','preventive','contact','resolution'],true)){if($note==='')throw new \InvalidArgumentException('شرح لازم است.');$x[$command]=$note;}
   else throw new \InvalidArgumentException('عملیات نامعتبر است.');unset($x);
  }
  $s['history'][]=['command'=>$command,'id'=>$id,'at'=>$now,'actor'=>$actor,'note'=>$note];$s['history']=array_slice($s['history'],-200);return $s;
 }
 public static function register(): void {add_action('admin_menu',[self::class,'menu']);add_action('admin_post_hm_mahex_v34_policy',[self::class,'save']);add_action('admin_post_hm_mahex_v34_case_export',[self::class,'export']);add_action('admin_enqueue_scripts',[self::class,'assets']);}
 public static function assets(): void {if(($_GET['page']??'')!=='hm-mahex-service-policies')return;$base=plugins_url('assets/',dirname(__DIR__,2).'/mahex-shipping-for-woocommerce.php');wp_enqueue_style('hm-mahex-v34-policies',$base.'v34-policies.css',[],'3.4.0');wp_enqueue_script('hm-mahex-v34-policies',$base.'v34-policies.js',[],'3.4.0',true);}
 public static function menu(): void {add_submenu_page('hm-mahex','تقویم خدمت و استثناها','تقویم خدمت',Access::can('operations')?'read':Access::OPERATIONS,'hm-mahex-service-policies',[self::class,'page']);}
 public static function policy(): array {return self::validate((array)get_option(self::OPTION,self::defaults()));}
 public static function save(): void {
  $id=absint($_POST['order_id']??0);$command=Support::input('command');Support::auth('hm_mahex_v34_policy',$command==='settings'?'settings':'operations',$id);
  try {if($command==='settings'){$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(-34001))throw new \RuntimeException('تنظیمات قفل است.');try{$p=self::policy();if((int)Support::input('revision')!==$p['revision'])throw new \RuntimeException('سیاست تغییر کرده است.');$json=$p;if(Support::input('policy_json')!=='')$json=json_decode(Support::input('policy_json'),true,16,JSON_THROW_ON_ERROR);else{foreach(['effort_minutes','transit_days','grace_minutes','warning_hours','max_open'] as $key)$json[$key]=Support::input($key,(string)$p[$key]);foreach(['timezone','work_start','cutoff'] as $key)$json[$key]=Support::input($key,$p[$key]);foreach(['holidays','blackout_dates'] as $key)$json[$key]=array_values(array_filter(array_map('trim',preg_split('/[\r\n]+/',Support::input($key,'')))));$json['weekend']=array_map('intval',array_filter(explode(',',Support::input('weekend')),'strlen'));foreach(['weekly_shifts','date_shifts','breaks'] as $key){$json[$key]=[];foreach(preg_split('/[\r\n]+/',Support::input($key,'')) as $line){if(trim($line)==='')continue;$parts=array_map('trim',explode('|',$line));if($key==='breaks'){$json[$key][]=$parts;}else{if(count($parts)!==2)throw new \InvalidArgumentException('بازه را با | جدا کنید.');$json[$key][$parts[0]]=$parts[1]==='closed'?[]:explode('-',$parts[1]);}}}}if(Support::input('policy_json')===''){foreach(['date_shifts','breaks'] as $key){if(isset($_POST[$key.'_start'])){$json[$key]=[];foreach((array)$_POST[$key.'_start'] as $row=>$start){$end=(string)($_POST[$key.'_end'][$row]??'');if($key==='breaks'){if($start!==''||$end!=='')$json[$key][]=[(string)$start,$end];}else{$date=(string)($_POST['date_shifts_date'][$row]??'');if($date!=='')$json[$key][$date]=isset($_POST['date_shifts_closed'][$row])?[]:[(string)$start,$end];}}}}}if(Support::input('policy_json')===''&&isset($_POST['weekly_mode'])){ $json['weekly_shifts']=[];foreach((array)$_POST['weekly_mode'] as $day=>$mode)if($mode==='custom')$json['weekly_shifts'][(int)$day]=[(string)($_POST['weekly_start'][$day]??''),(string)($_POST['weekly_end'][$day]??'')];}if(!is_array($json))throw new \InvalidArgumentException('ساختار JSON لازم است.');$next=self::validate($json);$next['revision']=$p['revision']+1;update_option(self::OPTION,$next,false);}finally{$lock->release(-34001);}}
   else {if(!$id||!wc_get_order($id))throw new \RuntimeException('سفارش معتبر لازم است.');$p=self::policy();$v=['id'=>Support::input('incident_id'),'note'=>Support::input('note'),'type'=>Support::input('type'),'severity'=>Support::input('severity'),'owner'=>Support::input('owner'),'due_at'=>Support::input('due_at'),'cost'=>Support::input('cost'),'recovery'=>Support::input('recovery'),'deadline'=>Support::input('deadline'),'created_at'=>wc_get_order($id)->get_date_created()->getTimestamp()];if($command==='open')$v['id']=wp_generate_uuid4();if($command==='assign'){if(!get_user_by('id',(int)$v['owner'])||!(user_can((int)$v['owner'],Access::OPERATIONS)||user_can((int)$v['owner'],'manage_woocommerce')))throw new \InvalidArgumentException('مسئول مجوز عملیات ندارد.');}if(in_array($command,['cost','recovery'],true)&&!Support::can('finance',$id))throw new \RuntimeException('ثبت هزینه مجوز مالی لازم دارد.');Support::edit($id,self::META,(int)Support::input('revision'),function($s,$o)use($command,$v,$p){\HoseinMomeni\MahexWoo\V33\BoardTools::guardOtherEditor($o->get_id());if($command==='due'){if(!preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?$/D',Support::input('due_at')))throw new \InvalidArgumentException('تاریخ و ساعت رسیدگی الزامی است.');$v['due_at']=self::localTimestamp(Support::input('due_at'),$p['timezone']);}if(in_array($command,['promise','forecast'],true))$v['promise']=self::deadline($o->get_date_created()->date(DATE_ATOM),$p,$o->get_shipping_state(),$o->get_shipping_city());return self::transition($s,$command,$v,time(),get_current_user_id(),$p);});}
   \HoseinMomeni\MahexWoo\V1\ActivityLog::write('service_policy.'.$command,'سیاست خدمت یا پرونده عملیاتی تغییر کرد.',$id);$message='ذخیره شد.';
  }catch(\Throwable $e){$message=$e->getMessage();}$returnId=$command==='settings'?absint($_POST['return_order_id']??0):$id;if($returnId&&!Support::can('operations',$returnId))$returnId=0;Support::redirect('hm-mahex-service-policies',$message,$returnId);
 }
 public static function export(): void {$id=absint($_GET['order_id']??0);Support::auth('hm_mahex_v34_case_export','operations',$id);$o=wc_get_order($id);if(!$o)wp_die('سفارش نامعتبر است.');$s=$o->get_meta(self::META,true);if(!Support::can('finance',$id)&&is_array($s)){foreach(array_keys($s['incidents']??[]) as $key){unset($s['incidents'][$key]['cost'],$s['incidents'][$key]['recovery']);}foreach($s['history']??[] as $key=>$h)if(in_array($h['command'],['cost','recovery'],true))unset($s['history'][$key]);}nocache_headers();header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="mahex-case-'.$id.'.json"');header('X-Content-Type-Options: nosniff');echo wp_json_encode(['order_id'=>$id,'case'=>$s],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;}
 public static function page(): void {
  if(!Support::can('operations'))wp_die('دسترسی مجاز نیست.');$p=self::policy();$id=absint($_GET['order_id']??0);echo '<div class="wrap hmx-service" dir="rtl"><h1>تقویم تعهد محلی و پرونده استثنا</h1><p>برآورد برنامه داخلی فروشگاه است؛ وضعیت یا تعهد شرکت حمل نیست. تاریخ تعطیلی میلادی است.</p>';Support::notice();
  if(Support::can('settings')){echo '<details><summary>تنظیم تقویم و قواعد مسیر</summary>';Support::form('hm_mahex_v34_policy');echo '<input type="hidden" name="command" value="settings"><input type="hidden" name="revision" value="'.esc_attr($p['revision']).'">';echo '<input type="hidden" name="return_order_id" value="'.esc_attr($id).'">';self::settingsFields($p);echo '<button class="button button-primary">ذخیره سیاست</button></form></details>';}
  Support::orderChooser('hm-mahex-service-policies',$id);$o=$id?wc_get_order($id):null;if($o&&Support::can('operations',$id)){$s=$o->get_meta(self::META,true);$s=is_array($s)?$s:[];$preview=self::deadline($o->get_date_created()->date(DATE_ATOM),$p,$o->get_shipping_state(),$o->get_shipping_city());echo '<section><h2>برآورد سفارش #'.esc_html($id).'</h2><p>مهلت: '.esc_html($preview['deadline']).' | مسیر: '.esc_html(['default'=>'پیش‌فرض','province'=>'استان','city'=>'شهر'][$preview['route_source']]).' | ریسک: '.esc_html(['normal'=>'عادی','warning'=>'نزدیک مهلت','overdue'=>'گذشته از مهلت'][self::risk($s['promise']??$preview,time(),$p)]).'</p><p>روزهای حذف‌شده: '.esc_html(implode('، ',$preview['skipped_dates'])).' | دلایل: '.esc_html(implode('، ',$preview['reasons'])).'</p><p>وضعیت داخلی: '.esc_html(!empty($s['hold'])?'متوقف':'فعال').'</p>';self::form($id,$s,'promise','ثبت نسخه ثابت تعهد');self::form($id,$s,'forecast','برآورد جدید مستقل');self::form($id,$s,'override','اصلاح مهلت با دلیل',false,true,'','deadline');echo '<p>پذیرش مؤثر: '.esc_html($preview['accepted_at']).'</p>';echo '<p>آماده‌سازی: '.esc_html($preview['preparation']['minutes']).' دقیقه | تکمیل: '.esc_html($preview['preparation']['completed']).'</p>';echo '<details><summary>صورت ریز آماده‌سازی روزانه</summary><ul>';foreach($preview['preparation']['daily_minutes'] as $day=>$minutes)echo '<li>'.esc_html($day.' — '.$minutes.' دقیقه').'</li>';echo '</ul></details>';if(!empty($s['promise']['policy_hash'])&&$s['promise']['policy_hash']!==$preview['policy_hash'])echo '<p class="notice notice-warning">سیاست از زمان ثبت تعهد تغییر کرده است.</p>';echo '<p>مهلت اصلی: '.esc_html($s['original_deadline']??'').' | توقف انباشته: '.esc_html($s['pause_seconds']??0).' ثانیه</p>';if(!empty($s['forecast']))echo '<p>برآورد جدید: '.esc_html($s['forecast']['deadline']).'</p>';echo '<details><summary>نسخه‌های تعهد</summary><pre>'.esc_html(wp_json_encode($s['promise_history']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre></details>';echo '<p><a class="button" href="'.esc_url(wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v34_case_export','order_id'=>$id],admin_url('admin-post.php')),'hm_mahex_v34_case_export')).'">خروجی خصوصی پرونده JSON</a></p>'; $summary=self::summary($s,time());$currency=$o->get_currency();echo '<p>باز: '.esc_html($summary['open']).' | بحرانی: '.esc_html($summary['critical']).' | معوق: '.esc_html($summary['overdue']).'</p>';if(Support::can('finance',$id))echo '<p>زیان: '.esc_html($summary['loss']).' | بازیافت: '.esc_html($summary['recovery']).' | خالص: '.esc_html($summary['net']).' | واحد پول سفارش: '.esc_html($currency).'</p>';echo '<input type="search" class="hmx-case-search" placeholder="جست‌وجوی پرونده">';echo '</section><section><h2>ثبت استثنا</h2>';self::form($id,$s,'open','ثبت پرونده',true);echo '</section><section><h2>توقف یا ادامه</h2>';self::form($id,$s,empty($s['hold'])?'hold':'resume',empty($s['hold'])?'توقف با دلیل':'ادامه با دلیل',false,true);echo '</section>';
   foreach($s['incidents']??[] as $incidentId=>$x){echo '<section class="hmx-incident" data-severity="'.esc_attr($x['severity']).'"><h3>'.esc_html(self::types()[$x['type']].' — '.(['open'=>'باز','acknowledged'=>'در رسیدگی','closed'=>'بسته'][$x['status']])).'</h3><p>'.esc_html($x['note']).'</p><p>مسئول: '.esc_html($x['owner']).' | مهلت: '.esc_html(gmdate('c',$x['due_at'])).' | سن: '.esc_html(max(0,(int)((time()-$x['created_at'])/3600))).' ساعت</p>';if($x['status']==='open')self::form($id,$s,'ack','پذیرش رسیدگی',false,false,$incidentId);self::form($id,$s,$x['status']==='closed'?'reopen':'resolve',$x['status']==='closed'?'بازگشایی':'بستن پرونده',false,true,$incidentId);self::form($id,$s,'assign','تغییر مسئول',false,false,$incidentId,'owner');self::form($id,$s,'due','تغییر مهلت رسیدگی',false,false,$incidentId,'due_at');if(Support::can('finance',$id)){echo '<p>هزینه ثبت‌شده: '.esc_html($x['cost']).' | واحد پول: '.esc_html($currency).'</p>';self::form($id,$s,'cost','ثبت هزینه استثنا ('.$currency.')',false,false,$incidentId,'cost');}foreach(['root_cause'=>'علت ریشه‌ای','corrective'=>'اقدام اصلاحی','preventive'=>'اقدام پیشگیرانه','contact'=>'نتیجه تماس','resolution'=>'طبقه نتیجه'] as $key=>$title){echo '<p>'.esc_html($title.': '.($x[$key]??'')).'</p>';self::form($id,$s,$key,$title,false,true,$incidentId);}echo '<p>زمان پذیرش: '.esc_html($x['ack_at']?max(0,$x['ack_at']-$x['created_at']):0).' ثانیه | زمان حل: '.esc_html($x['resolved_at']?max(0,$x['resolved_at']-$x['created_at']):0).' ثانیه | '.esc_html($x['status']!=='closed'&&$x['due_at']<time()?'مهلت گذشته':'در مهلت').'</p>';if(Support::can('finance',$id))self::form($id,$s,'recovery','مبلغ بازیافت ('.$currency.')',false,false,$incidentId,'recovery');echo '</section>';}
   echo '<details><summary>سوابق تغییرات</summary><ol>';foreach(array_reverse($s['history']??[]) as $h)echo '<li>'.esc_html(gmdate('c',$h['at']).' '.$h['command'].' '.$h['actor'].' '.$h['note']).'</li>';echo '</ol></details>';
  }
  echo '</div>';
 }
 private static function settingsFields(array $p): void {
  foreach(['effort_minutes'=>'آماده‌سازی (دقیقه)','transit_days'=>'حمل محلی (روز کاری)','grace_minutes'=>'فرجه (دقیقه)','warning_hours'=>'هشدار (ساعت)','max_open'=>'سقف پرونده باز'] as $key=>$label)echo '<label>'.esc_html($label).' <input type="number" min="0" name="'.esc_attr($key).'" value="'.esc_attr($p[$key]).'"></label>';
  foreach(['timezone'=>'منطقه زمانی','work_start'=>'شروع شیفت','cutoff'=>'پایان شیفت','weekend'=>'روزهای تعطیل هفتگی (۰ یکشنبه تا ۶ شنبه)'] as $key=>$label)echo '<label>'.esc_html($label).' <input name="'.esc_attr($key).'" value="'.esc_attr($key==='weekend'?implode(',',$p[$key]):$p[$key]).'"></label>';
  echo '<fieldset class="hmx-weekly-editor"><legend>شیفت هر روز هفته</legend><p>انتخاب «پیش‌فرض» از ساعات عمومی استفاده می‌کند. تعطیلی هفتگی از فیلد روزهای تعطیل پیروی می‌کند.</p>';
  foreach(['یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه','شنبه'] as $day=>$name){$pair=$p['weekly_shifts'][$day]??[$p['work_start'],$p['cutoff']];echo '<label>'.esc_html($name).' <select name="weekly_mode['.$day.']"><option value="default">پیش‌فرض</option><option value="custom" '.(isset($p['weekly_shifts'][$day])?'selected':'').'>شیفت اختصاصی</option></select><input type="time" name="weekly_start['.$day.']" value="'.esc_attr($pair[0]).'" aria-label="شروع '.esc_attr($name).'"><input type="time" name="weekly_end['.$day.']" value="'.esc_attr($pair[1]).'" aria-label="پایان '.esc_attr($name).'"></label>';}
  echo '</fieldset>';
  foreach(['breaks'=>'بازه‌های استراحت','date_shifts'=>'شیفت استثنایی تاریخ'] as $key=>$title){echo '<fieldset class="hmx-interval-editor" data-kind="'.esc_attr($key).'"><legend>'.esc_html($title).'</legend>'; $rows=$p[$key];if(!$rows)$rows=$key==='breaks'?[['','']]:[''=>['','']];$row=0;foreach($rows as $date=>$pair){echo '<div class="hmx-interval-row">';if($key==='date_shifts')echo '<label>تاریخ میلادی <input type="date" name="date_shifts_date['.$row.']" value="'.esc_attr($date).'"></label><label><input type="checkbox" name="date_shifts_closed['.$row.']" '.($pair===[]?'checked':'').'>بسته</label>';echo '<label>شروع <input type="time" name="'.$key.'_start['.$row.']" value="'.esc_attr($pair[0]??'').'"></label><label>پایان <input type="time" name="'.$key.'_end['.$row.']" value="'.esc_attr($pair[1]??'').'"></label><button type="button" class="button hmx-remove-interval">حذف بازه</button></div>';$row++;}echo '<button type="button" class="button hmx-add-interval">افزودن بازه</button></fieldset>';}
  foreach(['holidays'=>'تعطیلات؛ هر سطر تاریخ میلادی','blackout_dates'=>'توقف پذیرش؛ هر سطر تاریخ میلادی'] as $key=>$label){$lines=[];foreach($p[$key] as $index=>$pair)$lines[]=in_array($key,['holidays','blackout_dates'],true)?$pair:($key==='breaks'?implode('|',$pair):$index.'|'.($pair===[]?'closed':implode('-',$pair)));echo '<label>'.esc_html($label).'<textarea name="'.esc_attr($key).'" rows="3" dir="ltr">'.esc_textarea(implode("\n",$lines)).'</textarea></label>';}
  echo '<details><summary>تنظیم پیشرفته اختیاری</summary><p>تنها در صورت نیاز وارد کنید؛ در غیر این صورت فیلدهای بالا ذخیره می‌شوند.</p><textarea name="policy_json" rows="8" dir="ltr" aria-label="سیاست پیشرفته"></textarea></details>';
 }
 private static function form(int $id,array $s,string $command,string $label,bool $open=false,bool $note=false,string $incident='',string $field=''): void {Support::form('hm_mahex_v34_policy');foreach(['order_id'=>$id,'revision'=>$s['revision']??0,'command'=>$command,'incident_id'=>$incident] as $k=>$v)echo '<input type="hidden" name="'.esc_attr($k).'" value="'.esc_attr($v).'">';if($open){echo '<select name="type" aria-label="نوع استثنا">';foreach(self::types() as $k=>$v)echo '<option value="'.esc_attr($k).'">'.esc_html($v).'</option>';echo '</select><select name="severity" aria-label="شدت">';foreach(['low'=>'کم','medium'=>'متوسط','high'=>'زیاد','critical'=>'بحرانی'] as $k=>$v)echo '<option value="'.esc_attr($k).'">'.esc_html($v).'</option>';echo '</select>';}$note=$note||$open;if($note)echo '<input name="note" maxlength="1000" placeholder="دلیل یا نتیجه" required>';if($field)echo '<input type="'.(in_array($field,['deadline','due_at'],true)?'datetime-local':'number').'" min="'.(in_array($field,['deadline','due_at'],true)?'':'0').'" name="'.esc_attr($field).'" aria-label="'.esc_attr($field).'" required>';echo '<button class="button">'.esc_html($label).'</button></form>';}
}
