<?php
namespace HoseinMomeni\MahexWoo\V33;

final class Access {
 const FINANCE='hm_mahex_view_finance';const PACK='hm_mahex_pack_shipments';const PRINT_DOCS='hm_mahex_print_documents';const SETTINGS='hm_mahex_manage_settings';const OPERATIONS='hm_mahex_manage_shipping';
 public static function register(): void {add_action('init',[self::class,'install'],35);add_action('admin_menu',[self::class,'menu'],50);add_action('admin_post_hm_mahex_v33_access',[self::class,'save']);}
 public static function cap(string $area): string {return ['finance'=>self::FINANCE,'packing'=>self::PACK,'print'=>self::PRINT_DOCS,'operations'=>self::OPERATIONS,'settings'=>self::SETTINGS][$area]??$area;}
 public static function can(string $area,int $orderId=0): bool {$cap=self::cap($area);if(!in_array($cap,[self::FINANCE,self::PACK,self::PRINT_DOCS,self::OPERATIONS,self::SETTINGS],true))return false;$allowed=current_user_can('manage_woocommerce')||current_user_can($cap);return $allowed&&(!$orderId||current_user_can('edit_shop_order',$orderId));}
 public static function install(): void {
  foreach(['administrator','shop_manager'] as $slug){$role=get_role($slug);if($role)foreach([self::FINANCE,self::PACK,self::PRINT_DOCS,self::SETTINGS,self::OPERATIONS] as $cap)$role->add_cap($cap);}
  foreach(['mahex_print_only'=>['چاپ‌کار ماهکس',self::PRINT_DOCS],'mahex_finance_only'=>['حسابدار ماهکس',self::FINANCE],'mahex_packing_only'=>['بسته‌بند ماهکس',self::PACK]] as $slug=>[$name,$cap]){if(!get_role($slug))add_role($slug,$name,['view_admin_dashboard'=>true,'read'=>true,'edit_shop_orders'=>true,'edit_others_shop_orders'=>true,'edit_published_shop_orders'=>true,'read_private_shop_orders'=>true,$cap=>true]);$role=get_role($slug);if($role){$role->add_cap('view_admin_dashboard');if($slug==='mahex_packing_only')$role->add_cap('upload_files');}}
 }
 public static function menu(): void {add_submenu_page('hm-mahex','دسترسی تیم','دسترسی تیم','manage_woocommerce','hm-mahex-access',[self::class,'page']);}
 public static function page(): void {if(!current_user_can('manage_woocommerce'))return;echo '<div class="wrap" dir="rtl"><h1>دسترسی تیم ماهکس</h1><p>این مجوزها صفحات و عملیات افزونه را محدود می‌کنند؛ مجوزهای عمومی وردپرس و افزونه‌های دیگر مستقل هستند. مدیر و مدیر فروشگاه همیشه دسترسی کامل دارند.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('hm_mahex_v33_access');echo '<input type="hidden" name="action" value="hm_mahex_v33_access"><label>شناسه کاربر <input type="number" name="user_id" min="1" required></label>';foreach([self::FINANCE=>'امور مالی',self::PACK=>'بسته‌بندی',self::PRINT_DOCS=>'چاپ',self::SETTINGS=>'تنظیمات و قوانین',self::OPERATIONS=>'عملیات ارسال'] as $cap=>$label)echo '<p><label><input type="checkbox" name="caps[]" value="'.esc_attr($cap).'">'.esc_html($label).'</label></p>';submit_button('ذخیره دسترسی‌های افزونه');echo '</form></div>';}
 public static function save(): void {if(!current_user_can('manage_woocommerce'))wp_die('دسترسی مجاز نیست.');check_admin_referer('hm_mahex_v33_access');$user=get_user_by('id',absint($_POST['user_id']??0));if(!$user||user_can($user,'manage_woocommerce'))wp_die('کاربر نامعتبر یا مدیر است.');$caps=array_filter((array)wp_unslash($_POST['caps']??[]),'is_string');foreach([self::FINANCE,self::PACK,self::PRINT_DOCS,self::SETTINGS,self::OPERATIONS] as $cap)$user->add_cap($cap,in_array($cap,$caps,true));if($caps)$user->add_cap('view_admin_dashboard');\HoseinMomeni\MahexWoo\V1\ActivityLog::write('access.updated','مجوزهای افزونه برای کاربر تغییر کرد.',0,['user_id'=>$user->ID,'caps'=>$caps]);wp_safe_redirect(admin_url('admin.php?page=hm-mahex-access'));exit;}
}
