<?php
namespace HoseinMomeni\MahexWoo\V33;
use HoseinMomeni\MahexWoo\V32\Board;

final class BoardTools {
 const OPTION='hm_mahex_v33_board_settings';const FILTERS='hm_mahex_v33_board_filters';
 public static function register(): void {add_action('admin_menu',[self::class,'menu'],47);add_action('admin_enqueue_scripts',[self::class,'assets']);add_action('wp_ajax_hm_mahex_v33_boardtools',[self::class,'ajax']);add_action('admin_post_hm_mahex_v33_board_settings',[self::class,'settingsSave']);}
 public static function menu(): void {add_submenu_page('hm-mahex','برد زنده و دفتر تحویل','برد زنده و تحویل',Access::cap('operations'),'hm-mahex-v33-live',[self::class,'page']);}
 public static function assets(string $hook): void {if(strpos($hook,'hm-mahex-v33-live')===false)return;wp_enqueue_script('hm-mahex-v33-board',plugins_url('assets/admin/v33-board.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_enqueue_style('hm-mahex-v33-station',plugins_url('assets/admin/v33-station.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_localize_script('hm-mahex-v33-board','hmBoardTools',['url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('hm_mahex_v33_boardtools')]);}
 public static function settings(): array {$o=get_option(self::OPTION,[]);return array_merge(['deadline_hours'=>48,'capacities'=>[]],is_array($o)?$o:[]);}
 public static function lease(int $id): array {$lease=get_option('hm_mahex_v33_lease_'.$id,[]);return is_array($lease)&&($lease['expires']??0)>time()?$lease:[];}
 public static function assertLease(int $id,string $token): void {$lease=self::lease($id);if(!$lease||$lease['actor']!==get_current_user_id()||!hash_equals($lease['token'],$token))throw new \RuntimeException('قفل ایستگاه در اختیار شما نیست؛ شروع کار را بزنید.');$lease['expires']=time()+120;update_option('hm_mahex_v33_lease_'.$id,$lease,false);}
 /** For shared Board/Packing controllers: block foreign active station editors. */
 public static function guardOtherEditor(int $id): void {$lease=self::lease($id);if($lease&&$lease['actor']!==get_current_user_id())throw new \RuntimeException('ایستگاه این سفارش در اختیار اپراتور #'.$lease['actor'].' است.');}
 public static function claim(int $id,string $intent,string $token): array {
  if((!Access::can('packing',$id)&&!Access::can('operations',$id))||!wc_get_order($id))throw new \RuntimeException('دسترسی سفارش مجاز نیست.');$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire($id))throw new \RuntimeException('سفارش در حال ویرایش است.');try{
   $lease=self::lease($id);$key='hm_mahex_v33_lease_'.$id;
   if($intent==='release'){if($lease&&($lease['actor']!==get_current_user_id()||!hash_equals($lease['token'],$token)))throw new \RuntimeException('قفل متعلق به این صفحه نیست.');delete_option($key);return [];}
   if($lease&&(!hash_equals($lease['token'],$token)||$lease['actor']!==get_current_user_id()))throw new \RuntimeException('اپراتور #'.$lease['actor'].' روی این سفارش کار می‌کند.');
   $next=['actor'=>get_current_user_id(),'token'=>$lease['token']??wp_generate_password(32,false),'expires'=>time()+120];update_option($key,$next,false);return $next;
  }finally{$lock->release($id);}
 }
 public static function timing(int $created,int $stageEntered,int $now,int $deadlineHours): array {return ['age_hours'=>round(max(0,$now-$created)/3600,1),'stage_hours'=>round(max(0,$now-$stageEntered)/3600,1),'deadline'=>gmdate('c',$created+$deadlineHours*3600),'late'=>$now>$created+$deadlineHours*3600];}
 public static function candidates(array $capacities,array $daily,array $loads): array {$result=[];foreach($capacities as $id=>$capacity)if($capacity>0&&($daily[$id]??0)<$capacity)$result[(int)$id]=($loads[$id]??0)/$capacity;asort($result,SORT_NUMERIC);return array_keys($result);}
 public static function rows(): array {
  $orders=wc_get_orders(['limit'=>500,'status'=>['pending','processing','on-hold','completed'],'orderby'=>'date','order'=>'DESC']);$settings=self::settings();$rows=[];
  foreach($orders as $order){$id=$order->get_id();if(!Access::can('operations',$id))continue;$board=Board::state($order);$created=$order->get_date_created();$timestamp=$created?$created->getTimestamp():time();$history=$board['history'];$entered=$timestamp;foreach($history as $event)if(($event['from']??'')!==($event['to']??''))$entered=strtotime($event['at'])?:$entered;$lease=self::lease($id);$station=Station::data($order);
   $rows[]=['id'=>$id,'order_status'=>$order->get_status(),'number'=>$order->get_order_number(),'name'=>$order->get_formatted_billing_full_name(),'city'=>$order->get_shipping_city()?:$order->get_billing_city(),'stage'=>$board['stage'],'operator'=>$board['operator'],'revision'=>$board['revision'],'history'=>$history,'timing'=>self::timing($timestamp,$entered?:$timestamp,time(),(int)$settings['deadline_hours']),'lease'=>$lease?['actor'=>$lease['actor'],'expires'=>$lease['expires']]:null,'station'=>['pickup'=>$station['pickup']??null,'handover'=>$station['handover']??null],'url'=>add_query_arg(['page'=>'hm-mahex-v33-station','order_id'=>$id],admin_url('admin.php'))];
  }return $rows;
 }
 public static function settingsSave(): void {if(!Access::can('settings'))wp_die('دسترسی مجاز نیست.','',['response'=>403]);check_admin_referer('hm_mahex_v33_board_settings');$hours=absint($_POST['deadline_hours']??48);$caps=isset($_POST['capacities'])&&is_string($_POST['capacities'])?json_decode(wp_unslash($_POST['capacities']),true):null;if($hours<1||$hours>720||!is_array($caps)||count($caps)>100)wp_die('مهلت یا ظرفیت نامعتبر است.');$clean=[];foreach($caps as $id=>$value){if(!ctype_digit((string)$id)||!(user_can((int)$id,'manage_woocommerce')||user_can((int)$id,Access::PACK)||user_can((int)$id,Access::OPERATIONS))||!is_numeric($value)||$value<0||$value>10000)wp_die('اپراتور یا ظرفیت نامعتبر است.');$clean[(int)$id]=(int)$value;}update_option(self::OPTION,['deadline_hours'=>$hours,'capacities'=>$clean],false);wp_safe_redirect(admin_url('admin.php?page=hm-mahex-v33-live'));exit;}
 public static function autoAssign(): array {
  $rows=self::rows();$caps=self::settings()['capacities'];$daily=[];$loads=[];$today=wp_date('Y-m-d');
  foreach($rows as $row){$operator=$row['operator'];if($operator&&$row['stage']!=='ready'&&$row['order_status']!=='completed')$loads[$operator]=($loads[$operator]??0)+1;$todayActors=[];foreach($row['history'] as $event){$ts=strtotime($event['at']??'');$assignee=(int)($event['operator_to']??0);if($ts&&wp_date('Y-m-d',$ts)===$today&&$assignee)$todayActors[$assignee]=true;}foreach($todayActors as $assignee=>$_)$daily[$assignee]=($daily[$assignee]??0)+1;}
  usort($rows,static fn($a,$b)=>$b['timing']['age_hours']<=>$a['timing']['age_hours']);$done=[];$fail=[];
  foreach($rows as $row){if($row['operator']||$row['stage']==='ready'||$row['order_status']==='completed')continue;$candidates=self::candidates($caps,$daily,$loads);if(!$candidates)break;$operator=$candidates[0];try{self::guardOtherEditor($row['id']);Board::update($row['id'],$row['revision'],$row['stage'],$operator);$loads[$operator]=($loads[$operator]??0)+1;$daily[$operator]=($daily[$operator]??0)+1;$done[]=$row['id'];}catch(\Throwable $e){$fail[]='#'.$row['id'].': '.$e->getMessage();}}
  return ['assigned'=>$done,'errors'=>$fail];
 }
 public static function ajax(): void {
  if(!check_ajax_referer('hm_mahex_v33_boardtools','nonce',false))wp_send_json_error(['message'=>'دسترسی مجاز نیست.'],403);$intent=isset($_POST['intent'])&&is_string($_POST['intent'])?sanitize_key($_POST['intent']):'';
  try{
   if(in_array($intent,['claim','heartbeat','release'],true)){if(!Access::can('packing')&&!Access::can('operations'))throw new \RuntimeException('دسترسی ایستگاه مجاز نیست.');}elseif(!Access::can('operations'))throw new \RuntimeException('دسترسی عملیات مجاز نیست.');
   if(in_array($intent,['claim','heartbeat','release'],true)){$token=isset($_POST['token'])&&is_string($_POST['token'])?wp_unslash($_POST['token']):'';$data=self::claim(absint($_POST['order_id']??0),$intent,$token);}
   elseif($intent==='poll'){$data=['rows'=>self::rows(),'at'=>gmdate('c')];}
   elseif($intent==='save_filter'){$filter=isset($_POST['filter'])&&is_string($_POST['filter'])?json_decode(wp_unslash($_POST['filter']),true):null;if(!is_array($filter))throw new \InvalidArgumentException('فیلتر معتبر نیست.');$name=sanitize_text_field((string)($filter['name']??''));if(!$name||strlen($name)>100)throw new \InvalidArgumentException('نام فیلتر معتبر نیست.');$saved=get_user_meta(get_current_user_id(),self::FILTERS,true);$saved=is_array($saved)?$saved:[];$saved[$name]=['q'=>sanitize_text_field((string)($filter['q']??'')),'stage'=>isset(Board::STAGES[$filter['stage']??''])?$filter['stage']:'','operator'=>absint($filter['operator']??0),'late'=>!empty($filter['late'])];if(count($saved)>20)throw new \InvalidArgumentException('حداکثر ۲۰ فیلتر مجاز است.');update_user_meta(get_current_user_id(),self::FILTERS,$saved);$data=['filters'=>$saved];}
   elseif($intent==='assign'){$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(-3302,60))throw new \RuntimeException('تخصیص دیگری در حال اجراست.');try{$data=self::autoAssign();}finally{$lock->release(-3302);}}
   else throw new \InvalidArgumentException('عملیات ناشناخته است.');wp_send_json_success($data);
  }catch(\Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],409);}
 }
 public static function page(): void {
  if(!Access::can('operations'))return;$s=self::settings();$filters=get_user_meta(get_current_user_id(),self::FILTERS,true);$filters=is_array($filters)?$filters:[];echo '<div class="wrap hmx-live" dir="rtl"><h1>برد زنده، مهلت و دفتر تحویل</h1><p>نمای آخرین ۵۰۰ سفارش؛ تازه‌سازی هر ۱۵ ثانیه. ظرفیت و بار کاری تخصیص خودکار در همین محدوده محاسبه می‌شوند. ظرفیت روزانه تعداد سفارش واگذارشده است، نه تعداد بسته.</p><p data-live-status role="status"></p><label>جست‌وجوی سریع شماره/نام/شهر <input data-live-search></label><label>مرحله <select data-live-stage><option value="">همه</option>';foreach(Board::STAGES as $key=>$label)echo '<option value="'.esc_attr($key).'">'.esc_html($label).'</option>';echo '</select></label><label>اپراتور # <input type="number" min="0" data-live-operator value="0"></label><label><input type="checkbox" data-live-late>فقط دیرکرد</label><p><input data-filter-name placeholder="نام فیلتر"><button type="button" class="button" data-filter-save>ذخیره فیلتر</button><select data-filter-select><option value="">انتخاب فیلتر</option>';foreach($filters as $name=>$_)echo '<option>'.esc_html($name).'</option>';echo '</select><button class="button" type="button" data-autoassign>تخصیص خودکار طبق ظرفیت</button><button class="button" type="button" data-live-refresh>تازه‌سازی</button></p><table class="widefat striped"><thead><tr><th>سفارش</th><th>مرحله / مسئول</th><th>سن / توقف</th><th>مهلت</th><th>قفل ایستگاه</th><th>جمع‌آوری / تحویل</th></tr></thead><tbody data-live-rows></tbody></table><h2>ظرفیت اپراتورها و مهلت</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v33_board_settings">';wp_nonce_field('hm_mahex_v33_board_settings');echo '<label>مهلت از ساخت سفارش (ساعت) <input name="deadline_hours" type="number" min="1" max="720" value="'.(int)$s['deadline_hours'].'"></label><p>ظرفیت به شکل JSON شناسه اپراتور: تعداد سفارش در روز. صفر یعنی از تخصیص خودکار خارج شود.</p><textarea class="large-text code" rows="4" dir="ltr" name="capacities">'.esc_textarea(wp_json_encode($s['capacities'],JSON_PRETTY_PRINT)).'</textarea><button class="button">ذخیره ظرفیت و مهلت</button></form><script type="application/json" data-live-data>'.wp_json_encode(['rows'=>self::rows(),'filters'=>$filters,'stages'=>Board::STAGES],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP).'</script></div>';
 }
}
