<?php
namespace HoseinMomeni\MahexWoo\V33;

use HoseinMomeni\MahexWoo\V31\Finance;
use HoseinMomeni\MahexWoo\Shipments\OrderShipmentStore;

final class Management {
 const IMPORT='hm_mahex_v33_settings_preview_';const BILLS='hm_mahex_v33_bills_preview_';
 public static function register(): void {add_action('admin_menu',[self::class,'menu']);add_action('admin_post_hm_mahex_v33_management',[self::class,'request']);add_action('admin_enqueue_scripts',[self::class,'assets']);}
 public static function menu(): void {add_submenu_page('hm-mahex','تطبیق صورتحساب حمل','تطبیق صورتحساب',Access::FINANCE,'hm-mahex-reconciliation',[self::class,'billsPage']);add_submenu_page('hm-mahex','سود تفکیکی','سود تفکیکی',Access::FINANCE,'hm-mahex-profit-groups',[self::class,'profitPage']);add_submenu_page('hm-mahex','انتقال و بررسی ارتقا','انتقال و بررسی ارتقا',Access::SETTINGS,'hm-mahex-settings-transfer',[self::class,'settingsPage']);}
 public static function assets(): void {if(!in_array(sanitize_key($_GET['page']??''),['hm-mahex-reconciliation','hm-mahex-profit-groups','hm-mahex-settings-transfer','hm-mahex-rule-versions','hm-mahex-access'],true))return;wp_enqueue_style('hm-mahex-v33-management',plugins_url('assets/admin/v33-management.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_enqueue_script('hm-mahex-v33-management',plugins_url('assets/admin/v33-management.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);}
 public static function waybills($order): array {$out=[];foreach((new OrderShipmentStore())->getAll($order) as $s)if($s->waybill_number!=='')$out[]=$s->waybill_number;$v=(string)$order->get_meta('_hm_mahex_waybill_number',true);if($v!=='')$out[]=$v;return array_values(array_unique($out));}
 public static function resolveOrder(string $id,string $waybill) {
  if($id!==''&&ctype_digit($id))return wc_get_order((int)$id);if($waybill==='')return false;
  // Bounded scan is explicit; a supplied order ID is the reliable route on large stores.
  $matches=[];foreach(wc_get_orders(['limit'=>500,'orderby'=>'date','order'=>'DESC']) as $order)if(in_array($waybill,self::waybills($order),true))$matches[]=$order;return count($matches)===1?$matches[0]:false;
 }
 public static function parseBills(string $path): array {
  $h=fopen($path,'rb');if(!$h)throw new \InvalidArgumentException('فایل قابل خواندن نیست.');$rows=[];$seen=[];
  try{$header=fgetcsv($h,0,',','"','');if($header)$header[0]=preg_replace('/^\xEF\xBB\xBF/','',$header[0]);if($header!==['order_id','waybill','amount','currency'])throw new \InvalidArgumentException('ستون‌ها باید order_id,waybill,amount,currency باشند.');
   while(($cells=fgetcsv($h,0,',','"',''))!==false){if(count($rows)>=500)throw new \InvalidArgumentException('حداکثر ۵۰۰ ردیف مجاز است.');if($cells===[null])continue;$errors=[];if(count($cells)!==4){$rows[]=['data'=>$cells,'errors'=>['تعداد ستون نامعتبر است.']];continue;}[$id,$waybill,$amount,$currency]=array_map('trim',$cells);if(!is_numeric($amount)||!is_finite((float)$amount)||(float)$amount<0)$errors[]='مبلغ نامعتبر است.';if(!in_array($currency,['IRR','IRT'],true))$errors[]='واحد پول باید IRR یا IRT باشد.';if($id!==''&&!ctype_digit($id))$errors[]='شناسه سفارش باید عددی باشد.';$order=self::resolveOrder($id,$waybill);if(!$order||!Access::can('finance',$order?$order->get_id():0))$errors[]='سفارش مجاز پیدا نشد (جست‌وجوی بارنامه محدود به آخرین ۵۰۰ سفارش است).';
    $row=['data'=>[$id,$waybill,$amount,$currency],'errors'=>$errors];if($order){$oid=$order->get_id();if(isset($seen[$oid]))$row['errors'][]='سفارش تکراری در فایل؛ مبلغ کل حمل سفارش را در یک ردیف وارد کنید.';$seen[$oid]=true;if(!Finance::isMahex($order))$row['errors'][]='روش ارسال ماهکس نیست.';if($waybill!==''&&!in_array($waybill,self::waybills($order),true))$row['errors'][]='بارنامه با سفارش مطابقت ندارد.';if(!in_array($order->get_currency(),['IRR','IRT'],true))$row['errors'][]='واحد پول سفارش پشتیبانی نمی‌شود.';$irr=(float)$amount*($currency==='IRT'?10:1);$cost=$irr/($order->get_currency()==='IRT'?10:1);if(!is_finite($cost)||$cost>1000000000000)$row['errors'][]='مبلغ بیش از محدوده مجاز است.';$old=$order->get_meta('_hm_mahex_actual_carrier_cost',true);$row+=['order_id'=>$oid,'new_cost'=>$cost,'previous'=>$old,'currency'=>$order->get_currency(),'difference'=>is_numeric($old)?$cost-(float)$old:null,'revenue'=>Finance::allocation($order)['revenue'],'fingerprint'=>self::billFingerprint($order)];}$rows[]=$row;
   }return $rows;
  }finally{fclose($h);}
 }
 public static function billFingerprint($order): string {return hash('sha256',serialize([$order->get_meta('_hm_mahex_actual_carrier_cost',true),self::waybills($order),$order->get_currency()]));}
 public static function applyBill(array $row): void {
  if(!empty($row['errors'])||!isset($row['order_id']))throw new \InvalidArgumentException('ردیف دارای خطا است.');$id=(int)$row['order_id'];if(!Access::can('finance',$id))throw new \RuntimeException('دسترسی سفارش مجاز نیست.');$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire($id))throw new \RuntimeException('سفارش در حال ویرایش است.');
  try{$order=wc_get_order($id);if(!$order)throw new \RuntimeException('سفارش حذف شده است.');$order->read_meta_data(true);if(!hash_equals($row['fingerprint'],self::billFingerprint($order)))throw new \RuntimeException('اطلاعات حمل پس از پیش‌نمایش تغییر کرده است.');$old=$order->get_meta('_hm_mahex_actual_carrier_cost',true);$order->update_meta_data('_hm_mahex_actual_carrier_cost',wc_format_decimal($row['new_cost']));$order->update_meta_data('_hm_mahex_v33_carrier_bill',['amount'=>$row['new_cost'],'currency'=>$row['currency'],'previous'=>$old,'actor'=>get_current_user_id(),'date'=>current_time('mysql',true)]);$order->save_meta_data();$order->add_order_note('تطبیق صورتحساب حمل: هزینه واقعی '.$row['new_cost'].' '.$row['currency'].' ثبت شد.');\HoseinMomeni\MahexWoo\V1\OrderIndex::upsert($order);\HoseinMomeni\MahexWoo\V25\Finance::syncOrder($id);\HoseinMomeni\MahexWoo\V1\ActivityLog::write('finance.bill_reconciled','هزینه صورتحساب حمل تطبیق داده شد.',$id,['previous'=>$old,'amount'=>$row['new_cost']]);}finally{$lock->release($id);}
 }
 public static function form(string $intent,bool $upload=false): void {echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"'.($upload?' enctype="multipart/form-data"':'').'><input type="hidden" name="action" value="hm_mahex_v33_management"><input type="hidden" name="intent" value="'.esc_attr($intent).'">';wp_nonce_field('hm_mahex_v33_management');}
 public static function billsPage(): void {
  if(!Access::can('finance'))return;echo '<div class="wrap mhx-v33" dir="rtl"><h1>تطبیق صورتحساب شرکت حمل</h1><p>CSV با ستون‌های order_id,waybill,amount,currency؛ مبلغ کل هزینه حمل سفارش در یک ردیف و واحد IRR یا IRT. تطبیق شماره سفارش و بارنامه، اختلاف با هزینه ثبت‌شده و تبدیل پول پیش از تأیید نمایش داده می‌شود. این ورود دستی است و اتصال شرکت حمل ندارد.</p>';self::form('bill_preview',true);echo '<input type="file" name="file" accept=".csv" required>';submit_button('پیش‌نمایش تطبیق');echo '</form>';$rows=get_transient(self::BILLS.get_current_user_id());if(is_array($rows)){echo '<table class="widefat"><tr><th>سفارش</th><th>هزینه جدید</th><th>اختلاف</th><th>دریافتی ارسال</th><th>خطا</th></tr>';foreach($rows as $row)echo '<tr><td>'.esc_html($row['order_id']??$row['data'][0]??'').'</td><td>'.esc_html(($row['new_cost']??'').' '.($row['currency']??'')).'</td><td>'.esc_html($row['difference']??'هزینه قبلی نامشخص').'</td><td>'.esc_html($row['revenue']??'').'</td><td>'.esc_html(implode('؛ ',$row['errors'])).'</td></tr>';echo '</table>';self::form('bill_apply');submit_button('تأیید و ثبت ردیف‌های معتبر');echo '</form>';}echo '<h2>آخرین تطبیق‌های ثبت‌شده</h2><p>اختلاف = کرایه حمل دریافتی از مشتری − صورتحساب واقعی حمل (بدون هزینه بسته‌بندی/بیمه).</p><table class="widefat"><tr><th>سفارش</th><th>صورتحساب حمل</th><th>کرایه مشتری</th><th>اختلاف</th></tr>';foreach(wc_get_orders(['limit'=>200,'orderby'=>'date','order'=>'DESC']) as $o){if(!Access::can('finance',$o->get_id()))continue;$bill=$o->get_meta('_hm_mahex_v33_carrier_bill',true);if(!is_array($bill))continue;$freight=Finance::components($o)['freight'];echo '<tr><td><a href="'.esc_url($o->get_edit_order_url()).'">'.esc_html($o->get_order_number()).'</a></td><td>'.wp_kses_post(wc_price($bill['amount'],['currency'=>$o->get_currency()])).'</td><td>'.wp_kses_post(wc_price($freight,['currency'=>$o->get_currency()])).'</td><td>'.wp_kses_post(wc_price($freight-$bill['amount'],['currency'=>$o->get_currency()])).'</td></tr>';}echo '</table>';self::result();echo '</div>';
 }
 public static function groupProfit(array $orders,string $group): array {
  $out=[];foreach($orders as $order){if(!Finance::isMahex($order)||(float)$order->get_total_refunded()>0)continue;$a=Finance::allocation($order);if(!$a['complete'])continue;$groups=[];
   if($group==='product'){$sum=0;foreach($order->get_items() as $item)$sum+=max(0,(float)$item->get_total());foreach($order->get_items() as $item){$key=$item->get_product_id().' — '.$item->get_name();$groups[$key]=($groups[$key]??0)+($sum>0?max(0,(float)$item->get_total())/$sum:1/max(1,count($order->get_items())));}}
   elseif($group==='branch')$groups['شعبه '.($order->get_meta('_hm_mahex_branch_id',true)?:'نامشخص')]=1;
   else $groups[($order->get_shipping_state()?:$order->get_billing_state()).' / '.($order->get_shipping_city()?:$order->get_billing_city())]=1;
   foreach($groups as $name=>$share){$key=$a['currency'].'|'.$name;if(!isset($out[$key]))$out[$key]=['group'=>$name,'currency'=>$a['currency'],'orders'=>0,'revenue'=>0.0,'cost'=>0.0,'profit'=>0.0];$out[$key]['orders']++;$out[$key]['revenue']+=$a['revenue']*$share;$out[$key]['cost']+=array_sum($a['costs'])*$share;$out[$key]['profit']+=$a['profit']*$share;}
  }return array_values($out);
 }
 public static function profitPage(): void {if(!Access::can('finance'))return;$group=sanitize_key($_GET['group']??'city');if(!in_array($group,['city','product','branch'],true))$group='city';$page=max(1,absint($_GET['report_page']??1));$result=wc_get_orders(['limit'=>200,'page'=>$page,'paginate'=>true,'status'=>['wc-processing','wc-completed','wc-on-hold'],'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap mhx-v33" dir="rtl"><h1>سود تفکیکی ارسال</h1><p>فقط سفارش‌های همین صفحه با هزینه واقعی کامل و بدون بازپرداخت. سود محصول، سهم سود ارسال به نسبت مبلغ اقلام است؛ سود فروش خود محصول نیست. واحدهای پول جدا هستند.</p>';foreach(['city'=>'شهر','product'=>'محصول','branch'=>'شعبه'] as $key=>$label)echo '<a class="button" href="'.esc_url(add_query_arg(['page'=>'hm-mahex-profit-groups','group'=>$key],admin_url('admin.php'))).'">'.esc_html($label).'</a> ';echo '<table class="widefat"><tr><th>گروه</th><th>سفارش</th><th>دریافتی</th><th>هزینه</th><th>سود</th></tr>';foreach(self::groupProfit(array_filter($result->orders,static fn($order)=>Access::can('finance',$order->get_id())),$group) as $row){echo '<tr><td>'.esc_html($row['group']).'</td><td>'.$row['orders'].'</td>';foreach(['revenue','cost','profit'] as $key)echo '<td>'.wp_kses_post(wc_price($row[$key],['currency'=>$row['currency']])).'</td>';echo '</tr>';}echo '</table>';for($n=max(1,$page-2);$n<=min($result->max_num_pages,$page+2);$n++)echo '<a class="button" href="'.esc_url(add_query_arg(['page'=>'hm-mahex-profit-groups','group'=>$group,'report_page'=>$n],admin_url('admin.php'))).'">'.$n.'</a> ';echo '</div>';}
 public static function whitelist(): array {return ['hm_mahex_pricing_settings'=>'تعرفه پایه','hm_mahex_v1_rules'=>'قوانین نرخ','hm_mahex_v32_label_layout'=>'چیدمان برچسب','hm_mahex_v31_invoice_brand'=>'سربرگ صورتحساب','hm_mahex_v33_print_settings'=>'چاپگرها و قالب شعب'];}
 public static function sanitizeTransfer(array $data): array {
  if(($data['schema']??0)!==1||!is_array($data['options']??null))throw new \InvalidArgumentException('ساختار فایل انتقال نامعتبر است.');$out=[];foreach($data['options'] as $key=>$value){if(!isset(self::whitelist()[$key]))throw new \InvalidArgumentException('گزینه خارج از فهرست مجاز است.');
   if($key==='hm_mahex_pricing_settings'){if(!is_array($value))throw new \InvalidArgumentException('تعرفه نامعتبر است.');$out[$key]=\HoseinMomeni\MahexWoo\Rates\PricingSettings::normalizeStored($value);}
   elseif($key==='hm_mahex_v1_rules'){$out[$key]=\HoseinMomeni\MahexWoo\V32\Rules::normalize(is_array($value)?$value:[]);}
   elseif($key==='hm_mahex_v32_label_layout'){$out[$key]=\HoseinMomeni\MahexWoo\V32\Designer::validate(is_array($value)?$value:[]);}
   elseif($key==='hm_mahex_v33_print_settings')$out[$key]=self::sanitizePrint(is_array($value)?$value:[]);
   else {if(!is_scalar($value))throw new \InvalidArgumentException('سربرگ نامعتبر است.');$out[$key]=substr(sanitize_text_field((string)$value),0,250);}
  }if(!$out)throw new \InvalidArgumentException('فایل بدون گزینه است.');return $out;
 }
 public static function sanitizePrint(array $value): array {
  foreach(array_keys($value) as $key)if(!in_array($key,['printers','branch_templates','auto_print'],true))throw new \InvalidArgumentException('گزینه چاپ نامعتبر است.');
  $printers=$value['printers']??[];$templates=$value['branch_templates']??[];if(!is_array($printers)||!is_array($templates)||count($printers)>30||count($templates)>100)throw new \InvalidArgumentException('تعداد چاپگر/قالب نامعتبر است.');$out=['printers'=>[],'branch_templates'=>[],'auto_print'=>!empty($value['auto_print'])];
  foreach($printers as $key=>$p){if(!is_array($p)||!is_string($key)||sanitize_key($key)!==$key||!is_scalar($p['name']??''))throw new \InvalidArgumentException('چاپگر نامعتبر است.');$out['printers'][$key]=PrintCenter::printer($p);}
  foreach($templates as $key=>$template){if(!ctype_digit((string)$key)||(int)$key<1||!is_array($template)||!is_scalar($template['name']??''))throw new \InvalidArgumentException('قالب شعبه نامعتبر است.');$out['branch_templates'][(string)$key]=['name'=>sanitize_text_field((string)($template['name']??'')),'layout'=>\HoseinMomeni\MahexWoo\V32\Designer::validate((array)($template['layout']??[]))];}return $out;
 }
 public static function compatibility(): array {return ['php'=>PHP_VERSION,'php_ok'=>version_compare(PHP_VERSION,'8.1','>='),'wordpress'=>get_bloginfo('version'),'woocommerce'=>defined('WC_VERSION')?WC_VERSION:'missing','hpos'=>class_exists('Automattic\\WooCommerce\\Utilities\\OrderUtil')?\Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled():false,'zip'=>class_exists('ZipArchive'),'simplexml'=>function_exists('simplexml_load_string'),'scheduled_rules'=>count(array_filter(RuleVersions::all(),static fn($r)=>!$r['activated_at']&&$r['scheduled_at']>0)),'cron_disabled'=>defined('DISABLE_WP_CRON')&&DISABLE_WP_CRON,'setup'=>\HoseinMomeni\MahexWoo\V1\SetupVerifier::checks(),'scope'=>'بررسی همین نصب؛ سایت آزمایشی کپی یا اجرای ارتقا شبیه‌سازی نشده است.'];}
 public static function settingsPage(): void {if(!Access::can('settings'))return;echo '<div class="wrap mhx-v33" dir="rtl"><h1>انتقال تنظیمات و بررسی پیش از ارتقا</h1><p>فقط تعرفه پایه، قوانین، چیدمان برچسب و سربرگ منتقل می‌شوند. اطلاعات مشتری، سفارش، کلید اتصال و مجوز کاربران در فایل نیست.</p>';self::form('export');submit_button('دریافت JSON تنظیمات');echo '</form>';self::form('settings_preview',true);echo '<input type="file" name="file" accept=".json" required>';submit_button('پیش‌نمایش ورود');echo '</form>';$preview=get_transient(self::IMPORT.get_current_user_id());if(is_array($preview)){self::form('settings_apply');foreach($preview['options'] as $key=>$value)echo '<p><label><input type="checkbox" name="selected[]" value="'.esc_attr($key).'" checked>'.esc_html(self::whitelist()[$key]).'</label></p><pre>'.esc_html(wp_json_encode(['before'=>get_option($key),'after'=>$value],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre>';echo '<p>اعمال فقط روی گزینه‌های انتخابی؛ نسخه فعلی قبل از اعمال برای بازگردانی ذخیره می‌شود.</p>';submit_button('تأیید و اعمال');echo '</form>';}self::form('settings_undo');submit_button('بازگردانی آخرین ورود تنظیمات','secondary');echo '</form><h2>گزارش سازگاری همین نصب</h2><pre>'.esc_html(wp_json_encode(self::compatibility(),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre>';self::result();echo '</div>';}
 public static function result(): void {$r=get_transient('hm_mahex_v33_result_'.get_current_user_id());if($r)echo '<p class="notice notice-info">'.esc_html($r).'</p>';}
 public static function upload(): string {$f=$_FILES['file']??null;if(!is_array($f)||($f['error']??1)!==UPLOAD_ERR_OK||($f['size']??0)>1000000||!is_uploaded_file($f['tmp_name']))throw new \InvalidArgumentException('فایل معتبر با حداکثر حجم ۱ مگابایت لازم است.');return $f['tmp_name'];}
 public static function request(): void {
  check_admin_referer('hm_mahex_v33_management');$intent=sanitize_key($_POST['intent']??'');$area=str_starts_with($intent,'bill_')?'finance':'settings';if(!Access::can($area))wp_die('دسترسی مجاز نیست.');$page=$area==='finance'?'hm-mahex-reconciliation':'hm-mahex-settings-transfer';$message='';
  try{
   if($intent==='export'){$options=[];foreach(self::whitelist() as $key=>$label)$options[$key]=get_option($key,$key==='hm_mahex_v32_label_layout'?\HoseinMomeni\MahexWoo\V32\Designer::defaults():($key==='hm_mahex_v31_invoice_brand'?Finance::brand():[]));$out=self::sanitizeTransfer(['schema'=>1,'options'=>$options]);nocache_headers();header('Content-Type: application/json; charset=UTF-8');header('Content-Disposition: attachment; filename="mahex-settings.json"');echo wp_json_encode(['schema'=>1,'version'=>HM_MAHEX_VERSION,'options'=>$out],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;}
   elseif($intent==='bill_preview'){$rows=self::parseBills(self::upload());set_transient(self::BILLS.get_current_user_id(),$rows,1800);$message='پیش‌نمایش آماده است؛ ردیف‌های دارای خطا اعمال نمی‌شوند.';}
   elseif($intent==='bill_apply'){$rows=get_transient(self::BILLS.get_current_user_id());if(!is_array($rows))throw new \InvalidArgumentException('پیش‌نمایش منقضی شده است.');$done=0;$fail=0;foreach($rows as $row){if($row['errors']){$fail++;continue;}try{self::applyBill($row);$done++;}catch(\Throwable $e){$fail++;}}delete_transient(self::BILLS.get_current_user_id());$message=$done.' ردیف اعمال شد؛ '.$fail.' ردیف نامعتبر/متعارض اعمال نشد.';}
   elseif($intent==='settings_preview'){$raw=file_get_contents(self::upload());$data=json_decode($raw,true,32,JSON_THROW_ON_ERROR);$options=self::sanitizeTransfer($data);$fingerprints=[];foreach($options as $key=>$value)$fingerprints[$key]=hash('sha256',serialize(get_option($key)));set_transient(self::IMPORT.get_current_user_id(),['options'=>$options,'fingerprints'=>$fingerprints],1800);$message='پیش‌نمایش آماده است.';}
   elseif(in_array($intent,['settings_apply','settings_undo'],true)){$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(0))throw new \RuntimeException('عملیات تنظیمات در حال اجراست.');if(!$lock->acquire(-32001)){$lock->release(0);throw new \RuntimeException('طراح برچسب در حال ذخیره است.');}if(!$lock->acquire(-33003)){$lock->release(-32001);$lock->release(0);throw new \RuntimeException('مرکز چاپ در حال ذخیره است.');}try{$undoKey='hm_mahex_v33_settings_undo';if($intent==='settings_apply'){$preview=get_transient(self::IMPORT.get_current_user_id());if(!is_array($preview))throw new \InvalidArgumentException('پیش‌نمایش منقضی شده است.');$selected=array_filter((array)wp_unslash($_POST['selected']??[]),'is_string');$options=array_intersect_key($preview['options'],array_flip($selected));$before=[];foreach($options as $key=>$value){if(!hash_equals($preview['fingerprints'][$key],hash('sha256',serialize(get_option($key)))))throw new \RuntimeException('تنظیمات پس از پیش‌نمایش تغییر کرده است.');$before[$key]=get_option($key);}$undo=['options'=>$before,'after'=>[]];foreach($options as $key=>$value){if($key==='hm_mahex_v32_label_layout')$value['revision']=\HoseinMomeni\MahexWoo\V32\Designer::layout()['revision']+1;update_option($key,$value,false);$undo['after'][$key]=hash('sha256',serialize($value));}update_user_meta(get_current_user_id(),$undoKey,$undo);delete_transient(self::IMPORT.get_current_user_id());}else{$undo=get_user_meta(get_current_user_id(),$undoKey,true);if(!is_array($undo)||!is_array($undo['options']??null))throw new \InvalidArgumentException('نسخه بازگردانی موجود نیست.');foreach($undo['options'] as $key=>$value)if(!hash_equals($undo['after'][$key],hash('sha256',serialize(get_option($key)))))throw new \RuntimeException('تنظیمات پس از ورود تغییر کرده‌اند؛ بازگردانی مجاز نیست.');foreach($undo['options'] as $key=>$value){if($key==='hm_mahex_v32_label_layout'){$value=is_array($value)?$value:\HoseinMomeni\MahexWoo\V32\Designer::defaults();$value['revision']=\HoseinMomeni\MahexWoo\V32\Designer::layout()['revision']+1;}update_option($key,$value,false);}delete_user_meta(get_current_user_id(),$undoKey);}\HoseinMomeni\MahexWoo\V2\RateCache::invalidate();\HoseinMomeni\MahexWoo\V1\ActivityLog::write('settings.'.$intent,'تنظیمات مجاز منتقل/بازگردانی شد.',0,['actor'=>get_current_user_id()]);$message='تنظیمات انتخابی اعمال شد.';}finally{$lock->release(-33003);$lock->release(-32001);$lock->release(0);}}
   else throw new \InvalidArgumentException('عملیات نامعتبر است.');
  }catch(\Throwable $e){wp_die(esc_html($e->getMessage()));}set_transient('hm_mahex_v33_result_'.get_current_user_id(),$message,600);wp_safe_redirect(admin_url('admin.php?page='.$page));exit;
 }
}
