<?php
namespace HoseinMomeni\MahexWoo\V33;

/** Store-configured notifications; no carrier API or unsolicited default transport. */
final class NotificationCenter {
 const OPTION='hm_mahex_v33_notification_settings';const QUEUE='hm_mahex_v33_notification_queue';
 public static function register(): void {
  add_action('admin_menu',[self::class,'menu']);add_action('admin_post_hm_mahex_v33_notifications',[self::class,'save']);add_action('admin_post_hm_mahex_v33_notification_retry',[self::class,'retry']);
  add_action('hm_mahex_shipment_saved',[self::class,'shipment'],40,3);add_action('hm_mahex_v33_notification_tick',[self::class,'process']);add_action('init',[self::class,'schedule']);
  add_action('woocommerce_review_order_before_submit',[self::class,'consent']);add_action('woocommerce_checkout_create_order',[self::class,'storeConsent'],30,2);
  add_action('hm_mahex_v33_enqueue_notification',[self::class,'enqueue'],10,1);
  add_action('hm_mahex_v33_erase_notifications',[self::class,'erase'],10,1);
 }
 public static function menu(): void {add_submenu_page('hm-mahex','مرکز اعلان و تلاش مجدد','مرکز اعلان',Access::cap('operations'),'hm-mahex-notifications',[self::class,'page']);}
 public static function settings(): array {$s=get_option(self::OPTION,[]);return is_array($s)?$s:[];}
 public static function schedule(): void {if(!wp_next_scheduled('hm_mahex_v33_notification_tick'))wp_schedule_event(time()+60,'hourly','hm_mahex_v33_notification_tick');}
 public static function consent(): void {if(empty(self::settings()['sms']))return;echo '<p><label><input type="checkbox" name="hm_mahex_sms_consent" value="1"> با دریافت پیامک وضعیت ارسال همین سفارش موافقم.</label></p>';}
 public static function storeConsent($order,$data): void {$order->update_meta_data('_hm_mahex_v33_sms_consent',isset($_POST['hm_mahex_sms_consent'])&&$_POST['hm_mahex_sms_consent']==='1');}
 public static function fingerprint(int $id,string $shipment,string $status,string $channel,string $waybill): string {return hash('sha256',implode('|',[$id,$shipment,$status,$channel,$waybill]));}
 public static function nextAttempt(int $attempt,int $now): int {return $now+min(86400,60*(2**min(10,max(0,$attempt))));}
 public static function shipment($order,$shipment,string $action): void {
  $s=self::settings();$vars=['{order}'=>$order->get_order_number(),'{status}'=>$shipment->status,'{waybill}'=>$shipment->waybill_number,'{tracking_url}'=>$order->get_customer_id()?$order->get_view_order_url():home_url('/')];
  foreach(['email','sms'] as $channel){if(empty($s[$channel]))continue;if($channel==='sms'&&!$order->get_meta('_hm_mahex_v33_sms_consent',true))continue;$to=$channel==='email'?$order->get_billing_email():$order->get_billing_phone();if($channel==='email'&&!is_email($to))continue;$phone=\HoseinMomeni\MahexWoo\V31\OperationsValidation::digits($to);if($channel==='sms'&&!preg_match('/^(?:09\d{9}|\+989\d{9}|00989\d{9})$/',$phone))continue;
   $job=['id'=>self::fingerprint($order->get_id(),$shipment->shipment_id,$shipment->status,$channel,$shipment->waybill_number),'order_id'=>$order->get_id(),'channel'=>$channel,'to'=>$channel==='sms'?$phone:$to,'subject'=>str_replace(["\r","\n"],' ',strtr($s['subject']??'وضعیت ارسال سفارش {order}',$vars)),'message'=>strtr($s['message']??'سفارش {order}؛ وضعیت {status}؛ بارنامه {waybill}. {tracking_url}',$vars),'attempts'=>0,'state'=>'pending','next_at'=>time(),'created_at'=>gmdate('c'),'error'=>''];
   if(empty($shipment->package_snapshot['_manual_carrier_reference']))$job['message'].="\nشناسه فوق داخلی فروشگاه است.";self::enqueue($job);
  }
 }
 public static function enqueue(array $job): void {
  $lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(-33004)){wp_schedule_single_event(time()+45,'hm_mahex_v33_enqueue_notification',[$job]);return;}
  try{$queue=get_option(self::QUEUE,[]);$queue=is_array($queue)?$queue:[];if(isset($queue[$job['id']]))return;if(count($queue)>=1000){foreach($queue as $key=>$value)if(in_array($value['state'],['sent','failed'],true)){unset($queue[$key]);break;}if(count($queue)>=1000){wp_schedule_single_event(time()+3600,'hm_mahex_v33_enqueue_notification',[$job]);return;}}$queue[$job['id']]=$job;update_option(self::QUEUE,$queue,false);wp_schedule_single_event(time()+10,'hm_mahex_v33_notification_tick');}finally{$lock->release(-33004);}
 }
 public static function process(): void {
  $lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(-33004,180))return;
  try{$queue=get_option(self::QUEUE,[]);$queue=is_array($queue)?$queue:[];$count=0;foreach($queue as &$job){if($job['state']!=='pending'||(int)$job['next_at']>time()||$count>=10)continue;$count++;$order=wc_get_order((int)$job['order_id']);$s=self::settings();if(!$order||empty($s[$job['channel']])||($job['channel']==='sms'&&!$order->get_meta('_hm_mahex_v33_sms_consent',true))){$job['state']='blocked';$job['error']='کانال غیرفعال، رضایت موجود نیست یا سفارش حذف شده است.';continue;}
    $job['attempts']++;$job['state']='sending';update_option(self::QUEUE,$queue,false); // record the attempt before transport; interrupted sends require explicit retry
    try{$result=$job['channel']==='email'?wp_mail($job['to'],$job['subject'],$job['message'],['Content-Type: text/plain; charset=UTF-8']):apply_filters('hm_mahex_v33_sms_transport',new \WP_Error('missing_transport','ارائه‌دهنده پیامک متصل نیست.'),$job['to'],$job['message'],$job);
     if(is_wp_error($result)&&$result->get_error_code()==='missing_transport'){$job['state']='blocked';$job['error']=$result->get_error_message();}
     elseif($result===true){$job['state']='sent';$job['sent_at']=gmdate('c');$job['error']='';}else{$job['state']=$job['attempts']>=5?'failed':'pending';$job['error']=is_wp_error($result)?$result->get_error_message():'ارسال توسط کانال تأیید نشد.';$job['next_at']=self::nextAttempt($job['attempts'],time());}
    }catch(\Throwable $e){$job['state']=$job['attempts']>=5?'failed':'pending';$job['error']=$e->getMessage();$job['next_at']=self::nextAttempt($job['attempts'],time());}
   }unset($job);update_option(self::QUEUE,$queue,false);$next=null;foreach($queue as $job)if($job['state']==='pending')$next=$next===null?(int)$job['next_at']:min($next,(int)$job['next_at']);if($next!==null)wp_schedule_single_event(max(time()+30,$next),'hm_mahex_v33_notification_tick');
  }finally{$lock->release(-33004);}
 }
 public static function page(): void {
  if(!Support::can('operations'))return;echo '<div class="wrap mhx-v32" dir="rtl"><h1>مرکز اعلان</h1>';Support::notice();$s=self::settings();if(Support::can('settings')){Support::form('hm_mahex_v33_notifications');foreach(['email'=>'ایمیل صف‌دار','sms'=>'پیامک با رضایت مشتری و ارائه‌دهنده متصل'] as $key=>$label)echo '<p><label><input type="checkbox" name="'.$key.'" value="1" '.checked(!empty($s[$key]),true,false).'>'.esc_html($label).'</label></p>';echo '<p><input class="large-text" name="subject" value="'.esc_attr($s['subject']??'وضعیت ارسال سفارش {order}').'"></p><textarea class="large-text" name="message" maxlength="4000">'.esc_textarea($s['message']??'سفارش {order}؛ وضعیت {status}؛ بارنامه {waybill}. {tracking_url}').'</textarea><p>متغیرها: {order}، {status}، {waybill}، {tracking_url}. اتصال پیامک از هوک hm_mahex_v33_sms_transport انجام می‌شود؛ بدون ارائه‌دهنده، پیامک در وضعیت مسدود می‌ماند. رضایت سفارش‌های قدیمی فرض نمی‌شود. فعال‌کردن ایمیل صف‌دار، اعلان ایمیلی قدیمی ۳.۱ را غیرفعال می‌کند.</p><button class="button button-primary">ذخیره تنظیمات</button></form>';}
  echo '<table class="widefat striped"><tr><th>سفارش</th><th>کانال</th><th>وضعیت</th><th>تلاش</th><th>خطا</th><th>عملیات</th></tr>';$queue=get_option(self::QUEUE,[]);foreach(array_reverse(is_array($queue)?$queue:[]) as $job){if(!Support::can('operations',(int)$job['order_id']))continue;echo '<tr><td>#'.(int)$job['order_id'].'</td><td>'.esc_html($job['channel']).'</td><td>'.esc_html($job['state']).'</td><td>'.(int)$job['attempts'].'</td><td>'.esc_html($job['error']).'</td><td>';if(in_array($job['state'],['failed','blocked','sending'],true)){Support::form('hm_mahex_v33_notification_retry');echo '<input type="hidden" name="job" value="'.esc_attr($job['id']).'"><button class="button">تلاش مجدد (ممکن است ارسال قبلی انجام شده باشد)</button></form>';}echo '</td></tr>';}echo '</table></div>';
 }
 public static function save(): void {Support::auth('hm_mahex_v33_notifications','settings');$subject=sanitize_text_field(Support::input('subject'));$message=sanitize_textarea_field(Support::input('message'));if(mb_strlen($subject)>200||mb_strlen($message)>4000)wp_die('قالب بیش از حد طولانی است.');$s=['email'=>Support::input('email')==='1','sms'=>Support::input('sms')==='1','subject'=>$subject,'message'=>$message];update_option(self::OPTION,$s,false);if($s['email']){$old=get_option(\HoseinMomeni\MahexWoo\V31\Operations::OPTION,[]);$old=is_array($old)?$old:[];$old['notifications']=false;update_option(\HoseinMomeni\MahexWoo\V31\Operations::OPTION,$old,false);}Support::redirect('hm-mahex-notifications','تنظیمات اعلان ذخیره شد.');}
 public static function retry(): void {Support::auth('hm_mahex_v33_notification_retry','operations');$id=sanitize_key(Support::input('job'));$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(-33004))wp_die('صف در حال پردازش است.');try{$queue=get_option(self::QUEUE,[]);if(!isset($queue[$id])||!Support::can('operations',(int)$queue[$id]['order_id'])||!in_array($queue[$id]['state'],['failed','blocked','sending'],true))throw new \RuntimeException('اعلان مجاز برای تکرار نیست.');$queue[$id]['state']='pending';$queue[$id]['attempts']=0;$queue[$id]['next_at']=time();update_option(self::QUEUE,$queue,false);}catch(\Throwable $e){$error=$e->getMessage();}finally{$lock->release(-33004);}if(empty($error))wp_schedule_single_event(time()+10,'hm_mahex_v33_notification_tick');Support::redirect('hm-mahex-notifications',$error??'اعلان دوباره وارد صف شد.');}
 public static function erase(array $ids): void {$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(-33004,180)){wp_schedule_single_event(time()+180,'hm_mahex_v33_erase_notifications',[$ids]);return;}try{$queue=get_option(self::QUEUE,[]);if(!is_array($queue))return;foreach($queue as $key=>$job)if(in_array((int)$job['order_id'],$ids,true))unset($queue[$key]);update_option(self::QUEUE,$queue,false);}finally{$lock->release(-33004);}}
}
