<?php
namespace HoseinMomeni\MahexWoo\V33;
use HoseinMomeni\MahexWoo\V32\Designer;

final class PrintCenter {
 const OPTION='hm_mahex_v33_print_settings';
 public static function register(): void {
  add_action('admin_menu',[self::class,'menu']);add_action('admin_post_hm_mahex_v33_print_settings',[self::class,'save']);add_action('admin_post_hm_mahex_v33_batch_print',[self::class,'document']);add_action('admin_enqueue_scripts',[self::class,'assets']);
  add_action('woocommerce_admin_order_data_after_shipping_address',[self::class,'orderLinks']);
 }
 public static function menu(): void {add_submenu_page('hm-mahex','مرکز چاپ و قالب شعب','مرکز چاپ ۳.۳',Access::cap('print'),'hm-mahex-print-center',[self::class,'page']);}
 public static function assets(): void {if(!in_array(sanitize_key($_GET['page']??''),['hm-mahex-print-center','hm-mahex-v32-board','hm-mahex-v33-station'],true))return;wp_enqueue_script('hm-mahex-v33-print',plugins_url('assets/admin/v33-print.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_localize_script('hm-mahex-v33-print','MahexPrint',['url'=>admin_url('admin-post.php'),'nonce'=>wp_create_nonce('hm_mahex_v33_batch_print'),'auto'=>!empty(self::settings()['auto_print'])]);}
 public static function settings(): array {$s=get_option(self::OPTION,[]);return is_array($s)?$s:[];}
 public static function ids($raw): array {if(!is_scalar($raw))throw new \InvalidArgumentException('فهرست سفارش نامعتبر است.');$parts=preg_split('/[\s,،]+/u',trim((string)$raw),-1,PREG_SPLIT_NO_EMPTY);if(!$parts||count($parts)>100)throw new \InvalidArgumentException('بین ۱ و ۱۰۰ سفارش انتخاب کنید.');$ids=[];foreach($parts as $p){if(!ctype_digit($p)||(int)$p<1)throw new \InvalidArgumentException('شماره سفارش باید عدد مثبت باشد.');$ids[]=(int)$p;}return array_values(array_unique($ids));}
 public static function printer(array $p): array {return ['name'=>sanitize_text_field((string)($p['name']??'')),'x'=>self::offset($p['x']??0),'y'=>self::offset($p['y']??0),'scale'=>max(90,min(110,Support::number($p['scale']??100,110)))];}
 private static function offset($v): float {if(!is_scalar($v)||!is_numeric($v)||!is_finite((float)$v)||abs((float)$v)>15)throw new \InvalidArgumentException('تصحیح حاشیه باید بین منفی و مثبت ۱۵ میلی‌متر باشد.');return (float)$v;}
 public static function layout($order): array {$branch=(string)$order->get_meta('_hm_mahex_branch_id',true);$candidate=self::settings()['branch_templates'][$branch]['layout']??null;return is_array($candidate)?Designer::validate($candidate):Designer::layout();}
 public static function orderLinks($order): void {if(!Support::can('print',$order->get_id()))return;$url=wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v33_batch_print','ids'=>$order->get_id()],admin_url('admin-post.php')),'hm_mahex_v33_batch_print');echo '<p><a class="button" target="_blank" rel="noopener" href="'.esc_url($url).'">برچسب / PDF مستقیم ۳.۳</a></p>';}
 public static function page(): void {
  if(!Support::can('print'))return;echo '<div class="wrap mhx-v32" dir="rtl"><h1>مرکز چاپ گروهی و PDF فارسی</h1>';Support::notice();$s=self::settings();
  echo '<form method="get" action="'.esc_url(admin_url('admin-post.php')).'" target="_blank"><input type="hidden" name="action" value="hm_mahex_v33_batch_print">';wp_nonce_field('hm_mahex_v33_batch_print');echo '<p><label>شماره‌های داخلی سفارش <input name="ids" required placeholder="11,12,13"></label></p><p><label>پروفایل چاپگر <select name="printer"><option value="">بدون تصحیح</option>';foreach($s['printers']??[] as $key=>$p)echo '<option value="'.esc_attr($key).'">'.esc_html($p['name']).'</option>';echo '</select></label> <label><input type="checkbox" name="return_label" value="1">برچسب مرجوعی (مقصد فروشگاه)</label></p><button class="button" name="output" value="html">چاپ یکپارچه</button> <button class="button button-primary" name="output" value="pdf">دانلود PDF مستقیم</button></form><p>مرورگر پنجره چاپ را باز می‌کند؛ چاپ بی‌صدا بدون تنظیم دستگاه و مرورگر ممکن نیست. قالب شعبه از شعبه ثبت‌شده روی سفارش انتخاب می‌شود.</p>';
  if(Support::can('settings')){Support::form('hm_mahex_v33_print_settings');echo '<h2>چاپگر و قالب شعبه</h2><p><label>کلید چاپگر <input name="printer_key" value="default" required></label> <label>نام <input name="printer_name" value="'.esc_attr($s['printers']['default']['name']??'چاپگر اصلی').'"></label></p>';foreach(['x'=>'تصحیح افقی mm','y'=>'تصحیح عمودی mm','scale'=>'مقیاس درصد'] as $k=>$label)echo '<label>'.esc_html($label).' <input type="number" step="0.1" name="'.$k.'" value="'.esc_attr($s['printers']['default'][$k]??($k==='scale'?100:0)).'"></label> ';echo '<p><label><input type="checkbox" name="auto_print" value="1" '.checked(!empty($s['auto_print']),true,false).'>بازکردن چاپ پس از تأیید نهایی ایستگاه</label></p><p><label>شناسه شعبه (اختیاری) <input name="branch_id" type="number" min="1"></label> <label>نام قالب <input name="template_name"></label></p><p>با انتخاب شعبه، چیدمان فعلی طراح برچسب به‌عنوان قالب همان شعبه کپی می‌شود؛ می‌توانید چیدمان دیگری بسازید و برای شعبه بعدی ذخیره کنید.</p><button class="button button-primary">ذخیره</button></form>';foreach($s['branch_templates']??[] as $key=>$t)echo '<p>شعبه #'.esc_html($key).' — '.esc_html($t['name']).' — '.esc_html($t['layout']['format']).'</p>';}
  echo '</div>';
 }
 public static function save(): void {
  Support::auth('hm_mahex_v33_print_settings','settings');$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(-33003))wp_die('تنظیمات در حال ذخیره است.');$error='';try{$s=self::settings();$key=sanitize_key(Support::input('printer_key'));if(!$key)throw new \InvalidArgumentException('کلید چاپگر ضروری است.');$s['printers'][$key]=self::printer(['name'=>Support::input('printer_name'),'x'=>Support::input('x'),'y'=>Support::input('y'),'scale'=>Support::input('scale')]);if(count($s['printers'])>30)throw new \InvalidArgumentException('حداکثر ۳۰ چاپگر.');$s['auto_print']=Support::input('auto_print')==='1';$id=absint(Support::input('branch_id'));if($id){$s['branch_templates'][(string)$id]=['name'=>sanitize_text_field(Support::input('template_name')),'layout'=>Designer::layout()];if(count($s['branch_templates'])>100)throw new \InvalidArgumentException('حداکثر ۱۰۰ قالب شعبه.');}update_option(self::OPTION,$s,false);}catch(\Throwable $e){$error=$e->getMessage();}finally{$lock->release(-33003);}Support::redirect('hm-mahex-print-center',$error?:'تنظیمات چاپ ذخیره شد.');
 }
 public static function values($order,bool $return): array {$values=Designer::values($order);if($return){$origin=(array)get_option('hm_mahex_settings',[]);$values['recipient']=$origin['sender_name']??'فروشگاه';$values['address']=$origin['origin_address']??'';$values['phone']=$origin['sender_phone']??'';$values['sender_address']=$order->get_shipping_address_1()?:$order->get_billing_address_1();$values['sender_phone']=$order->get_billing_phone();$values['destination']='مرجوعی به '.($origin['origin_city']??'مبدا');$values['notes']='مرجوعی سفارش #'.$order->get_order_number();}return $values;}
 public static function document(): void {
  Support::auth('hm_mahex_v33_batch_print','print');try{$ids=self::ids($_REQUEST['ids']??'');$orders=[];foreach($ids as $id){if(!Support::can('print',$id))throw new \RuntimeException('دسترسی سفارش #'.$id.' مجاز نیست.');$order=wc_get_order($id);if(!$order)throw new \RuntimeException('سفارش #'.$id.' پیدا نشد.');$orders[]=$order;}$p=self::settings()['printers'][sanitize_key($_REQUEST['printer']??'')]??['x'=>0,'y'=>0,'scale'=>100];$return=($_REQUEST['return_label']??'')==='1';if(($_REQUEST['output']??'')==='pdf'){$bytes=self::pdf($orders,$p,$return)->Output('mahex-labels.pdf','S');nocache_headers();header('Content-Type: application/pdf');header('X-Content-Type-Options: nosniff');header('Content-Disposition: attachment; filename="mahex-labels.pdf"');header('Content-Length: '.strlen($bytes));echo $bytes;exit;}
  nocache_headers();header('Content-Type: text/html; charset=UTF-8');echo '<!doctype html><html lang="fa" dir="rtl"><head><meta charset="UTF-8"><title>چاپ گروهی ماهکس</title><link rel="stylesheet" href="'.esc_url(plugins_url('assets/admin/v32-designer.css',HM_MAHEX_FILE)).'"><style>body{margin:0;background:white}.mhx-label-paper{border:0;box-shadow:none}.mhx-batch-page{break-after:page;page-break-after:always;overflow:hidden}.mhx-batch-page:last-child{break-after:auto}';foreach(['thermal'=>'100mm 150mm','a4'=>'A4'] as $f=>$size)echo '@page '.$f.'{size:'.$size.';margin:0}.mhx-batch-'.$f.'{page:'.$f.'}';echo '@media print{.mhx-print-tools{display:none}}.mhx-label-paper{transform-origin:top left;transform:translate('.(float)$p['x'].'mm,'.(float)$p['y'].'mm) scale('.((float)$p['scale']/100).')}</style></head><body><div class="mhx-print-tools"><button onclick="print()">چاپ همه برچسب‌ها</button><p>مقیاس مرورگر ۱۰۰٪، حاشیه صفر؛ پروفایل چاپگر اعمال شده است.</p></div>';foreach($orders as $order){$layout=self::layout($order);echo '<section class="mhx-batch-page mhx-batch-'.esc_attr($layout['format']).'">'.Designer::canvas($layout,self::values($order,$return)).'</section>';do_action('hm_mahex_document_printed',$order->get_id(),$return?'return-label':'label-batch',1);}if(($_REQUEST['auto']??'')==='1')echo '<script>window.addEventListener("load",()=>window.print());</script>';echo '</body></html>';exit;
  }catch(\Throwable $e){wp_die(esc_html($e->getMessage()));}
 }
 public static function pdf(array $orders,array $printer,bool $return=false): \TCPDF {
  if(!extension_loaded('curl'))throw new \RuntimeException('PDF مستقیم به افزونه PHP cURL نیاز دارد.');if(!class_exists('TCPDF'))throw new \RuntimeException('کتابخانه PDF در بسته نصب موجود نیست؛ ZIP رسمی نسخه را نصب کنید.');$pdf=new \TCPDF('P','mm','A4',true,'UTF-8',false);$pdf->setPrintHeader(false);$pdf->setPrintFooter(false);$pdf->SetMargins(0,0,0);$pdf->SetAutoPageBreak(false,0);$pdf->setFontSubsetting(true);$pdf->SetFont('dejavusans','',10);$pdf->SetCreator('Mahex WooCommerce');$pdf->setRTL(false);$scale=(float)($printer['scale']??100)/100;
  foreach($orders as $order){$layout=self::layout($order);$pdf->AddPage('P',$layout['format']==='a4'?'A4':[100,150]);$values=self::values($order,$return);foreach($layout['fields'] as $id=>$f){if(!$f['enabled'])continue;$x=$f['x']*$scale+(float)($printer['x']??0);$y=$f['y']*$scale+(float)($printer['y']??0);$w=$f['w']*$scale;$h=$f['h']*$scale;if($id==='barcode'){$pdf->write1DBarcode($values['barcode'],'C128C',$x,$y,$w,$h,.25,['text'=>true,'font'=>'dejavusans','fontsize'=>8,'stretch'=>true,'fitwidth'=>false]);}elseif($id==='logo'){if(function_exists('imagecreatefrompng'))$pdf->Image(dirname(HM_MAHEX_FILE).'/assets/brand/mahex-reference.png',$x,$y,$w,$h,'PNG');else{$pdf->SetFont('dejavusans','',12);$pdf->MultiCell($w,$h,'MAHEX',0,'C',false,1,$x,$y);}}else{$pdf->SetFont('dejavusans','',$f['font']*.75*$scale);$pdf->setRTL(true);$pdf->MultiCell($w,$h,(string)($values[$id]??''),0,'R',false,1,($layout['format']==='a4'?210:100)-$x-$w,$y,true,0,false,true,$h,'T',true);$pdf->setRTL(false);}}do_action('hm_mahex_document_printed',$order->get_id(),'pdf-direct',1);}return $pdf;
 }
}
