<?php
namespace HoseinMomeni\MahexWoo\V33;

final class Returns {
 const META='_hm_mahex_v33_return';const DOCUMENTS='_hm_mahex_v33_official_documents';
 const STATES=['requested'=>'درخواست مشتری','approved'=>'تأیید مرجوعی','in_transit'=>'در مسیر بازگشت','received'=>'دریافت شد','closed'=>'بسته شد','rejected'=>'رد شد'];
 public static function register(): void {
  add_action('admin_menu',[self::class,'menu']);add_action('woocommerce_order_details_after_order_table',[self::class,'customer']);
  foreach(['customer_return','return_save','document_upload','document_download','return_photo'] as $method)add_action('admin_post_hm_mahex_v33_'.$method,[self::class,$method]);
 }
 public static function menu(): void {add_submenu_page('hm-mahex','مرجوعی، خسارت و فایل رسمی','مرجوعی و مدارک',Access::cap('operations'),'hm-mahex-returns',[self::class,'page']);}
 public static function owns($order,int $user): bool {return $user>0&&(int)$order->get_customer_id()===$user;}
 public static function canRead($order): bool {return self::owns($order,get_current_user_id())||Support::can('operations',$order->get_id())||Support::can('print',$order->get_id());}
 public static function quantities(array $input,array $available): array {$out=[];foreach($input as $id=>$n){if(!is_scalar($n)||!ctype_digit((string)$n))throw new \InvalidArgumentException('تعداد مرجوعی نامعتبر است.');$n=(int)$n;if(!$n)continue;if(!isset($available[(int)$id])||$n>$available[(int)$id])throw new \InvalidArgumentException('تعداد از سفارش بیشتر است.');$out[(int)$id]=$n;}if(!$out)throw new \InvalidArgumentException('حداقل یک کالا انتخاب کنید.');return $out;}
 public static function transition(string $from,string $to): bool {$next=['requested'=>['approved','rejected'],'approved'=>['in_transit','received','rejected'],'in_transit'=>['received'],'received'=>['closed'],'rejected'=>[],'closed'=>[]];return $from===$to||in_array($to,$next[$from]??[],true);}
 private static function record($order): array {$r=$order->get_meta(self::META,true);return is_array($r)?$r:[];}
 public static function customer($order): void {
  if(!self::owns($order,get_current_user_id()))return;$parcels=$order->get_meta(Station::META,true);if(is_array($parcels)&&!empty($parcels['parcels'])){echo '<section dir="rtl"><h2>رهگیری بسته‌های سفارش</h2><p>این اطلاعات دستی توسط فروشگاه ثبت شده است.</p>';foreach($parcels['parcels'] as $index=>$parcel)echo '<p>بسته '.((int)$index+1).' — کد رهگیری: '.esc_html($parcel['tracking']??'ثبت نشده').' — وزن: '.esc_html($parcel['weight_g']??'ثبت نشده').' گرم</p>';echo '</section>';}$r=self::record($order);echo '<section dir="rtl"><h2>درخواست مرجوعی</h2>';if($r){echo '<p>شناسه: '.esc_html($r['reference']??'').'؛ وضعیت: '.esc_html(self::STATES[$r['status']]??$r['status']).'</p><p>دلیل: '.esc_html($r['reason']??'').'</p><p>کد رهگیری بازگشت: '.esc_html($r['tracking']??'ثبت نشده').'</p>';if(!empty($r['customer_note']))echo '<p>'.esc_html($r['customer_note']).'</p>';}elseif(in_array($order->get_status(),['processing','completed'],true)){
  Support::form('hm_mahex_v33_customer_return');echo '<input type="hidden" name="order_id" value="'.$order->get_id().'"><p>ثبت درخواست به‌معنی تأیید مرجوعی یا بازپرداخت نیست.</p>';foreach($order->get_items() as $id=>$line)echo '<p><label>'.esc_html($line->get_name()).' <input type="number" name="quantities['.(int)$id.']" value="0" min="0" max="'.(int)$line->get_quantity().'"></label></p>';echo '<p><label>دلیل <textarea name="reason" required maxlength="2000"></textarea></label></p><p><label>عکس آسیب (JPEG/PNG تا ۱ مگابایت، اختیاری) <input type="file" name="photo" accept="image/jpeg,image/png"></label></p><button class="button">ثبت درخواست</button></form>';}
  echo '</section>';
 }
 public static function customer_return(): void {
  check_admin_referer('hm_mahex_v33_customer_return');$id=absint(Support::input('order_id'));$order=wc_get_order($id);if(!$order||!self::owns($order,get_current_user_id())||!in_array($order->get_status(),['processing','completed'],true))wp_die('این سفارش مجاز نیست.','',['response'=>403]);
  try{$reason=sanitize_textarea_field(Support::input('reason'));if(!$reason||mb_strlen($reason)>2000)throw new \InvalidArgumentException('دلیل بین ۱ تا ۲۰۰۰ نویسه ضروری است.');$available=[];foreach($order->get_items() as $lineId=>$line)$available[$lineId]=(int)$line->get_quantity();$qty=self::quantities(is_array($_POST['quantities']??null)?$_POST['quantities']:[],$available);$photo=null;if(($_FILES['photo']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE)$photo=Support::file($_FILES['photo'],['image/jpeg','image/png'],1048576);
   Support::edit($id,self::META,0,static function($old,$fresh)use($reason,$qty,$photo){if($old)throw new \RuntimeException('درخواست قبلاً ثبت شده است.');$fresh->add_order_note('درخواست مرجوعی مشتری ثبت شد.');return ['reference'=>'RMA-'.$fresh->get_id().'-'.strtoupper(wp_generate_password(6,false)),'status'=>'requested','reason'=>$reason,'quantities'=>$qty,'photos'=>$photo?[$photo]:[],'history'=>[['status'=>'requested','at'=>gmdate('c'),'actor'=>get_current_user_id()]]];});
  }catch(\Throwable $e){wp_die(esc_html($e->getMessage()));}wp_safe_redirect($order->get_view_order_url());exit;
 }
 public static function page(): void {
  if(!Support::can('operations'))return;$id=absint($_GET['order_id']??0);echo '<div class="wrap mhx-v32" dir="rtl"><h1>مرجوعی، خسارت و فایل بارنامه رسمی</h1>';Support::notice();Support::orderChooser('hm-mahex-returns',$id);$order=$id?wc_get_order($id):null;if($order&&Support::can('operations',$id)){self::editor($order);}else{
   $page=max(1,absint($_GET['paged']??1));$result=wc_get_orders(['limit'=>50,'page'=>$page,'paginate'=>true,'orderby'=>'date','order'=>'DESC']);echo '<p>پرونده‌های موجود در سفارش‌های این صفحه:</p><table class="widefat striped"><tr><th>سفارش</th><th>پرونده</th><th>وضعیت</th><th>دلیل</th></tr>';foreach($result->orders as $o){$r=self::record($o);if(!$r||!Support::can('operations',$o->get_id()))continue;echo '<tr><td><a href="'.esc_url(add_query_arg(['page'=>'hm-mahex-returns','order_id'=>$o->get_id()],admin_url('admin.php'))).'">#'.$o->get_id().'</a></td><td>'.esc_html($r['reference']??'').'</td><td>'.esc_html(self::STATES[$r['status']]??'').'</td><td>'.esc_html($r['reason']??'').'</td></tr>';}echo '</table>';if($page<(int)$result->max_num_pages)echo '<a class="button" href="'.esc_url(add_query_arg(['page'=>'hm-mahex-returns','paged'=>$page+1],admin_url('admin.php'))).'">سفارش‌های بعدی</a>';}
  echo '</div>';
 }
 private static function editor($order): void {
  $id=$order->get_id();$r=self::record($order);Support::form('hm_mahex_v33_return_save');echo '<input type="hidden" name="order_id" value="'.$id.'"><input type="hidden" name="revision" value="'.(int)($r['revision']??0).'"><h2>پرونده سفارش #'.esc_html($order->get_order_number()).'</h2><p>شناسه: '.esc_html($r['reference']??'پرونده جدید').'</p><p><label>وضعیت <select name="status">';foreach(self::STATES as $key=>$label)if(!$r?$key==='requested':self::transition($r['status'],$key))echo '<option value="'.esc_attr($key).'" '.selected($r['status']??'requested',$key,false).'>'.esc_html($label).'</option>';echo '</select></label></p>';
  foreach(['reason'=>'دلیل مرجوعی/آسیب','tracking'=>'کد رهگیری بازگشت','claim_reference'=>'شماره پرونده خسارت شرکت حمل','customer_note'=>'پیام قابل نمایش به مشتری','internal_note'=>'یادداشت داخلی'] as $key=>$label)echo '<p><label>'.esc_html($label).' <textarea name="'.$key.'" maxlength="2000">'.esc_textarea($r[$key]??'').'</textarea></label></p>';
  foreach(['claim_requested_irr'=>'خسارت مطالبه‌شده ریال','claim_received_irr'=>'خسارت دریافتی ریال'] as $key=>$label)echo '<p><label>'.esc_html($label).' <input type="number" min="0" name="'.$key.'" value="'.esc_attr($r[$key]??0).'"></label></p>';echo '<p><label>وضعیت پرونده خسارت <select name="claim_status">';foreach(['none'=>'ندارد','filed'=>'ثبت شده','reviewing'=>'در بررسی','paid'=>'پرداخت شد','denied'=>'رد شد'] as $key=>$label)echo '<option value="'.$key.'" '.selected($r['claim_status']??'none',$key,false).'>'.esc_html($label).'</option>';echo '</select></label></p><p><label>عکس آسیب JPEG/PNG تا ۱ مگابایت <input type="file" name="photo" accept="image/jpeg,image/png"></label></p><button class="button button-primary">ذخیره پرونده</button></form>';
  foreach($r['photos']??[] as $index=>$photo){$u=wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v33_return_photo','order_id'=>$id,'index'=>$index],admin_url('admin-post.php')),'hm_mahex_v33_return_photo_'.$id);echo '<p><a href="'.esc_url($u).'">دانلود عکس '.($index+1).'</a></p>';}
  $print=wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v33_batch_print','ids'=>$id,'return_label'=>1],admin_url('admin-post.php')),'hm_mahex_v33_batch_print');if($r&&in_array($r['status'],['approved','in_transit','received'],true)&&Support::can('print',$id))echo '<p><a class="button" target="_blank" rel="noopener" href="'.esc_url($print).'">چاپ برچسب مرجوعی</a></p>';
  echo '<h2>مدارک رسمی شرکت حمل</h2><p>فقط فایل دریافت‌شده از شرکت حمل را بارگذاری کنید؛ این قسمت بارنامه تولید نمی‌کند. فایل در اطلاعات سفارش نگهداری می‌شود و لینک عمومی ندارد.</p>';Support::form('hm_mahex_v33_document_upload');echo '<input type="hidden" name="order_id" value="'.$id.'"><input type="file" name="document" accept="application/pdf" required><button class="button">ذخیره PDF رسمی (تا ۳ مگابایت؛ حداکثر ۵ فایل)</button></form>';
  $docs=$order->get_meta(self::DOCUMENTS,true);foreach(is_array($docs)?$docs:[] as $key=>$doc){$u=wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v33_document_download','order_id'=>$id,'index'=>$key],admin_url('admin-post.php')),'hm_mahex_v33_document_download_'.$id);echo '<p><a href="'.esc_url($u).'">'.esc_html($doc['name']).'</a> — '.esc_html($doc['created_at']).'</p>';}
  echo '<details><summary>تاریخچه پرونده</summary><ol>';foreach($r['history']??[] as $h)echo '<li>'.esc_html(($h['at']??'').' — '.(self::STATES[$h['status']]??'').' — #'.($h['actor']??0)).'</li>';echo '</ol></details>';
 }
 public static function return_save(): void {
  $id=absint(Support::input('order_id'));Support::auth('hm_mahex_v33_return_save','operations',$id);$error='';try{$fields=[];foreach(['reason','tracking','claim_reference','customer_note','internal_note'] as $key){$fields[$key]=sanitize_textarea_field(Support::input($key));if(mb_strlen($fields[$key])>2000)throw new \InvalidArgumentException('متن بیش از حد طولانی است.');}if(!$fields['reason'])throw new \InvalidArgumentException('دلیل ضروری است.');foreach(['claim_requested_irr','claim_received_irr'] as $key)$fields[$key]=Support::number(Support::input($key,'0'));$claim=sanitize_key(Support::input('claim_status'));if(!in_array($claim,['none','filed','reviewing','paid','denied'],true))throw new \InvalidArgumentException('وضعیت خسارت نامعتبر است.');$fields['claim_status']=$claim;$status=sanitize_key(Support::input('status'));$photo=null;if(($_FILES['photo']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE)$photo=Support::file($_FILES['photo'],['image/jpeg','image/png'],1048576);
   Support::edit($id,self::META,absint(Support::input('revision')),static function($old,$order)use($fields,$status,$photo){if(!isset(self::STATES[$status])||(!$old&&$status!=='requested')||($old&&!self::transition($old['status'],$status)))throw new \InvalidArgumentException('انتقال وضعیت مجاز نیست.');$r=array_replace($old,$fields);$r['reference']=$old['reference']??('RMA-'.$order->get_id().'-'.strtoupper(wp_generate_password(6,false)));$r['status']=$status;if($photo){$r['photos'][]=$photo;if(count($r['photos'])>3)throw new \InvalidArgumentException('حداکثر سه عکس برای هر پرونده.');}$r['history'][]=['status'=>$status,'at'=>gmdate('c'),'actor'=>get_current_user_id()];$r['history']=array_slice($r['history'],-100);$order->add_order_note('پرونده مرجوعی/خسارت: '.self::STATES[$status]);return $r;});
  }catch(\Throwable $e){$error=$e->getMessage();}Support::redirect('hm-mahex-returns',$error?:'پرونده ذخیره شد.',$id);
 }
 public static function document_upload(): void {
  $id=absint(Support::input('order_id'));Support::auth('hm_mahex_v33_document_upload','operations',$id);$error='';$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();try{$file=Support::file($_FILES['document']??[],['application/pdf']);if(!$lock->acquire($id))throw new \RuntimeException('سفارش در حال ویرایش است.');try{$order=wc_get_order($id);if(!$order)throw new \RuntimeException('سفارش پیدا نشد.');$order->read_meta_data(true);$docs=$order->get_meta(self::DOCUMENTS,true);$docs=is_array($docs)?$docs:[];foreach($docs as $doc)if(hash_equals($doc['sha256'],$file['sha256']))throw new \RuntimeException('این فایل قبلاً ثبت شده است.');if(count($docs)>=5)throw new \RuntimeException('حداکثر پنج فایل.');$docs[]=$file;$order->update_meta_data(self::DOCUMENTS,$docs);$order->save_meta_data();$order->add_order_note('فایل بارنامه رسمی بارگذاری شد.');}finally{$lock->release($id);}}catch(\Throwable $e){$error=$e->getMessage();}Support::redirect('hm-mahex-returns',$error?:'فایل رسمی ذخیره شد.',$id);
 }
 private static function downloadedOrder(string $action){$id=absint($_GET['order_id']??0);check_admin_referer($action.'_'.$id);$order=wc_get_order($id);if(!$order||!self::canRead($order))wp_die('دسترسی مجاز نیست.','',['response'=>403]);return $order;}
 public static function document_download(): void {$order=self::downloadedOrder('hm_mahex_v33_document_download');$docs=$order->get_meta(self::DOCUMENTS,true);$i=absint($_GET['index']??0);if(!is_array($docs)||!isset($docs[$i]))wp_die('فایل موجود نیست.');Support::download($docs[$i]);}
 public static function return_photo(): void {$order=self::downloadedOrder('hm_mahex_v33_return_photo');$r=self::record($order);$i=absint($_GET['index']??0);if(!isset($r['photos'][$i]))wp_die('عکس موجود نیست.');Support::download($r['photos'][$i]);}
}
