<?php
namespace HoseinMomeni\MahexWoo\V33;

use HoseinMomeni\MahexWoo\V1\Config;
use HoseinMomeni\MahexWoo\V1\RuleEngine;
use HoseinMomeni\MahexWoo\V32\Rules;

final class RuleVersions {
 const OPTION='hm_mahex_v33_rule_versions';const HOOK='hm_mahex_v33_activate_rules';
 public static function register(): void {add_action('admin_menu',[self::class,'menu']);add_action('admin_post_hm_mahex_v33_rules',[self::class,'request']);add_action(self::HOOK,[self::class,'activate'],10,1);}
 public static function menu(): void {add_submenu_page('hm-mahex','نسخه‌ها و آزمایش قوانین','نسخه‌ها و آزمایش قوانین',Access::SETTINGS,'hm-mahex-rule-versions',[self::class,'page']);}
 public static function all(): array {$v=get_option(self::OPTION,[]);return is_array($v)?$v:[];}
 public static function record(array $rules,string $title,int $when=0): string {$rows=self::all();$id=wp_generate_uuid4();$rows[$id]=['id'=>$id,'title'=>sanitize_text_field($title),'rules'=>Rules::normalize($rules),'created_at'=>time(),'actor'=>get_current_user_id(),'scheduled_at'=>$when,'activated_at'=>0];while(count($rows)>50){$remove=null;foreach($rows as $key=>$row)if(!$row['scheduled_at']||$row['activated_at']){$remove=$key;break;}if($remove===null)throw new \InvalidArgumentException('حداکثر ۵۰ نسخه زمان‌بندی‌شده هم‌زمان مجاز است.');unset($rows[$remove]);}update_option(self::OPTION,$rows,false);if($when>0)wp_schedule_single_event($when,self::HOOK,[$id]);return $id;}
 public static function activate(string $id): void {
  $lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(0)){if(!wp_next_scheduled(self::HOOK,[$id]))wp_schedule_single_event(time()+60,self::HOOK,[$id]);return;}
  try{$rows=self::all();if(!isset($rows[$id])||$rows[$id]['activated_at'])return;if(($rows[$id]['scheduled_at']??0)>time())return;$before=RuleEngine::rules();update_option(Config::RULES,$rows[$id]['rules'],false);$rows[$id]['activated_at']=time();$rows[$id]['previous_rules']=$before;update_option(self::OPTION,$rows,false);\HoseinMomeni\MahexWoo\V2\RateCache::invalidate();\HoseinMomeni\MahexWoo\V1\ActivityLog::write('rules.scheduled_activated','نسخه زمان‌بندی‌شده قوانین فعال شد.',0,['version'=>$id]);}finally{$lock->release(0);}
 }
 public static function simulate($order,array $rules): array {
  $package=['contents'=>[],'contents_cost'=>0];$weight=0;$base=0;foreach($order->get_items('shipping') as $item)if($item->get_method_id()==='hm_mahex')$base+=(float)$item->get_meta('hm_mahex_freight',true);$base=$order->get_currency()==='IRT'?$base*10:$base;
  foreach($order->get_items() as $line){$p=$line->get_product();if(!$p||$p->is_virtual())continue;$package['contents'][]=['data'=>$p,'quantity'=>$line->get_quantity(),'line_total'=>$line->get_total()];$package['contents_cost']+=(float)$line->get_total();$weight+=(float)wc_get_weight($p->get_weight(),'g')*$line->get_quantity();}
  // Stored order amounts are historical currency, not necessarily the current store currency.
  $irr=$order->get_currency()==='IRT'?$package['contents_cost']*10:$package['contents_cost'];$package['contents_cost']=\HoseinMomeni\MahexWoo\Shipping\PricingSettings::to_store_currency($irr);
  $filter=static fn()=>$rules;add_filter('pre_option_'.Config::RULES,$filter);try{return ['base_irr'=>$base]+RuleEngine::apply($base,$package,\HoseinMomeni\MahexWoo\Shipping\PricingSettings::province_name($order->get_shipping_state()?:$order->get_billing_state()),$order->get_shipping_city()?:$order->get_billing_city(),(int)ceil($weight));}finally{remove_filter('pre_option_'.Config::RULES,$filter);}
 }
 public static function difference(array $a,array $b): array {$out=[];$aa=[];$bb=[];foreach($a as $r)$aa[$r['id']]=$r;foreach($b as $r)$bb[$r['id']]=$r;foreach(array_unique(array_merge(array_keys($aa),array_keys($bb))) as $id)if(($aa[$id]??null)!==($bb[$id]??null))$out[$id]=['before'=>$aa[$id]??null,'after'=>$bb[$id]??null];return $out;}
 public static function page(): void {
  if(!Access::can(Access::SETTINGS))return;$rows=self::all();echo '<div class="wrap" dir="rtl"><h1>نسخه‌ها و آزمایش قوانین</h1><p>شبیه‌سازی قوانین انتخابی را روی کرایه تاریخی سفارش اعمال می‌کند؛ مبنای قبل از تخفیف‌های تاریخی بازسازی نمی‌شود و محصول‌ها و دسته‌بندی‌ها از اطلاعات فعلی خوانده می‌شوند. هیچ سفارش تغییر نمی‌کند. زمان‌بندی با WP-Cron در اولین اجرای کرون پس از موعد انجام می‌شود.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('hm_mahex_v33_rules');echo '<input type="hidden" name="action" value="hm_mahex_v33_rules"><input type="hidden" name="revision" value="'.esc_attr(Rules::revision(RuleEngine::rules())).'"><p><label>عنوان نسخه <input name="title"></label> <label>موعد (زمان وردپرس) <input type="datetime-local" name="when"></label></p><button class="button" name="intent" value="snapshot">ثبت نسخه قوانین فعلی</button> <button class="button" name="intent" value="schedule">زمان‌بندی نسخه انتخابی / قوانین فعلی</button><hr><label>نسخه <select name="version">';foreach($rows as $id=>$row)echo '<option value="'.esc_attr($id).'">'.esc_html($row['title'].' — '.wp_date('Y-m-d H:i',$row['created_at'])).'</option>';echo '</select></label> <label>شناسه سفارش <input type="number" name="order_id" min="1"></label> <button class="button" name="intent" value="simulate">آزمایش روی سفارش</button> <button class="button" name="intent" value="compare">مقایسه با قوانین فعلی</button><p><label>شناسه قوانین برای بازگردانی انتخابی (با کاما؛ خالی یعنی تمام نسخه) <input name="rule_ids" size="45"></label> <button class="button" name="intent" value="restore">بازگردانی انتخابی</button></p></form>';
  $result=get_transient('hm_mahex_v33_rules_result_'.get_current_user_id());if($result)echo '<pre style="white-space:pre-wrap">'.esc_html(wp_json_encode($result,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre>';echo '<table class="widefat"><tr><th>عنوان</th><th>تعداد قانون</th><th>موعد</th><th>فعال‌سازی</th></tr>';foreach($rows as $row)echo '<tr><td>'.esc_html($row['title']).'</td><td>'.count($row['rules']).'</td><td>'.esc_html($row['scheduled_at']?wp_date('Y-m-d H:i',$row['scheduled_at']):'—').'</td><td>'.esc_html($row['activated_at']?wp_date('Y-m-d H:i',$row['activated_at']):'—').'</td></tr>';echo '</table></div>';
 }
 public static function request(): void {
  if(!Access::can(Access::SETTINGS))wp_die('دسترسی مجاز نیست.');check_admin_referer('hm_mahex_v33_rules');$intent=sanitize_key($_POST['intent']??'');$lock=new \HoseinMomeni\MahexWoo\Shipments\OptionOperationLock();if(!$lock->acquire(0))wp_die('عملیات دیگری در حال اجراست.');$error=null;$result=[];
  try{$current=RuleEngine::rules();if(!hash_equals(Rules::revision($current),(string)($_POST['revision']??'')))throw new \RuntimeException('قوانین تغییر کرده‌اند؛ صفحه را تازه کنید.');$rows=self::all();$id=sanitize_text_field(wp_unslash($_POST['version']??''));$selected=$rows[$id]['rules']??null;
   if(in_array($intent,['snapshot','schedule'],true)){$when=0;if($intent==='schedule'){$date=\DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',sanitize_text_field(wp_unslash($_POST['when']??'')),wp_timezone());if(!$date||$date->format('Y-m-d\TH:i')!==sanitize_text_field(wp_unslash($_POST['when']??''))||$date->getTimestamp()<=time())throw new \InvalidArgumentException('موعد آینده معتبر لازم است.');$when=$date->getTimestamp();}$result=['version'=>self::record($intent==='schedule'&&is_array($selected)?$selected:$current,sanitize_text_field(wp_unslash($_POST['title']??''))?:'نسخه قوانین',$when)];}
   elseif(!is_array($selected))throw new \InvalidArgumentException('نسخه دارای قانون پیدا نشد.');
   elseif($intent==='compare')$result=self::difference($current,$selected);
   elseif($intent==='simulate'){$oid=absint($_POST['order_id']??0);$order=wc_get_order($oid);if(!$order||!current_user_can('edit_shop_order',$oid))throw new \InvalidArgumentException('سفارش مجاز پیدا نشد.');$result=self::simulate($order,$selected);}
   elseif($intent==='restore'){$ids=array_filter(array_map('sanitize_key',explode(',',sanitize_text_field(wp_unslash($_POST['rule_ids']??'')))));$next=$selected;if($ids){$next=array_values(array_filter($current,static fn($r)=>!in_array($r['id'],$ids,true)));foreach($selected as $r)if(in_array($r['id'],$ids,true))$next[]=$r;}$next=Rules::normalize($next);self::record($current,'پیش از بازگردانی');update_option(Config::RULES,$next,false);\HoseinMomeni\MahexWoo\V2\RateCache::invalidate();\HoseinMomeni\MahexWoo\V1\ActivityLog::write('rules.selective_restore','قوانین انتخابی از نسخه بازگردانی شد.',0,['version'=>$id,'ids'=>$ids]);$result=['restored'=>count($next)];}
   else throw new \InvalidArgumentException('عملیات نامعتبر است.');
  }catch(\Throwable $e){$error=$e->getMessage();}finally{$lock->release(0);}if($error)wp_die(esc_html($error));set_transient('hm_mahex_v33_rules_result_'.get_current_user_id(),$result,600);wp_safe_redirect(admin_url('admin.php?page=hm-mahex-rule-versions'));exit;
 }
}
