<?php
namespace HoseinMomeni\MahexWoo\V33;

/** Inspect a candidate ZIP in isolation; never execute candidate PHP on the live site. */
final class UpgradeSandbox {
 public static function register(): void {add_action('admin_menu',[self::class,'menu']);add_action('admin_post_hm_mahex_v33_sandbox',[self::class,'request']);}
 public static function menu(): void {add_submenu_page('hm-mahex','آزمایش بسته ارتقا','آزمایش بسته ارتقا',Access::cap('settings'),'hm-mahex-upgrade-sandbox',[self::class,'page']);}
 public static function inspect(string $path): array {
  $zip=new \ZipArchive();if($zip->open($path)!==true)throw new \InvalidArgumentException('ZIP قابل خواندن نیست.');$total=0;$php=0;$errors=[];$header=null;$hasPdf=false;
  try{if($zip->numFiles>12000)throw new \InvalidArgumentException('تعداد فایل بیش از حد است.');for($i=0;$i<$zip->numFiles;$i++){$stat=$zip->statIndex($i);if(!$stat)throw new \InvalidArgumentException('آرشیو خراب است.');$name=$stat['name'];if(str_contains($name,'\\')||str_starts_with($name,'/')||in_array('..',explode('/',$name),true)||!str_starts_with($name,'mahex-shipping-for-woocommerce/'))throw new \InvalidArgumentException('مسیر آرشیو مجاز نیست.');$total+=(int)$stat['size'];if($total>100*1024*1024||(int)$stat['size']>10*1024*1024)throw new \InvalidArgumentException('حجم بازشده بیش از حد است.');$attributes=0;$opsys=0;if($zip->getExternalAttributesIndex($i,$opsys,$attributes)&&(($attributes>>16)&0170000)===0120000)throw new \InvalidArgumentException('لینک نمادین مجاز نیست.');if($name==='mahex-shipping-for-woocommerce/vendor/tecnickcom/tcpdf/tcpdf.php')$hasPdf=true;if($name==='mahex-shipping-for-woocommerce/mahex-shipping-for-woocommerce.php')$header=$zip->getFromIndex($i);if(str_ends_with($name,'.php')){$code=$zip->getFromIndex($i);if($code===false)throw new \InvalidArgumentException('فایل قابل خواندن نیست.');$php++;try{token_get_all($code,TOKEN_PARSE);}catch(\ParseError $e){$errors[]=$name.': '.$e->getMessage();}}}
   if(!$header)throw new \InvalidArgumentException('فایل اصلی افزونه موجود نیست.');$fields=[];foreach(['Version','Requires PHP','Requires at least','WC requires at least'] as $key){preg_match('/'.preg_quote($key,'/').':\s*([^\r\n]+)/',$header,$m);$fields[$key]=trim($m[1]??'');}if(!preg_match('/^\d+\.\d+\.\d+(?:[-+][a-zA-Z0-9.-]+)?$/',$fields['Version']))$errors[]='نسخه بسته معتبر نیست.';global $wp_version;foreach([['Requires PHP',PHP_VERSION],['Requires at least',$wp_version??'0'],['WC requires at least',defined('WC_VERSION')?WC_VERSION:'0']] as [$key,$installed])if(!$fields[$key]||version_compare($installed,$fields[$key],'<'))$errors[]=$key.' نیاز دارد: '.$fields[$key].'؛ نصب‌شده: '.$installed;
   return ['version'=>$fields['Version'],'installed'=>HM_MAHEX_VERSION,'sha256'=>hash_file('sha256',$path),'files'=>$zip->numFiles,'php_files'=>$php,'uncompressed_bytes'=>$total,'pdf_library'=>$hasPdf,'errors'=>$errors,'checked_at'=>gmdate('c'),'scope'=>'فقط بررسی ایزوله فایل، نحو PHP روی نسخه جاری و پیش‌نیازها؛ کد بسته اجرا یا نصب نشده است. آزمون واقعی MySQL/HPOS و مرورگر در workflow مستقل انجام می‌شود.'];
  }finally{$zip->close();}
 }
 public static function page(): void {if(!Support::can('settings'))return;echo '<div class="wrap mhx-v32" dir="rtl"><h1>آزمایش بسته ارتقا</h1><p>بسته نامزد در حافظه بررسی می‌شود؛ روی فروشگاه نصب یا اجرا نمی‌شود. برای آزمون نصب واقعی، محیط جدا و موقت GitHub Actions در دسترس است.</p>';Support::form('hm_mahex_v33_sandbox');echo '<input type="file" name="candidate" accept=".zip" required><button class="button button-primary">بررسی ZIP (تا ۴۰ مگابایت)</button></form>';echo '<p><a target="_blank" rel="noopener" href="https://github.com/anonyset/mahex-shipping-for-woocommerce/actions/workflows/integration.yml">آزمون ایزوله نصب، MySQL، HPOS و مرورگر</a></p>';$report=get_transient('hm_mahex_v33_sandbox_'.get_current_user_id());if(is_array($report)){echo '<pre dir="rtl" style="white-space:pre-wrap">'.esc_html(wp_json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre>';}echo '</div>';}
 public static function request(): void {Support::auth('hm_mahex_v33_sandbox','settings');$f=$_FILES['candidate']??[];try{if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_string($f['tmp_name']??null)||!is_uploaded_file($f['tmp_name'])||filesize($f['tmp_name'])>40*1024*1024||strtolower(pathinfo($f['name']??'',PATHINFO_EXTENSION))!=='zip')throw new \InvalidArgumentException('فایل ZIP معتبر تا ۴۰ مگابایت انتخاب کنید.');$report=self::inspect($f['tmp_name']);}catch(\Throwable $e){$report=['errors'=>[$e->getMessage()]];}set_transient('hm_mahex_v33_sandbox_'.get_current_user_id(),$report,1800);wp_safe_redirect(admin_url('admin.php?page=hm-mahex-upgrade-sandbox'));exit;}
}
