<?php
namespace HoseinMomeni\MahexWoo\V3;
final class Admin {
 const PAGE='hm-mahex-v3';
 public static function register():void{add_action('admin_menu',[self::class,'menu'],32);foreach(array('save_branch'=>'saveBranch','transfer'=>'transfer','save_settings'=>'saveSettings','qc'=>'qc','snapshot'=>'snapshot','approve'=>'approve') as $a=>$m)add_action('admin_post_hm_mahex_v3_'.$a,[self::class,$m]);}
 public static function menu():void{add_submenu_page('hm-mahex','Mahex Control Center 3.0','Control Center 3.0','manage_woocommerce',self::PAGE,[self::class,'render']);}
 private static function cap():void{if(!current_user_can('manage_woocommerce'))wp_die('Access denied');}
 private static function nonce(string $a):void{check_admin_referer('hm_mahex_v3_'.$a);self::cap();}
 private static function back(string $tab):void{wp_safe_redirect(admin_url('admin.php?page='.self::PAGE.'&tab='.$tab.'&updated=1'));exit;}
 public static function render():void{self::cap();$tab=sanitize_key($_GET['tab']??'overview');$tabs=array('overview'=>'مرکز کنترل','branches'=>'شعب و موجودی','governance'=>'Rule و تأیید','operations'=>'عملیات و QC','finance'=>'اعتبار و مالی','analytics'=>'تحلیل شبکه','system'=>'سیستم');if(!isset($tabs[$tab]))$tab='overview';echo '<div class="wrap" dir="rtl"><h1>Mahex Shipping OS <small style="font-size:14px">3.0.0 Multi-Store & Control Center</small></h1><p>کنترل محلی چندشعبه‌ای، بدون API خارجی.</p><nav class="nav-tab-wrapper">';foreach($tabs as $k=>$l)echo '<a class="nav-tab '.($tab===$k?'nav-tab-active':'').'" href="'.esc_url(admin_url('admin.php?page='.self::PAGE.'&tab='.$k)).'">'.esc_html($l).'</a>';echo '</nav><div style="margin-top:16px">';match($tab){'branches'=>self::branches(),'governance'=>self::governance(),'operations'=>self::operations(),'finance'=>self::finance(),'analytics'=>self::analytics(),'system'=>self::system(),default=>self::overview()};echo '</div></div>';}
 private static function overview():void{$r=Operations::branchRanking();$pending=Governance::pending();$tasks=Operations::tasks();echo '<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px"><div class="card"><h3>شعب فعال</h3><strong>'.count(BranchManager::all()).'</strong></div><div class="card"><h3>تأییدهای معلق</h3><strong>'.count($pending).'</strong></div><div class="card"><h3>کارهای باز</h3><strong>'.count($tasks).'</strong></div><div class="card"><h3>نسخه</h3><strong>3.0.0</strong></div></div><div class="card"><h2>رتبه‌بندی شعب</h2><table class="widefat striped"><tr><th>شعبه</th><th>سفارش</th><th>درآمد ارسال</th><th>هزینه</th><th>سود</th><th>Score</th></tr>';foreach($r as $x)echo '<tr><td>'.esc_html($x['branch']['name']).'</td><td>'.(int)$x['orders'].'</td><td>'.wc_price($x['revenue']).'</td><td>'.wc_price($x['cost']).'</td><td>'.wc_price($x['profit']).'</td><td>'.esc_html((string)$x['score']).'</td></tr>';echo '</table></div>';}
 private static function branches():void{$bs=BranchManager::all(false);echo '<div class="card"><h2>تعریف شعبه</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v3_save_branch">';wp_nonce_field('hm_mahex_v3_save_branch');echo '<p><input name="name" placeholder="نام شعبه" required> <input name="code" placeholder="کد شعبه" required> <input name="province" placeholder="استان"> <input name="city" placeholder="شهر"> <input type="number" name="capacity_daily" placeholder="ظرفیت روزانه"> <button class="button button-primary">ذخیره</button></p></form></div><div class="card"><h2>شعب</h2><table class="widefat striped"><tr><th>کد</th><th>نام</th><th>محدوده</th><th>ظرفیت</th><th>موجودی بسته‌بندی</th></tr>';foreach($bs as $b){$stock=BranchManager::stock((int)$b['id']);echo '<tr><td>'.esc_html($b['code']).'</td><td>'.esc_html($b['name']).'</td><td>'.esc_html($b['province'].' / '.$b['city']).'</td><td>'.(int)$b['capacity_daily'].'</td><td>'.count($stock).' پروفایل</td></tr>';}echo '</table></div><div class="card"><h2>انتقال موجودی بین شعب</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v3_transfer">';wp_nonce_field('hm_mahex_v3_transfer');echo '<select name="from">';foreach($bs as $b)echo '<option value="'.$b['id'].'">'.esc_html($b['name']).'</option>';echo '</select> → <select name="to">';foreach($bs as $b)echo '<option value="'.$b['id'].'">'.esc_html($b['name']).'</option>';echo '</select> <input name="profile" placeholder="کد پروفایل بسته" required> <input type="number" min="1" name="qty" value="1"> <button class="button">انتقال</button></form></div>';}
 private static function governance():void{echo '<div class="card"><h2>Approval Workflow</h2><table class="widefat striped"><tr><th>ID</th><th>نوع</th><th>درخواست‌کننده</th><th>زمان</th><th></th></tr>';foreach(Governance::pending() as $a){$url=wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v3_approve&id='.$a['id'].'&decision=1'),'hm_mahex_v3_approve');echo '<tr><td>'.$a['id'].'</td><td>'.esc_html($a['object_type']).'</td><td>'.$a['requested_by'].'</td><td>'.esc_html($a['created_at']).'</td><td><a class="button" href="'.esc_url($url).'">تأیید</a></td></tr>';}echo '</table></div><div class="card"><h2>Rule Version History</h2><p>'.count(Governance::rules('',-1)).' نسخه ثبت‌شده</p></div>';}
 private static function operations():void{echo '<div class="card"><h2>Smart Task Queue</h2><table class="widefat striped"><tr><th>اولویت</th><th>نوع</th><th>شعبه</th><th>سفارش</th><th>مسئول</th></tr>';foreach(Operations::tasks() as $t)echo '<tr><td>'.$t['priority'].'</td><td>'.esc_html($t['task_type']).'</td><td>'.$t['branch_id'].'</td><td>#'.$t['order_id'].'</td><td>'.$t['assignee_id'].'</td></tr>';echo '</table></div><div class="card"><h2>QC Station</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v3_qc">';wp_nonce_field('hm_mahex_v3_qc');echo '<input type="number" name="order_id" placeholder="شماره سفارش" required> <select name="result"><option value="pass">قبول</option><option value="fail">رد</option></select> <input name="note" placeholder="توضیح"> <button class="button">ثبت QC</button></form></div>';}
 private static function finance():void{echo '<div class="card"><h2>Wallet / Credit</h2><p>زیرساخت اعتبار داخلی، سقف اعتبار، دفتر گردش و Aging فعال است.</p><p>مانده‌های قدیمی: '.count(Wallet::aging()).' مشتری</p></div>';}
 private static function analytics():void{echo '<div class="card"><h2>Network Analytics</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v3_snapshot">';wp_nonce_field('hm_mahex_v3_snapshot');echo '<button class="button">ساخت Snapshot امروز</button></form><table class="widefat striped"><tr><th>شعبه</th><th>میانگین روزانه</th><th>پیک پیش‌بینی</th><th>ظرفیت پیشنهادی</th></tr>';foreach(BranchManager::all() as $b){$f=Analytics::forecastCapacity((int)$b['id']);echo '<tr><td>'.esc_html($b['name']).'</td><td>'.$f['daily_average'].'</td><td>'.$f['predicted_peak'].'</td><td>'.$f['recommended_capacity'].'</td></tr>';}echo '</table></div>';}
 private static function system():void{$s=Config::all();echo '<div class="card"><h2>تنظیمات 3.0</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v3_save_settings">';wp_nonce_field('hm_mahex_v3_save_settings');foreach(array('auto_branch'=>'تخصیص خودکار شعبه','approval_required'=>'تأیید تغییر Rule','four_eyes'=>'تأیید دو نفره','wallet_enabled'=>'اعتبار داخلی','snapshot_enabled'=>'Snapshot تحلیلی') as $k=>$l)echo '<p><label><input type="checkbox" name="'.$k.'" value="1" '.checked(!empty($s[$k]),true,false).'> '.esc_html($l).'</label></p>';echo '<button class="button button-primary">ذخیره</button></form><p>Migration: '.esc_html(MigrationManager::status()).'</p></div>';}
 public static function saveBranch():void{self::nonce('save_branch');BranchManager::save($_POST);self::back('branches');}public static function transfer():void{self::nonce('transfer');BranchManager::transfer((int)$_POST['from'],(int)$_POST['to'],sanitize_key($_POST['profile']??''),(int)$_POST['qty']);self::back('branches');}public static function saveSettings():void{self::nonce('save_settings');Config::save($_POST);self::back('system');}public static function qc():void{self::nonce('qc');Operations::qc((int)$_POST['order_id'],($_POST['result']??'')==='pass',sanitize_textarea_field($_POST['note']??''));self::back('operations');}public static function snapshot():void{self::nonce('snapshot');Analytics::snapshotDate();self::back('analytics');}public static function approve():void{self::nonce('approve');Governance::decide((int)($_GET['id']??0),!empty($_GET['decision']));self::back('governance');}
}
