<?php
namespace HoseinMomeni\MahexWoo\V3;
final class BranchManager {
 private static function t(string $n): string {global $wpdb;return $wpdb->prefix.'hm_mahex_v3_'.$n;}
 public static function all(bool $active=true): array {global $wpdb;$sql='SELECT * FROM '.self::t('branches');if($active)$sql.=" WHERE status='active'";$sql.=' ORDER BY name';return (array)$wpdb->get_results($sql,ARRAY_A);}
 public static function save(array $d,int $id=0): int {global $wpdb;$row=array('code'=>sanitize_key($d['code']??('branch-'.time())),'name'=>sanitize_text_field($d['name']??''),'status'=>in_array(($d['status']??'active'),array('active','inactive'),true)?$d['status']:'active','manager_id'=>max(0,(int)($d['manager_id']??0)),'province'=>sanitize_text_field($d['province']??''),'city'=>sanitize_text_field($d['city']??''),'territories'=>wp_json_encode(array_values(array_filter(array_map('sanitize_text_field',(array)($d['territories']??array())))),JSON_UNESCAPED_UNICODE),'capacity_daily'=>max(0,(int)($d['capacity_daily']??0)),'parent_id'=>max(0,(int)($d['parent_id']??0)),'updated_at'=>current_time('mysql'));
  if($id){$wpdb->update(self::t('branches'),$row,array('id'=>$id));return $id;}$row['created_at']=current_time('mysql');$wpdb->insert(self::t('branches'),$row);return (int)$wpdb->insert_id;}
 public static function assignOrder(int $orderId): int {$o=wc_get_order($orderId);if(!$o)return 0;$existing=(int)$o->get_meta('_hm_mahex_branch_id',true);if($existing)return $existing;$province=(string)$o->get_shipping_state();$city=trim((string)$o->get_shipping_city());$best=0;$bestScore=-1;foreach(self::all() as $b){$score=0;if($province&&mb_stripos((string)$b['province'],$province)!==false)$score+=4;if($city&&mb_stripos((string)$b['city'],$city)!==false)$score+=8;$terr=json_decode((string)$b['territories'],true)?:array();foreach($terr as $x)if($city&&mb_stripos($city,(string)$x)!==false)$score+=10;if($score>$bestScore){$bestScore=$score;$best=(int)$b['id'];}}if(!$best)$best=(int)(Config::all()['default_branch']??0);if($best){$o->update_meta_data('_hm_mahex_branch_id',$best);$o->save();}return $best;}
 public static function stock(int $branchId): array {global $wpdb;return (array)$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::t('branch_stock').' WHERE branch_id=%d ORDER BY profile_id',$branchId),ARRAY_A);}
 public static function adjustStock(int $branchId,string $profile,int $delta,int $min=0,float $cost=0): void {global $wpdb;$t=self::t('branch_stock');$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE branch_id=%d AND profile_id=%s",$branchId,$profile),ARRAY_A);if($row)$wpdb->update($t,array('qty'=>(int)$row['qty']+$delta,'min_qty'=>$min?:$row['min_qty'],'unit_cost_irr'=>$cost?:$row['unit_cost_irr'],'updated_at'=>current_time('mysql')),array('branch_id'=>$branchId,'profile_id'=>$profile));else $wpdb->insert($t,array('branch_id'=>$branchId,'profile_id'=>$profile,'qty'=>max(0,$delta),'min_qty'=>$min,'unit_cost_irr'=>$cost,'updated_at'=>current_time('mysql')));}
 public static function transfer(int $from,int $to,string $profile,int $qty,string $note=''): int {global $wpdb;if($from<1||$to<1||$from===$to||$qty<1)return 0;$wpdb->insert(self::t('transfers'),array('from_branch'=>$from,'to_branch'=>$to,'profile_id'=>sanitize_key($profile),'qty'=>$qty,'status'=>'completed','note'=>sanitize_textarea_field($note),'created_by'=>get_current_user_id(),'created_at'=>current_time('mysql'),'completed_at'=>current_time('mysql')));$id=(int)$wpdb->insert_id;if($id){self::adjustStock($from,$profile,-$qty);self::adjustStock($to,$profile,$qty);}return $id;}
 public static function profitability(int $days=30): array {$since=(new \DateTimeImmutable('now',wp_timezone()))->modify('-'.$days.' days')->format('Y-m-d H:i:s');$out=[];foreach(self::all(false) as $b){$ids=wc_get_orders(array('limit'=>-1,'date_created'=>'>='.$since,'meta_key'=>'_hm_mahex_branch_id','meta_value'=>(string)$b['id'],'return'=>'ids'));$rev=$cost=0;foreach($ids as $id){$o=wc_get_order($id);if(!$o)continue;$rev+=(float)$o->get_shipping_total();$cost+=(float)$o->get_meta('_hm_mahex_actual_shipping_cost',true);}$out[]=array('branch'=>$b,'orders'=>count($ids),'revenue'=>$rev,'cost'=>$cost,'profit'=>$rev-$cost);}return $out;}
}
