<?php
namespace HoseinMomeni\MahexWoo\V3;
final class Governance {
 private static function t(string $n):string{global $wpdb;return $wpdb->prefix.'hm_mahex_v3_'.$n;}
 public static function versionRule(string $key,int $branch,array $payload,string $status='draft'): int {global $wpdb;$v=1+(int)$wpdb->get_var($wpdb->prepare('SELECT MAX(version_no) FROM '.self::t('rule_versions').' WHERE rule_key=%s AND branch_id=%d',$key,$branch));$wpdb->insert(self::t('rule_versions'),array('rule_key'=>sanitize_key($key),'branch_id'=>$branch,'version_no'=>$v,'payload'=>wp_json_encode($payload,JSON_UNESCAPED_UNICODE),'status'=>$status,'created_by'=>get_current_user_id(),'created_at'=>current_time('mysql'),'published_at'=>$status==='published'?current_time('mysql'):null));$id=(int)$wpdb->insert_id;if($id&&Config::bool('approval_required',true))self::requestApproval('rule_version',$id);return $id;}
 public static function requestApproval(string $type,int $id): int {global $wpdb;$wpdb->insert(self::t('approvals'),array('object_type'=>sanitize_key($type),'object_id'=>$id,'requested_by'=>get_current_user_id(),'status'=>'pending','created_at'=>current_time('mysql')));return (int)$wpdb->insert_id;}
 public static function decide(int $approvalId,bool $approve,string $note=''): bool {global $wpdb;$a=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::t('approvals').' WHERE id=%d',$approvalId),ARRAY_A);if(!$a||$a['status']!=='pending')return false;if(Config::bool('four_eyes',false)&&(int)$a['requested_by']===get_current_user_id())return false;$wpdb->update(self::t('approvals'),array('status'=>$approve?'approved':'rejected','approved_by'=>get_current_user_id(),'note'=>sanitize_textarea_field($note),'decided_at'=>current_time('mysql')),array('id'=>$approvalId));if($approve&&$a['object_type']==='rule_version')$wpdb->update(self::t('rule_versions'),array('status'=>'published','published_at'=>current_time('mysql')),array('id'=>(int)$a['object_id']));return true;}
 public static function pending(): array {global $wpdb;return (array)$wpdb->get_results("SELECT * FROM ".self::t('approvals')." WHERE status='pending' ORDER BY created_at ASC LIMIT 200",ARRAY_A);}
 public static function rules(string $key='',int $branch=0): array {global $wpdb;$where='1=1';$args=[];if($key){$where.=' AND rule_key=%s';$args[]=$key;}if($branch>=0){$where.=' AND branch_id=%d';$args[]=$branch;}$sql='SELECT * FROM '.self::t('rule_versions').' WHERE '.$where.' ORDER BY rule_key,branch_id,version_no DESC';if($args)$sql=$wpdb->prepare($sql,...$args);return (array)$wpdb->get_results($sql,ARRAY_A);}
 public static function rollback(int $versionId): int {global $wpdb;$r=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::t('rule_versions').' WHERE id=%d',$versionId),ARRAY_A);if(!$r)return 0;return self::versionRule($r['rule_key'],(int)$r['branch_id'],json_decode((string)$r['payload'],true)?:array(),'draft');}
}
