<?php
namespace HoseinMomeni\MahexWoo\V3;
final class Operations {
 private static function t(string $n):string{global $wpdb;return $wpdb->prefix.'hm_mahex_v3_'.$n;}
 public static function createTask(int $branch,int $order,string $type,int $priority=50,int $assignee=0,array $payload=[]): int {global $wpdb;$wpdb->insert(self::t('tasks'),array('branch_id'=>$branch,'order_id'=>$order,'task_type'=>sanitize_key($type),'priority'=>max(1,min(100,$priority)),'assignee_id'=>$assignee,'status'=>'open','payload'=>wp_json_encode($payload,JSON_UNESCAPED_UNICODE),'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')));return (int)$wpdb->insert_id;}
 public static function tasks(int $branch=0,string $status='open'): array {global $wpdb;$sql='SELECT * FROM '.self::t('tasks').' WHERE status=%s';$args=[$status];if($branch){$sql.=' AND branch_id=%d';$args[]=$branch;}$sql.=' ORDER BY priority DESC,created_at ASC LIMIT 500';return (array)$wpdb->get_results($wpdb->prepare($sql,...$args),ARRAY_A);}
 public static function smartAssign(int $taskId): int {global $wpdb;$t=self::t('tasks');$task=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d",$taskId),ARRAY_A);if(!$task)return 0;$users=get_users(array('role__in'=>array('administrator','shop_manager'),'fields'=>'ids'));$best=0;$min=PHP_INT_MAX;foreach($users as $u){$n=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $t WHERE assignee_id=%d AND status='open'",$u));if($n<$min){$min=$n;$best=(int)$u;}}if($best)$wpdb->update($t,array('assignee_id'=>$best,'updated_at'=>current_time('mysql')),array('id'=>$taskId));return $best;}
 public static function qc(int $orderId,bool $pass,string $note=''): int {global $wpdb;$o=wc_get_order($orderId);if(!$o)return 0;$b=(int)$o->get_meta('_hm_mahex_branch_id',true);$wpdb->insert(self::t('qc'),array('order_id'=>$orderId,'branch_id'=>$b,'result'=>$pass?'pass':'fail','note'=>sanitize_textarea_field($note),'actor_id'=>get_current_user_id(),'created_at'=>current_time('mysql')));if(!$pass)self::createTask($b,$orderId,'qc_failure',95,0,array('note'=>$note));return (int)$wpdb->insert_id;}
 public static function branchRanking(int $days=30): array {$rows=BranchManager::profitability($days);foreach($rows as &$r){$r['score']=round(max(0,100-($r['orders']?max(0,-$r['profit'])/max(1,$r['orders']):0)),1);}unset($r);usort($rows,fn($a,$b)=>$b['score']<=>$a['score']);return $rows;}
}
