<?php
namespace HoseinMomeni\MahexWoo\V3;
final class Schema {
 public const VERSION='3.0.0';
 public static function install(): void {global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();$p=$wpdb->prefix;
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_branches (id bigint unsigned NOT NULL AUTO_INCREMENT,code varchar(40) NOT NULL,name varchar(190) NOT NULL,status varchar(20) NOT NULL DEFAULT 'active',manager_id bigint unsigned NOT NULL DEFAULT 0,province varchar(120) NOT NULL DEFAULT '',city varchar(120) NOT NULL DEFAULT '',territories longtext NULL,capacity_daily int NOT NULL DEFAULT 0,parent_id bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY code(code),KEY status(status)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_branch_stock (branch_id bigint unsigned NOT NULL,profile_id varchar(80) NOT NULL,qty int NOT NULL DEFAULT 0,min_qty int NOT NULL DEFAULT 0,unit_cost_irr decimal(20,4) NOT NULL DEFAULT 0,updated_at datetime NOT NULL,PRIMARY KEY(branch_id,profile_id),KEY low_stock(qty,min_qty)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_transfers (id bigint unsigned NOT NULL AUTO_INCREMENT,from_branch bigint unsigned NOT NULL,to_branch bigint unsigned NOT NULL,profile_id varchar(80) NOT NULL,qty int NOT NULL,status varchar(20) NOT NULL DEFAULT 'draft',note text NULL,created_by bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,completed_at datetime NULL,PRIMARY KEY(id),KEY branch_status(from_branch,to_branch,status)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_rule_versions (id bigint unsigned NOT NULL AUTO_INCREMENT,rule_key varchar(80) NOT NULL,branch_id bigint unsigned NOT NULL DEFAULT 0,version_no int NOT NULL,payload longtext NOT NULL,status varchar(20) NOT NULL DEFAULT 'draft',created_by bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,published_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY rule_version(rule_key,branch_id,version_no),KEY status(status)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_approvals (id bigint unsigned NOT NULL AUTO_INCREMENT,object_type varchar(40) NOT NULL,object_id bigint unsigned NOT NULL,requested_by bigint unsigned NOT NULL DEFAULT 0,approved_by bigint unsigned NOT NULL DEFAULT 0,status varchar(20) NOT NULL DEFAULT 'pending',note text NULL,created_at datetime NOT NULL,decided_at datetime NULL,PRIMARY KEY(id),KEY object_status(object_type,object_id,status)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_tasks (id bigint unsigned NOT NULL AUTO_INCREMENT,branch_id bigint unsigned NOT NULL DEFAULT 0,order_id bigint unsigned NOT NULL DEFAULT 0,task_type varchar(40) NOT NULL,priority int NOT NULL DEFAULT 50,assignee_id bigint unsigned NOT NULL DEFAULT 0,status varchar(20) NOT NULL DEFAULT 'open',payload longtext NULL,due_at datetime NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),KEY branch_status(branch_id,status),KEY assignee_status(assignee_id,status),KEY order_id(order_id)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_qc (id bigint unsigned NOT NULL AUTO_INCREMENT,order_id bigint unsigned NOT NULL,branch_id bigint unsigned NOT NULL DEFAULT 0,result varchar(20) NOT NULL,note text NULL,actor_id bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,PRIMARY KEY(id),KEY order_created(order_id,created_at),KEY result(result)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_wallet (customer_id bigint unsigned NOT NULL,balance_irr decimal(20,4) NOT NULL DEFAULT 0,credit_limit_irr decimal(20,4) NOT NULL DEFAULT 0,updated_at datetime NOT NULL,PRIMARY KEY(customer_id)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_wallet_ledger (id bigint unsigned NOT NULL AUTO_INCREMENT,customer_id bigint unsigned NOT NULL,order_id bigint unsigned NOT NULL DEFAULT 0,amount_irr decimal(20,4) NOT NULL,type varchar(30) NOT NULL,note text NULL,actor_id bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,PRIMARY KEY(id),KEY customer_created(customer_id,created_at),KEY order_id(order_id)) $c;");
  dbDelta("CREATE TABLE {$p}hm_mahex_v3_snapshots (id bigint unsigned NOT NULL AUTO_INCREMENT,snapshot_date date NOT NULL,branch_id bigint unsigned NOT NULL DEFAULT 0,metric_key varchar(80) NOT NULL,value_num decimal(20,4) NOT NULL DEFAULT 0,context longtext NULL,created_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY snap(snapshot_date,branch_id,metric_key),KEY metric_date(metric_key,snapshot_date)) $c;");
  update_option('hm_mahex_v3_schema',self::VERSION,false);
 }
 public static function maybeInstall(): void {if((string)get_option('hm_mahex_v3_schema','')!==self::VERSION)self::install();}
}
