<?php
namespace {function get_option($name,$default=[]){return $default;}function sanitize_key($s){return preg_replace('/[^a-z0-9_-]/','',strtolower($s));}function esc_attr($s){return htmlspecialchars((string)$s);} }
namespace HoseinMomeni\MahexWoo\V32 {
 require __DIR__.'/../src/V32/Designer.php';require __DIR__.'/../src/V32/Packing.php';
 function check($value,$msg){if(!$value)throw new \RuntimeException($msg);}function rejects(callable $fn,$msg){try{$fn();}catch(\InvalidArgumentException $e){return;}throw new \RuntimeException($msg);}
 $layout=Designer::validate(Designer::defaults());check($layout['fields']['barcode']['w']===84.0,'Default label size incorrect');$invalid=$layout;$invalid['fields']['address']['x']=95;rejects(fn()=>Designer::validate($invalid),'Out of paper fields allowed');$invalid=$layout;$invalid['fields']['barcode']['w']=20;rejects(fn()=>Designer::validate($invalid),'Unscannable barcode width allowed');$invalid=$layout;$invalid['fields']['phone']['font']=NAN;rejects(fn()=>Designer::validate($invalid),'Nonfinite font allowed');
 $units=['1:0'=>['weight_g'=>400,'dimensions_mm'=>[80,100,50],'group'=>'normal'],'2:0'=>['weight_g'=>300,'dimensions_mm'=>[50,50,50],'group'=>'normal']];$profiles=['box'=>['name'=>'Box','length_mm'=>200,'width_mm'=>150,'height_mm'=>100,'empty_weight_g'=>100,'max_weight_g'=>1000,'max_items'=>5,'unit_cost_irr'=>50000]];$assign=[['profile_id'=>'box','units'=>['1:0','2:0']]];
 $plan=Packing::validate($assign,$units,$profiles);check($plan['actual_weight_g']===800,'Tare or item weight wrong');check($plan['volumetric_weight_g']===600,'Volumetric formula wrong');check($plan['chargeable_weight_g']===800,'Chargeable weight wrong');check($plan['cost_irr']===50000,'Cost taken from client');
 rejects(fn()=>Packing::validate([['profile_id'=>'box','units'=>['1:0','1:0']]],$units,$profiles),'Duplicate unit allowed');rejects(fn()=>Packing::validate([['profile_id'=>'box','units'=>['1:0']]],$units,$profiles),'Missing unit allowed');$different=$units;$different['2:0']['group']='fragile';rejects(fn()=>Packing::validate($assign,$different,$profiles),'Fragile mixed with normal');$different['2:0']['group']='nomix:liquid';rejects(fn()=>Packing::validate($assign,$different,$profiles),'No mix group ignored');$different['2:0']['group']='danger:chemical';rejects(fn()=>Packing::validate($assign,$different,$profiles),'Dangerous group mixed');$large=$units;$large['1:0']['dimensions_mm']=[201,100,100];rejects(fn()=>Packing::validate($assign,$large,$profiles),'Oversize dimensions allowed');$heavy=$units;$heavy['1:0']['weight_g']=900;rejects(fn()=>Packing::validate($assign,$heavy,$profiles),'Overweight allowed');$full=$units;$full['1:0']['dimensions_mm']=[200,150,100];rejects(fn()=>Packing::validate($assign,$full,$profiles),'Over volume allowed');$limited=$profiles;$limited['box']['max_items']=1;rejects(fn()=>Packing::validate($assign,$units,$limited),'Max items ignored');check(Packing::fingerprint($units)!==Packing::fingerprint($heavy),'Changed order fingerprint not detected');
 echo "Designer and manual packing tests passed\n";
}
