<?php
namespace { $caps=[];function current_user_can($cap,...$args){global $caps;return !empty($caps[$cap]);}function sanitize_text_field($text){return strip_tags($text);}function get_option($key,$default=[]){return $default;} }
namespace HoseinMomeni\MahexWoo\V33 {
 require __DIR__.'/../src/V33/Access.php';require __DIR__.'/../src/V33/Management.php';require __DIR__.'/../src/V33/RuleVersions.php';require __DIR__.'/../src/V31/Finance.php';
 function check($ok,$message){if(!$ok)throw new \RuntimeException($message);}function rejected($callback){try{$callback();}catch(\InvalidArgumentException $e){return;}throw new \RuntimeException('Unsafe settings accepted');}
 global $caps;$caps=[Access::FINANCE=>true];check(Access::can('finance'),'Finance role denied');check(!Access::can('print'),'Finance role can print');check(!Access::can('settings'),'Finance role can configure');check(!Access::can('finance',12),'Unauthorized order passed');$caps['edit_shop_order']=true;check(Access::can('finance',12),'Authorized finance order denied');check(!Access::can('arbitrary_admin_cap'),'Unknown capability accepted');$caps=['manage_woocommerce'=>true];check(Access::can('packing'),'Admin cannot pack');
 rejected(fn()=>Management::sanitizeTransfer(['schema'=>1,'options'=>['admin_email'=>'evil']]));rejected(fn()=>Management::sanitizeTransfer(['schema'=>2,'options'=>[]]));rejected(fn()=>Management::sanitizeTransfer(['schema'=>1,'options'=>['hm_mahex_v31_invoice_brand'=>['bad']]]));check(Management::sanitizeTransfer(['schema'=>1,'options'=>['hm_mahex_v31_invoice_brand'=>'<script>bad</script>Brand']])['hm_mahex_v31_invoice_brand']==='badBrand','Brand HTML retained');
 $a=[['id'=>'a','amount'=>10],['id'=>'b','amount'=>20]];$b=[['id'=>'a','amount'=>15],['id'=>'c','amount'=>30]];$diff=RuleVersions::difference($a,$b);check(count($diff)===3,'Version diff missing edits');check($diff['b']['after']===null,'Removed rule not detected');check($diff['c']['before']===null,'New rule not detected');
 class Ship {function get_method_id(){return 'hm_mahex';}function get_meta($key,$single=true){return ['hm_mahex_freight'=>100,'hm_mahex_packaging'=>20,'hm_mahex_insurance'=>0][$key]??'';}function get_total(){return 120;}}
 class Line {function get_total(){return 100;}function get_product_id(){return 5;}function get_name(){return 'Product';}}
 class Order {function get_items($type='line_item'){return $type==='shipping'?[new Ship()]:[new Line()];}function get_total_refunded(){return 0;}function get_currency(){return 'IRT';}function get_meta($key,$single=true){return ['_hm_mahex_actual_carrier_cost'=>50,'_hm_mahex_actual_packaging_cost'=>10,'_hm_mahex_actual_insurance_cost'=>0,'_hm_mahex_actual_operational_cost'=>0,'_hm_mahex_branch_id'=>2][$key]??'';}function get_shipping_state(){return 'QHM';}function get_shipping_city(){return 'Qom';}}
 $groups=Management::groupProfit([new Order(),new Order()],'city');check(count($groups)===1&&$groups[0]['profit']===120.0,'City profit double-counted packaging');check($groups[0]['currency']==='IRT','Currency group lost');$groups=Management::groupProfit([new Order()],'product');check($groups[0]['profit']===60.0,'Product shipping share wrong');$groups=Management::groupProfit([new Order()],'branch');check($groups[0]['group']==='شعبه 2','Branch incorrect');echo "Management/access/version tests passed\n";
}
