<?php
namespace HoseinMomeni\MahexWoo\V32 {final class Packing {static function snapshot($o){return $o->plan;}static function units($o){return $o->units;}static function fingerprint($u){return hash('sha256',json_encode($u));}}}
namespace HoseinMomeni\MahexWoo\V33 {final class Station {static function data($o){return ['parcels'=>$o->parcels];}} final class BoardTools {public static array $blocked=[];static function guardOtherEditor($id){if(in_array($id,self::$blocked,true))throw new \RuntimeException('leased');}}}
namespace HoseinMomeni\MahexWoo\V34 {final class DispatchWorkbench {static function address($o){return $o->address;}static function assertReady($o){if($o->hold)throw new \RuntimeException('hold');}}}
namespace {
define('ABSPATH',__DIR__);$options=[];$orders=[];$denied=[];$failOption=false;$actor=7;
function add_option($k,$v,...$a){global $options;if(isset($options[$k]))return false;$options[$k]=$v;return true;}
function get_option($k,$default=0){global $options;return $options[$k]??$default;}
function delete_option($k){global $options;unset($options[$k]);}
function update_option($k,$v,...$a){global $options,$failOption;if($failOption)return false;$options[$k]=$v;return true;}
function current_user_can($cap,...$args){global $denied;return $cap==='edit_shop_order'?!in_array($args[0],$denied,true):$cap==='manage_woocommerce';}
function get_current_user_id(){global $actor;return $actor;}
function wp_timezone(){return new \DateTimeZone('Asia/Tehran');}
function wp_json_encode($v,...$args){return json_encode($v,...$args);}
function wc_get_order($id){global $orders;return isset($orders[$id])?clone $orders[$id]:false;}
class HandoverOrder {public array $meta=[],$plan=['boxes'=>[['profile_id'=>'a','units'=>['u1']]]],$units=['u1'=>['product_id'=>1]],$parcels=[['weight_g'=>600,'dimensions_mm'=>[300,200,100]]],$address=['phone'=>'09123456789','city'=>'قم'];public bool $hold=false;public int $saves=0;function __construct(public int $id){}function get_id(){return $this->id;}function get_order_number(){return 'MH-'.$this->id;}function get_meta($k,$single=true){return $this->meta[$k]??'';}function update_meta_data($k,$v){$this->meta[$k]=$v;}function delete_meta_data($k){unset($this->meta[$k]);}function read_meta_data($fresh){}function save(){global $orders;$this->saves++;$orders[$this->id]=clone $this;return $this->id;}}
require __DIR__.'/../src/V33/Access.php';require __DIR__.'/../src/Shipments/OptionOperationLock.php';require __DIR__.'/../src/V35/LocalHandover.php';
use HoseinMomeni\MahexWoo\V35\LocalHandover as H;
function check($ok,$label){if(!$ok)throw new \RuntimeException('FAIL: '.$label);}
function rejects($fn,$label){try{$fn();}catch(\Throwable $e){return;}throw new \RuntimeException('FAIL accepted: '.$label);}
$orders=[10=>new HandoverOrder(10),11=>new HandoverOrder(11),12=>new HandoverOrder(12),13=>new HandoverOrder(13)];
$p=['order_id'=>10,'title'=>'گروه صبح','origin'=>'قم مدرس','destination'=>'مرکز انتقال','route'=>'driver','vehicle'=>'QOM-659315','start'=>'2026-10-07T10:00','end'=>'2026-10-07T14:00','capacity'=>3];
rejects(fn()=>H::create(array_merge($p,['start'=>'2026-02-30T10:00'])),'invalid date');rejects(fn()=>H::create(array_merge($p,['end'=>'2026-10-07T09:00'])),'reverse window');rejects(fn()=>H::create(array_merge($p,['capacity'=>'2.5'])),'fraction capacity');rejects(fn()=>H::create(array_merge($p,['route'=>'carrier-api'])),'invalid route');rejects(fn()=>H::create(array_merge($p,['title'=>'x'])),'short title');
$g=H::create($p);$id=$g['id'];check($g['revision']===1&&$g['state']==='draft'&&count($g['members'])===1,'created draft');check($g['totals']['weight_g']===600.0&&$g['totals']['parcels']===1,'real cargo totals');check($g['details']['vehicle']==='QOM-659315'&&$g['details']['route']==='driver','route/vehicle');check(str_contains($g['details']['start'],'+03:30'),'timezone persisted');check(H::meta($orders[10])['refs'][$id]['member'],'CRUD reference');rejects(fn()=>H::create($p),'exclusive active membership');rejects(fn()=>H::mutate($id,0,'seal',['seal'=>'SEAL-A']),'revision conflict');
$g=H::mutate($id,$g['revision'],'add',['order_id'=>11]);check($g['totals']['parcels']===2&&$g['totals']['weight_g']===1200.0,'aggregate membership');rejects(fn()=>H::mutate($id,$g['revision'],'add',['order_id'=>11]),'duplicate member');$g=H::mutate($id,$g['revision'],'reorder',['order'=>[11,10]]);check($g['order']===[11,10],'persisted ordering');rejects(fn()=>H::mutate($id,$g['revision'],'reorder',['order'=>[10,10]]),'duplicate reorder');rejects(fn()=>H::mutate($id,$g['revision'],'remove',['order_id'=>11]),'removal reason');
$orders[11]->address['city']='تهران';check(H::get($id)['rows'][0]['changed'],'address drift');rejects(fn()=>H::mutate($id,$g['revision'],'seal',['seal'=>'SEAL-A']),'drift prevents seal');rejects(fn()=>H::mutate($id,$g['revision'],'refresh',['order_id'=>11]),'refresh requires reason');$g=H::mutate($id,$g['revision'],'refresh',['order_id'=>11,'note'=>'نشانی بازبینی شد']);check(!$g['rows'][0]['changed'],'refresh captures new shipment');$orders[11]->hold=true;rejects(fn()=>H::mutate($id,$g['revision'],'seal',['seal'=>'SEAL-A']),'hold prevents seal');$orders[11]->hold=false;$orders[11]->parcels[0]['dimensions_mm']=[0,200,100];check(!H::shipment($orders[11])['measured'],'zero dimension incomplete');rejects(fn()=>H::mutate($id,$g['revision'],'seal',['seal'=>'SEAL-A']),'invalid measurements');$orders[11]->parcels[0]['dimensions_mm']=[300,200,100];
$g=H::mutate($id,$g['revision'],'seal',['seal'=>'SEAL-A']);check($g['state']==='sealed'&&$g['sealed_digest']===$g['digest']&&$g['sealed_revision']===$g['revision'],'frozen sealed digest');rejects(fn()=>H::mutate($id,$g['revision'],'add',['order_id'=>12]),'sealed membership immutable');rejects(fn()=>H::mutate($id,$g['revision'],'unseal',[]),'unseal reason');$g=H::mutate($id,$g['revision'],'unseal',['note'=>'بازبینی دفتر']);check($g['state']==='draft'&&$g['details']['seal']===''&&end($g['details']['history'])['detail']['previous_seal']==='SEAL-A','seal history retained');$g=H::mutate($id,$g['revision'],'seal',['seal'=>'SEAL-B']);rejects(fn()=>H::mutate($id,$g['revision'],'dispatch',['receiver'=>'راننده محلی']),'dispatch reference');$orders[10]->parcels[0]['weight_g']=601;rejects(fn()=>H::mutate($id,$g['revision'],'dispatch',['receiver'=>'راننده محلی','reference'=>'REF-01']),'post seal drift');$orders[10]->parcels[0]['weight_g']=600;$g=H::mutate($id,$g['revision'],'dispatch',['receiver'=>'راننده محلی','reference'=>'REF-01']);check($g['state']==='dispatched'&&$g['details']['custodian']==='راننده محلی','manual dispatch');rejects(fn()=>H::mutate($id,$g['revision'],'cancel',['note'=>'لغو دستی']),'cannot cancel departed');rejects(fn()=>H::mutate($id,$g['revision'],'transfer',['receiver'=>'راننده محلی','place'=>'مرکز قم','note'=>'انتقال داخلی']),'same custodian');rejects(fn()=>H::mutate($id,$g['revision'],'transfer',['receiver'=>'اپراتور جدید','place'=>'مرکز قم']),'transfer note');$g=H::mutate($id,$g['revision'],'transfer',['receiver'=>'اپراتور جدید','place'=>'مرکز قم','note'=>'انتقال داخلی']);$e=end($g['details']['history']);check($e['detail']['from']==='راننده محلی'&&$e['detail']['to']==='اپراتور جدید'&&$e['actor']===7,'custody chain');rejects(fn()=>H::mutate($id,$g['revision'],'close',[]),'must review all');
$r=['order_id'=>10,'accepted'=>1,'condition'=>'intact','receiver'=>'پذیرنده مرکز','reference'=>'REC-01'];$g=H::mutate($id,$g['revision'],'receive',$r);check($g['totals']['reviewed_orders']===1&&$g['totals']['received_parcels']===1,'partial receiving');rejects(fn()=>H::mutate($id,$g['revision'],'receive',$r),'correction reason');$g=H::mutate($id,$g['revision'],'receive',array_merge($r,['reference'=>'REC-02','correction_reason'=>'اصلاح مرجع رسید']));check(end($g['details']['history'])['detail']['previous']['reference']==='REC-01','receipt correction history');rejects(fn()=>H::mutate($id,$g['revision'],'receive',array_merge($r,['order_id'=>11,'accepted'=>0,'condition'=>'short'])),'mismatch note');rejects(fn()=>H::mutate($id,$g['revision'],'receive',array_merge($r,['order_id'=>11,'accepted'=>1,'condition'=>'refused','note'=>'دریافت نشد'])),'refused cannot accept');$g=H::mutate($id,$g['revision'],'receive',array_merge($r,['order_id'=>11,'accepted'=>0,'condition'=>'refused','note'=>'بسته پذیرش نشد','receiver'=>'پذیرنده خصوصی سفارش دوم']));check($g['totals']['reviewed_orders']===2&&$g['totals']['received_parcels']===1&&$g['totals']['exceptions']===1,'rejected separate from received');rejects(fn()=>H::mutate($id,$g['revision'],'close',[]),'exceptions need summary');$g=H::mutate($id,$g['revision'],'close',['note'=>'مغایرت برای بررسی داخلی ثبت شد']);check($g['state']==='closed','closure');rejects(fn()=>H::mutate($id,$g['revision'],'transfer',[]),'closed immutable');check(!H::active(H::catalog(),10),'closed frees membership');
$central=json_encode(H::catalog(),JSON_UNESCAPED_UNICODE);check(!str_contains($central,'پذیرنده')&&!str_contains($central,'09123456789')&&!str_contains($central,'راننده')&&!str_contains($central,'QOM-659315'),'central has no personal text');$export=H::export($id);check($export['schema']==='mahex-local-handover/1'&&!$export['carrier_delivery_verified'],'export explicit local schema');check(!str_contains(json_encode($export),'total_irr')&&!str_contains(json_encode($export),'materials_irr'),'no financial output');$denied=[11];rejects(fn()=>H::get($id),'all member access rechecked');check(count(H::listing())===0,'unauthorized group absent');$denied=[];
$g2=H::create(array_merge($p,['order_id'=>12,'capacity'=>1]));rejects(fn()=>H::mutate($g2['id'],$g2['revision'],'add',['order_id'=>13]),'capacity exceeded');$options['hm_mahex_shipment_lock_12']=time()+60;rejects(fn()=>H::mutate($g2['id'],$g2['revision'],'seal',['seal'=>'SEAL-C']),'common order lock');unset($options['hm_mahex_shipment_lock_12']);\HoseinMomeni\MahexWoo\V33\BoardTools::$blocked=[12];rejects(fn()=>H::mutate($g2['id'],$g2['revision'],'seal',['seal'=>'SEAL-C']),'foreign lease');\HoseinMomeni\MahexWoo\V33\BoardTools::$blocked=[];
$before=$orders[12]->meta;$failOption=true;rejects(fn()=>H::mutate($g2['id'],$g2['revision'],'seal',['seal'=>'SEAL-C']),'catalog persistence failure');$failOption=false;check($orders[12]->meta===$before&&H::get($g2['id'])['state']==='draft','metadata rollback');$g2=H::mutate($g2['id'],$g2['revision'],'remove',['order_id'=>12,'note'=>'بررسی مجدد']);rejects(fn()=>H::mutate($g2['id'],$g2['revision'],'seal',['seal'=>'SEAL-C']),'empty seal');$g2=H::mutate($g2['id'],$g2['revision'],'cancel',['note'=>'توقف این دفتر']);check($g2['state']==='cancelled','cancellation');
$privateA=H::privacy($orders[10]);$privateB=H::privacy($orders[11]);check($privateA['groups'][$id]['receipt']['reference']==='REC-02'&&$privateB['groups'][$id]['receipt']['reference']==='REC-01','privacy receipt scoped to order');foreach($privateA['groups'][$id]['history'] as $event)check($event['detail']['order_id']===10,'privacy history scoped to order');check(!str_contains(json_encode($privateA,JSON_UNESCAPED_UNICODE),'پذیرنده خصوصی سفارش دوم'),'anchor privacy export excludes other recipient');check(!isset($privateA['groups'][$id]['members'])&&!isset($privateA['groups'][$id]['receipts']),'privacy omits other members and aggregate receipts');
check(H::eraseOrder(11)===1&&H::get($id)['redacted'],'non anchor privacy redacts all journal');check(!str_contains(json_encode(H::meta($orders[10]),JSON_UNESCAPED_UNICODE),'پذیرنده مرکز'),'no receipt residual in anchor');$g3=H::create(array_merge($p,['order_id'=>13]));H::eraseOrder(13);check(!H::active(H::catalog(),13),'redacted membership freed');rejects(fn()=>H::mutate($g3['id'],$g3['revision'],'seal',['seal'=>'SEAL-D']),'redacted group immutable');
$orders[14]=new HandoverOrder(14);$refs=[];$journals=[];for($n=0;$n<50;$n++){$refs['archive-'.$n]=['code'=>'MH35-ARCHIVE-'.$n,'state'=>'closed','revision'=>1,'member'=>true];$journals['archive-'.$n]=['history'=>[['intent'=>'archive','detail'=>['note'=>'preserve evidence']]]];}$orders[14]->meta[H::META]=['refs'=>$refs,'groups'=>$journals];$oldArchive=$orders[14]->meta;rejects(fn()=>H::create(array_merge($p,['order_id'=>14])),'association limit preserves archive');check($orders[14]->meta===$oldArchive,'no archived journal silently pruned');
$h=['history'=>array_fill(0,200,[])];rejects(function()use(&$h){H::event($h,'transfer');},'history bounded without deleting evidence');
echo "V35 local handover lifecycle, custody, privacy, access, cargo and persistence regressions passed.\n";
}
