<?php
namespace HoseinMomeni\MahexWoo\V34 {final class DispatchWorkbench {static function data($o){return ['hold'=>$o->hold,'priority'=>$o->priority];}}}
namespace HoseinMomeni\MahexWoo\V35 {final class OrderQuality {static function scan($o,$finance=false){return ['findings'=>$o->critical?[['severity'=>'critical','state'=>'open']]:[]];}} final class LocalHandover {static array $active=[];static function shipment($o){return ['fingerprint'=>hash('sha256',json_encode([$o->weight,$o->parcels,$o->city])),'parcels'=>$o->parcels,'weight_g'=>$o->weight,'measured'=>$o->measured];}static function catalog(){return [];}static function active($all,$id,$except=''){return in_array($id,self::$active,true);}}}
namespace HoseinMomeni\MahexWoo\V33 {final class BoardTools {public static array $blocked=[];static function guardOtherEditor($id){if(in_array($id,self::$blocked,true))throw new \RuntimeException('leased');}}}
namespace {
define('ABSPATH',__DIR__);$options=[];$orders=[];$denied=[];$failOption=false;
function add_option($k,$v,...$x){global $options;if(isset($options[$k]))return false;$options[$k]=$v;return true;}function get_option($k,$d=0){global $options;return $options[$k]??$d;}function delete_option($k){global $options;unset($options[$k]);}function update_option($k,$v,...$x){global $options,$failOption;if($failOption)return false;$options[$k]=$v;return true;}function current_user_can($cap,...$args){global $denied;return $cap==='edit_shop_order'?!in_array($args[0],$denied,true):$cap==='manage_woocommerce';}function get_current_user_id(){return 9;}function wp_timezone(){return new \DateTimeZone('Asia/Tehran');}function wp_json_encode($v,...$args){return json_encode($v,...$args);}function sanitize_key($v){return preg_replace('/[^a-z0-9_-]/','',strtolower($v));}function wc_get_order($id){global $orders;return isset($orders[$id])?clone $orders[$id]:false;}function wc_get_orders($args){global $orders;return array_values(array_map(fn($o)=>clone $o,$orders));}
class WaveDate {function __construct(private int $t){}function getTimestamp(){return $this->t;}}
class WaveItem {function __construct(private int $q=1,private string $method='mahex'){}function get_quantity(){return $this->q;}function get_method_id(){return $this->method;}}
class WaveOrder {public array $meta=[];public bool $hold=false,$critical=false,$measured=true;public string $priority='normal',$city='قم',$state='IR-25',$postcode='3712345678',$status='processing';public int $weight=600,$parcels=1,$quantity=2,$created=1000;function __construct(public int $id){}function get_id(){return $this->id;}function get_order_number(){return 'W-'.$this->id;}function get_meta($k,$s=true){return $this->meta[$k]??'';}function update_meta_data($k,$v){$this->meta[$k]=$v;}function delete_meta_data($k){unset($this->meta[$k]);}function read_meta_data($f){}function save(){global $orders;$orders[$this->id]=clone $this;return $this->id;}function get_shipping_state(){return $this->state;}function get_shipping_city(){return $this->city;}function get_shipping_postcode(){return $this->postcode;}function get_status(){return $this->status;}function get_date_created(){return new WaveDate($this->created);}function get_items($type){return $type==='shipping'?[new WaveItem(1,'mahex')]:[new WaveItem($this->quantity)];}}
require __DIR__.'/../src/V33/Access.php';require __DIR__.'/../src/Shipments/OptionOperationLock.php';require __DIR__.'/../src/V36/OfflineDispatchWaves.php';
use HoseinMomeni\MahexWoo\V36\OfflineDispatchWaves as W;use HoseinMomeni\MahexWoo\V35\LocalHandover as H;
function check($v,$m){if(!$v)throw new \RuntimeException('FAIL '.$m);}function rejects($fn,$m){try{$fn();}catch(\Throwable $e){return;}throw new \RuntimeException('FAIL accepted '.$m);}
$orders=[10=>new WaveOrder(10),11=>new WaveOrder(11),12=>new WaveOrder(12),13=>new WaveOrder(13),14=>new WaveOrder(14)];$base=['order_id'=>10,'title'=>'موج صبح قم','day'=>'2026-10-07','start'=>'2026-10-07T09:00','end'=>'2026-10-07T12:00','origin_id'=>'QOM-1','origin_label'=>'انبار قم','orders'=>3,'parcels'=>5,'weight_g'=>5000,'minutes'=>120,'threshold'=>80];
rejects(fn()=>W::create(array_merge($base,['day'=>'2026-02-30'])),'invalid day');rejects(fn()=>W::create(array_merge($base,['end'=>'2026-10-07T08:00'])),'reverse window');rejects(fn()=>W::create(array_merge($base,['threshold'=>69])),'threshold');$orders[12]->hold=true;rejects(fn()=>W::create(array_merge($base,['order_id'=>12])),'hold');$orders[12]->hold=false;$orders[13]->critical=true;rejects(fn()=>W::create(array_merge($base,['order_id'=>13])),'quality');$orders[13]->critical=false;H::$active=[14];rejects(fn()=>W::create(array_merge($base,['order_id'=>14])),'handover');H::$active=[];
$g=W::create($base);$id=$g['id'];check($g['state']==='draft'&&$g['revision']===1,'create');check(str_starts_with($g['code'],'MW36-'),'code');check($g['totals']['orders']===1&&$g['totals']['weight_g']===600.0,'real totals');check($g['details']['day']==='2026-10-07T00:00:00+03:30','timezone day');check(W::meta($orders[10])['refs'][$id]['member'],'order ref');rejects(fn()=>W::create($base),'exclusive');rejects(fn()=>W::mutate($id,0,'add',['order_id'=>11]),'revision');
$g=W::mutate($id,$g['revision'],'add',['order_id'=>11]);check($g['totals']['orders']===2,'add');rejects(fn()=>W::mutate($id,$g['revision'],'add',['order_id'=>11]),'duplicate');$g=W::mutate($id,$g['revision'],'reorder',['order'=>[11,10]]);check($g['order']===[11,10],'reorder');rejects(fn()=>W::mutate($id,$g['revision'],'remove',['order_id'=>11,'note'=>'x']),'removal reason');$g=W::mutate($id,$g['revision'],'remove',['order_id'=>11,'note'=>'بازچینی موج']);check($g['totals']['orders']===1,'remove');$g=W::mutate($id,$g['revision'],'add',['order_id'=>11]);
$orders[11]->measured=false;$g=W::mutate($id,$g['revision'],'remove',['order_id'=>11,'note'=>'اندازه ناقص']);$g=W::mutate($id,$g['revision'],'add',['order_id'=>11]);rejects(fn()=>W::mutate($id,$g['revision'],'publish',[]),'unknown blocks');$g=W::mutate($id,$g['revision'],'ack_unknown',['order_id'=>11,'note'=>'وزن پیش از اجرا بازبینی دستی می‌شود']);$g=W::mutate($id,$g['revision'],'publish',[]);check($g['state']==='published'&&$g['snapshot_version']===1&&count($g['details']['snapshots'])===1,'publish snapshot');rejects(fn()=>W::mutate($id,$g['revision'],'add',['order_id'=>12]),'published immutable');
$orders[10]->city='تهران';check(isset(W::get($id)['drifts'][10]),'drift');rejects(fn()=>W::mutate($id,$g['revision'],'start',[]),'drift blocks start');$g=W::mutate($id,$g['revision'],'refresh',['note'=>'مقصد با سفارش تازه تطبیق شد']);check($g['snapshot_version']===2&&!$g['drifts'],'refresh version');$g=W::mutate($id,$g['revision'],'start',[]);check($g['state']==='in_progress','start');$g=W::mutate($id,$g['revision'],'complete',[]);check($g['state']==='completed','complete');check(!W::active(W::catalog(),10),'completed releases');
$export=W::export($id);check($export['schema']==='mahex-offline-dispatch-wave/1'&&!$export['carrier_route_verified']&&!$export['physical_execution_verified'],'honest export');check(!str_contains(json_encode(W::catalog()),'قم')&&!str_contains(json_encode(W::catalog()),'3712345678'),'central minimized');$private=W::privacy($orders[10]);check(isset($private['waves'][$id]['member'])&&!isset($private['waves'][$id]['details']),'privacy scoped');
$g2=W::create(array_merge($base,['order_id'=>12,'orders'=>1]));rejects(fn()=>W::mutate($g2['id'],$g2['revision'],'add',['order_id'=>13]),'order capacity');$options['hm_mahex_shipment_lock_12']=time()+60;rejects(fn()=>W::mutate($g2['id'],$g2['revision'],'cancel',['note'=>'لغو تست']), 'common lock');unset($options['hm_mahex_shipment_lock_12']);$before=$orders[12]->meta;$failOption=true;rejects(fn()=>W::mutate($g2['id'],$g2['revision'],'cancel',['note'=>'لغو تست']), 'option fail');$failOption=false;check($orders[12]->meta===$before&&W::get($g2['id'])['state']==='draft','rollback');$g2=W::mutate($g2['id'],$g2['revision'],'cancel',['note'=>'لغو برنامه']);check($g2['state']==='cancelled','cancel');check(W::eraseOrder(10)===1&&W::get($id)['redacted'],'privacy erase redacts journal');rejects(fn()=>W::mutate($id,$g['revision'],'note',['note'=>'x']),'final immutable');
$rows=W::candidates(['statuses'=>['processing']]);check(count($rows)>=5&&isset($rows[0]['cluster_hash']),'real CRUD candidates');echo "V36 offline dispatch waves lifecycle, capacity, drift, privacy, access and persistence regressions passed.\n";
}
