<?php
namespace HoseinMomeni\MahexWoo\V33 {final class Access {public static function can(string $area,int $orderId=0): bool {return !in_array($orderId,$GLOBALS['denied']??[],true);}}}
namespace {
$options=[];$orders=[];$actor=7;$denied=[];$manager=true;
function get_option($k,$d=[]){return $GLOBALS['options'][$k]??$d;}function update_option($k,$v,...$x){$GLOBALS['options'][$k]=$v;return true;}function current_user_can($cap,...$args){return $cap==='manage_woocommerce'?$GLOBALS['manager']:!in_array((int)($args[0]??0),$GLOBALS['denied'],true);}function get_current_user_id(){return $GLOBALS['actor'];}function wc_get_order($id){return $GLOBALS['orders'][$id]??false;}function wc_get_orders($args){return array_keys($GLOBALS['orders']);}function wc_get_order_statuses(){return ['wc-processing'=>'در حال انجام','wc-completed'=>'تکمیل'];}function wp_json_encode($v,...$x){return json_encode($v,...$x);}
final class D {function __construct(private int $t){}function getTimestamp(){return $this->t;}}
final class Product {function __construct(private bool $v=false){}function is_virtual(){return $this->v;}}
final class Item {function __construct(private int $id,private bool $virtual=false){}function get_method_id(){return 'flat_rate';}function get_product(){return new Product($this->virtual);}function get_product_id(){return $this->id;}function get_quantity(){return 1;}}
final class Order {public array $meta=[];function __construct(public int $id,public string $status='processing',public int $created=1700000000,public bool $virtual=false){}function get_id(){return $this->id;}function get_version(){return '9.9';}function get_status(){return $this->status;}function get_date_created(){return new D($this->created);}function get_items($type='line_item'){return $type==='shipping'?[new Item(0)]:[new Item($this->id,$this->virtual)];}function get_total(){return 100;}function get_total_refunded(){return 0;}function get_meta($k,$one=true){return $this->meta[$k]??'';}}
require __DIR__.'/../src/V36/QualitySampling.php';use HoseinMomeni\MahexWoo\V36\QualitySampling as Q;
function ok($v,$m){if(!$v)throw new \RuntimeException('FAIL '.$m);}function reject($f,$m){try{$f();}catch(\Throwable $e){return;}throw new \RuntimeException('ACCEPTED '.$m);}
$base=['from'=>'2023-01-01T00:00:00Z','to'=>'2025-01-01T00:00:00Z','statuses'=>['processing'],'methods'=>['flat_rate'],'mode'=>'fixed','value'=>3,'seed'=>'seed-one','sample_cap'=>10,'population_limit'=>50,'overlap'=>'deny','minimum_station_sample'=>2,'target_rate'=>5,'name'=>'کنترل کیفیت صبح','purpose'=>'نمونه‌برداری دستی بسته‌های واقعی'];
$orders=[1=>new Order(1),2=>new Order(2),3=>new Order(3),4=>new Order(4),5=>new Order(5)];$orders[2]->meta['_hm_mahex_station_id']='station-a';$orders[2]->meta['_hm_mahex_material_usage']=['box'=>1];
$snaps=[];foreach($orders as $o)$snaps[$o->id]=Q::orderSnapshot($o);ok(count(Q::select($snaps,'fixed',2,'same'))===2,'fixed selection');ok(Q::select($snaps,'fixed',3,'same')===Q::select($snaps,'fixed',3,'same'),'deterministic seed');ok(count(Q::select($snaps,'percent',40,'same'))===2,'percent');ok(count(Q::select($snaps,'interval',2,'same'))===3,'interval');$risk=$snaps;$risk[5]['risk']=99;ok(Q::select($risk,'risk',1,'same')[0]['order_id']===5,'risk local');reject(fn()=>Q::select($snaps,'api',1,'x'),'external mode');
$virtual=Q::orderSnapshot(new Order(9,'processing',1700000000,true));ok(Q::eligible($virtual,Q::baseSettings($base))[1]==='virtual','virtual exclusion');$inactive=$snaps[1];$inactive['status']='cancelled';ok(Q::eligible($inactive,Q::baseSettings($base))[1]==='inactive','cancel exclusion');
$c=Q::create($base,$snaps);ok(strlen($c['id'])===24&&str_starts_with($c['code'],'MHQA-'),'opaque campaign id');ok($c['state']==='draft'&&count($c['members'])===3,'draft sampled');ok(count($c['template'])===5&&count($c['defects'])===4,'versioned template and taxonomy');ok($c['population_count']===5&&strlen($c['population_fingerprint'])===64,'population fingerprint');reject(fn()=>Q::mutate($c['id'],0,'activate'),'revision conflict');
$manual=array_values(array_diff(array_keys($snaps),array_keys($c['members'])))[0];reject(fn()=>Q::mutate($c['id'],$c['revision'],'add',['order_id'=>$manual,'reason'=>'']),'manual reason');$c=Q::mutate($c['id'],$c['revision'],'add',['order_id'=>$manual,'reason'=>'ریسک مشاهده‌شده داخلی']);ok($c['members'][$manual]['source']==='manual','manual inclusion');$c=Q::mutate($c['id'],$c['revision'],'remove',['order_id'=>$manual,'reason'=>'نمونه جایگزین شد']);ok(!isset($c['members'][$manual]),'reasoned removal');
$c=Q::mutate($c['id'],$c['revision'],'defects',['defects'=>array_merge(Q::DEFAULT_DEFECTS,['sharp_edge'=>['title'=>'لبه تیز بسته','severity'=>'critical','active'=>true]])]);ok(isset($c['defects']['sharp_edge'])&&$c['template_version']===2,'custom normalized defect');reject(fn()=>Q::mutate($c['id'],$c['revision'],'defects',['defects'=>['BAD CODE'=>['title'=>'خرابی بسته','severity'=>'warning','active'=>true]]]),'bad defect code');
$c=Q::mutate($c['id'],$c['revision'],'activate');ok($c['state']==='active'&&isset($c['locked_template']),'locked snapshot');reject(fn()=>Q::mutate($c['id'],$c['revision'],'add',['order_id'=>5,'reason'=>'پس از قفل']),'membership immutable');$oid=array_key_first($c['members']);$mr=$c['members'][$oid]['revision'];$pass=[];foreach($c['template'] as $criterion){$pass[$criterion['code']]='pass';$pass[$criterion['code'].'_note']='';}
reject(fn()=>Q::inspect($c['id'],$c['revision'],$oid,$mr,$pass,[],'pass','بازرسی دستی انجام شد',false),'human acknowledgement');$bad=$pass;$bad['identity']='fail';$bad['identity_note']='';reject(fn()=>Q::inspect($c['id'],$c['revision'],$oid,$mr,$bad,['wrong_item'],'quarantine','مغایرت محتوا',true),'failure note');$bad['identity_note']='قلم روی برگه با بسته متفاوت بود';reject(fn()=>Q::inspect($c['id'],$c['revision'],$oid,$mr,$bad,['wrong_item'],'pass','مغایرت محتوا',true),'critical cannot pass');$c=Q::inspect($c['id'],$c['revision'],$oid,$mr,$bad,['wrong_item'],'quarantine','مشاهده دستی مغایرت محتوا',true,true);ok(Q::memberQuarantined($c['members'][$oid])&&$c['members'][$oid]['lane']==='review','quarantine');ok($c['members'][$oid]['inspections'][0]['blind'],'blind inspection');ok(Q::hasOpenQuarantine($oid),'global quarantine');reject(fn()=>Q::assertNoQuarantine($oid),'handover guard');reject(fn()=>Q::move($c['id'],$c['revision'],$oid,$c['members'][$oid]['revision'],'released'),'quarantine board guard');
$actor=7;reject(fn()=>Q::secondReview($c['id'],$c['revision'],$oid,true,'تأیید اصلاح'),'distinct reviewer');$actor=8;$c=Q::secondReview($c['id'],$c['revision'],$oid,true,'اصلاح بسته مشاهده و تأیید شد');ok(!Q::memberQuarantined($c['members'][$oid])&&$c['members'][$oid]['lane']==='released','second review release');ok(!Q::hasOpenQuarantine($oid),'quarantine cleared');
$oid2=array_values(array_diff(array_keys($c['members']),[$oid]))[0];$c=Q::move($c['id'],$c['revision'],$oid2,$c['members'][$oid2]['revision'],'inspecting');ok($c['members'][$oid2]['lane']==='inspecting','board transition');reject(fn()=>Q::move($c['id'],$c['revision'],$oid2,$c['members'][$oid2]['revision'],'released'),'inspection required');$c=Q::inspect($c['id'],$c['revision'],$oid2,$c['members'][$oid2]['revision'],$pass,[],'pass','بسته به صورت دستی سالم مشاهده شد',true);ok($c['members'][$oid2]['lane']==='released','pass release');
$summary=Q::summary($c);ok($summary['inspected']===2&&$summary['quarantined']===0&&isset($summary['pareto'][0]),'summary and pareto');$csv=Q::csv($c);ok(str_contains($csv,'order_id')&&!str_contains($csv,'phone')&&!str_contains($csv,'address'),'low data csv');$private=Q::privacyForUser(7);ok($private&&$private[0]['inspections'],'privacy actor export');ok(Q::eraseUser(7)>0,'privacy actor erase');ok(!str_contains(json_encode(Q::catalog()),'"actor":7'),'actor anonymized');
$orders[$oid2]->status='completed';ok(Q::drift($c)[$oid2]==='changed','live drift warning');$analysis=Q::analytics([]);ok($analysis['causality_claimed']===false,'no causality claim');reject(fn()=>Q::mutate($c['id'],$c['revision'],'close'),'cannot close unfinished');
ok(substr_count(file_get_contents(__DIR__.'/../assets/admin/v36-sampling.js'),'drag')>=3,'drag implementation');ok(str_contains(file_get_contents(__DIR__.'/../assets/admin/v36-sampling.js'),'data-hqs-move'),'keyboard/select alternative');ok(str_contains(file_get_contents(__DIR__.'/../assets/admin/v36-sampling.css'),'@media(max-width:520px)'),'responsive RTL UI');
echo "V36 quality sampling: deterministic campaigns, manual inspection, quarantine, second review, board, analytics, privacy and export passed\n";
}
