<?php
namespace HoseinMomeni\MahexWoo\V33 {final class Access {public static function can(string $area,int $id=0): bool {return $GLOBALS['access']??true;}public static function cap(string $area): string{return 'manage_woocommerce';}}}
namespace {
$options=[];$actor=7;$access=true;$manager=true;$failReceiptWrite=false;
function get_option($k,$d=[]){return $GLOBALS['options'][$k]??$d;}
function update_option($k,$v,...$x){if($k==='hm_mahex_v37_supply_receipts'&&$GLOBALS['failReceiptWrite']){$GLOBALS['failReceiptWrite']=false;return false;}$GLOBALS['options'][$k]=$v;return true;}
function current_user_can($cap,...$args){return $cap==='manage_woocommerce'?$GLOBALS['manager']:true;}
function get_current_user_id(){return $GLOBALS['actor'];}
function wp_json_encode($v,...$x){return json_encode($v,...$x);}
require __DIR__.'/../src/V37/SupplyReceiving.php';
use HoseinMomeni\MahexWoo\V37\SupplyReceiving as R;
function ok($v,$m){if(!$v)throw new \RuntimeException('FAIL '.$m);}
function reject($f,$m){try{$f();}catch(\Throwable $e){return;}throw new \RuntimeException('ACCEPTED '.$m);}
$options[R::PURCHASES]=['po-old'=>['id'=>'po-old','status'=>'draft','supplier'=>'  کارتن قم  ','created_at'=>'2026-10-07T00:00:00Z','actor'=>4,'lines'=>['box'=>['name'=>'کارتن','qty'=>10,'unit_cost_irr'=>5000],'tape'=>['name'=>'چسب','qty'=>2.5,'unit_cost_irr'=>1000]]]];
$options[R::STOCK]=['box'=>['name'=>'کارتن','stock'=>5],'tape'=>['name'=>'چسب','stock'=>1]];
$p=R::purchases(true)['po-old'];ok($p['revision']===1&&$p['receiving_version']===37&&$p['lines']['box']['precision']===0,'legacy migration');ok($p['supplier']==='کارتن قم','supplier normalize');
$r=R::create('po-old',1,'request-one',['box']);ok(strlen($r['id'])===24&&$r['state']==='awaiting_count','opaque staged receipt');ok(R::create('po-old',1,'request-one',['box'])['id']===$r['id'],'idempotent create token');reject(fn()=>R::create('po-old',0,'other-token',['box']),'purchase revision conflict');
reject(fn()=>R::countLine($r['id'],$r['revision'],'box',$r['lines']['box']['revision'],['human'=>false,'counted'=>4,'damaged'=>0,'lot'=>'L-1','no_expiry'=>true]),'human count required');
reject(fn()=>R::countLine($r['id'],$r['revision'],'box',$r['lines']['box']['revision'],['human'=>true,'counted'=>4,'damaged'=>5,'lot'=>'L-1','no_expiry'=>true,'observation'=>'آسیب']), 'damage cap');
$r=R::countLine($r['id'],$r['revision'],'box',$r['lines']['box']['revision'],['human'=>true,'counted'=>4,'damaged'=>1,'lot'=>'L-1','no_expiry'=>true,'observation'=>'یک کارتن له شده','defects'=>['crushed']]);ok($r['state']==='inspecting'&&$r['lines']['box']['counts'][0]['healthy']===3.0,'manual count and damage');
reject(fn()=>R::decide($r['id'],$r['revision'],'box',$r['lines']['box']['revision'],['accepted'=>4,'quarantined'=>0,'rejected'=>0,'reason'=>'']), 'damaged unit disposition');
$r=R::decide($r['id'],$r['revision'],'box',$r['lines']['box']['revision'],['accepted'=>3,'quarantined'=>1,'rejected'=>0,'reason'=>'بررسی دوباره بخش آسیب‌دیده']);ok($r['state']==='quarantined','split and quarantine');reject(fn()=>R::post($r['id'],$r['revision']),'open quarantine blocks stock');
reject(fn()=>R::release($r['id'],$r['revision'],'box',false,'رد ماده'),'distinct reviewer');$actor=8;$r=R::release($r['id'],$r['revision'],'box',false,'کارتن آسیب‌دیده رد شد');ok($r['state']==='accepted'&&$r['lines']['box']['rejected']===1.0,'second reviewer release reject');
$before=$options[R::STOCK]['box']['stock'];$failReceiptWrite=true;reject(fn()=>R::post($r['id'],$r['revision']),'receipt write failure after atomic stock marker');ok((float)$options[R::STOCK]['box']['stock']==(float)$before+3&&isset($options[R::STOCK]['__v37_receipts'][$r['id']]),'stock journal committed once');
$r=R::post($r['id'],$r['revision']);ok($r['posted']&&(float)$options[R::STOCK]['box']['stock']==(float)$before+3,'retry repairs without duplicate stock');$same=R::post($r['id'],$r['revision']);ok((float)$options[R::STOCK]['box']['stock']==(float)$before+3,'repeat post exactly once');ok(R::lotsForUse('box')[0]['lot']==='L-1','lot ledger FEFO');
$summary=R::purchaseSummary('po-old');ok($summary['box']['accepted']===3.0&&$summary['box']['rejected']===1.0&&$summary['box']['remaining']===6.0,'partial remainder');
$r2=R::create('po-old',$options[R::PURCHASES]['po-old']['revision'],'request-two',['box']);reject(fn()=>R::countLine($r2['id'],$r2['revision'],'box',$r2['lines']['box']['revision'],['human'=>true,'counted'=>7,'damaged'=>0,'lot'=>'L-2','no_expiry'=>true,'over_reason'=>'اضافه']), 'over tolerance');
$r2=R::countLine($r2['id'],$r2['revision'],'box',$r2['lines']['box']['revision'],['human'=>true,'counted'=>6,'damaged'=>0,'lot'=>'L-2','expiry'=>'2027-12-31','no_expiry'=>false]);$r2=R::decide($r2['id'],$r2['revision'],'box',$r2['lines']['box']['revision'],['accepted'=>6,'quarantined'=>0,'rejected'=>0]);$r2=R::post($r2['id'],$r2['revision']);ok($options[R::PURCHASES]['po-old']['status']==='partially_received'&&(float)R::purchaseSummary('po-old')['box']['remaining']==0.0,'multi-stage material complete with purchase remainder');
$orders=$options[R::PURCHASES];$orders['po-critical']=['id'=>'po-critical','status'=>'draft','revision'=>1,'supplier'=>'نمونه','created_at'=>'2026-10-07T00:00:00Z','lines'=>['tape'=>['name'=>'چسب','qty'=>2.5,'unit_cost_irr'=>1,'precision'=>1]],'_v37'=>true,'receiving_version'=>37];$options[R::PURCHASES]=$orders;$r3=R::create('po-critical',1,'request-three',['tape']);$r3=R::countLine($r3['id'],$r3['revision'],'tape',$r3['lines']['tape']['revision'],['human'=>true,'counted'=>2.5,'damaged'=>0.5,'lot'=>'T-1','no_expiry'=>true,'observation'=>'رطوبت مشاهده شد','defects'=>['wet']]);reject(fn()=>R::decide($r3['id'],$r3['revision'],'tape',$r3['lines']['tape']['revision'],['accepted'=>2,'quarantined'=>0,'rejected'=>.5,'reason'=>'رد']), 'critical auto quarantine');
$csv=R::csv(R::receipts());ok(str_contains($csv,'receipt_id')&&!str_contains($csv,'phone')&&!str_contains($csv,'address'),'low data csv');ok(str_starts_with(R::csv([['id'=>'=evil','purchase_id'=>'p','state'=>'accepted','lines'=>[['material'=>'box','lot'=>'x','counted'=>1,'accepted'=>1,'quarantined'=>0,'rejected'=>0]]]]),"receipt_id"),'formula safe csv generated');
$privacy=R::privacyForUser(7);ok($privacy,'privacy actor export');ok(R::eraseUser(7)>0&&!str_contains(json_encode(R::receipts()),'"actor":7'),'privacy actor erase');$score=R::score(R::supplierId('کارتن قم'));ok($score['insufficient']&&$score['descriptive_only']&&!$score['causality_claimed'],'descriptive supplier score minimum sample');
ok(R::purge(730,true)['dry_run'],'retention dry run');reject(fn()=>R::move($r3['id'],$r3['revision'],'accepted'),'invalid board transition');ok(substr_count(file_get_contents(__DIR__.'/../assets/admin/v37-receiving.js'),'drag')>=3,'real drag implementation');ok(str_contains(file_get_contents(__DIR__.'/../assets/admin/v37-receiving.js'),'data-hmr-move'),'keyboard alternative');ok(str_contains(file_get_contents(__DIR__.'/../assets/admin/v37-receiving.css'),'@media(max-width:520px)'),'responsive RTL');
echo "V37 staged supply receiving: migration, partial receipts, manual QC, lot/expiry, quarantine, exactly-once stock, privacy, CSV and board passed\n";
}
