<?php
if(!defined('ABSPATH'))require getenv('MAHEX_WP_ROOT').'/wp-load.php';
add_filter('pre_wp_mail',static fn()=>true);wp_set_current_user(1);
use HoseinMomeni\MahexWoo\V33\PrintCenter;use HoseinMomeni\MahexWoo\V33\Management;use HoseinMomeni\MahexWoo\V33\RuleVersions;use HoseinMomeni\MahexWoo\V33\NotificationCenter;use HoseinMomeni\MahexWoo\V33\Access;
function checkIntegration($ok,$message){if(!$ok)throw new RuntimeException($message);}
$f=json_decode(file_get_contents(getenv('MAHEX_FIXTURES')),true);$id=$f['orders'][0];$order=wc_get_order($id);$order->read_meta_data(true);
$store=$order->get_data_store()->get_current_class_name();$expected=getenv('MAHEX_EXPECT_HPOS')==='yes'?'Automattic\\WooCommerce\\Internal\\DataStores\\Orders\\OrdersTableDataStore':'WC_Order_Data_Store_CPT';checkIntegration(is_a($store,$expected,true),'Actual HPOS/CPT datastore: '.$store);global $wpdb;$table=getenv('MAHEX_EXPECT_HPOS')==='yes'?$wpdb->prefix.'wc_orders':$wpdb->posts;checkIntegration((int)$wpdb->get_var($wpdb->prepare("SELECT id FROM $table WHERE id=%d",$id))===$id,'Order persisted in expected datastore table');
$csv=getenv('MAHEX_FIXTURES').'.csv';file_put_contents($csv,"order_id,waybill,amount,currency\n$id,,90000,IRR\n");$rows=Management::parseBills($csv);checkIntegration(!$rows[0]['errors'],'CSV real order matching');Management::applyBill($rows[0]);$fresh=wc_get_order($id);$fresh->read_meta_data(true);checkIntegration((float)$fresh->get_meta('_hm_mahex_actual_carrier_cost',true)===90000.0,'Actual cost persisted');
$pdf=PrintCenter::pdf([$fresh],['x'=>0,'y'=>0,'scale'=>100])->Output('test.pdf','S');checkIntegration(str_starts_with($pdf,'%PDF-')&&strlen($pdf)>10000,'Embedded RTL PDF font');file_put_contents(dirname(getenv('MAHEX_FIXTURES')).'/label.pdf',$pdf);
$rules=HoseinMomeni\MahexWoo\V32\Rules::normalize([['name'=>'Scheduled test','active'=>true,'mode'=>'surcharge','amount'=>1234]]);$before=get_option('hm_mahex_v1_rules',[]);$version=RuleVersions::record($rules,'Integration',time()+600);RuleVersions::activate($version);checkIntegration(get_option('hm_mahex_v1_rules',[])===$before,'No early activation');$versions=RuleVersions::all();$versions[$version]['scheduled_at']=time()-1;update_option(RuleVersions::OPTION,$versions,false);RuleVersions::activate($version);checkIntegration(get_option('hm_mahex_v1_rules')===$rules,'Due rules active');update_option('hm_mahex_v1_rules',$before,false);wp_clear_scheduled_hook(RuleVersions::HOOK,[$version]);
$job=['id'=>'e2e-email','order_id'=>$id,'channel'=>'email','to'=>'fixture@example.test','subject'=>'Fixture','message'=>'Fixture','attempts'=>0,'state'=>'pending','next_at'=>time(),'created_at'=>gmdate('c'),'error'=>''];update_option(NotificationCenter::OPTION,['email'=>true,'sms'=>false]);NotificationCenter::enqueue($job);NotificationCenter::enqueue($job);NotificationCenter::process();$queue=get_option(NotificationCenter::QUEUE);checkIntegration($queue['e2e-email']['state']==='sent'&&$queue['e2e-email']['attempts']===1,'Notification queue idempotence');update_option(NotificationCenter::OPTION,['email'=>false,'sms'=>false]);
wp_set_current_user($f['print_user']);checkIntegration(Access::can('print',$id)&&!Access::can('finance',$id)&&!Access::can('packing',$id),'Scoped role');wp_set_current_user(1);
echo 'Real MySQL/Woo CRUD, PDF, reconciliation, schedule, notification and access checks passed'.PHP_EOL;
