const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const fixtures=JSON.parse(fs.readFileSync(process.env.MAHEX_FIXTURES));const id=fixtures.orders[0];const base=process.env.MAHEX_BASE_URL||'http://127.0.0.1:8092';const browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
async function login(p,user,password){await p.goto(base+'/wp-login.php');await p.locator('#user_login').fill(user);await p.locator('#user_pass').fill(password);await Promise.all([p.waitForURL(/wp-admin/),p.locator('#wp-submit').click()]);}
await login(page,'mahex-admin','mahex-local-test-password');
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-workspace');await page.locator('#hmx32-grid [data-widget="finance"] [data-move="up"]').click();await page.locator('#hmx32-status').filter({hasText:'ذخیره شد'}).waitFor();await page.reload();const order=await page.locator('#hmx32-grid [data-widget]').evaluateAll(xs=>xs.map(x=>x.dataset.widget));assert.equal(order[2],'finance');await page.locator('#hmx32-layout-undo').click();await page.locator('#hmx32-status').filter({hasText:'برگشت'}).waitFor();
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-v32-board');const card=page.locator(`[data-id="${id}"]`);await card.locator('.hmx-board-customer').dragTo(page.locator('[data-stage="packing"]'));await page.locator('#hmx-board-message').filter({hasText:/ذخیره|ثبت/}).waitFor();await page.reload();assert.equal(await page.locator(`[data-id="${id}"] .hmx-board-stage`).inputValue(),'packing');
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-v33-station&order_id='+id);await page.locator('[data-station-lock]').click();await page.locator('[data-station-status]').filter({hasText:'در اختیار شماست'}).waitFor();for(let n=0;n<2;n++){await page.locator('[data-station-code]').fill('MHX-E2E-1');await page.locator('[data-station-scan]').click();await page.locator('[data-station-count]').filter({hasText:`${n+1} / 2`}).waitFor();}await page.locator('[data-station-code]').fill('MHX-E2E-1');await page.locator('[data-station-scan]').click();await page.locator('[data-station-status]').filter({hasText:'اسکن اضافه'}).waitFor();const parcel=page.locator('[data-station-parcel="0"]');await parcel.locator('[data-weight]').fill('900');await parcel.locator('[data-measure]').click();await page.locator('[data-station-status]').filter({hasText:'ذخیره شد'}).waitFor();const committed=page.waitForResponse(r=>r.url().endsWith('admin-ajax.php')&&new URLSearchParams(r.request().postData()||'').get('intent')==='commit');await page.locator('[data-station-commit]').click();assert.equal((await (await committed).json()).success,true);const repeat=page.waitForResponse(r=>r.url().endsWith('admin-ajax.php')&&new URLSearchParams(r.request().postData()||'').get('intent')==='commit');await page.locator('[data-station-commit]').click();assert.equal((await (await repeat).json()).success,true);await page.locator('[data-station-release]').click();await page.locator('[data-station-status]').filter({hasText:'آزاد شد'}).waitFor();
await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/station.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-print-center');await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/print-mobile.png',fullPage:true});
const printContext=await browser.newContext();const restricted=await printContext.newPage();await login(restricted,'mahex-print-fixture','mahex-local-print-test');await restricted.goto(base+'/wp-admin/admin.php?page=hm-mahex-print-center');assert.ok((await restricted.locator('body').innerText()).includes('مرکز چاپ گروهی'));const denied=await restricted.goto(base+'/wp-admin/admin.php?page=hm-mahex-reconciliation');assert.equal(denied.status(),403);assert.deepEqual(errors,[]);await browser.close();console.log('Browser drag persistence, scans, measurements, stock commit, mobile rendering and scoped-page denial passed');})().catch(e=>{console.error(e);process.exit(1);});
