const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const fixtures=JSON.parse(fs.readFileSync(process.env.MAHEX_FIXTURES));const id=fixtures.orders[0];const base=process.env.MAHEX_BASE_URL||'http://127.0.0.1:8092';const browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
async function login(p,user,password){await p.goto(base+'/wp-login.php');await p.locator('#user_login').fill(user);await p.locator('#user_pass').fill(password);await Promise.all([p.waitForURL(/wp-admin/),p.locator('#wp-submit').click()]);}
await login(page,'mahex-admin','mahex-local-test-password');
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-workspace');await page.locator('#hmx32-grid [data-widget="finance"] [data-move="up"]').click();await page.locator('#hmx32-status').filter({hasText:'ذخیره شد'}).waitFor();await page.reload();const order=await page.locator('#hmx32-grid [data-widget]').evaluateAll(xs=>xs.map(x=>x.dataset.widget));assert.equal(order[2],'finance');await page.locator('#hmx32-layout-undo').click();await page.locator('#hmx32-status').filter({hasText:'برگشت'}).waitFor();
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-v32-board');const card=page.locator(`[data-id="${id}"]`);await card.locator('.hmx-board-customer').scrollIntoViewIfNeeded();const boardTarget=page.locator('.hmx-board-column[data-stage="packing"]');const sourceRect=await card.locator('.hmx-board-customer').boundingBox(),targetRect=await boardTarget.boundingBox();assert.deepEqual(errors,[]);await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/board-before-drag.png'});const boardSaved=page.waitForResponse(r=>r.url().endsWith('admin-ajax.php')&&new URLSearchParams(r.request().postData()||'').get('action')==='hm_mahex_v32_board');await card.locator('.hmx-board-customer').dragTo(boardTarget,{targetPosition:{x:targetRect.width/2,y:sourceRect.y+sourceRect.height/2-targetRect.y}});const savedBoard=await(await boardSaved).json();assert.equal(savedBoard.success,true,JSON.stringify(savedBoard));assert.equal(savedBoard.data.stage,'packing');await page.locator('#hmx-board-message').filter({hasText:/ذخیره|ثبت/}).waitFor();await page.reload();assert.equal(await page.locator(`[data-id="${id}"] .hmx-board-stage`).inputValue(),'packing');
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-v33-station&order_id='+id);await page.locator('[data-station-lock]').click();await page.locator('[data-station-status]').filter({hasText:'در اختیار شماست'}).waitFor();for(let n=0;n<2;n++){await page.locator('[data-station-code]').fill('MHX-E2E-1');await page.locator('[data-station-scan]').click();await page.locator('[data-station-count]').filter({hasText:`${n+1} / 2`}).waitFor();}await page.locator('[data-station-code]').fill('MHX-E2E-1');await page.locator('[data-station-scan]').click();await page.locator('[data-station-status]').filter({hasText:'اسکن اضافه'}).waitFor();const parcel=page.locator('[data-station-parcel="0"]');await parcel.locator('[data-weight]').fill('900');await parcel.locator('[data-measure]').click();await page.locator('[data-station-status]').filter({hasText:'ذخیره شد'}).waitFor();const committed=page.waitForResponse(r=>r.url().endsWith('admin-ajax.php')&&new URLSearchParams(r.request().postData()||'').get('intent')==='commit');await page.locator('[data-station-commit]').click();assert.equal((await (await committed).json()).success,true);const repeat=page.waitForResponse(r=>r.url().endsWith('admin-ajax.php')&&new URLSearchParams(r.request().postData()||'').get('intent')==='commit');await page.locator('[data-station-commit]').click();assert.equal((await (await repeat).json()).success,true);await page.locator('[data-station-release]').click();await page.locator('[data-station-status]').filter({hasText:'آزاد شد'}).waitFor();
await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/station.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-print-center');await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/print-mobile.png',fullPage:true});

await page.setViewportSize({width:1440,height:1000});const dispatchId=fixtures.orders[1];
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-v34-dispatch');const dispatch=page.locator(`[data-order-id="${dispatchId}"]`);await dispatch.waitFor();
async function applyDispatch(){const applied=page.waitForResponse(r=>r.url().endsWith('admin-ajax.php')&&new URLSearchParams(r.request().postData()||'').get('intent')==='apply');await page.locator('[data-dispatch-apply]').click();const result=await(await applied).json();assert.equal(result.success,true);assert.equal(result.data.errors.length,0);await page.locator('[data-dispatch-status]').filter({hasText:'سفارش موفق'}).waitFor();}
await dispatch.locator('details').nth(0).locator('summary').click();await dispatch.locator('[data-dispatch-action="normalize"]').click();await page.locator('[data-dispatch-dialog]').waitFor({state:'visible'});await applyDispatch();await page.reload();assert.ok((await dispatch.locator('.hmx-dispatch-address').innerText()).includes('09123456789'));
await page.locator('[data-dispatch-bin]').fill('QOM-A1');await page.locator('[data-dispatch-addbin]').click();await dispatch.locator('h2').dragTo(page.locator('[data-drop-bin="QOM-A1"]'));await page.locator('[data-dispatch-dialog]').waitFor({state:'visible'});await applyDispatch();await page.reload();assert.ok((await dispatch.innerText()).includes('QOM-A1'));
await dispatch.locator('details').nth(0).locator('summary').click();await dispatch.locator('[data-verify-note]').fill('تأیید مقصد در آزمون مرورگر');await dispatch.locator('[data-dispatch-action="verify"]').click();await page.locator('[data-dispatch-dialog]').waitFor({state:'visible'});await applyDispatch();
await page.setViewportSize({width:360,height:800});await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/dispatch-mobile.png',fullPage:true});assert.ok(await page.locator('.hmx-dispatch').evaluate(e=>e.scrollWidth<=e.clientWidth+2),'Dispatch mobile horizontal overflow');await page.setViewportSize({width:1440,height:1000});
await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-service-policies&order_id='+dispatchId);
await page.locator('.hmx-service > details').first().locator('summary').first().click();const settingsForm=page.locator('form:has(input[name="command"][value="settings"])');await settingsForm.locator('[name="effort_minutes"]').fill('90');await settingsForm.locator('[name="weekly_mode[3]"]').selectOption('custom');await settingsForm.locator('[name="weekly_start[3]"]').fill('10:00');await settingsForm.locator('[name="weekly_end[3]"]').fill('17:00');const breakEditor=settingsForm.locator('[data-kind="breaks"]');await breakEditor.locator('.hmx-add-interval').click();await breakEditor.locator('.hmx-interval-row').last().locator('input').nth(0).fill('15:00');await breakEditor.locator('.hmx-interval-row').last().locator('input').nth(1).fill('15:30');const dateEditor=settingsForm.locator('[data-kind="date_shifts"]');await dateEditor.locator('[type="date"]').first().fill('2026-10-09');await dateEditor.locator('[type="time"]').nth(0).fill('06:00');await dateEditor.locator('[type="time"]').nth(1).fill('20:00');await Promise.all([page.waitForNavigation(),settingsForm.locator('button[type="submit"],button.button-primary').last().click()]);assert.ok((await page.locator('body').innerText()).includes('ذخیره شد.'));assert.equal(await page.locator('[name="effort_minutes"]').inputValue(),'90');
async function submitCase(command,note){const form=page.locator(`form:has(input[name="command"][value="${command}"])`).first();if(note)await form.locator('input[name="note"]').fill(note);await Promise.all([page.waitForNavigation(),form.locator('button').click()]);assert.ok((await page.locator('body').innerText()).includes('ذخیره شد.'));}
await submitCase('promise');const openCase=page.locator('form:has(input[name="command"][value="open"])');await openCase.locator('[name="type"]').selectOption('document');await openCase.locator('[name="severity"]').selectOption('critical');await submitCase('open','مدرک آزمایشی نیازمند بازبینی');await submitCase('ack');await submitCase('corrective','مدرک کنترل شد');await submitCase('resolve','پرونده آزمایشی حل شد');await page.locator('.hmx-case-search').fill('واژه‌ای بدون نتیجه');assert.equal(await page.locator('.hmx-incident:visible').count(),0);await page.locator('.hmx-case-search').fill('مدرک');assert.equal(await page.locator('.hmx-incident:visible').count(),1);await page.locator('.hmx-case-search').fill('');await page.locator('form:has(input[name="command"][value="cost"]) [name="cost"]').fill('500');await submitCase('cost');await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/local-service-case.png',fullPage:true});
const opsContext=await browser.newContext();const ops=await opsContext.newPage();await login(ops,'mahex-ops-fixture','mahex-local-ops-test');await ops.goto(base+'/wp-admin/admin.php?page=hm-mahex-service-policies&order_id='+dispatchId);assert.equal(await ops.locator('form:has(input[name="command"][value="cost"])').count(),0);assert.equal(await ops.locator('form:has(input[name="command"][value="recovery"])').count(),0);const caseUrl=await ops.getByRole('link',{name:'خروجی خصوصی پرونده JSON'}).getAttribute('href');const caseResponse=await ops.request.get(caseUrl);assert.equal(caseResponse.status(),200);const evidence=await caseResponse.json();assert.ok(Object.values(evidence.case.incidents).every(x=>!('cost' in x)&&!('recovery' in x)));assert.ok(Object.values(evidence.case.history).every(x=>x.command!=='cost'));const opForm=ops.locator('form:has(input[name="command"][value="open"])');const csrf=await opForm.locator('[name="_wpnonce"]').inputValue();const deniedCost=await ops.request.post(base+'/wp-admin/admin-post.php',{form:{action:'hm_mahex_v34_policy',_wpnonce:csrf,order_id:String(dispatchId),revision:String(evidence.case.revision),command:'cost',incident_id:Object.keys(evidence.case.incidents)[0],cost:'999'}});assert.ok((await deniedCost.text()).includes('ثبت هزینه مجوز مالی لازم دارد.'));await opsContext.close();
const printContext=await browser.newContext();const restricted=await printContext.newPage();await login(restricted,'mahex-print-fixture','mahex-local-print-test');await restricted.goto(base+'/wp-admin/admin.php?page=hm-mahex-print-center');assert.ok((await restricted.locator('body').innerText()).includes('مرکز چاپ گروهی'));const denied=await restricted.goto(base+'/wp-admin/admin.php?page=hm-mahex-reconciliation');assert.equal(denied.status(),403);const deniedDispatch=await restricted.goto(base+'/wp-admin/admin.php?page=hm-mahex-v34-dispatch');assert.equal(deniedDispatch.status(),403);const deniedCase=await restricted.goto(base+'/wp-admin/admin.php?page=hm-mahex-service-policies');assert.equal(deniedCase.status(),403);assert.deepEqual(errors,[]);await browser.close();console.log('Browser drag persistence, scans, measurements, stock commit, mobile rendering and scoped-page denial passed');})().catch(e=>{console.error(e);process.exit(1);});
