<?php
if(!defined('ABSPATH'))require getenv('MAHEX_WP_ROOT').'/wp-load.php';
add_filter('pre_wp_mail',static fn()=>true);wp_set_current_user(1);
update_option('woocommerce_currency','IRR');update_option('woocommerce_weight_unit','kg');update_option('woocommerce_dimension_unit','cm');
update_option('hm_mahex_settings',['sender_name'=>'فروشگاه آزمایشی','sender_phone'=>'09120000000','origin_state'=>'QOM','origin_city'=>'قم','postal_code'=>'1234567890','origin_address'=>'قم، نشانی آزمایشی']);
$p=new WC_Product_Simple();$p->set_name('کالای آزمایشی');$p->set_sku('MHX-E2E-1');$p->set_regular_price('250000');$p->set_weight('.4');$p->set_length('8');$p->set_width('10');$p->set_height('5');$p->save();
$profile=['name'=>'کارتن آزمایشی','length_mm'=>300,'width_mm'=>200,'height_mm'=>150,'empty_weight_g'=>100,'max_weight_g'=>5000,'max_items'=>20,'unit_cost_irr'=>50000,'stock'=>100,'active'=>true];update_option('hm_mahex_packaging_profiles',['e2e-box'=>$profile]);
$orders=[];foreach([1,2] as $index){$o=wc_create_order();$o->add_product($p,2);$address=['first_name'=>'گیرنده','last_name'=>'آزمایشی '.$index,'address_1'=>'تهران، نشانی آزمایشی','city'=>'تهران','state'=>'THR','postcode'=>'1234567890','country'=>'IR','phone'=>'09123456789','email'=>'fixture@example.test'];$o->set_address($address,'billing');$o->set_address($address,'shipping');$s=new WC_Order_Item_Shipping();$s->set_method_id('hm_mahex');$s->set_method_title('ماهکس');$s->set_total(180000);$s->add_meta_data('hm_mahex_freight',130000);$s->add_meta_data('hm_mahex_packaging',50000);$o->add_item($s);$o->calculate_totals();$o->set_status('processing');$o->save();$units=HoseinMomeni\MahexWoo\V32\Packing::units($o);$plan=HoseinMomeni\MahexWoo\V32\Packing::validate([['profile_id'=>'e2e-box','units'=>array_keys($units)]],$units,['e2e-box'=>$profile]);$plan['revision']=1;$o->update_meta_data(HoseinMomeni\MahexWoo\V32\Packing::META,$plan);$o->save_meta_data();$barcode=(new HoseinMomeni\MahexWoo\Barcode\OrderBarcodeRepository())->for_order($o);if(!preg_match('/^\d{10}$/',$barcode))throw new RuntimeException('MySQL sequence failed');$orders[]=$o->get_id();}
update_option(HoseinMomeni\MahexWoo\V33\Station::STOCK,['carton_e2e-box'=>['name'=>'کارتن','stock'=>10,'unit_cost_irr'=>50000,'min_stock'=>2,'target_stock'=>20],'tape'=>['name'=>'چسب','stock'=>100,'unit_cost_irr'=>1000,'min_stock'=>10,'target_stock'=>100]]);
$uid=wp_insert_user(['user_login'=>'mahex-print-fixture','user_pass'=>'mahex-local-print-test','user_email'=>'print@example.test','role'=>'mahex_print_only']);if(is_wp_error($uid))throw new RuntimeException($uid->get_error_message());
$f=['orders'=>$orders,'product'=>$p->get_id(),'print_user'=>$uid,'hpos'=>get_option('woocommerce_custom_orders_table_enabled'),'wp_version'=>$GLOBALS['wp_version'],'wc_version'=>WC_VERSION];file_put_contents(getenv('MAHEX_FIXTURES'),wp_json_encode($f));echo wp_json_encode($f).PHP_EOL;
