const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{
 const f=JSON.parse(fs.readFileSync(process.env.MAHEX_FIXTURES));const base=process.env.MAHEX_BASE_URL||'http://127.0.0.1:8092';const browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function login(p,user,pass){await p.goto(base+'/wp-login.php');await p.locator('#user_login').fill(user);await p.locator('#user_pass').fill(pass);await Promise.all([p.waitForURL(/wp-admin/),p.locator('#wp-submit').click()]);}
 await login(page,'mahex-admin','mahex-local-test-password');
 await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-order-quality&order_id='+f.quality_order);
 const sku=page.locator('.hq-finding[data-finding^="missing_sku:"]');await sku.waitFor();await sku.locator('[data-quality-reason]').fill('ثبت مغایرت SKU در آزمون مرورگر');await Promise.all([page.waitForNavigation(),sku.locator('[data-verdict="confirmed"]').click()]);assert.equal(await sku.getAttribute('data-state'),'confirmed');
 await page.locator('[data-quality-state]').selectOption('open');assert.equal(await sku.isVisible(),false);await page.locator('[data-quality-state]').selectOption('confirmed');assert.equal(await sku.isVisible(),true);await page.locator('[data-quality-state]').selectOption('');await page.locator('[data-quality-search]').fill('بدون‌نتیجه‌ممیزی');assert.equal(await page.locator('.hq-finding:visible').count(),0);await page.locator('[data-quality-search]').fill('');
 const exportUrl=await page.getByRole('link',{name:'خروجی خصوصی ممیزی'}).getAttribute('href');const qualityExport=await(await page.request.get(exportUrl)).json();assert.ok(qualityExport.findings.some(x=>x.state==='confirmed'));assert.equal(JSON.stringify(qualityExport).includes('quality@example.test'),false);
 await page.setViewportSize({width:360,height:800});assert.ok(await page.locator('.hm-quality').evaluate(e=>e.scrollWidth<=e.clientWidth+2),'Quality mobile overflow');await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/quality-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 const opsContext=await browser.newContext();const ops=await opsContext.newPage();await login(ops,'mahex-ops-fixture','mahex-local-ops-test');await ops.goto(base+'/wp-admin/admin.php?page=hm-mahex-order-quality&order_id='+f.quality_order);assert.equal(await ops.locator('[data-finding="missing_payment_method"]').count(),0);const opsUrl=await ops.getByRole('link',{name:'خروجی خصوصی ممیزی'}).getAttribute('href');const opsData=await(await ops.request.get(opsUrl)).json();assert.ok(opsData.findings.every(x=>!x.financial));assert.ok(opsData.history.every(x=>!x.financial));await opsContext.close();
 await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-v35-handover');await page.locator('details').first().locator('summary').click();const create=page.locator('[data-handover-create]');const [a,b]=f.handover_orders;
 for(const [name,value] of Object.entries({order_id:String(a),title:'دفتر مرورگر قم',origin:'انبار آزمایشی قم',destination:'دفتر مقصد آزمایشی',start:'2026-10-07T10:00',end:'2026-10-07T14:00',capacity:'4'}))await create.locator(`[name="${name}"]`).fill(value);
 async function mutation(click){const response=page.waitForResponse(r=>r.url().endsWith('admin-ajax.php')&&new URLSearchParams(r.request().postData()||'').get('action')==='hm_mahex_v35_handover');await click();const json=await(await response).json();assert.equal(json.success,true,JSON.stringify(json));await page.locator('.hmx-handover[aria-busy="false"]').waitFor();return json.data.group;}
 let group=await mutation(()=>create.locator('button').click());const add=page.locator('[data-handover-operation="add"]');await add.locator('[name="order_id"]').fill(String(b));group=await mutation(()=>add.locator('button').click());assert.equal(group.totals.parcels,2);
 group=await mutation(()=>page.locator(`[data-handover-drag="${b}"]`).dragTo(page.locator(`[data-handover-member="${a}"]`)));assert.deepEqual(group.order,[b,a]);
 await page.goto(base+'/wp-admin/admin.php?page=hm-mahex-v35-handover&group='+group.id);await page.locator(`[data-handover-member="${b}"]`).waitFor();assert.equal(await page.locator('[data-handover-member]').first().getAttribute('data-handover-member'),String(b));
 const seal=page.locator('[data-handover-operation="seal"]');await seal.locator('[name="seal"]').fill('BROWSER-SEAL-35');group=await mutation(()=>seal.locator('button').click());assert.equal(group.state,'sealed');
 const dispatch=page.locator('[data-handover-operation="dispatch"]');await dispatch.locator('[name="receiver"]').fill('راننده آزمون مرورگر');await dispatch.locator('[name="reference"]').fill('BROWSER-OUT');group=await mutation(()=>dispatch.locator('button').click());assert.equal(group.state,'dispatched');
 for(const oid of [a,b]){const receive=page.locator(`[data-handover-member="${oid}"] [data-handover-operation="receive"]`);await receive.locator('[name="receiver"]').fill('پذیرنده آزمون');await receive.locator('[name="reference"]').fill('BROWSER-IN-'+oid);group=await mutation(()=>receive.locator('button').click());}
 group=await mutation(()=>page.locator('[data-handover-operation="close"] button').click());assert.equal(group.state,'closed');assert.equal(group.totals.received_parcels,2);
 const exportForm=page.locator('[data-handover-export]');const nonce=await exportForm.locator('[name="_wpnonce"]').inputValue();const privateExport=await page.request.post(base+'/wp-admin/admin-post.php',{form:{action:'hm_mahex_v35_handover_export',group:group.id,_wpnonce:nonce,format:'json'}});assert.equal(privateExport.status(),200);const exported=await privateExport.json();assert.equal(exported.carrier_delivery_verified,false);assert.equal(exported.group.state,'closed');assert.equal(JSON.stringify(exported).includes('manifest-v35@example.test'),false);
 const sheet=await page.request.post(base+'/wp-admin/admin-post.php',{form:{action:'hm_mahex_v35_handover_export',group:group.id,_wpnonce:nonce,format:'sheet'}});assert.ok((await sheet.text()).includes('BROWSER-SEAL-35'));
 await page.locator('[data-handover-filter]').selectOption('draft');assert.equal(await page.locator('[data-handover-group]').count(),0);await page.locator('[data-handover-filter]').selectOption('closed');await page.locator('[data-handover-search]').fill('دفتر مرورگر قم');assert.equal(await page.locator('[data-handover-group]').count(),1);
 await page.setViewportSize({width:360,height:800});assert.ok(await page.locator('.hmx-handover').evaluate(e=>e.scrollWidth<=e.clientWidth+2),'Handover mobile overflow');await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/handover-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:process.env.MAHEX_REPORT_DIR+'/handover-closed.png',fullPage:true});
 const printContext=await browser.newContext();const restricted=await printContext.newPage();await login(restricted,'mahex-print-fixture','mahex-local-print-test');for(const slug of ['hm-mahex-order-quality','hm-mahex-v35-handover'])assert.equal((await restricted.goto(base+'/wp-admin/admin.php?page='+slug)).status(),403);await printContext.close();
 fs.writeFileSync(process.env.MAHEX_REPORT_DIR+'/v35-browser.json',JSON.stringify({quality_order:f.quality_order,handover_group:group.id,orders:group.order,state:group.state,totals:group.totals},null,2));assert.deepEqual(errors,[]);await browser.close();console.log('V35 real browser quality review/filter/private export, native member drag persistence, seal/dispatch/receipts/closure, mobile and capability denial passed');
})().catch(e=>{console.error(e);process.exit(1);});
