<?php
if(!defined('ABSPATH'))require getenv('MAHEX_WP_ROOT').'/wp-load.php';
wp_set_current_user(1);
use HoseinMomeni\MahexWoo\V36\OfflineDispatchWaves as W;
use HoseinMomeni\MahexWoo\V36\QualitySampling as Q;
use HoseinMomeni\MahexWoo\V32\Packing as P;
use HoseinMomeni\MahexWoo\V33\Station as S;
function checkV36($ok,$message){if(!$ok)throw new RuntimeException($message);}
function v36Order($product,string $email){
 $o=wc_create_order();$o->add_product(wc_get_product($product),1);$address=['first_name'=>'دور۳','last_name'=>'آزمایشی','address_1'=>'قم نشانی تست','city'=>'قم','state'=>'QOM','postcode'=>'3712345678','country'=>'IR','phone'=>'09120000000','email'=>$email];$o->set_address($address,'billing');$o->set_address($address,'shipping');$s=new WC_Order_Item_Shipping();$s->set_method_id('hm_mahex');$s->set_method_title('ماهکس محلی');$s->set_total(10000);$o->add_item($s);$o->set_status('processing');$o->calculate_totals();$o->save();
 $units=P::units($o);$profile=get_option('hm_mahex_packaging_profiles')['e2e-box'];$plan=P::validate([['profile_id'=>'e2e-box','units'=>array_keys($units)]],$units,['e2e-box'=>$profile]);$plan['revision']=1;$o->update_meta_data(P::META,$plan);$o->update_meta_data(S::META,['revision'=>1,'scans'=>[],'parcels'=>[0=>['weight_g'=>650,'dimensions_mm'=>[300,200,150]]]]);$o->save_meta_data();return $o;
}
$f=json_decode(file_get_contents(getenv('MAHEX_FIXTURES')),true);$a=v36Order($f['product'],'v36-a@example.test');$b=v36Order($f['product'],'v36-b@example.test');$c=v36Order($f['product'],'v36-c@example.test');
$base=['order_id'=>$a->get_id(),'title'=>'موج backend قم','day'=>'2026-10-07','start'=>'2026-10-07T09:00','end'=>'2026-10-07T12:00','origin_id'=>'QOM-1','origin_label'=>'انبار قم','orders'=>3,'parcels'=>4,'weight_g'=>5000,'minutes'=>120,'threshold'=>80];
$wave=W::create($base);$wave=W::mutate($wave['id'],$wave['revision'],'add',['order_id'=>$b->get_id()]);$wave=W::mutate($wave['id'],$wave['revision'],'reorder',['order'=>[$b->get_id(),$a->get_id()]]);$wave=W::mutate($wave['id'],$wave['revision'],'publish');checkV36($wave['state']==='published'&&$wave['snapshot_version']===1,'wave snapshot');
$changed=wc_get_order($a->get_id());$changed->set_shipping_city('تهران');$changed->save();checkV36(isset(W::get($wave['id'])['drifts'][$a->get_id()]),'wave drift');$wave=W::mutate($wave['id'],$wave['revision'],'refresh',['note'=>'مقصد واقعی سفارش بازبینی شد']);$wave=W::mutate($wave['id'],$wave['revision'],'start');$wave=W::mutate($wave['id'],$wave['revision'],'complete');checkV36($wave['state']==='completed','wave lifecycle');
$private=new HoseinMomeni\MahexWoo\Privacy\WooCommercePersonalDataRepository();$export=$private->export_for_email('v36-a@example.test',1,100);checkV36(count(array_filter($export,fn($x)=>str_contains($x['name'],'Offline dispatch wave')))===1,'wave privacy export');
$settings=['from'=>'2020-01-01T00:00:00Z','to'=>'2030-01-01T00:00:00Z','statuses'=>['processing'],'methods'=>['hm_mahex'],'mode'=>'fixed','value'=>2,'seed'=>'integration-v36','sample_cap'=>10,'population_limit'=>200,'overlap'=>'warn','minimum_station_sample'=>2,'target_rate'=>5,'name'=>'کمپین یکپارچه دور سوم','purpose'=>'ثبت مشاهده دستی بسته‌های آزمون واقعی'];
$campaign=Q::create($settings,[$a->get_id()=>Q::orderSnapshot($a),$c->get_id()=>Q::orderSnapshot($c)]);$campaign=Q::mutate($campaign['id'],$campaign['revision'],'activate');$oid=array_key_first($campaign['members']);$member=$campaign['members'][$oid];$answers=[];foreach($campaign['template'] as $criterion){$answers[$criterion['code']]='pass';$answers[$criterion['code'].'_note']='';}$answers['identity']='fail';$answers['identity_note']='شناسه روی بسته در مشاهده دستی متفاوت بود';$campaign=Q::inspect($campaign['id'],$campaign['revision'],$oid,$member['revision'],$answers,['wrong_item'],'quarantine','بازرسی فیزیکی دستی در محیط آزمون',true,true);checkV36(Q::hasOpenQuarantine($oid),'quarantine persisted');$blocked=false;try{Q::assertNoQuarantine($oid);}catch(Throwable $e){$blocked=true;}checkV36($blocked,'quarantine guard');
$first=get_current_user_id();$reviewer=wp_insert_user(['user_login'=>'mahex-qa-reviewer','user_pass'=>'qa-reviewer-test','user_email'=>'qa-reviewer@example.test','role'=>'administrator']);if(is_wp_error($reviewer))$reviewer=get_user_by('login','mahex-qa-reviewer')->ID;wp_set_current_user($reviewer);$campaign=Q::secondReview($campaign['id'],$campaign['revision'],$oid,true,'اصلاح بسته با مشاهده دستی دوم تأیید شد');checkV36(!Q::hasOpenQuarantine($oid),'distinct second review');wp_set_current_user($first);
$f['v36_wave_orders']=[$a->get_id(),$b->get_id(),$c->get_id()];$f['v36_campaign']=$campaign['id'];$f['v36_campaign_pending']=array_values(array_diff(array_keys($campaign['members']),[$oid]))[0];file_put_contents(getenv('MAHEX_FIXTURES'),wp_json_encode($f));
echo 'V36 real Woo CRUD wave snapshot/drift/lifecycle/privacy and manual QA quarantine/second-review passed'.PHP_EOL;
