<?php
namespace HoseinMomeni\MahexWoo\V37;

use HoseinMomeni\MahexWoo\V33\Access;

/** Local, human-entered receiving for internal packaging purchase orders. */
final class SupplyReceiving {
 const PURCHASES='hm_mahex_v33_purchase_orders';
 const RECEIPTS='hm_mahex_v37_supply_receipts';
 const STOCK='hm_mahex_v33_materials';
 const SETTINGS='hm_mahex_v37_receiving_settings';
 const SLUG='hm-mahex-v37-receiving';
 const NONCE='hm_mahex_v37_receiving';
 const LANES=['awaiting_count','inspecting','quarantined','accepted','rejected'];
 const DEFECTS=[
  'torn'=>['title'=>'پارگی','severity'=>'warning','active'=>true],
  'wet'=>['title'=>'رطوبت','severity'=>'critical','active'=>true],
  'crushed'=>['title'=>'لهیدگی','severity'=>'warning','active'=>true],
  'contaminated'=>['title'=>'آلودگی','severity'=>'critical','active'=>true],
  'mismatch'=>['title'=>'مغایرت ماده','severity'=>'critical','active'=>true],
 ];

 public static function register(): void {add_action('admin_menu',[self::class,'menu'],50);add_action('admin_enqueue_scripts',[self::class,'assets']);add_action('wp_ajax_hm_mahex_v37_receiving',[self::class,'ajax']);add_action('admin_post_hm_mahex_v37_receiving_csv',[self::class,'download']);add_action('admin_post_hm_mahex_v37_receiving_print',[self::class,'printSheet']);}
 public static function menu(): void {add_submenu_page('hm-mahex','دریافت ملزومات','دریافت ملزومات',Access::cap('settings'),self::SLUG,[self::class,'page']);}
 public static function assets(string $hook): void {if(strpos($hook,self::SLUG)===false)return;wp_enqueue_style('hm-v37-receiving',plugins_url('assets/admin/v37-receiving.css',HM_MAHEX_FILE),[],HM_MAHEX_VERSION);wp_enqueue_script('hm-v37-receiving',plugins_url('assets/admin/v37-receiving.js',HM_MAHEX_FILE),[],HM_MAHEX_VERSION,true);wp_localize_script('hm-v37-receiving','hmReceiving',['url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce(self::NONCE)]);}
 public static function canView(): bool {return Access::can('settings')||current_user_can('manage_woocommerce');}
 public static function canCount(): bool {return Access::can('packing')||current_user_can('manage_woocommerce');}
 public static function canDecide(): bool {return Access::can('settings')||current_user_can('manage_woocommerce');}
 public static function canManage(): bool {return current_user_can('manage_woocommerce');}
 public static function now(): string {return gmdate('c');}
 public static function text($value,int $min=0,int $max=500): string {if(!is_scalar($value))throw new \InvalidArgumentException('متن معتبر نیست.');$value=trim(strip_tags((string)$value));if(mb_strlen($value)<$min||mb_strlen($value)>$max)throw new \InvalidArgumentException('طول متن معتبر نیست.');return $value;}
 public static function key($value): string {$value=(string)$value;if(!preg_match('/^[A-Za-z0-9_-]{1,80}$/',$value))throw new \InvalidArgumentException('شناسه معتبر نیست.');return $value;}
 public static function receiptId(string $value): string {if(!preg_match('/^[a-f0-9]{24}$/',$value))throw new \InvalidArgumentException('شناسه رسید معتبر نیست.');return $value;}
 public static function quantity($value,int $precision=3,bool $positive=false): float {if(!is_numeric($value)||!is_finite((float)$value))throw new \InvalidArgumentException('مقدار عددی معتبر نیست.');$number=(float)$value;if($number<0||($positive&&$number<=0)||$number>1000000000)throw new \InvalidArgumentException('مقدار خارج محدوده است.');if(abs($number-round($number,$precision))>pow(10,-$precision)/2)throw new \InvalidArgumentException('دقت مقدار بیشتر از واحد ماده است.');return round($number,$precision);}
 public static function lot(string $value): string {$value=strtoupper(trim(strip_tags($value)));if(!preg_match('/^[A-Z0-9][A-Z0-9._-]{1,39}$/',$value))throw new \InvalidArgumentException('کد lot معتبر نیست.');return $value;}
 public static function expiry($value,bool $noExpiry,string $receivedAt): ?string {if($noExpiry){if(trim((string)$value)!=='')throw new \InvalidArgumentException('تاریخ مصرف و بدون انقضا هم‌زمان مجاز نیست.');return null;}$value=trim((string)$value);$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$value,new \DateTimeZone('UTC'));if(!$d||$d->format('Y-m-d')!==$value||$d->getTimestamp()<strtotime(substr($receivedAt,0,10)))throw new \InvalidArgumentException('تاریخ مصرف معتبر نیست.');return $value;}
 public static function settings(): array {$raw=get_option(self::SETTINGS,[]);$raw=is_array($raw)?$raw:[];return array_merge(['over_pct'=>5,'expiry_warning_days'=>30,'retention_days'=>730,'receipt_cap'=>500,'line_cap'=>100,'event_cap'=>800,'minimum_score_sample'=>3,'defects'=>self::DEFECTS],$raw);}
 public static function defects(): array {$out=[];foreach((array)self::settings()['defects'] as $code=>$row){$code=strtolower(self::key($code));$severity=(string)($row['severity']??'warning');if(!in_array($severity,['info','warning','critical'],true))continue;$out[$code]=['title'=>self::text($row['title']??$code,1,120),'severity'=>$severity,'active'=>!empty($row['active'])];}return $out;}
 public static function stock(): array {$v=get_option(self::STOCK,[]);return is_array($v)?$v:[];}
 public static function receipts(): array {$v=get_option(self::RECEIPTS,[]);return is_array($v)?$v:[];}
 /** Read-compatible migration: old rows are normalized in memory without destroying legacy fields. */
 public static function purchases(bool $persist=false): array {$rows=get_option(self::PURCHASES,[]);$rows=is_array($rows)?$rows:[];$changed=false;foreach($rows as $id=>&$p){if(!is_array($p))continue;$p['id']=(string)($p['id']??$id);$p['supplier']=self::text($p['supplier']??'تأمین‌کننده ثبت‌نشده',0,120);$p['revision']=max(1,(int)($p['revision']??1));$p['receiving_version']=37;$p['created_at']=(string)($p['created_at']??self::now());$status=(string)($p['status']??'draft');if($status==='received')$status='received';elseif(!in_array($status,['draft','ordered','partially_received','cancelled'],true))$status='draft';$p['status']=$status;$p['lines']=is_array($p['lines']??null)?$p['lines']:[];foreach($p['lines'] as $material=>&$line){$line=is_array($line)?$line:[];$line['name']=self::text($line['name']??$material,1,120);$line['qty']=self::quantity($line['qty']??0,3);$line['unit_cost_irr']=self::quantity($line['unit_cost_irr']??0,3);$line['precision']=min(3,max(0,(int)($line['precision']??(floor($line['qty'])==$line['qty']?0:3))));}unset($line);if(!isset($p['_v37'])){$p['_v37']=true;$changed=true;}}unset($p);if($persist&&$changed&&!update_option(self::PURCHASES,$rows,false))throw new \RuntimeException('ارتقای سفارش‌های خرید ذخیره نشد.');return $rows;}
 public static function purchaseSummary(string $purchaseId,?array $receipts=null): array {$p=self::purchases()[$purchaseId]??null;if(!$p)throw new \RuntimeException('سفارش خرید وجود ندارد.');$out=[];foreach($p['lines'] as $material=>$line)$out[$material]=['ordered'=>(float)$line['qty'],'counted'=>0.0,'accepted'=>0.0,'quarantined'=>0.0,'rejected'=>0.0,'remaining'=>(float)$line['qty']];foreach($receipts??self::receipts() as $receipt)if($receipt['purchase_id']===$purchaseId&&!in_array($receipt['state'],['cancelled'],true))foreach($receipt['lines'] as $material=>$line){if(!isset($out[$material]))continue;$out[$material]['counted']+=(float)($line['counted']??0);foreach(['accepted','quarantined','rejected'] as $field)$out[$material][$field]+=(float)($line[$field]??0);$out[$material]['remaining']=max(0,$out[$material]['ordered']-$out[$material]['accepted']-$out[$material]['rejected']);}return $out;}
 private static function event(array &$receipt,string $intent,array $detail=[]): void {if(count($receipt['history'])>=(int)self::settings()['event_cap'])throw new \RuntimeException('ظرفیت تاریخچه رسید پر است.');$receipt['history'][]=['intent'=>$intent,'detail'=>$detail,'actor'=>get_current_user_id(),'at'=>self::now()];}
 private static function save(array $all,array $receipt): void {$receipt['updated_at']=self::now();$all[$receipt['id']]=$receipt;if(!update_option(self::RECEIPTS,$all,false))throw new \RuntimeException('ذخیره رسید موفق نشد.');}
 public static function create(string $purchaseId,int $purchaseRevision,string $token,array $materials): array {if(!self::canCount())throw new \RuntimeException('مجوز شمارش وجود ندارد.');$orders=self::purchases(true);$p=$orders[$purchaseId]??null;if(!$p||$p['revision']!==$purchaseRevision||in_array($p['status'],['received','cancelled'],true))throw new \RuntimeException('سفارش خرید یا نسخه آن معتبر نیست.');$token=self::key($token);$all=self::receipts();foreach($all as $r)if(hash_equals($r['token'],$token))return $r;if(count($all)>=(int)self::settings()['receipt_cap'])throw new \RuntimeException('ظرفیت رسیدها پر است.');$summary=self::purchaseSummary($purchaseId,$all);$lines=[];foreach(array_values(array_unique($materials)) as $material){$material=self::key($material);if(!isset($p['lines'][$material])||$summary[$material]['remaining']<=0)throw new \InvalidArgumentException('ماده قابل دریافت نیست.');$line=$p['lines'][$material];$lines[$material]=['material'=>$material,'name'=>$line['name'],'ordered'=>(float)$line['qty'],'unit_cost_irr'=>(float)$line['unit_cost_irr'],'precision'=>(int)$line['precision'],'counted'=>0.0,'damaged'=>0.0,'accepted'=>0.0,'quarantined'=>0.0,'rejected'=>0.0,'lot'=>'','expiry'=>null,'no_expiry'=>false,'observation'=>'','defects'=>[],'counts'=>[],'decision'=>null,'revision'=>1];}if(!$lines||count($lines)>(int)self::settings()['line_cap'])throw new \InvalidArgumentException('اقلام رسید معتبر نیست.');$id=bin2hex(random_bytes(12));$r=['id'=>$id,'code'=>'MHR-'.strtoupper(substr($id,0,12)),'token'=>$token,'purchase_id'=>$purchaseId,'purchase_snapshot'=>['supplier'=>$p['supplier'],'created_at'=>$p['created_at'],'lines'=>$lines],'supplier_id'=>self::supplierId($p['supplier']),'supplier'=>$p['supplier'],'state'=>'awaiting_count','revision'=>1,'created_at'=>self::now(),'updated_at'=>self::now(),'actor'=>get_current_user_id(),'thresholds'=>['over_pct'=>(float)self::settings()['over_pct'],'expiry_warning_days'=>(int)self::settings()['expiry_warning_days']],'lines'=>$lines,'history'=>[],'posted'=>false];self::event($r,'create',['materials'=>array_keys($lines)]);self::save($all,$r);return $r;}
 public static function supplierId(string $name): string {$normalized=mb_strtolower(trim(preg_replace('/\s+/u',' ',$name)));$canonical=self::supplierAliases()[$normalized]??$normalized;$normalized=mb_strtolower(trim(preg_replace('/\s+/u',' ',$canonical)));return 'supplier-'.substr(hash('sha256',$normalized),0,16);}
 public static function supplierAliases(): array {$aliases=(array)(self::settings()['supplier_aliases']??[]);$out=[];foreach($aliases as $alias=>$canonical)$out[mb_strtolower(self::text($alias,1,120))]=self::text($canonical,1,120);return $out;}
 public static function resolveSupplier(string $name): array {$name=self::text($name,0,120);$key=mb_strtolower(trim(preg_replace('/\s+/u',' ',$name)));$canonical=self::supplierAliases()[$key]??$name;return ['id'=>self::supplierId($canonical),'name'=>$canonical,'source_name'=>$name];}
 public static function transitionPurchase(string $id,int $revision,string $to,string $reason=''): array {if(!self::canManage())throw new \RuntimeException('مدیریت خرید مجاز نیست.');$all=self::purchases();$p=$all[$id]??null;if(!$p||$p['revision']!==$revision)throw new \RuntimeException('خرید یا نسخه آن معتبر نیست.');$allowed=['draft'=>['ordered','cancelled'],'ordered'=>['partially_received','cancelled'],'partially_received'=>['received','cancelled'],'received'=>[],'cancelled'=>[]];if(!in_array($to,$allowed[$p['status']]??[],true))throw new \RuntimeException('گذار وضعیت خرید مجاز نیست.');if($to==='cancelled')$p['cancel_reason']=self::text($reason,3,500);$p['status']=$to;$p['revision']++;$p['updated_at']=self::now();$all[$id]=$p;if(!update_option(self::PURCHASES,$all,false))throw new \RuntimeException('ذخیره وضعیت خرید ناموفق بود.');return $p;}
 public static function countLine(string $id,int $revision,string $material,int $lineRevision,array $p): array {$all=self::receipts();$r=$all[self::receiptId($id)]??null;if(!$r||$r['revision']!==$revision||!self::canCount())throw new \RuntimeException('رسید، نسخه یا مجوز معتبر نیست.');if(!in_array($r['state'],['awaiting_count','inspecting'],true))throw new \RuntimeException('رسید در مرحله شمارش نیست.');$material=self::key($material);$line=$r['lines'][$material]??null;if(!$line||$line['revision']!==$lineRevision)throw new \RuntimeException('ردیف یا نسخه آن معتبر نیست.');if(empty($p['human']))throw new \InvalidArgumentException('تأیید مشاهده و شمارش دستی لازم است.');$counted=self::quantity($p['counted']??null,$line['precision']);$damaged=self::quantity($p['damaged']??0,$line['precision']);if($damaged>$counted)throw new \InvalidArgumentException('آسیب از شمارش بیشتر است.');$observation=self::text($p['observation']??'',($damaged>0?3:0),1000);$lot=self::lot((string)($p['lot']??''));$expires=self::expiry($p['expiry']??'',!empty($p['no_expiry']),self::now());$defects=[];$critical=false;foreach(array_unique((array)($p['defects']??[])) as $code){$code=strtolower(self::key($code));$d=self::defects()[$code]??null;if(!$d||!$d['active'])throw new \InvalidArgumentException('کد عیب فعال نیست.');$defects[$code]=$d;if($d['severity']==='critical')$critical=true;}if(($damaged>0||$defects)&&$observation==='')throw new \InvalidArgumentException('شرح مشاهده برای آسیب لازم است.');$summary=self::purchaseSummary($r['purchase_id'],$all);$remaining=$summary[$material]['remaining']+$line['accepted']+$line['rejected'];$max=$remaining*(1+$r['thresholds']['over_pct']/100);if($counted>$remaining){if(!self::canManage()||$counted>$max||self::text($p['over_reason']??'',3,500)==='')throw new \RuntimeException('اضافه‌تحویل مجاز یا مستدل نیست.');}$snapshot=['id'=>bin2hex(random_bytes(8)),'counted'=>$counted,'damaged'=>$damaged,'healthy'=>$counted-$damaged,'lot'=>$lot,'expiry'=>$expires,'no_expiry'=>!empty($p['no_expiry']),'observation'=>$observation,'defects'=>$defects,'critical'=>$critical,'human'=>true,'actor'=>get_current_user_id(),'at'=>self::now(),'over_reason'=>$counted>$remaining?self::text($p['over_reason'],3,500):''];$line['counts'][]=$snapshot;$line['counted']=$counted;$line['damaged']=$damaged;$line['lot']=$lot;$line['expiry']=$expires;$line['no_expiry']=!empty($p['no_expiry']);$line['observation']=$observation;$line['defects']=$defects;$line['decision']=null;$line['accepted']=0.0;$line['quarantined']=0.0;$line['rejected']=0.0;$line['revision']++;$r['lines'][$material]=$line;$r['state']='inspecting';$r['revision']++;self::event($r,'count',['material'=>$material,'count_id'=>$snapshot['id'],'counted'=>$counted,'damaged'=>$damaged]);self::save($all,$r);return $r;}
 public static function decide(string $id,int $revision,string $material,int $lineRevision,array $p): array {$all=self::receipts();$r=$all[self::receiptId($id)]??null;if(!$r||$r['revision']!==$revision||!self::canDecide())throw new \RuntimeException('رسید، نسخه یا مجوز معتبر نیست.');if($r['state']!=='inspecting')throw new \RuntimeException('رسید در مرحله تصمیم نیست.');$material=self::key($material);$line=$r['lines'][$material]??null;if(!$line||$line['revision']!==$lineRevision||!$line['counts'])throw new \RuntimeException('ردیف شمارش‌شده معتبر نیست.');$accepted=self::quantity($p['accepted']??0,$line['precision']);$quarantine=self::quantity($p['quarantined']??0,$line['precision']);$rejected=self::quantity($p['rejected']??0,$line['precision']);if(abs($accepted+$quarantine+$rejected-$line['counted'])>pow(10,-$line['precision'])/2)throw new \InvalidArgumentException('جمع تصمیم‌ها باید برابر شمارش باشد.');$critical=false;foreach($line['defects'] as $d)if($d['severity']==='critical')$critical=true;if($critical&&$quarantine<=0)throw new \RuntimeException('نقص بحرانی نیازمند قرنطینه است.');if($line['damaged']>0&&$quarantine+$rejected<$line['damaged'])throw new \RuntimeException('مقدار آسیب‌دیده باید قرنطینه یا رد شود.');$reason=self::text($p['reason']??'',($quarantine>0||$rejected>0?3:0),500);$decision=['accepted'=>$accepted,'quarantined'=>$quarantine,'rejected'=>$rejected,'reason'=>$reason,'actor'=>get_current_user_id(),'at'=>self::now(),'released_by'=>0];$line['accepted']=$accepted;$line['quarantined']=$quarantine;$line['rejected']=$rejected;$line['decision']=$decision;$line['revision']++;$r['lines'][$material]=$line;$r['state']=self::deriveState($r);$r['revision']++;self::event($r,'decide',['material'=>$material]+$decision);self::save($all,$r);return $r;}
 public static function deriveState(array $r): string {$pending=false;$q=0.0;$accepted=0.0;$rejected=0.0;foreach($r['lines'] as $line){if(!$line['decision'])$pending=true;$q+=$line['quarantined'];$accepted+=$line['accepted'];$rejected+=$line['rejected'];}if($pending)return 'inspecting';if($q>0)return 'quarantined';if($accepted>0)return 'accepted';return $rejected>0?'rejected':'inspecting';}
 public static function release(string $id,int $revision,string $material,bool $accept,string $reason): array {$all=self::receipts();$r=$all[self::receiptId($id)]??null;if(!$r||$r['revision']!==$revision||!self::canDecide())throw new \RuntimeException('رفع قرنطینه مجاز نیست.');$line=$r['lines'][self::key($material)]??null;if(!$line||$line['quarantined']<=0||!$line['decision'])throw new \RuntimeException('قرنطینه باز وجود ندارد.');if((int)$line['decision']['actor']===get_current_user_id())throw new \RuntimeException('بازبین دوم باید کاربر متفاوت باشد.');$reason=self::text($reason,3,500);$qty=$line['quarantined'];if($accept)$line['accepted']+=$qty;else $line['rejected']+=$qty;$line['quarantined']=0.0;$line['decision']['released_by']=get_current_user_id();$line['decision']['released_at']=self::now();$line['decision']['release_reason']=$reason;$line['revision']++;$r['lines'][$material]=$line;$r['state']=self::deriveState($r);$r['revision']++;self::event($r,'release',['material'=>$material,'accepted'=>$accept,'quantity'=>$qty,'reason'=>$reason]);self::save($all,$r);return $r;}
 /** Stock and idempotency marker share one option write. A retry repairs receipt state without adding stock again. */
 public static function post(string $id,int $revision): array {$all=self::receipts();$r=$all[self::receiptId($id)]??null;if(!$r||!self::canDecide())throw new \RuntimeException('ثبت موجودی مجاز نیست.');if($r['revision']!==$revision&&!$r['posted'])throw new \RuntimeException('نسخه رسید تغییر کرده است.');if($r['state']==='quarantined'||$r['state']==='inspecting'||$r['state']==='awaiting_count')throw new \RuntimeException('همه ردیف‌ها باید تعیین تکلیف شوند.');$stock=self::stock();$markers=is_array($stock['__v37_receipts']??null)?$stock['__v37_receipts']:[];$totals=[];foreach($r['lines'] as $material=>$line)if($line['accepted']>0)$totals[$material]=($totals[$material]??0)+$line['accepted'];if(!isset($markers[$id])){$next=$stock;foreach($totals as $material=>$qty){if(!isset($next[$material])||!is_array($next[$material]))throw new \RuntimeException('ماده در موجودی وجود ندارد: '.$material);$next[$material]['stock']=(float)($next[$material]['stock']??0)+$qty;$lotKey=$material.'|'.$r['lines'][$material]['lot'];$next['__v37_lots'][$lotKey]=['material'=>$material,'lot'=>$r['lines'][$material]['lot'],'expiry'=>$r['lines'][$material]['expiry'],'available'=>$qty,'receipt_id'=>$id,'received_at'=>$r['created_at']];}$next['__v37_receipts']=$markers;$next['__v37_receipts'][$id]=['totals'=>$totals,'at'=>self::now(),'actor'=>get_current_user_id()];if(!update_option(self::STOCK,$next,false))throw new \RuntimeException('افزایش موجودی ذخیره نشد.');}$r['posted']=true;$r['posted_at']=$stock['__v37_receipts'][$id]['at']??self::now();$r['posted_actor']=get_current_user_id();$r['revision']++;self::event($r,'post',['totals'=>$totals]);self::save($all,$r);self::syncPurchase($r,$all);return $r;}
 private static function syncPurchase(array $r,array $receipts): void {$orders=self::purchases();$p=$orders[$r['purchase_id']]??null;if(!$p)return;$summary=self::purchaseSummary($r['purchase_id'],$receipts);$complete=true;$any=false;foreach($summary as $row){if($row['accepted']+$row['rejected']>0)$any=true;if($row['remaining']>0)$complete=false;}$p['status']=$complete?'received':($any?'partially_received':'ordered');$p['revision']++;$p['updated_at']=self::now();$orders[$p['id']]=$p;update_option(self::PURCHASES,$orders,false);}
 public static function move(string $id,int $revision,string $lane): array {$all=self::receipts();$r=$all[self::receiptId($id)]??null;if(!$r||$r['revision']!==$revision||!self::canCount())throw new \RuntimeException('انتقال مجاز نیست.');if(!in_array($lane,self::LANES,true))throw new \InvalidArgumentException('ستون معتبر نیست.');$allowed=['awaiting_count'=>['inspecting'],'inspecting'=>['awaiting_count'],'quarantined'=>[],'accepted'=>[],'rejected'=>[]];if(!in_array($lane,$allowed[$r['state']]??[],true))throw new \RuntimeException('گذار برد مجاز نیست.');$r['state']=$lane;$r['revision']++;self::event($r,'move',['lane'=>$lane]);self::save($all,$r);return $r;}
 public static function score(string $supplierId): array {$final=[];foreach(self::receipts() as $r)if($r['supplier_id']===$supplierId&&$r['posted'])$final[]=$r;$n=count($final);$counted=$accepted=$quarantine=$over=$delay=0.0;foreach($final as $r){$delay+=max(0,(strtotime($r['created_at'])-strtotime($r['purchase_snapshot']['created_at']))/86400);foreach($r['lines'] as $line){$counted+=$line['counted'];$accepted+=$line['accepted'];$quarantine+=$line['quarantined'];if(($line['counts'][count($line['counts'])-1]['over_reason']??'')!=='')$over++;}}return ['sample'=>$n,'insufficient'=>$n<(int)self::settings()['minimum_score_sample'],'healthy_pct'=>$counted?round(100*$accepted/$counted,2):0,'quarantine_pct'=>$counted?round(100*$quarantine/$counted,2):0,'over_receipts'=>$over,'average_recorded_delay_days'=>$n?round($delay/$n,2):0,'descriptive_only'=>true,'causality_claimed'=>false];}
 public static function lotsForUse(string $material): array {$today=gmdate('Y-m-d');$rows=[];foreach((array)(self::stock()['__v37_lots']??[]) as $row)if($row['material']===$material&&$row['available']>0&&($row['expiry']===null||$row['expiry']>=$today))$rows[]=$row;usort($rows,static fn($a,$b)=>strcmp($a['expiry']??'9999-12-31',$b['expiry']??'9999-12-31')?:strcmp($a['received_at'],$b['received_at']));return $rows;}
 public static function csv(array $rows): string {$out="receipt_id,purchase_id,material,lot,counted,accepted,quarantined,rejected,state\r\n";foreach($rows as $r)foreach($r['lines'] as $line){$cells=[$r['id'],$r['purchase_id'],$line['material'],$line['lot'],$line['counted'],$line['accepted'],$line['quarantined'],$line['rejected'],$r['state']];$cells=array_map(static function($v){$v=(string)$v;if(preg_match('/^[=+\-@]/',$v))$v="'".$v;return '"'.str_replace('"','""',$v).'"';},$cells);$out.=implode(',',$cells)."\r\n";}return $out;}
 public static function privacyForUser(int $user): array {$out=[];foreach(self::receipts() as $r){$events=array_values(array_filter($r['history'],static fn($e)=>(int)$e['actor']===$user));$lines=[];foreach($r['lines'] as $line){$counts=array_values(array_filter($line['counts'],static fn($e)=>(int)$e['actor']===$user));if($counts||((int)($line['decision']['actor']??0)===$user)||(int)($line['decision']['released_by']??0)===$user)$lines[$line['material']]=['counts'=>$counts,'decision'=>$line['decision']];}if($events||$lines||(int)$r['actor']===$user||(int)($r['posted_actor']??0)===$user)$out[]=['receipt_id'=>$r['id'],'events'=>$events,'lines'=>$lines];}return $out;}
 public static function eraseUser(int $user): int {$all=self::receipts();$changed=0;foreach($all as &$r){foreach(['actor','posted_actor'] as $field)if((int)($r[$field]??0)===$user){$r[$field]=0;$changed++;}foreach($r['history'] as &$e){if((int)$e['actor']===$user){$e['actor']=0;$changed++;}if((int)($e['detail']['actor']??0)===$user){$e['detail']['actor']=0;$changed++;}if((int)($e['detail']['released_by']??0)===$user){$e['detail']['released_by']=0;$changed++;}}unset($e);foreach($r['lines'] as &$line){foreach($line['counts'] as &$c)if((int)$c['actor']===$user){$c['actor']=0;$changed++;}unset($c);foreach(['actor','released_by'] as $field)if((int)($line['decision'][$field]??0)===$user){$line['decision'][$field]=0;$changed++;}}unset($line);}unset($r);if($changed&&!update_option(self::RECEIPTS,$all,false))throw new \RuntimeException('ناشناس‌سازی ناموفق بود.');return $changed;}
 public static function purge(int $days,bool $dryRun=true): array {$cut=time()-max(30,$days)*86400;$ids=[];foreach(self::receipts() as $id=>$r)if($r['posted']&&strtotime($r['updated_at'])<$cut)$ids[]=$id;if(!$dryRun&&$ids){$all=self::receipts();foreach($ids as $id)unset($all[$id]);update_option(self::RECEIPTS,$all,false);}return ['dry_run'=>$dryRun,'ids'=>$ids,'count'=>count($ids)];}
 public static function ajax(): void {if(!check_ajax_referer(self::NONCE,'nonce',false))wp_send_json_error(['message'=>'درخواست نامعتبر است.'],403);$p=isset($_POST['payload'])&&is_string($_POST['payload'])?json_decode(wp_unslash($_POST['payload']),true):null;if(!is_array($p))wp_send_json_error(['message'=>'داده نامعتبر است.'],400);try{$intent=(string)($p['intent']??'');if($intent==='create')$r=self::create((string)$p['purchase_id'],(int)$p['purchase_revision'],(string)$p['token'],(array)$p['materials']);elseif($intent==='count')$r=self::countLine((string)$p['id'],(int)$p['revision'],(string)$p['material'],(int)$p['line_revision'],(array)($p['data']??[]));elseif($intent==='decide')$r=self::decide((string)$p['id'],(int)$p['revision'],(string)$p['material'],(int)$p['line_revision'],(array)($p['data']??[]));elseif($intent==='release')$r=self::release((string)$p['id'],(int)$p['revision'],(string)$p['material'],!empty($p['accept']),(string)($p['reason']??''));elseif($intent==='move')$r=self::move((string)$p['id'],(int)$p['revision'],(string)$p['lane']);elseif($intent==='post')$r=self::post((string)$p['id'],(int)$p['revision']);else throw new \InvalidArgumentException('عملیات رابط معتبر نیست.');wp_send_json_success(['receipt'=>$r]);}catch(\Throwable $e){wp_send_json_error(['message'=>$e->getMessage()],409);}}
 public static function download(): void {if(!self::canView()||!check_admin_referer(self::NONCE))wp_die('دسترسی مجاز نیست.');nocache_headers();header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename=mahex-supply-receipts.csv');echo "\xEF\xBB\xBF".self::csv(self::receipts());exit;}
 public static function printSheet(): void {if(!self::canView()||!check_admin_referer(self::NONCE))wp_die('دسترسی مجاز نیست.');$id=self::receiptId((string)($_GET['receipt']??''));$r=self::receipts()[$id]??null;if(!$r)wp_die('رسید وجود ندارد.');echo '<!doctype html><html dir="rtl"><meta charset="utf-8"><title>برگه دریافت</title><style>body{font-family:tahoma;max-width:900px;margin:auto}table{width:100%;border-collapse:collapse}td,th{border:1px solid #555;padding:8px}</style><h1>برگه دریافت آفلاین '.esc_html($r['code']).'</h1><p>این برگه تا ورود دستی در سامانه نهایی نیست.</p><table><tr><th>ماده</th><th>lot</th><th>شمارش</th><th>امضا</th></tr>';foreach($r['lines'] as $line)echo '<tr><td>'.esc_html($line['name']).'</td><td>'.esc_html($line['lot']).'</td><td></td><td></td></tr>';echo '</table></html>';exit;}
 public static function page(): void {if(!self::canView())wp_die('دسترسی مجاز نیست.');$rows=self::receipts();$counts=array_fill_keys(self::LANES,0);foreach($rows as $r)$counts[$r['state']]++;echo '<div class="wrap hmr-v37" dir="rtl"><h1>دریافت مرحله‌ای ملزومات بسته‌بندی</h1><p class="notice notice-info">همه شمارش‌ها و تصمیم‌ها ثبت دستی کاربر مجازند؛ هیچ API ماهکس، اتصال تأمین‌کننده، دستگاه یا تأیید بیرونی وجود ندارد.</p><nav><a class="button" href="'.esc_url(wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v37_receiving_csv'],admin_url('admin-post.php')),self::NONCE)).'">CSV کم‌داده</a></nav><div class="hmr-filter"><label>جست‌وجو <input type="search" data-hmr-search></label><label>وضعیت <select data-hmr-state><option value="">همه</option>';foreach(self::LANES as $lane)echo '<option value="'.$lane.'">'.$lane.'</option>';echo '</select></label></div><p data-hmr-live aria-live="polite"></p><div class="hmr-board">';foreach(self::LANES as $lane){echo '<section class="hmr-lane" data-lane="'.$lane.'"><h2>'.$lane.' <span>'.$counts[$lane].'</span></h2><div class="hmr-drop" data-drop="'.$lane.'">';foreach($rows as $r)if($r['state']===$lane){echo '<article class="hmr-card" draggable="true" tabindex="0" data-id="'.$r['id'].'" data-revision="'.$r['revision'].'" data-state="'.$lane.'" data-search="'.esc_attr($r['code'].' '.$r['purchase_id'].' '.$r['supplier'].' '.implode(' ',array_keys($r['lines']))).'"><b>'.esc_html($r['code']).'</b><small>'.esc_html($r['supplier']).'</small><label>انتقال با صفحه‌کلید <select data-hmr-move><option value="">انتخاب</option>';foreach(self::LANES as $to)echo '<option value="'.$to.'">'.$to.'</option>';echo '</select></label><a target="_blank" href="'.esc_url(wp_nonce_url(add_query_arg(['action'=>'hm_mahex_v37_receiving_print','receipt'=>$r['id']],admin_url('admin-post.php')),self::NONCE)).'">چاپ آفلاین</a></article>';}echo '</div></section>';}echo '</div></div>';}
}
