<?php

namespace HoseinMomeni\MahexWoo\V2;

final class Admin {
	private const PAGE='hm-mahex-v2';
	public static function register(): void {
		add_action('admin_menu',array(self::class,'menu'),30);
		add_action('admin_post_hm_mahex_v2_save_settings',array(self::class,'saveSettings'));
		add_action('admin_post_hm_mahex_v2_scan_problems',array(self::class,'scanProblems'));
		add_action('admin_post_hm_mahex_v2_resolve_problem',array(self::class,'resolveProblem'));
		add_action('admin_post_hm_mahex_v2_shift_start',array(self::class,'startShift'));
		add_action('admin_post_hm_mahex_v2_shift_end',array(self::class,'endShift'));
		add_action('admin_post_hm_mahex_v2_return_save',array(self::class,'saveReturn'));
		add_action('admin_post_hm_mahex_v2_metrics_rebuild',array(self::class,'rebuildMetrics'));
		add_action('admin_post_hm_mahex_v2_cache_flush',array(self::class,'flushCache'));
	}
	public static function menu(): void { add_submenu_page('hm-mahex','Mahex Shipping OS 2.0','Shipping OS 2.0','manage_woocommerce',self::PAGE,array(self::class,'render')); }
	public static function render(): void {
		if(!current_user_can('manage_woocommerce'))wp_die('Forbidden','',array('response'=>403));
		$tab=sanitize_key((string)($_GET['tab']??'overview'));$tabs=array('overview'=>'نمای کلی','problems'=>'مشکلات امروز','operators'=>'اپراتورها','returns'=>'برگشتی‌ها','insights'=>'Insightها','performance'=>'Performance','system'=>'سیستم');if(!isset($tabs[$tab]))$tab='overview';
		echo '<div class="wrap" dir="rtl"><h1>Mahex Shipping OS <small style="font-size:14px">2.x Core</small></h1><p>مرکز عملیات، Performance و تحلیل ارسال محلی ووکامرس.</p><nav class="nav-tab-wrapper">';foreach($tabs as $k=>$label)echo '<a class="nav-tab '.($tab===$k?'nav-tab-active':'').'" href="'.esc_url(admin_url('admin.php?page='.self::PAGE.'&tab='.$k)).'">'.esc_html($label).'</a>';echo '</nav><div style="margin-top:16px">';
		match($tab){'problems'=>self::problems(),'operators'=>self::operators(),'returns'=>self::returns(),'insights'=>self::insights(),'performance'=>self::performance(),'system'=>self::system(),default=>self::overview()}; echo '</div></div>';
	}
	private static function overview(): void {
		$metrics=DailyMetrics::range(30);$sum=array('orders'=>0,'shipping'=>0.0,'profit'=>0.0,'returned'=>0);foreach($metrics as $r){$sum['orders']+=(int)$r['orders_count'];$sum['shipping']+=(float)$r['shipping_revenue'];$sum['profit']+=(float)$r['profit'];$sum['returned']+=(int)$r['returned_count'];}$problems=ProblemCenter::open(100);$shift=ShiftManager::current();
		echo '<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px"><div class="card"><h3>سفارش ۳۰ روز</h3><strong style="font-size:26px">'.number_format_i18n($sum['orders']).'</strong></div><div class="card"><h3>درآمد ارسال</h3><strong>'.wp_kses_post(wc_price($sum['shipping'])).'</strong></div><div class="card"><h3>سود ارسال</h3><strong>'.wp_kses_post(wc_price($sum['profit'])).'</strong></div><div class="card"><h3>مشکلات باز</h3><strong style="font-size:26px">'.count($problems).'</strong></div></div>';
		echo '<div class="card" style="margin-top:16px"><h2>شیفت شما</h2>';if($shift){echo '<p>شیفت از '.esc_html((string)$shift['started_at']).' در ایستگاه '.esc_html((string)$shift['station']).' فعال است.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v2_shift_end">';wp_nonce_field('hm_mahex_v2_shift_end');submit_button('پایان شیفت','secondary','',false);echo '</form>';}else{echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v2_shift_start">';wp_nonce_field('hm_mahex_v2_shift_start');echo '<input name="station" placeholder="مثلاً میز بسته‌بندی ۱" value="default"> ';submit_button('شروع شیفت','primary','',false);echo '</form>';}echo '</div>';
		$ins=Insights::generate();if($ins){echo '<div class="card"><h2>پیشنهادهای امروز</h2><ul>';foreach(array_slice($ins,0,5) as $i)echo '<li><strong>'.esc_html($i['title']).':</strong> '.esc_html($i['message']).' <em>'.esc_html($i['action']).'</em></li>';echo '</ul></div>';}
	}
	private static function problems(): void {$rows=ProblemCenter::open(200);echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="margin-bottom:12px"><input type="hidden" name="action" value="hm_mahex_v2_scan_problems">';wp_nonce_field('hm_mahex_v2_scan_problems');submit_button('اسکن مجدد','secondary','',false);echo '</form><table class="widefat striped"><thead><tr><th>شدت</th><th>سفارش</th><th>مشکل</th><th>جزئیات</th><th></th></tr></thead><tbody>';foreach($rows as $r){echo '<tr><td>'.esc_html($r['severity']).'</td><td>'.((int)$r['order_id']?'#'.(int)$r['order_id']:'—').'</td><td>'.esc_html($r['title']).'</td><td>'.esc_html($r['details']).'</td><td><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v2_resolve_problem&id='.(int)$r['id']),'hm_mahex_v2_resolve_problem')).'">حل شد</a></td></tr>';}echo '</tbody></table>';}
	private static function operators(): void {$rows=ShiftManager::performance(30);echo '<table class="widefat striped"><thead><tr><th>اپراتور</th><th>شیفت</th><th>سفارش بسته‌شده</th><th>اقلام</th><th>خطا</th><th>دقیقه</th><th>سفارش/ساعت</th></tr></thead><tbody>';foreach($rows as $r){$u=get_userdata((int)$r['user_id']);$perHour=(float)$r['minutes']>0?((float)$r['packed_orders']/((float)$r['minutes']/60)):0;echo '<tr><td>'.esc_html($u?$u->display_name:'#'.$r['user_id']).'</td><td>'.(int)$r['shifts'].'</td><td>'.(int)$r['packed_orders'].'</td><td>'.(int)$r['packed_items'].'</td><td>'.(int)$r['errors'].'</td><td>'.(int)$r['minutes'].'</td><td>'.esc_html(number_format($perHour,1)).'</td></tr>';}echo '</tbody></table>';}
	private static function returns(): void {$rows=ReturnManager::recent(100);echo '<div class="card"><h2>ثبت پرونده برگشتی</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v2_return_save">';wp_nonce_field('hm_mahex_v2_return_save');echo '<input name="order_id" type="number" min="1" placeholder="شماره سفارش"> <input name="reason" placeholder="علت"> <input name="cost" type="number" min="0" placeholder="هزینه برگشت (ریال)"> <input name="note" placeholder="یادداشت"> ';submit_button('ثبت','primary','',false);echo '</form></div><table class="widefat striped"><thead><tr><th>ID</th><th>سفارش</th><th>وضعیت</th><th>علت</th><th>هزینه</th><th>زمان</th></tr></thead><tbody>';foreach($rows as $r)echo '<tr><td>'.(int)$r['id'].'</td><td>#'.(int)$r['order_id'].'</td><td>'.esc_html($r['status']).'</td><td>'.esc_html($r['reason']).'</td><td>'.wp_kses_post(wc_price(\HoseinMomeni\MahexWoo\Shipping\PricingSettings::to_store_currency((float)$r['return_cost']))).'</td><td>'.esc_html($r['updated_at']).'</td></tr>';echo '</tbody></table>';}
	private static function insights(): void {$rows=Insights::generate();echo '<div style="display:grid;gap:12px">';foreach($rows as $r)echo '<div class="card"><h3>'.esc_html($r['title']).'</h3><p>'.esc_html($r['message']).'</p><p><strong>اقدام پیشنهادی:</strong> '.esc_html($r['action']).'</p></div>';echo '</div>';}
	private static function performance(): void {$metrics=DailyMetrics::range(30);echo '<div class="card"><h2>متریک روزانه ۳۰ روز اخیر</h2><table class="widefat striped"><thead><tr><th>روز</th><th>سفارش</th><th>سود</th><th>برگشتی</th><th>بسته‌شده</th><th>خطای بسته‌بندی</th></tr></thead><tbody>';foreach(array_reverse($metrics) as $r)echo '<tr><td>'.esc_html($r['metric_date']).'</td><td>'.(int)$r['orders_count'].'</td><td>'.wp_kses_post(wc_price((float)$r['profit'])).'</td><td>'.(int)$r['returned_count'].'</td><td>'.(int)$r['packed_count'].'</td><td>'.(int)$r['packing_errors'].'</td></tr>';echo '</tbody></table></div><div class="card"><h2>Profiler</h2><pre style="direction:ltr;text-align:left">'.esc_html(wp_json_encode(\HoseinMomeni\MahexWoo\V1\Profiler::summary(),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre></div>';}
	private static function system(): void {$s=Config::all();$mods=ModuleRegistry::modules();echo '<div class="card"><h2>تنظیمات 2.0</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v2_save_settings">';wp_nonce_field('hm_mahex_v2_save_settings');foreach(array('rate_cache_enabled'=>'کش نرخ','problem_scan_enabled'=>'اسکن مشکلات','daily_metrics_enabled'=>'متریک روزانه','operator_shifts_enabled'=>'شیفت اپراتورها','insights_enabled'=>'Insightها') as $k=>$l)echo '<label style="display:block;margin:8px 0"><input type="checkbox" name="settings['.esc_attr($k).']" value="1" '.checked(!empty($s[$k]),true,false).'> '.esc_html($l).'</label>';echo '<label>TTL کش نرخ (ثانیه) <input type="number" name="settings[rate_cache_ttl]" value="'.(int)$s['rate_cache_ttl'].'"></label> <label>ساعت سفارش مانده <input type="number" name="settings[problem_stale_hours]" value="'.(int)$s['problem_stale_hours'].'"></label> <label>نگهداری Event (روز) <input type="number" name="settings[event_retention_days]" value="'.(int)$s['event_retention_days'].'"></label> <label>Batch فروشگاه بزرگ <input type="number" name="settings[large_store_batch]" value="'.(int)$s['large_store_batch'].'"></label>';submit_button('ذخیره');echo '</form></div><div class="card"><h2>ماژول‌ها</h2><ul>';foreach($mods as $m)echo '<li><strong>'.esc_html($m['label']).'</strong> — '.esc_html($m['description']).' <code>'.esc_html($m['status']).'</code></li>';echo '</ul><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v2_metrics_rebuild'),'hm_mahex_v2_metrics_rebuild')).'">بازسازی Metrics</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v2_cache_flush'),'hm_mahex_v2_cache_flush')).'">خالی‌کردن کش نرخ</a></p></div>';}
	public static function saveSettings(): void {self::guard('hm_mahex_v2_save_settings');update_option(Config::OPTION,Config::sanitize($_POST['settings']??array()),false);RateCache::invalidate();self::back('system');}
	public static function scanProblems(): void {self::guard('hm_mahex_v2_scan_problems');ProblemCenter::scan();self::back('problems');}
	public static function resolveProblem(): void {self::guard('hm_mahex_v2_resolve_problem');ProblemCenter::resolve(absint($_GET['id']??0));self::back('problems');}
	public static function startShift(): void {self::guard('hm_mahex_v2_shift_start');ShiftManager::start(sanitize_text_field((string)($_POST['station']??'default')));self::back('overview');}
	public static function endShift(): void {self::guard('hm_mahex_v2_shift_end');ShiftManager::end();self::back('overview');}
	public static function saveReturn(): void {self::guard('hm_mahex_v2_return_save');$id=absint($_POST['order_id']??0);if($id&&wc_get_order($id)){ReturnManager::ensure($id,sanitize_text_field((string)($_POST['reason']??'')),sanitize_textarea_field((string)($_POST['note']??'')));global $wpdb;$rid=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}hm_mahex_v2_returns WHERE order_id=%d ORDER BY id DESC LIMIT 1",$id));if($rid)ReturnManager::update($rid,'open',max(0,(float)($_POST['cost']??0)),sanitize_text_field((string)($_POST['reason']??'')),sanitize_textarea_field((string)($_POST['note']??'')));}self::back('returns');}
	public static function rebuildMetrics(): void {self::guard('hm_mahex_v2_metrics_rebuild');DailyMetrics::rebuildRecent(35);self::back('system');}
	public static function flushCache(): void {self::guard('hm_mahex_v2_cache_flush');RateCache::invalidate();self::back('system');}
	private static function guard(string $nonce): void {if(!current_user_can('manage_woocommerce'))wp_die('Forbidden','',array('response'=>403));check_admin_referer($nonce);}
	private static function back(string $tab): void {wp_safe_redirect(admin_url('admin.php?page='.self::PAGE.'&tab='.$tab));exit;}
}
