<?php

namespace HoseinMomeni\MahexWoo\V1;

use HoseinMomeni\MahexWoo\Admin\PackagingProfiles;
use HoseinMomeni\MahexWoo\Enterprise\Roles;
use HoseinMomeni\MahexWoo\Shipping\PricingSettings;

final class Admin {
	private const PAGE = 'hm-mahex-v1';

	public static function register(): void {
		add_action( 'admin_menu', array( self::class, 'menu' ), 20 );
		add_action( 'admin_enqueue_scripts', array( self::class, 'assets' ) );
		foreach ( array(
			'hm_mahex_v1_save_settings'=>'saveSettings','hm_mahex_v1_save_rules'=>'saveRules','hm_mahex_v1_repair'=>'repair','hm_mahex_v1_backup'=>'backup',
			'hm_mahex_v1_restore'=>'restore','hm_mahex_v1_export'=>'export','hm_mahex_v1_import'=>'import','hm_mahex_v1_partial_reset'=>'partialReset',
			'hm_mahex_v1_factory_reset'=>'factoryReset','hm_mahex_v1_inventory_adjust'=>'inventoryAdjust','hm_mahex_v1_qualification'=>'qualification',
			'hm_mahex_v1_save_dashboard'=>'saveDashboard','hm_mahex_v1_save_filter'=>'saveFilter','hm_mahex_v1_bulk_edit'=>'bulkEdit','hm_mahex_v1_reindex'=>'reindex',
			'hm_mahex_v1_print_enqueue'=>'printEnqueue','hm_mahex_v1_print_mark'=>'printMark',
		) as $hook => $method ) add_action( 'admin_post_' . $hook, array( self::class, $method ) );
	}

	public static function menu(): void {
		add_submenu_page( 'hm-mahex', 'Mahex Shipping Core', 'مرکز اصلی', 'read', self::PAGE, array( self::class, 'render' ) );
	}

	public static function assets( string $hook ): void {
		if ( false === strpos( $hook, self::PAGE ) ) return;
		wp_enqueue_style( 'hm-mahex-admin', plugins_url( 'assets/admin/dashboard.css', HM_MAHEX_FILE ), array(), HM_MAHEX_VERSION );
		wp_add_inline_style( 'hm-mahex-admin', '.hmv1-tabs{display:flex;gap:6px;flex-wrap:wrap;margin:14px 0}.hmv1-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.hmv1-card{background:#fff;border:1px solid #dbe3ec;border-radius:14px;padding:16px}.hmv1-card h2,.hmv1-card h3{margin-top:0}.hmv1-kpi b{display:block;font-size:25px;color:#082e63}.hmv1-two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.hmv1-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.hmv1-form label{display:flex;flex-direction:column;gap:5px}.hmv1-form input,.hmv1-form select,.hmv1-form textarea{width:100%;max-width:none}.hmv1-section{margin:14px 0}.hmv1-rule{background:#fff;border:1px solid #dbe3ec;border-radius:12px;padding:12px;margin:10px 0}.hmv1-code{direction:ltr;text-align:left;background:#f8fafc;padding:8px;border-radius:8px}.hmv1-ok{color:#067647}.hmv1-bad{color:#b42318}.hmv1-warn{color:#b54708}.hmv1-command{position:sticky;top:32px;z-index:10;background:#fff;border:1px solid #dbe3ec;padding:8px;border-radius:10px;margin:10px 0}.hmv1-command input{width:100%}@media(max-width:1000px){.hmv1-grid,.hmv1-form,.hmv1-two{grid-template-columns:1fr 1fr}}@media(max-width:700px){.hmv1-grid,.hmv1-form,.hmv1-two{grid-template-columns:1fr}}' );
		wp_add_inline_script( 'jquery-core', 'document.addEventListener("DOMContentLoaded",()=>{const q=document.querySelector("#hmv1-command");if(!q)return;q.addEventListener("keydown",e=>{if(e.key!=="Enter")return;const v=q.value.trim().toLowerCase();const map={"نرخ":"pricing","قیمت":"pricing","بسته":"packing","انبار":"inventory","چاپ":"labels","عملیات":"operations","گزارش":"reports","سلامت":"diagnostics","ابزار":"tools","rule":"rules"};for(const k in map){if(v.includes(k)){location.href="'.esc_js(admin_url('admin.php?page='.self::PAGE.'&tab=')).'"+map[k];break;}}});});' );
	}

	public static function render(): void {
		self::access(); $tab=sanitize_key((string)($_GET['tab']??'overview'));
		$tabs=array('overview'=>'داشبورد');
		if(Roles::canSettings()||Roles::canManage()){$tabs['pricing']='قیمت و سود';$tabs['rules']='Rule Builder';}
		if(Roles::canPack()||Roles::canManage())$tabs['packing']='بسته‌بندی';
		if(Roles::canInventory()||Roles::canManage())$tabs['inventory']='موجودی';
		if(Roles::canPack()||Roles::canManage())$tabs['operations']='عملیات';
		if(Roles::canPrint()||Roles::canManage())$tabs['labels']='چاپ';
		if(Roles::canReport()||Roles::canManage())$tabs['reports']='گزارش';
		if(Roles::canSettings()||Roles::canManage()){$tabs['diagnostics']='عیب‌یابی';$tabs['tools']='ابزارها';}
		if(!isset($tabs[$tab]))$tab='overview';
		echo '<div class="wrap hm-mahex" dir="rtl"><h1>Mahex Shipping for WooCommerce <small style="font-size:14px">2.x Core</small></h1><p>مرکز محلی مدیریت ارسال، نرخ، بسته‌بندی، انبار و عملیات؛ بدون اتصال API خارجی.</p>';self::notice();
		echo '<div class="hmv1-command"><input id="hmv1-command" placeholder="فرمان سریع: نرخ، بسته‌بندی، چاپ، گزارش، سلامت… (Enter)"></div><nav class="nav-tab-wrapper hmv1-tabs">';foreach($tabs as $k=>$label)echo '<a class="nav-tab '.($tab===$k?'nav-tab-active':'').'" href="'.esc_url(admin_url('admin.php?page='.self::PAGE.'&tab='.$k)).'">'.esc_html($label).'</a>';echo '</nav>';
		match($tab){'pricing'=>self::pricing(),'rules'=>self::rules(),'packing'=>self::packing(),'inventory'=>self::inventory(),'operations'=>self::operations(),'labels'=>self::labels(),'reports'=>self::reports(),'diagnostics'=>self::diagnostics(),'tools'=>self::tools(),default=>self::overview()};echo '</div>';
	}

	private static function overview(): void {
		$days=max(1,min(3650,absint($_GET['days']??30)));$summary=Reports::summary($days);$activity=ActivityLog::recent(15);$q=isset($_GET['s'])?sanitize_text_field(wp_unslash($_GET['s'])):'';$found=$q!==''?OrderIndex::search($q,50):array();$widgets=get_option(Config::DASHBOARD_WIDGETS,array('orders','profit','inventory','activity'));$widgets=is_array($widgets)?$widgets:array();
		echo '<form method="get" style="margin:10px 0"><input type="hidden" name="page" value="'.self::PAGE.'"><input type="hidden" name="tab" value="overview"><select name="days"><option value="1" '.selected($days,1,false).'>امروز</option><option value="7" '.selected($days,7,false).'>۷ روز</option><option value="30" '.selected($days,30,false).'>۳۰ روز</option><option value="90" '.selected($days,90,false).'>۹۰ روز</option><option value="365" '.selected($days,365,false).'>یک سال</option></select> <button class="button">اعمال بازه</button></form>';
		echo '<div class="hmv1-grid">';
		if(in_array('orders',$widgets,true))self::kpi('سفارش در بازه',$summary['orders']);
		if(in_array('profit',$widgets,true)){self::money('درآمد ارسال',$summary['shipping']);self::money('سود خالص',$summary['profit']);}
		if(in_array('packing',$widgets,true))self::money('درآمد بسته‌بندی',$summary['packaging']);
		if(in_array('returns',$widgets,true))self::money('هزینه برگشتی',$summary['return_cost']);
		if(in_array('inventory',$widgets,true)){ $stock=InventoryLedger::lowAndCritical(); self::kpi('هشدار موجودی بسته',count($stock['low'])+count($stock['critical'])); }
		echo '</div>';
		echo '<div class="hmv1-two hmv1-section"><section class="hmv1-card"><h2>جست‌وجوی سراسری</h2><form method="get"><input type="hidden" name="page" value="'.self::PAGE.'"><input type="hidden" name="tab" value="overview"><input type="hidden" name="days" value="'.$days.'"><input class="regular-text" name="s" value="'.esc_attr($q).'" placeholder="سفارش، مشتری، موبایل، رهگیری، شهر، کدپستی"> <button class="button">جست‌وجو</button></form>';
		if($found){echo '<table class="widefat striped"><thead><tr><th>سفارش</th><th>مشتری</th><th>شهر</th><th>رهگیری</th><th>سود</th></tr></thead><tbody>';foreach($found as $r)echo '<tr><td>#'.esc_html($r['order_number']).'</td><td>'.esc_html($r['customer_name']).'</td><td>'.esc_html($r['city']).'</td><td dir="ltr">'.esc_html($r['tracking']).'</td><td>'.wp_kses_post(wc_price((float)$r['profit'])).'</td></tr>';echo '</tbody></table>';}echo '</section>';
		echo '<section class="hmv1-card"><h2>ویجت‌های داشبورد</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_save_dashboard">';wp_nonce_field('hm_mahex_v1_save_dashboard');foreach(array('orders'=>'سفارش‌ها','profit'=>'سود','inventory'=>'موجودی بسته','activity'=>'فعالیت‌ها','returns'=>'برگشتی‌ها','packing'=>'بسته‌بندی') as $k=>$label)echo '<label style="display:block;margin:7px"><input type="checkbox" name="widgets[]" value="'.esc_attr($k).'" '.checked(in_array($k,$widgets,true),true,false).'> '.esc_html($label).'</label>';submit_button('ذخیره چینش','secondary','',false);echo '</form><hr><h3>ذخیره فیلتر</h3><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_save_filter">';wp_nonce_field('hm_mahex_v1_save_filter');echo '<input name="name" placeholder="نام فیلتر"><input name="query" value="'.esc_attr($q).'" placeholder="عبارت جست‌وجو"> <button class="button">ذخیره</button></form>';self::savedFilters();echo '</section></div>';
		if(in_array('activity',$widgets,true)){echo '<section class="hmv1-card hmv1-section"><h2>آخرین فعالیت‌ها</h2><table class="widefat striped"><thead><tr><th>زمان</th><th>رویداد</th><th>سفارش</th><th>توضیح</th></tr></thead><tbody>';foreach($activity as $r)echo '<tr><td>'.esc_html((string)$r['created_at']).'</td><td>'.esc_html((string)$r['event_type']).'</td><td>'.((int)$r['order_id']?'#'.(int)$r['order_id']:'—').'</td><td>'.esc_html((string)$r['message']).'</td></tr>';echo '</tbody></table></section>';}
	}

	private static function pricing(): void { $s=Config::all();echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_save_settings">';wp_nonce_field('hm_mahex_v1_save_settings');echo '<section class="hmv1-card"><h2>کنترل سود و قیمت‌گذاری</h2><div class="hmv1-form">';self::num('min_shipping_margin_irr','حداقل سود ارسال (ریال)',$s);self::num('margin_percent','سود درصدی',$s,'0.01');self::num('margin_fixed_irr','سود ثابت (ریال)',$s);self::num('max_customer_shipping_irr','سقف کرایه مشتری (ریال)',$s);self::num('subsidy_percent','یارانه فروشگاه (%)',$s,'0.01');self::num('customer_share_percent','سهم مشتری از کرایه (%)',$s,'0.01');self::num('rounding_step_irr','پله گردکردن (ریال)',$s);self::num('psychological_ending_irr','پایان قیمت روانی (ریال)',$s);echo '</div>';self::area('margin_tiers','سود پلکانی: حداقل|حداکثر|درصد|مبلغ ثابت',$s,'0|1000000|5|0');echo '<p>محاسبه با اعداد صحیح انجام می‌شود تا خطای اعشاری باعث یک پله اضافه نشود.</p></section><section class="hmv1-card hmv1-section"><h2>Feature Flags و پایداری</h2>';foreach(array('safe_mode'=>'Safe Mode','large_store_mode'=>'Large Store Mode','profiler_enabled'=>'Performance Profiler','sensitive_lock'=>'قفل تنظیمات حساس','feature_pricing'=>'موتور قیمت','feature_packing'=>'موتور بسته‌بندی','feature_inventory'=>'موجودی','feature_operations'=>'عملیات انبار','feature_customer'=>'تجربه مشتری','feature_reporting'=>'گزارش‌ها') as $k=>$l)self::check($k,$l,$s);echo '</section>';submit_button('ذخیره تنظیمات نسخه 1');echo '</form>'; $sim=isset($_GET['sim_base'])?max(0,(float)$_GET['sim_base']):null;echo '<section class="hmv1-card hmv1-section"><h2>Margin Simulator</h2><form method="get"><input type="hidden" name="page" value="'.self::PAGE.'"><input type="hidden" name="tab" value="pricing"><input type="number" min="0" name="sim_base" placeholder="کرایه پایه (ریال)" value="'.esc_attr(null===$sim?'':(string)$sim).'"> <button class="button">محاسبه</button></form>';if(null!==$sim){$r=MarginEngine::apply($sim);echo '<p>کرایه پایه: <b>'.number_format_i18n((int)$sim).'</b> ریال → مبلغ مشتری: <b>'.number_format_i18n((int)$r['freight']).'</b> ریال · یارانه/سهم فروشگاه: <b>'.number_format_i18n((int)$r['subsidy']).'</b> ریال</p><code class="hmv1-code">'.esc_html(implode(' | ',$r['breakdown'])).'</code>';}echo '</section>'; }

	private static function rules(): void { $rows=RuleEngine::rules();for($i=count($rows);$i<min(5,count($rows)+2);$i++)$rows[]=array('id'=>'','name'=>'','active'=>true,'priority'=>100+$i,'logic'=>'AND','stop'=>false,'mode'=>'surcharge','amount'=>0);echo '<p>شرط‌های خالی نادیده گرفته می‌شوند. در حالت AND همه شرط‌های تکمیل‌شده باید برقرار باشند؛ در OR یکی کافی است.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_save_rules">';wp_nonce_field('hm_mahex_v1_save_rules');foreach($rows as $i=>$r){echo '<article class="hmv1-rule"><input type="hidden" name="rules['.$i.'][id]" value="'.esc_attr((string)($r['id']??'')).'"><div class="hmv1-form">';self::rawText("rules[$i][name]",'نام قانون',(string)($r['name']??''));self::rawNum("rules[$i][priority]",'اولویت',(string)($r['priority']??100));self::rawSelect("rules[$i][logic]",'منطق',(string)($r['logic']??'AND'),array('AND'=>'AND','OR'=>'OR'));self::rawSelect("rules[$i][mode]",'عمل',(string)($r['mode']??'surcharge'),array('surcharge'=>'افزایش ثابت','fixed'=>'نرخ ثابت','percent'=>'افزایش درصدی','discount'=>'تخفیف درصدی','free'=>'رایگان'));self::rawNum("rules[$i][amount]",'مقدار',(string)($r['amount']??0),'0.01');self::rawText("rules[$i][province]",'استان',(string)($r['province']??''));self::rawText("rules[$i][city]",'شهر',(string)($r['city']??''));self::rawNum("rules[$i][min_weight_g]",'حداقل وزن g',(string)($r['min_weight_g']??0));self::rawNum("rules[$i][max_weight_g]",'حداکثر وزن g',(string)($r['max_weight_g']??0));self::rawNum("rules[$i][min_qty]",'حداقل تعداد',(string)($r['min_qty']??0));self::rawNum("rules[$i][max_qty]",'حداکثر تعداد',(string)($r['max_qty']??0));self::rawNum("rules[$i][min_cart_irr]",'حداقل سبد ریال',(string)($r['min_cart_irr']??0));self::rawNum("rules[$i][max_cart_irr]",'حداکثر سبد ریال',(string)($r['max_cart_irr']??0));self::rawText("rules[$i][categories]",'دسته‌ها (slug)',implode(',',(array)($r['categories']??array())));self::rawText("rules[$i][shipping_classes]",'Shipping Class',implode(',',(array)($r['shipping_classes']??array())));self::rawText("rules[$i][brands]",'برندها (slug)',implode(',',(array)($r['brands']??array())));echo '</div><label><input type="checkbox" name="rules['.$i.'][active]" value="1" '.checked(!empty($r['active']),true,false).'> فعال</label> &nbsp; <label><input type="checkbox" name="rules['.$i.'][stop]" value="1" '.checked(!empty($r['stop']),true,false).'> پس از اجرا ادامه Ruleها متوقف شود</label></article>';}submit_button('ذخیره Ruleها');echo '</form>'; }

	private static function packing(): void { $s=Config::all();$orderId=absint($_GET['order_id']??0);$plan=null;if($orderId){$o=wc_get_order($orderId);if($o)$plan=PackingEngine::plan(self::packageFromOrder($o));}echo '<div class="hmv1-two"><section class="hmv1-card"><h2>تنظیمات موتور بسته‌بندی</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_save_settings">';wp_nonce_field('hm_mahex_v1_save_settings');echo '<div class="hmv1-form">';self::num('packing_waste_percent','فضای خالی/ضایعات (%)',$s,'0.1');self::num('packing_max_units','حداکثر واحد در یک محاسبه',$s);self::num('critical_stock_threshold','آستانه موجودی بحرانی',$s);echo '</div>';self::check('packing_verification','الزام تأیید بسته‌بندی',$s);self::check('barcode_verification','تأیید با بارکد/SKU',$s);self::check('auto_ready_to_ship','آماده‌ارسال خودکار در صورت عدم الزام تأیید',$s);self::area('order_columns','ستون‌های عملیات (order,customer,status,city,total,quick)',$s,'order,customer,status,city,total,quick');submit_button('ذخیره','secondary','',false);echo '</form><p><a class="button" href="'.esc_url(admin_url('admin.php?page=hm-mahex-packaging-profiles')).'">مدیریت پروفایل‌های بسته‌بندی</a></p></section><section class="hmv1-card"><h2>پیش‌نمایش بسته‌بندی سفارش</h2><form method="get"><input type="hidden" name="page" value="'.self::PAGE.'"><input type="hidden" name="tab" value="packing"><input type="number" name="order_id" min="1" placeholder="Order ID" value="'.($orderId?:'').'"> <button class="button">محاسبه</button></form>';if(is_array($plan)){echo '<p><strong>'.(int)$plan['package_count'].'</strong> بسته · هزینه '.number_format_i18n((int)$plan['cost_irr']).' ریال · وزن قابل محاسبه '.number_format_i18n((int)$plan['chargeable_weight_g']).' گرم</p><table class="widefat striped"><thead><tr><th>بسته</th><th>پروفایل</th><th>اقلام</th><th>وزن</th><th>حجمی</th></tr></thead><tbody>';foreach($plan['packages'] as $i=>$b)echo '<tr><td>'.($i+1).'</td><td>'.esc_html((string)$b['profile_name']).'</td><td>'.count((array)$b['items']).'</td><td>'.number_format_i18n((int)$b['actual_weight_g']).'g</td><td>'.number_format_i18n((int)$b['volumetric_weight_g']).'g</td></tr>';echo '</tbody></table>';if($plan['warnings'])echo '<p class="hmv1-warn">'.esc_html(implode(' | ',$plan['warnings'])).'</p>';}echo '</section></div>'; }

	private static function inventory(): void { $profiles=PackagingProfiles::all();$status=InventoryLedger::lowAndCritical();echo '<div class="hmv1-grid">';self::kpi('نوع بسته',count($profiles));self::kpi('هشدار کمبود',count($status['low']));self::kpi('بحرانی',count($status['critical']));echo '<div class="hmv1-card hmv1-kpi"><b>'.number_format_i18n(InventoryLedger::valuation()).'</b><span>ارزش موجودی (ریال)</span></div></div><section class="hmv1-card hmv1-section"><h2>شمارش/اصلاح موجودی</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_inventory_adjust">';wp_nonce_field('hm_mahex_v1_inventory_adjust');echo '<select name="profile_id">';foreach($profiles as $id=>$p)echo '<option value="'.esc_attr($id).'">'.esc_html((string)($p['name']??$id)).' — '.(int)($p['stock']??0).'</option>';echo '</select> <input type="number" min="0" name="new_stock" required placeholder="موجودی واقعی"> <input name="reason" required placeholder="دلیل اصلاح"> <button class="button button-primary">ثبت Adjustment</button></form></section><section class="hmv1-card hmv1-section"><h2>دفتر موجودی</h2><table class="widefat striped"><thead><tr><th>زمان</th><th>بسته</th><th>جهت</th><th>تعداد</th><th>مانده</th><th>سفارش</th><th>دلیل</th></tr></thead><tbody>';foreach(InventoryLedger::recent(100) as $r)echo '<tr><td>'.esc_html($r['created_at']).'</td><td>'.esc_html((string)($profiles[$r['profile_id']]['name']??$r['profile_id'])).'</td><td>'.esc_html($r['direction']).'</td><td>'.(int)$r['quantity'].'</td><td>'.(int)$r['balance_after'].'</td><td>'.((int)$r['order_id']?'#'.(int)$r['order_id']:'—').'</td><td>'.esc_html($r['reason']).'</td></tr>';echo '</tbody></table></section>'; }

	private static function operations(): void {
		$orders = wc_get_orders( array( 'limit'=>80, 'status'=>array('wc-processing','wc-on-hold'), 'orderby'=>'date', 'order'=>'DESC' ) );
		$result = get_transient( 'hm_mahex_pack_result_' . get_current_user_id() );
		if ( is_array( $result ) ) {
			delete_transient( 'hm_mahex_pack_result_' . get_current_user_id() );
			echo '<div class="notice '.(!empty($result['ok'])?'notice-success':'notice-error').' inline"><p>'.(!empty($result['ok'])?'بسته‌بندی تأیید شد.':'مغایرت: کمبود '.esc_html(wp_json_encode($result['missing'],JSON_UNESCAPED_UNICODE)).' | اضافه '.esc_html(wp_json_encode($result['wrong'],JSON_UNESCAPED_UNICODE))).'</p></div>';
		}
		$allowed = array('order','customer','status','city','total','quick');
		$columns = array_values( array_intersect( explode( ',', (string) Config::get( 'order_columns', 'order,customer,status,city,total,quick' ) ), $allowed ) );
		if ( ! $columns ) $columns = $allowed;
		echo '<section class="hmv1-card"><h2>Batch Picking / Packing</h2><p class="description">ستون‌های این جدول از تنظیمات موتور بسته‌بندی قابل انتخاب‌اند.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" target="_blank"><table class="widefat striped"><thead><tr><th></th>';
		$labels=array('order'=>'سفارش','customer'=>'مشتری','status'=>'وضعیت بسته','city'=>'شهر','total'=>'مبلغ','quick'=>'Quick View');foreach($columns as $c)echo '<th>'.esc_html($labels[$c]).'</th>';echo '</tr></thead><tbody>';
		foreach ( $orders as $o ) {
			$expected=Operations::expected($o);echo '<tr><td><input type="checkbox" name="order_ids[]" value="'.$o->get_id().'"></td>';
			foreach($columns as $c){switch($c){case 'order':echo '<td>#'.esc_html($o->get_order_number()).'</td>';break;case 'customer':echo '<td>'.esc_html($o->get_formatted_billing_full_name()).'</td>';break;case 'status':echo '<td>'.esc_html((string)$o->get_meta('_hm_mahex_packing_status',true)?:'در انتظار').'</td>';break;case 'city':echo '<td>'.esc_html($o->get_shipping_city()?:$o->get_billing_city()).'</td>';break;case 'total':echo '<td>'.wp_kses_post($o->get_formatted_order_total()).'</td>';break;case 'quick':echo '<td><details><summary>اقلام</summary>';foreach($expected as $r)echo esc_html($r['name']).' × '.(int)$r['qty'].' ['.esc_html($r['zone']).']<br>';echo '</details></td>';break;}}echo '</tr>';
		}
		echo '</tbody></table>';
		wp_nonce_field('hm_mahex_v1_print_pick');echo '<button class="button" name="action" value="hm_mahex_v1_print_pick">چاپ Pick List زون‌بندی‌شده</button> ';
		wp_nonce_field('hm_mahex_v1_print_packing','_wpnonce_pack');echo '<button class="button" onclick="this.form._wpnonce.value=this.form._wpnonce_pack.value" name="action" value="hm_mahex_v1_print_packing">چاپ Packing List</button></form></section>';

		echo '<section class="hmv1-card hmv1-section"><h2>ویرایش گروهی سفارش‌ها</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_bulk_edit">';wp_nonce_field('hm_mahex_v1_bulk_edit');echo '<input class="regular-text" name="order_ids_text" placeholder="شناسه‌ها: 1201,1202,1203"> <select name="packing_status"><option value="pending">در انتظار</option><option value="packed">بسته‌بندی‌شده</option><option value="ready_to_ship">آماده ارسال</option></select> <button class="button">اعمال</button></form></section>';

		$orderId=absint($_GET['order_id']??0);echo '<section class="hmv1-card hmv1-section"><h2>Packing Station / اسکن و تأیید</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_verify_packing">';wp_nonce_field('hm_mahex_v1_verify_packing');echo '<input type="number" name="order_id" min="1" required value="'.($orderId?:'').'" placeholder="Order ID"><textarea name="scanned" rows="5" class="large-text code" placeholder="SKU یا Product ID هر کالا؛ هر اسکن در یک خط"></textarea><button class="button button-primary">تأیید بسته‌بندی</button></form></section>';
		echo '<section class="hmv1-card hmv1-section"><h2>صف Ready to Ship</h2><table class="widefat striped"><thead><tr><th>سفارش</th><th>مشتری</th><th>عملیات</th></tr></thead><tbody>';foreach(Operations::readyOrders() as $o)echo '<tr><td>#'.esc_html($o->get_order_number()).'</td><td>'.esc_html($o->get_formatted_billing_full_name()).'</td><td><a class="button" href="'.esc_url($o->get_edit_order_url()).'">بازکردن سفارش</a></td></tr>';echo '</tbody></table></section>';
	}

	private static function labels(): void {
		$s=Config::all();$all=array('recipient'=>'گیرنده','destination'=>'مقصد','address'=>'نشانی','phone'=>'موبایل','barcode'=>'بارکد','items'=>'اقلام','weight'=>'وزن','eta'=>'ETA','order'=>'شماره بارنامه');$current=array_values(array_intersect(explode(',',(string)($s['label_fields']??'')),array_keys($all)));foreach(array_keys($all) as $k)if(!in_array($k,$current,true))$current[]=$k;
		echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_save_settings">';wp_nonce_field('hm_mahex_v1_save_settings');echo '<section class="hmv1-card"><h2>Label Builder</h2><div class="hmv1-form">';self::select('label_font','فونت',$s,array('Tahoma'=>'Tahoma','Arial'=>'Arial','Vazirmatn'=>'Vazirmatn','IRANSansX'=>'IRANSansX','sans-serif'=>'Sans Serif'));self::text('label_watermark','نشانی واترمارک/لوگو',$s);self::num('a4_columns','تعداد ستون A4',$s);echo '</div><h3>ترتیب فیلدها — Drag & Drop</h3><input type="hidden" id="hmv1-label-fields-input" name="settings[label_fields]" value="'.esc_attr((string)$s['label_fields']).'"><ul id="hmv1-label-fields" style="display:flex;gap:8px;flex-wrap:wrap">';foreach($current as $k)echo '<li draggable="true" data-key="'.esc_attr($k).'" style="cursor:move;background:#f6f7f7;border:1px solid #c3c4c7;padding:8px 12px;border-radius:7px">☰ '.esc_html($all[$k]).'</li>';echo '</ul>';self::check('label_conditional_cod','نمایش مبلغ فقط برای COD',$s);self::check('allow_customer_label','اجازه چاپ لیبل به مشتری از حساب کاربری',$s);self::check('print_queue_enabled','فعال بودن Print Queue',$s);submit_button('ذخیره تنظیمات چاپ');echo '</section></form>';
		echo '<section class="hmv1-card hmv1-section"><h2>صف چاپ</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="display:flex;gap:8px;align-items:end;flex-wrap:wrap"><input type="hidden" name="action" value="hm_mahex_v1_print_enqueue">';wp_nonce_field('hm_mahex_v1_print_enqueue');echo '<label>شماره سفارش<br><input type="number" name="order_id" min="1" required></label><label>سند<br><select name="document_type"><option value="label">لیبل</option><option value="waybill">بارنامه</option><option value="combined">ترکیبی</option><option value="pick">Pick List</option><option value="packing">Packing List</option></select></label><label>کپی<br><input type="number" name="copies" min="1" max="100" value="1"></label><button class="button button-primary">افزودن به صف</button></form><table class="widefat striped" style="margin-top:12px"><thead><tr><th>ID</th><th>سفارش</th><th>نوع</th><th>کپی</th><th>زمان</th><th>عملیات</th></tr></thead><tbody>';foreach(PrintManager::pending(100) as $r){$print='';if(in_array($r['document_type'],array('label','waybill','combined'),true))$print=wp_nonce_url(add_query_arg(array('action'=>'hm_mahex_print_waybill','order_id'=>(int)$r['order_id'],'document'=>$r['document_type']),admin_url('admin-post.php')),'hm_mahex_print_waybill:'.(int)$r['order_id']);$mark=wp_nonce_url(add_query_arg(array('action'=>'hm_mahex_v1_print_mark','id'=>(int)$r['id']),admin_url('admin-post.php')),'hm_mahex_v1_print_mark:'.(int)$r['id']);echo '<tr><td>'.(int)$r['id'].'</td><td>#'.(int)$r['order_id'].'</td><td>'.esc_html($r['document_type']).'</td><td>'.(int)$r['copies'].'</td><td>'.esc_html($r['created_at']).'</td><td>'.($print?'<a target="_blank" class="button button-small" href="'.esc_url($print).'">چاپ</a> ':'').'<a class="button button-small" href="'.esc_url($mark).'">انجام شد</a></td></tr>';}echo '</tbody></table></section>';
		echo '<script>(function(){const list=document.getElementById("hmv1-label-fields"),input=document.getElementById("hmv1-label-fields-input");if(!list||!input)return;let drag=null;const sync=()=>input.value=[...list.children].map(x=>x.dataset.key).join(",");list.addEventListener("dragstart",e=>{drag=e.target.closest("li")});list.addEventListener("dragover",e=>{e.preventDefault();const t=e.target.closest("li");if(drag&&t&&t!==drag){const r=t.getBoundingClientRect();list.insertBefore(drag,e.clientX<r.left+r.width/2?t:t.nextSibling);sync();}});list.addEventListener("drop",e=>{e.preventDefault();sync()});sync();})();</script>';
	}

	private static function reports(): void { $days=max(1,min(3650,absint($_GET['days']??30)));$s=Reports::summary($days);echo '<form method="get"><input type="hidden" name="page" value="'.self::PAGE.'"><input type="hidden" name="tab" value="reports"><select name="days"><option value="7" '.selected($days,7,false).'>۷ روز</option><option value="30" '.selected($days,30,false).'>۳۰ روز</option><option value="90" '.selected($days,90,false).'>۹۰ روز</option><option value="365" '.selected($days,365,false).'>یک سال</option></select> <button class="button">اعمال</button></form><div class="hmv1-grid hmv1-section">';self::kpi('سفارش',$s['orders']);self::money('درآمد کل ارسال',$s['shipping']+$s['packaging']);self::money('هزینه حمل',$s['carrier']);self::money('سود',$s['profit']);self::money('هزینه برگشتی',$s['return_cost']);echo '</div><div class="hmv1-two"><section class="hmv1-card"><h2>سودآوری شهرها</h2><table class="widefat striped"><thead><tr><th>شهر</th><th>سفارش</th><th>درآمد</th><th>سود</th></tr></thead><tbody>';foreach(Reports::cities($days) as $r)echo '<tr><td>'.esc_html($r['province'].' / '.$r['city']).'</td><td>'.(int)$r['orders'].'</td><td>'.wp_kses_post(wc_price((float)$r['revenue'])).'</td><td>'.wp_kses_post(wc_price((float)$r['profit'])).'</td></tr>';echo '</tbody></table></section><section class="hmv1-card"><h2>سودآوری مشتریان</h2><table class="widefat striped"><thead><tr><th>مشتری</th><th>سفارش</th><th>درآمد</th><th>سود</th></tr></thead><tbody>';foreach(Reports::customers($days) as $r)echo '<tr><td>'.esc_html($r['customer_name']).'</td><td>'.(int)$r['orders'].'</td><td>'.wp_kses_post(wc_price((float)$r['revenue'])).'</td><td>'.wp_kses_post(wc_price((float)$r['profit'])).'</td></tr>';echo '</tbody></table></section></div>'; }

	private static function diagnostics(): void { $issues=Diagnostics::scan();$qual=get_transient('hm_mahex_v1_qualification_'.get_current_user_id());$setup=SetupVerifier::checks();echo '<section class="hmv1-card"><h2>Setup Verification</h2><table class="widefat striped"><thead><tr><th>بخش</th><th>وضعیت</th><th>جزئیات</th></tr></thead><tbody>';foreach($setup as $c)echo '<tr><td>'.esc_html($c['label']).'</td><td class="'.(!empty($c['ok'])?'hmv1-ok':'hmv1-bad').'">'.(!empty($c['ok'])?'آماده':'نیاز به تنظیم').'</td><td>'.esc_html($c['detail']).'</td></tr>';echo '</tbody></table></section>';echo '<section class="hmv1-card"><h2>Database Integrity / Repair Center</h2><table class="widefat striped"><thead><tr><th>شدت</th><th>مشکل</th><th>عملیات</th></tr></thead><tbody>';foreach($issues as $i){$cls='success'===$i['severity']?'hmv1-ok':('critical'===$i['severity']?'hmv1-bad':'hmv1-warn');echo '<tr><td class="'.$cls.'">'.esc_html($i['severity']).'</td><td>'.esc_html($i['message']).'</td><td>';if($i['repairable'])echo '<a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v1_repair&code='.rawurlencode($i['code'])),'hm_mahex_v1_repair_'.$i['code'])).'">تعمیر خودکار</a>';echo '</td></tr>';}echo '</tbody></table><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v1_reindex'),'hm_mahex_v1_reindex')).'">بازسازی Order Index</a></p></section><section class="hmv1-card hmv1-section"><h2>Performance Profiler</h2><table class="widefat striped"><thead><tr><th>بخش</th><th>تعداد</th><th>میانگین ms</th><th>P95</th><th>Max</th></tr></thead><tbody>';foreach(Profiler::summary() as $k=>$r)echo '<tr><td>'.esc_html($k).'</td><td>'.(int)$r['count'].'</td><td>'.esc_html((string)$r['avg']).'</td><td>'.esc_html((string)$r['p95']).'</td><td>'.esc_html((string)$r['max']).'</td></tr>';echo '</tbody></table></section><section class="hmv1-card hmv1-section"><h2>Release Qualification Suite</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_qualification">';wp_nonce_field('hm_mahex_v1_qualification');echo '<button class="button button-primary">اجرای تست‌های نسخه</button></form>';if(is_array($qual)){echo '<p><strong>'.(int)$qual['passed'].' / '.(int)$qual['total'].'</strong> تست Pass</p><ul>';foreach($qual['tests'] as $t)echo '<li class="'.(!empty($t['ok'])?'hmv1-ok':'hmv1-bad').'">'.(!empty($t['ok'])?'✓':'✗').' '.esc_html($t['name']).' '.esc_html($t['detail']??'').'</li>';echo '</ul>';}echo '</section>'; }

	private static function tools(): void { $backups=BackupManager::all();echo '<div class="hmv1-two"><section class="hmv1-card"><h2>Backup / Restore</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_backup">';wp_nonce_field('hm_mahex_v1_backup');echo '<button class="button button-primary">ساخت Backup</button></form><table class="widefat striped"><tbody>';foreach($backups as $b)echo '<tr><td>'.esc_html($b['created_at']??'').'</td><td>'.esc_html($b['reason']??'').'</td><td><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v1_restore&id='.rawurlencode((string)$b['id'])),'hm_mahex_v1_restore_'.$b['id'])).'">Restore</a></td></tr>';echo '</tbody></table></section><section class="hmv1-card"><h2>Export / Import</h2><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_v1_export'),'hm_mahex_v1_export')).'">دانلود تنظیمات JSON</a></p><form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_import">';wp_nonce_field('hm_mahex_v1_import');echo '<input type="file" name="file" accept=".json,application/json" required> <button class="button">Import</button></form></section></div><section class="hmv1-card hmv1-section"><h2>Reset</h2><form style="display:inline-block" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_v1_partial_reset">';wp_nonce_field('hm_mahex_v1_partial_reset');echo '<select name="section"><option value="pricing">قیمت و Ruleها</option><option value="printing">چاپ</option><option value="customer">تجربه مشتری</option><option value="profiler">داده Profiler</option></select> <button class="button">Reset بخش</button></form>';if(current_user_can('manage_options')){echo '<hr><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(\'تمام تنظیمات نسخه 1 پاک شود؟\')"><input type="hidden" name="action" value="hm_mahex_v1_factory_reset">';wp_nonce_field('hm_mahex_v1_factory_reset');echo '<input name="confirm" placeholder="DELETE V1" required> <button class="button button-link-delete">Factory Reset</button></form>';}echo '</section>'; }

	public static function saveSettings(): void { if(!(Roles::canSettings()||Roles::canManage()||Roles::canPack()||Roles::canPrint()))wp_die('Forbidden','',array('response'=>403));check_admin_referer('hm_mahex_v1_save_settings');$input=isset($_POST['settings'])&&is_array($_POST['settings'])?wp_unslash($_POST['settings']):array();if(!(Roles::canSettings()||Roles::canManage())){$allowed=Roles::canPrint()?array('label_font','label_watermark','label_fields','label_conditional_cod','print_queue_enabled'):array();if(Roles::canPack())$allowed=array_merge($allowed,array('packing_waste_percent','packing_max_units','critical_stock_threshold','packing_verification','barcode_verification','auto_ready_to_ship','order_columns'));$input=array_intersect_key($input,array_flip($allowed));}$current=Config::all();update_option(Config::OPTION,Config::sanitize(array_replace($current,$input)),false);ActivityLog::write('settings.saved','تنظیمات نسخه 1 ذخیره شد.');self::back(); }
	public static function saveRules(): void { self::guard('hm_mahex_v1_save_rules');$rows=isset($_POST['rules'])&&is_array($_POST['rules'])?wp_unslash($_POST['rules']):array();update_option(Config::RULES,RuleEngine::sanitizeRules($rows),false);ActivityLog::write('rules.saved','قوانین نرخ نسخه 1 ذخیره شدند.',0,array('count'=>count($rows)));self::back(); }
	public static function repair(): void { $code=isset($_GET['code'])?sanitize_text_field(wp_unslash($_GET['code'])):'';self::guard('hm_mahex_v1_repair_'.$code,true);Diagnostics::repair($code);self::back(); }
	public static function backup(): void { self::guard('hm_mahex_v1_backup');BackupManager::snapshot('manual');self::back(); }
	public static function restore(): void { self::sensitive();$id=isset($_GET['id'])?sanitize_text_field(wp_unslash($_GET['id'])):'';self::guard('hm_mahex_v1_restore_'.$id,true);BackupManager::restore($id);self::back(); }
	public static function export(): void { self::guard('hm_mahex_v1_export',true);nocache_headers();header('Content-Type:application/json;charset=utf-8');header('Content-Disposition:attachment;filename="mahex-v1-settings-'.gmdate('Ymd-His').'.json"');echo wp_json_encode(BackupManager::export(),JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);exit; }
	public static function import(): void { self::sensitive();self::guard('hm_mahex_v1_import');if(empty($_FILES['file']['tmp_name'])||!is_uploaded_file($_FILES['file']['tmp_name'])||(int)($_FILES['file']['size']??0)>1048576)self::redirect('tools','invalid');$d=json_decode((string)file_get_contents($_FILES['file']['tmp_name']),true);if(!is_array($d)||($d['format']??'')!=='hm-mahex-v1')self::redirect('tools','invalid');BackupManager::snapshot('pre_import');if(isset($d['settings']))update_option(Config::OPTION,Config::sanitize($d['settings']),false);if(isset($d['rules']))update_option(Config::RULES,RuleEngine::sanitizeRules($d['rules']),false);if(isset($d['packaging_profiles'])&&is_array($d['packaging_profiles']))update_option(PackagingProfiles::OPTION_NAME,$d['packaging_profiles'],false);if(isset($d['warehouses'])&&is_array($d['warehouses']))update_option('hm_mahex_warehouses',$d['warehouses'],false);self::redirect('tools','imported'); }
	public static function partialReset(): void { self::guard('hm_mahex_v1_partial_reset');$section=sanitize_key((string)($_POST['section']??''));$s=Config::all();$d=Config::defaults();$keys=match($section){'pricing'=>array('min_shipping_margin_irr','margin_percent','margin_fixed_irr','margin_tiers','max_customer_shipping_irr','subsidy_percent','customer_share_percent','rounding_step_irr','psychological_ending_irr'),'printing'=>array('label_font','label_watermark','label_fields','label_conditional_cod','a4_columns','allow_customer_label','print_queue_enabled'),'customer'=>array('account_shipping_card','delivery_preferences','preferred_time','address_book','reorder_shipping'),default=>array()};foreach($keys as $k)$s[$k]=$d[$k];if('pricing'===$section)update_option(Config::RULES,array(),false);if('profiler'===$section)delete_option('hm_mahex_v1_profile_samples');update_option(Config::OPTION,$s,false);ActivityLog::write('settings.partial_reset','بخشی از تنظیمات Reset شد.',0,array('section'=>$section));self::redirect('tools','reset'); }
	public static function factoryReset(): void { self::sensitive();if(!current_user_can('manage_options'))wp_die('Forbidden','',array('response'=>403));check_admin_referer('hm_mahex_v1_factory_reset');if('DELETE V1'!==(string)($_POST['confirm']??''))self::redirect('tools','invalid');BackupManager::snapshot('pre_factory_reset');delete_option(Config::OPTION);delete_option(Config::RULES);delete_option(Config::SAVED_FILTERS);delete_option(Config::DASHBOARD_WIDGETS);delete_option('hm_mahex_v1_profile_samples');ActivityLog::write('settings.factory_reset','Factory Reset نسخه 1 انجام شد.');self::redirect('tools','reset'); }
	public static function inventoryAdjust(): void { if(!(Roles::canInventory()||Roles::canManage()))wp_die('Forbidden','',array('response'=>403));check_admin_referer('hm_mahex_v1_inventory_adjust');InventoryLedger::adjust(sanitize_key((string)($_POST['profile_id']??'')),max(0,absint($_POST['new_stock']??0)),sanitize_text_field((string)($_POST['reason']??'manual')),get_current_user_id());self::redirect('inventory','saved'); }
	public static function qualification(): void { self::guard('hm_mahex_v1_qualification');set_transient('hm_mahex_v1_qualification_'.get_current_user_id(),ReleaseQualification::run(),10*MINUTE_IN_SECONDS);self::redirect('diagnostics','qualified'); }
	public static function saveDashboard(): void { self::access();check_admin_referer('hm_mahex_v1_save_dashboard');$allowed=array('orders','profit','inventory','activity','returns','packing');$in=array_map('sanitize_key',(array)($_POST['widgets']??array()));update_option(Config::DASHBOARD_WIDGETS,array_values(array_intersect($allowed,$in)),false);self::back(); }
	public static function saveFilter(): void { self::access();check_admin_referer('hm_mahex_v1_save_filter');$name=substr(sanitize_text_field((string)($_POST['name']??'')),0,50);$query=substr(sanitize_text_field((string)($_POST['query']??'')),0,100);if($name!==''){$v=get_option(Config::SAVED_FILTERS,array());$v=is_array($v)?$v:array();$v[sanitize_key($name)?:'filter-'.count($v)]=array('name'=>$name,'query'=>$query);update_option(Config::SAVED_FILTERS,array_slice($v,-20,null,true),false);}self::back(); }
	public static function bulkEdit(): void { if(!(Roles::canPack()||Roles::canManage()))wp_die('Forbidden','',array('response'=>403));check_admin_referer('hm_mahex_v1_bulk_edit');$ids=array_map('absint',(array)($_POST['order_ids']??array()));if(!$ids&&!empty($_POST['order_ids_text'])){$ids=array_map('absint',preg_split('/[\s,،;]+/u',sanitize_text_field((string)wp_unslash($_POST['order_ids_text'])))?:array());}$ids=array_values(array_filter(array_unique($ids)));$status=sanitize_key((string)($_POST['packing_status']??''));if(!in_array($status,array('','pending','packed','ready_to_ship'),true))$status='';foreach(array_slice($ids,0,200) as $id){$o=wc_get_order($id);if(!$o)continue;if($status!=='')$o->update_meta_data('_hm_mahex_packing_status',$status);$o->save_meta_data();OrderIndex::upsert($o);}ActivityLog::write('orders.bulk_edit','ویرایش گروهی سفارش‌ها انجام شد.',0,array('count'=>count($ids),'status'=>$status));self::back(); }
	public static function reindex(): void { self::guard('hm_mahex_v1_reindex',true);$count=Diagnostics::rebuildOrderIndex(5000);ActivityLog::write('index.rebuilt','ایندکس سفارش‌ها بازسازی شد.',0,array('count'=>$count));self::back(); }


	public static function printEnqueue(): void { if(!Roles::canPrint())wp_die('Forbidden','',array('response'=>403));check_admin_referer('hm_mahex_v1_print_enqueue');$id=absint($_POST['order_id']??0);$type=sanitize_key((string)($_POST['document_type']??'label'));$copies=max(1,min(100,absint($_POST['copies']??1)));if(!$id||!wc_get_order($id))self::redirect('labels','invalid');PrintManager::enqueue($id,$type,$copies,get_current_user_id());self::redirect('labels','saved'); }
	public static function printMark(): void { if(!Roles::canPrint())wp_die('Forbidden','',array('response'=>403));$id=absint($_GET['id']??0);check_admin_referer('hm_mahex_v1_print_mark:'.$id);PrintManager::markPrinted($id);self::redirect('labels','saved'); }

	private static function packageFromOrder(\WC_Order $order): array {$contents=array();foreach($order->get_items() as $id=>$item){$p=$item->get_product();if(!$p)continue;$contents[$id]=array('data'=>$p,'quantity'=>(int)$item->get_quantity());}return array('contents'=>$contents,'contents_cost'=>(float)$order->get_subtotal(),'destination'=>array('state'=>$order->get_shipping_state()?:$order->get_billing_state(),'city'=>$order->get_shipping_city()?:$order->get_billing_city(),'postcode'=>$order->get_shipping_postcode()?:$order->get_billing_postcode()));}
	private static function savedFilters(): void {$v=get_option(Config::SAVED_FILTERS,array());if(!is_array($v)||!$v)return;echo '<p>';foreach($v as $f)echo '<a class="button button-small" href="'.esc_url(add_query_arg(array('page'=>self::PAGE,'tab'=>'overview','s'=>$f['query']??''),admin_url('admin.php'))).'">'.esc_html($f['name']??'فیلتر').'</a> ';echo '</p>';}
	private static function notice(): void {$n=sanitize_key((string)($_GET['hm_notice']??''));$m=array('saved'=>'ذخیره شد.','invalid'=>'اطلاعات معتبر نیست.','imported'=>'تنظیمات وارد شد.','reset'=>'Reset انجام شد.','qualified'=>'تست‌های نسخه اجرا شدند.');if(isset($m[$n]))echo '<div class="notice notice-'.('invalid'===$n?'error':'success').' inline"><p>'.esc_html($m[$n]).'</p></div>';}
	private static function access(): void {if(!(Roles::canManage()||Roles::canSettings()||Roles::canPack()||Roles::canPrint()||Roles::canInventory()||Roles::canReport()))wp_die('Forbidden','',array('response'=>403));}
	private static function cap(): void {if(!(Roles::canManage()||Roles::canSettings()))wp_die('Forbidden','',array('response'=>403));}
	private static function guard(string $nonce,bool $get=false): void {self::cap();check_admin_referer($nonce);}
	private static function sensitive(): void {if(Config::bool('sensitive_lock',true)&&!current_user_can('manage_options'))wp_die('Forbidden','',array('response'=>403));}
	private static function back(): never {$url=wp_get_referer()?:admin_url('admin.php?page='.self::PAGE);wp_safe_redirect(add_query_arg('hm_notice','saved',$url));exit;}
	private static function redirect(string $tab,string $notice): never {wp_safe_redirect(add_query_arg(array('page'=>self::PAGE,'tab'=>$tab,'hm_notice'=>$notice),admin_url('admin.php')));exit;}
	private static function kpi(string $label,int $value): void {echo '<div class="hmv1-card hmv1-kpi"><b>'.esc_html(number_format_i18n($value)).'</b><span>'.esc_html($label).'</span></div>';}
	private static function money(string $label,float $value): void {echo '<div class="hmv1-card hmv1-kpi"><b>'.wp_kses_post(wc_price($value)).'</b><span>'.esc_html($label).'</span></div>';}
	private static function check(string $key,string $label,array $s): void {echo '<label style="display:block;margin:8px"><input type="hidden" name="settings['.esc_attr($key).']" value="0"><input type="checkbox" name="settings['.esc_attr($key).']" value="1" '.checked(!empty($s[$key]),true,false).'> '.esc_html($label).'</label>';}
	private static function num(string $key,string $label,array $s,string $step='1'): void {echo '<label><span>'.esc_html($label).'</span><input type="number" step="'.esc_attr($step).'" name="settings['.esc_attr($key).']" value="'.esc_attr((string)($s[$key]??0)).'"></label>';}
	private static function text(string $key,string $label,array $s): void {echo '<label><span>'.esc_html($label).'</span><input type="text" name="settings['.esc_attr($key).']" value="'.esc_attr((string)($s[$key]??'')).'"></label>';}
	private static function area(string $key,string $label,array $s,string $placeholder=''): void {echo '<label style="display:block;margin:12px 0"><span>'.esc_html($label).'</span><textarea rows="5" class="large-text code" name="settings['.esc_attr($key).']" placeholder="'.esc_attr($placeholder).'">'.esc_textarea((string)($s[$key]??'')).'</textarea></label>';}
	private static function select(string $key,string $label,array $s,array $opts): void {echo '<label><span>'.esc_html($label).'</span><select name="settings['.esc_attr($key).']">';foreach($opts as $v=>$l)echo '<option value="'.esc_attr($v).'" '.selected((string)($s[$key]??''),(string)$v,false).'>'.esc_html($l).'</option>';echo '</select></label>';}
	private static function rawText(string $name,string $label,string $value): void {echo '<label><span>'.esc_html($label).'</span><input name="'.esc_attr($name).'" value="'.esc_attr($value).'"></label>';}
	private static function rawNum(string $name,string $label,string $value,string $step='1'): void {echo '<label><span>'.esc_html($label).'</span><input type="number" step="'.esc_attr($step).'" name="'.esc_attr($name).'" value="'.esc_attr($value).'"></label>';}
	private static function rawSelect(string $name,string $label,string $value,array $opts): void {echo '<label><span>'.esc_html($label).'</span><select name="'.esc_attr($name).'">';foreach($opts as $v=>$l)echo '<option value="'.esc_attr($v).'" '.selected($value,$v,false).'>'.esc_html($l).'</option>';echo '</select></label>';}
}
