<?php

namespace HoseinMomeni\MahexWoo\V25;

final class Finance {
	public static function register(): void {
		add_action('woocommerce_new_order',array(self::class,'syncOrder'),90);add_action('woocommerce_update_order',array(self::class,'syncOrder'),90);add_action('woocommerce_order_status_changed',array(self::class,'syncOrder'),90);
	}
	public static function syncOrder(int $orderId): void {if(!Config::bool('finance_enabled',true))return;$o=wc_get_order($orderId);if(!$o instanceof \WC_Order)return;global $wpdb;$t=$wpdb->prefix.'hm_mahex_v25_ledger';$wpdb->delete($t,array('order_id'=>$orderId,'reference'=>'order-auto'),array('%d','%s'));$a=\HoseinMomeni\MahexWoo\V1\Reports::allocation($o);$center=self::costCenter($o);$entries=array('shipping_revenue'=>(float)$a['shipping_revenue'],'packaging_revenue'=>(float)$a['packaging_revenue'],'carrier_cost'=>(float)$a['carrier_cost'],'operational_cost'=>(float)$a['operational_cost'],'profit'=>(float)$a['profit']);foreach($entries as $type=>$value){if(0.0===$value)continue;$irr=\HoseinMomeni\MahexWoo\Shipping\PricingSettings::from_store_currency(abs($value));if(in_array($type,array('carrier_cost','operational_cost'),true))$irr=-$irr;$wpdb->insert($t,array('order_id'=>$orderId,'entry_type'=>$type,'amount_irr'=>$irr,'cost_center'=>$center,'reference'=>'order-auto','note'=>'ثبت خودکار از سفارش','actor_id'=>0,'created_at'=>current_time('mysql',true)),array('%d','%s','%f','%s','%s','%s','%d','%s'));}}
	public static function add(int $orderId,string $type,float $amountIrr,string $center='',string $note='',string $reference='manual'): int {global $wpdb;$t=$wpdb->prefix.'hm_mahex_v25_ledger';$wpdb->insert($t,array('order_id'=>$orderId,'entry_type'=>sanitize_key($type),'amount_irr'=>$amountIrr,'cost_center'=>substr(sanitize_text_field($center),0,100),'reference'=>substr(sanitize_text_field($reference),0,120),'note'=>sanitize_textarea_field($note),'actor_id'=>get_current_user_id(),'created_at'=>current_time('mysql',true)),array('%d','%s','%f','%s','%s','%s','%d','%s'));return (int)$wpdb->insert_id;}
	public static function ledger(int $days=30,int $limit=500): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_v25_ledger';return $wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) ORDER BY id DESC LIMIT %d",max(1,$days),max(1,min(2000,$limit))),ARRAY_A)?:array();}
	public static function dailySettlement(string $date=''): array {global $wpdb;$date=preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)?$date:gmdate('Y-m-d');$t=$wpdb->prefix.'hm_mahex_v25_ledger';$rows=$wpdb->get_results($wpdb->prepare("SELECT entry_type,COALESCE(SUM(amount_irr),0) amount FROM $t WHERE created_at>=%s AND created_at<DATE_ADD(%s,INTERVAL 1 DAY) GROUP BY entry_type",$date.' 00:00:00',$date.' 00:00:00'),ARRAY_A)?:array();$map=array();foreach($rows as $r)$map[$r['entry_type']]=(float)$r['amount'];$revenue=max(0,(float)($map['shipping_revenue']??0))+max(0,(float)($map['packaging_revenue']??0));$cost=abs(min(0,(float)($map['carrier_cost']??0)))+abs(min(0,(float)($map['operational_cost']??0)));return array('date'=>$date,'entries'=>$map,'revenue_irr'=>$revenue,'cost_irr'=>$cost,'net_irr'=>$revenue-$cost);}
	public static function monthSummary(string $period=''): array {global $wpdb;$period=preg_match('/^\d{4}-\d{2}$/',$period)?$period:gmdate('Y-m');$start=$period.'-01 00:00:00';$end=gmdate('Y-m-d H:i:s',strtotime($period.'-01 +1 month'));$t=$wpdb->prefix.'hm_mahex_v25_ledger';$rows=$wpdb->get_results($wpdb->prepare("SELECT entry_type,COALESCE(SUM(amount_irr),0) amount FROM $t WHERE created_at>=%s AND created_at<%s GROUP BY entry_type",$start,$end),ARRAY_A)?:array();$map=array();foreach($rows as $r)$map[$r['entry_type']]=(float)$r['amount'];$wf=$wpdb->prefix.'hm_mahex_v25_workflows';$returnCost=(float)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(cost_irr),0) FROM $wf WHERE workflow_type='return' AND created_at>=%s AND created_at<%s",$start,$end));$shipping=max(0,(float)($map['shipping_revenue']??0));$packing=max(0,(float)($map['packaging_revenue']??0));$cost=abs(min(0,(float)($map['carrier_cost']??0)))+abs(min(0,(float)($map['operational_cost']??0)))+$returnCost;$budget=Config::int('monthly_budget_irr',0,0,2000000000000);return array('period'=>$period,'shipping_revenue'=>$shipping,'packaging_revenue'=>$packing,'total_cost'=>$cost,'return_cost'=>$returnCost,'profit'=>$shipping+$packing-$cost,'budget_irr'=>$budget,'budget_variance'=>$budget>0?$budget-$cost:0);}
	public static function closeMonth(string $period=''): bool {$s=self::monthSummary($period);global $wpdb;return false!==$wpdb->replace($wpdb->prefix.'hm_mahex_v25_closings',array('period_key'=>$s['period'],'budget_irr'=>$s['budget_irr'],'shipping_revenue'=>$s['shipping_revenue'],'packaging_revenue'=>$s['packaging_revenue'],'total_cost'=>$s['total_cost'],'return_cost'=>$s['return_cost'],'profit'=>$s['profit'],'closed_by'=>get_current_user_id(),'closed_at'=>current_time('mysql',true),'context'=>wp_json_encode($s,JSON_UNESCAPED_UNICODE)),array('%s','%f','%f','%f','%f','%f','%f','%d','%s','%s'));}
	public static function closings(int $limit=24): array {global $wpdb;return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}hm_mahex_v25_closings ORDER BY period_key DESC LIMIT %d",max(1,min(120,$limit))),ARRAY_A)?:array();}
	public static function costCenters(int $days=90): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_v25_ledger';return $wpdb->get_results($wpdb->prepare("SELECT cost_center,COUNT(DISTINCT order_id) orders,SUM(CASE WHEN amount_irr>0 THEN amount_irr ELSE 0 END) revenue,SUM(CASE WHEN amount_irr<0 THEN -amount_irr ELSE 0 END) cost,SUM(amount_irr) net FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) GROUP BY cost_center ORDER BY net DESC",max(1,$days)),ARRAY_A)?:array();}
	private static function costCenter(\WC_Order $o): string {$warehouse=(string)$o->get_meta('_hm_mahex_warehouse_id',true);if($warehouse)return 'warehouse:'.$warehouse;$items=$o->get_items();foreach($items as $i){$p=$i->get_product();if(!$p)continue;$cats=wp_get_post_terms($p->get_id(),'product_cat',array('fields'=>'slugs'));if($cats)return 'category:'.(string)$cats[0];}return 'default';}
}
