<?php

namespace HoseinMomeni\MahexWoo\V25;

final class Intelligence {
	public static function overview(): array {
		return array(
			'advisor'=>self::shippingAdvisor(),'losses'=>self::losses(),'rule_suggestions'=>self::ruleSuggestions(),'rule_conflicts'=>self::ruleConflicts(),
			'packaging_forecast'=>self::packagingForecast(),'profit_forecast'=>self::profitForecast(),'anomalies'=>self::anomalies(),'duplicates'=>self::duplicateShipments(),
			'cities'=>self::cityScores(),'products'=>self::productScores(),'customers'=>self::customerScores(),
		);
	}
	public static function shippingAdvisor(): array {
		$loss=self::losses();$forecast=self::profitForecast();$pack=self::packagingForecast();$out=array();
		if(($loss['count']??0)>0)$out[]=array('severity'=>'critical','title'=>'کرایه‌های زیان‌ده','message'=>sprintf('%d سفارش در بازه تحلیل سود منفی داشته‌اند.',(int)$loss['count']),'action'=>'حداقل کرایه یا Margin را افزایش دهید.');
		foreach(array_slice(self::ruleSuggestions(),0,5) as $s)$out[]=array('severity'=>'warning','title'=>'پیشنهاد Rule: '.$s['name'],'message'=>$s['reason'],'action'=>'پیشنهاد را در شبیه‌ساز بررسی کنید.','suggestion'=>$s);
		foreach($pack as $p)if(!empty($p['reorder']))$out[]=array('severity'=>'warning','title'=>'تأمین بسته‌بندی','message'=>sprintf('%s: موجودی %d، مصرف پیش‌بینی‌شده %d.',(string)$p['name'],(int)$p['stock'],(int)$p['forecast_qty']),'action'=>'خرید مجدد پیشنهاد می‌شود.');
		if(($forecast['forecast_profit']??0)<0)$out[]=array('severity'=>'critical','title'=>'پیش‌بینی سود منفی','message'=>'بر اساس روند اخیر، سود ارسال دوره بعد منفی پیش‌بینی می‌شود.','action'=>'نرخ و هزینه بسته‌بندی بازبینی شود.');
		return $out;
	}
	public static function losses(int $days=90): array {
		global $wpdb;$t=$wpdb->prefix.'hm_mahex_order_index';$row=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) cnt,COALESCE(SUM(profit),0) loss,COALESCE(AVG(profit),0) avg_profit FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) AND profit<0",max(1,$days)),ARRAY_A)?:array();
		$worst=$wpdb->get_results($wpdb->prepare("SELECT order_id,province,city,shipping_total,packaging_total,carrier_cost,profit FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) AND profit<0 ORDER BY profit ASC LIMIT 20",max(1,$days)),ARRAY_A)?:array();
		return array('count'=>(int)($row['cnt']??0),'loss'=>(float)($row['loss']??0),'avg_profit'=>(float)($row['avg_profit']??0),'worst'=>$worst);
	}
	public static function ruleSuggestions(): array {
		global $wpdb;$t=$wpdb->prefix.'hm_mahex_order_index';$rows=$wpdb->get_results("SELECT province,city,COUNT(*) orders,AVG(shipping_total) avg_shipping,AVG(carrier_cost) avg_cost,SUM(profit) profit FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 90 DAY) GROUP BY province,city HAVING COUNT(*)>=3 ORDER BY profit ASC LIMIT 30",ARRAY_A)?:array();$out=array();
		foreach($rows as $r){$profit=(float)$r['profit'];$avgCost=(float)$r['avg_cost'];$avgShip=(float)$r['avg_shipping'];if($profit>=0||$avgCost<=0)continue;$deltaIrr=\HoseinMomeni\MahexWoo\Shipping\PricingSettings::from_store_currency(max(0,$avgCost-$avgShip));$needed=max(1000,(int)ceil($deltaIrr*1.12/1000)*1000);$out[]=array('id'=>'v25-'.substr(md5((string)$r['province'].'|'.$r['city']),0,12),'name'=>'جبران زیان '.$r['city'],'province'=>(string)$r['province'],'city'=>(string)$r['city'],'mode'=>'surcharge','amount'=>$needed,'priority'=>50,'reason'=>sprintf('%d سفارش این مقصد جمعاً %s زیان داشته‌اند.',(int)$r['orders'],number_format_i18n(abs($profit))));}
		return $out;
	}
	public static function applySuggestedRule(string $id): bool { foreach(self::ruleSuggestions() as $s){if($s['id']!==$id)continue;$rules=\HoseinMomeni\MahexWoo\V1\RuleEngine::rules();$rules[]=array('id'=>$s['id'],'name'=>$s['name'],'active'=>true,'priority'=>$s['priority'],'logic'=>'AND','stop'=>false,'mode'=>$s['mode'],'amount'=>$s['amount'],'province'=>$s['province'],'city'=>$s['city'],'min_weight_g'=>0,'max_weight_g'=>0,'min_qty'=>0,'max_qty'=>0,'min_cart_irr'=>0,'max_cart_irr'=>0,'categories'=>array(),'shipping_classes'=>array(),'brands'=>array());update_option(\HoseinMomeni\MahexWoo\V1\Config::RULES,$rules,false);if(class_exists('\HoseinMomeni\MahexWoo\V2\RateCache'))\HoseinMomeni\MahexWoo\V2\RateCache::invalidate();return true;}return false; }
	public static function ruleConflicts(): array {
		$rules=\HoseinMomeni\MahexWoo\V1\RuleEngine::rules();$out=array();$n=count($rules);for($i=0;$i<$n;$i++)for($j=$i+1;$j<$n;$j++){$a=$rules[$i];$b=$rules[$j];if(empty($a['active'])||empty($b['active']))continue;$sameProvince=self::sameOrEmpty($a['province']??'',$b['province']??'');$sameCity=self::sameOrEmpty($a['city']??'',$b['city']??'');$overlap=self::rangesOverlap((int)($a['min_weight_g']??0),(int)($a['max_weight_g']??0),(int)($b['min_weight_g']??0),(int)($b['max_weight_g']??0));if($sameProvince&&$sameCity&&$overlap)$out[]=array('a'=>(string)($a['name']??$a['id']??''),'b'=>(string)($b['name']??$b['id']??''),'severity'=>(!empty($a['stop'])||!empty($b['stop']))?'high':'medium','reason'=>'شرایط مقصد/وزن هم‌پوشان است و ممکن است هر دو Rule روی یک سفارش اجرا شوند.');}
		return array_slice($out,0,100);
	}
	public static function whatIf(float $percent=10,int $days=90): array {$rows=Stats::indexed($days);$before=0.0;$after=0.0;$lossBefore=0;$lossAfter=0;foreach($rows as $r){$ship=(float)$r['shipping_total'];$pack=(float)$r['packaging_total'];$cost=(float)$r['carrier_cost'];$p=$ship+$pack-$cost;$p2=$ship*(1+$percent/100)+$pack-$cost;$before+=$p;$after+=$p2;if($p<0)$lossBefore++;if($p2<0)$lossAfter++;}return array('percent'=>$percent,'orders'=>count($rows),'profit_before'=>$before,'profit_after'=>$after,'delta'=>$after-$before,'loss_orders_before'=>$lossBefore,'loss_orders_after'=>$lossAfter);}
	public static function simulateSuggestion(array $s,int $days=90): array {$rows=Stats::indexed($days);$before=0.0;$after=0.0;$matched=0;foreach($rows as $r){$p=(float)$r['profit'];$before+=$p;$match=(!$s['province']||self::norm((string)$r['province'])===self::norm((string)$s['province']))&&(!$s['city']||str_contains(self::norm((string)$r['city']),self::norm((string)$s['city'])));if($match){$p+=\HoseinMomeni\MahexWoo\Shipping\PricingSettings::to_store_currency((float)$s['amount']);$matched++;}$after+=$p;}return array('matched'=>$matched,'profit_before'=>$before,'profit_after'=>$after,'delta'=>$after-$before);}
	public static function packagingForecast(): array {$cons=\HoseinMomeni\MahexWoo\V1\InventoryLedger::consumptionReport(30);$profiles=(array)get_option('hm_mahex_packaging_profiles',array());$days=Config::int('forecast_days',14,3,90);$out=array();foreach($profiles as $id=>$p){if(!is_array($p))continue;$used30=0;foreach($cons as $r)if((string)($r['profile_id']??'')===(string)$id)$used30=max(0,(int)($r['qty']??0));$daily=$used30/30;$forecast=(int)ceil($daily*$days);$stock=max(0,(int)($p['stock']??0));$reorder=max(0,$forecast+$forecast/2-$stock);$out[]=array('id'=>(string)$id,'name'=>(string)($p['name']??$id),'stock'=>$stock,'used30'=>$used30,'forecast_qty'=>$forecast,'reorder_qty'=>(int)ceil($reorder),'reorder'=>$stock<$forecast,'days_cover'=>$daily>0?round($stock/$daily,1):999);}
		usort($out,static fn($a,$b)=>($a['days_cover']<=>$b['days_cover']));return $out;}
	public static function packagingEfficiency(array $package): array {$plan=\HoseinMomeni\MahexWoo\V1\PackingEngine::plan($package);$rows=array();foreach($plan['packages'] as $box){$d=(array)$box['dimensions_mm'];$cap=max(1,(int)$d[0]*(int)$d[1]*(int)$d[2]);$used=max(0,(int)($box['content_volume']??0));$eff=min(100,round($used/$cap*100,1));$rows[]=array('profile_id'=>$box['profile_id'],'name'=>$box['profile_name'],'efficiency'=>$eff,'waste'=>round(100-$eff,1),'oversized'=>$eff<25);};return array('packages'=>$rows,'score'=>$rows?round(array_sum(array_column($rows,'efficiency'))/count($rows),1):0);}
	public static function packingCostOptimizer(array $package): array {$plan=\HoseinMomeni\MahexWoo\V1\PackingEngine::plan($package);$eff=self::packagingEfficiency($package);return array('package_count'=>$plan['package_count'],'cost_irr'=>$plan['cost_irr'],'efficiency_score'=>$eff['score'],'oversized_count'=>count(array_filter($eff['packages'],static fn($p)=>!empty($p['oversized']))),'suggestion'=>$eff['score']<40?'پروفایل‌های بسته کوچک‌تر/متنوع‌تر تعریف کنید.':'ترکیب فعلی بسته‌بندی قابل قبول است.');}
	public static function profitForecast(): array {$m=\HoseinMomeni\MahexWoo\V2\DailyMetrics::range(35);if(!$m)return array('forecast_profit'=>0,'forecast_orders'=>0,'trend'=>0);$recent=array_slice($m,-14);$prev=array_slice($m,max(0,count($m)-28),14);$avgProfit=array_sum(array_map(static fn($r)=>(float)$r['profit'],$recent))/max(1,count($recent));$avgOrders=array_sum(array_map(static fn($r)=>(float)$r['orders_count'],$recent))/max(1,count($recent));$prevProfit=$prev?array_sum(array_map(static fn($r)=>(float)$r['profit'],$prev))/count($prev):$avgProfit;$days=Config::int('forecast_days',14,3,90);return array('forecast_profit'=>$avgProfit*$days,'forecast_orders'=>(int)round($avgOrders*$days),'trend'=>$prevProfit!=0?round(($avgProfit-$prevProfit)/abs($prevProfit)*100,1):0,'days'=>$days);}
	public static function returnRisk(\WC_Order $order): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_order_index';$phone=(string)$order->get_billing_phone();$city=(string)($order->get_shipping_city()?:$order->get_billing_city());$post=(string)($order->get_shipping_postcode()?:$order->get_billing_postcode());$score=5;$reasons=array();if($phone){$x=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) n,SUM(CASE WHEN shipment_status='returned' THEN 1 ELSE 0 END) r FROM $t WHERE phone=%s",$phone),ARRAY_A);if((int)($x['n']??0)>=2){$rate=(int)($x['r']??0)/max(1,(int)$x['n']);$score+=min(45,(int)round($rate*60));if($rate>.25)$reasons[]='سابقه برگشتی برای این شماره';}}if($city){$x=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) n,SUM(CASE WHEN shipment_status='returned' THEN 1 ELSE 0 END) r FROM $t WHERE city=%s",$city),ARRAY_A);if((int)($x['n']??0)>=5){$rate=(int)($x['r']??0)/max(1,(int)$x['n']);$score+=min(25,(int)round($rate*30));if($rate>.2)$reasons[]='نرخ برگشت بالاتر در این شهر';}}if(strlen(preg_replace('/\D+/','',$post))<10){$score+=10;$reasons[]='کدپستی ناقص';}if(\HoseinMomeni\MahexWoo\Shipping\PricingSettings::from_store_currency((float)$order->get_total())>50000000){$score+=10;$reasons[]='ارزش سفارش بالا';}return array('score'=>min(100,$score),'level'=>$score>=70?'high':($score>=40?'medium':'low'),'reasons'=>$reasons);}
	public static function customerScores(int $limit=30): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_order_index';$rows=$wpdb->get_results($wpdb->prepare("SELECT customer_name,phone,COUNT(*) orders,SUM(profit) profit,SUM(CASE WHEN shipment_status='returned' THEN 1 ELSE 0 END) returns FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 180 DAY) GROUP BY customer_name,phone ORDER BY orders DESC LIMIT %d",max(1,$limit)),ARRAY_A)?:array();foreach($rows as &$r){$returnRate=(int)$r['orders']?((int)$r['returns']/(int)$r['orders']):0;$marginStore=(float)$r['profit']/max(1,(int)$r['orders']);$margin=\HoseinMomeni\MahexWoo\Shipping\PricingSettings::from_store_currency(max(0,$marginStore));$r['score']=max(0,min(100,(int)round(70-50*$returnRate+min(30,$margin/100000))));}unset($r);return $rows;}
	public static function cityScores(int $limit=30): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_order_index';$rows=$wpdb->get_results($wpdb->prepare("SELECT province,city,COUNT(*) orders,SUM(profit) profit,SUM(CASE WHEN shipment_status='returned' THEN 1 ELSE 0 END) returns FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 180 DAY) GROUP BY province,city HAVING COUNT(*)>=2 ORDER BY orders DESC LIMIT %d",max(1,$limit)),ARRAY_A)?:array();foreach($rows as &$r){$rate=(int)$r['returns']/max(1,(int)$r['orders']);$avgStore=(float)$r['profit']/max(1,(int)$r['orders']);$avg=\HoseinMomeni\MahexWoo\Shipping\PricingSettings::from_store_currency(max(0,$avgStore));$r['score']=max(0,min(100,(int)round(65-45*$rate+min(35,$avg/100000))));}unset($r);return $rows;}
	public static function productScores(int $limit=30): array {$rows=Stats::productScores(180,$limit);foreach($rows as &$r){$avgStore=(float)$r['profit']/max(1,(int)$r['qty']);$sign=$avgStore<0?-1:1;$avg=\HoseinMomeni\MahexWoo\Shipping\PricingSettings::from_store_currency(abs($avgStore))*$sign;$r['score']=max(0,min(100,(int)round(50+max(-50,min(50,$avg/100000)))));}unset($r);return $rows;}
	public static function anomalies(int $days=90): array {$rows=Stats::indexed($days);$ships=array_column($rows,'shipping_total');$med=Stats::median($ships);$mult=Config::int('anomaly_multiplier',3,2,20);$out=array();foreach($rows as $r){$ship=(float)$r['shipping_total'];$profit=(float)$r['profit'];if(($med>0&&$ship>$med*$mult)||$profit<-$med){$out[]=array('order_id'=>(int)$r['order_id'],'type'=>$ship>$med*$mult?'shipping_outlier':'loss_outlier','value'=>$ship,'profit'=>$profit,'message'=>'مقدار این سفارش نسبت به الگوی تاریخی غیرعادی است.');}}return array_slice($out,0,100);}
	public static function duplicateShipments(): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_order_index';return $wpdb->get_results("SELECT tracking,COUNT(*) cnt,GROUP_CONCAT(order_id ORDER BY order_id DESC) order_ids FROM $t WHERE tracking<>'' GROUP BY tracking HAVING COUNT(*)>1 ORDER BY cnt DESC LIMIT 100",ARRAY_A)?:array();}
	public static function suspiciousPatterns(): array {$out=array();foreach(self::customerScores(100) as $r)if((int)$r['orders']>=3&&(int)$r['score']<25)$out[]=array('type'=>'customer_pattern','subject'=>(string)$r['phone'],'message'=>'این مشتری نرخ برگشت/سود نامناسبی در تاریخچه ارسال دارد.');foreach(self::anomalies(60) as $r)$out[]=array('type'=>'order_anomaly','subject'=>'#'.$r['order_id'],'message'=>$r['message']);return array_slice($out,0,100);}

	public static function recentPackingAudits(int $limit=20): array {
		$orders=wc_get_orders(array('limit'=>max(1,min(100,$limit)),'status'=>array('processing','completed','on-hold'),'orderby'=>'date','order'=>'DESC'));$out=array();
		foreach($orders as $order){if(!$order instanceof \WC_Order)continue;$package=self::orderPackage($order);if(!$package['contents'])continue;$eff=self::packagingEfficiency($package);$opt=self::packingCostOptimizer($package);$out[]=array('order_id'=>$order->get_id(),'order_number'=>$order->get_order_number(),'score'=>$eff['score'],'package_count'=>$opt['package_count'],'cost_irr'=>$opt['cost_irr'],'oversized_count'=>$opt['oversized_count'],'suggestion'=>$opt['suggestion']);}
		usort($out,static fn($a,$b)=>$a['score']<=>$b['score']);return $out;
	}
	private static function orderPackage(\WC_Order $order): array {$contents=array();$cost=0.0;foreach($order->get_items() as $item){$product=$item->get_product();if(!$product)continue;$q=max(1,(int)$item->get_quantity());$contents['order-item-'.$item->get_id()]=array('data'=>$product,'quantity'=>$q,'line_total'=>(float)$item->get_total());$cost+=(float)$item->get_total();}return array('contents'=>$contents,'contents_cost'=>$cost,'destination'=>array('state'=>$order->get_shipping_state()?:$order->get_billing_state(),'city'=>$order->get_shipping_city()?:$order->get_billing_city(),'postcode'=>$order->get_shipping_postcode()?:$order->get_billing_postcode()));}
	private static function sameOrEmpty(string $a,string $b): bool {$a=self::norm($a);$b=self::norm($b);return $a===''||$b===''||$a===$b;}
	private static function rangesOverlap(int $amin,int $amax,int $bmin,int $bmax): bool {$amax=$amax?:PHP_INT_MAX;$bmax=$bmax?:PHP_INT_MAX;return max($amin,$bmin)<=min($amax,$bmax);}
	private static function norm(string $s): string {return trim(preg_replace('/\s+/u',' ',str_replace(array('ي','ك'),array('ی','ک'),$s))?:$s);}
}
