<?php

namespace HoseinMomeni\MahexWoo\V25;

final class Operations {
	public static function scanInbox(): int {
		global $wpdb;$table=$wpdb->prefix.'hm_mahex_v25_inbox';$seen=array();$now=current_time('mysql',true);$add=static function(array $r)use($wpdb,$table,$now,&$seen):void{$fp=hash('sha256',implode('|',array($r['type']??'issue',$r['order_id']??0,$r['title']??'')));$seen[]=$fp;$wpdb->query($wpdb->prepare("INSERT INTO $table (fingerprint,order_id,item_type,severity,priority,title,details,status,due_at,created_at,updated_at) VALUES (%s,%d,%s,%s,%d,%s,%s,'open',%s,%s,%s) ON DUPLICATE KEY UPDATE severity=VALUES(severity),priority=VALUES(priority),title=VALUES(title),details=VALUES(details),due_at=VALUES(due_at),updated_at=VALUES(updated_at),status=IF(status='resolved','open',status)",$fp,(int)($r['order_id']??0),(string)($r['type']??'issue'),(string)($r['severity']??'warning'),(int)($r['priority']??50),(string)($r['title']??''),(string)($r['details']??''),$r['due_at']??null,$now,$now));};
		foreach(\HoseinMomeni\MahexWoo\V2\ProblemCenter::open(200) as $p)$add(array('type'=>'problem','order_id'=>(int)$p['order_id'],'severity'=>(string)$p['severity'],'priority'=>self::priority((string)$p['severity'],(int)$p['order_id']),'title'=>(string)$p['title'],'details'=>(string)$p['details']));
		foreach(self::slaPredictions(100) as $p)if($p['risk']!=='low')$add(array('type'=>'sla','order_id'=>$p['order_id'],'severity'=>$p['risk']==='high'?'critical':'warning','priority'=>$p['risk']==='high'?95:70,'title'=>'ریسک نقض SLA','details'=>$p['message'],'due_at'=>$p['due_at']));
		foreach(Intelligence::anomalies(60) as $a)$add(array('type'=>'anomaly','order_id'=>$a['order_id'],'severity'=>'warning','priority'=>65,'title'=>'سفارش غیرعادی','details'=>$a['message']));
		foreach(Intelligence::suspiciousPatterns() as $s)if(($s['type']??'')==='customer_pattern')$add(array('type'=>'risk','severity'=>'warning','priority'=>55,'title'=>'الگوی مشتری نیازمند بررسی','details'=>$s['subject'].' — '.$s['message']));
		foreach(wc_get_orders(array('limit'=>100,'status'=>array('processing','on-hold'),'orderby'=>'date','order'=>'DESC')) as $o){if(!$o instanceof \WC_Order)continue;$risk=Intelligence::returnRisk($o);if((int)$risk['score']>=Config::int('return_risk_threshold',65,1,100))$add(array('type'=>'return_risk','order_id'=>$o->get_id(),'severity'=>$risk['level']==='high'?'critical':'warning','priority'=>min(100,50+(int)$risk['score']/2),'title'=>'ریسک برگشت بالا','details'=>'امتیاز '.(int)$risk['score'].' — '.implode('، ',(array)$risk['reasons'])));}
		if($seen){$placeholders=implode(',',array_fill(0,count($seen),'%s'));$wpdb->query($wpdb->prepare("UPDATE $table SET status='resolved',updated_at=%s WHERE status='open' AND fingerprint NOT IN ($placeholders)",array_merge(array($now),$seen)));}
		return count($seen);
	}
	public static function inbox(int $limit=200): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_v25_inbox';return $wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE status='open' ORDER BY priority DESC,created_at ASC LIMIT %d",max(1,min(500,$limit))),ARRAY_A)?:array();}
	public static function resolve(int $id): bool {global $wpdb;return false!==$wpdb->update($wpdb->prefix.'hm_mahex_v25_inbox',array('status'=>'resolved','updated_at'=>current_time('mysql',true)),array('id'=>$id),array('%s','%s'),array('%d'));}
	public static function dailyPlan(): array {$rows=self::inbox(Config::int('daily_plan_limit',50,10,500));$ready=\HoseinMomeni\MahexWoo\V1\Operations::readyOrders(100);$plan=array();foreach($rows as $r)$plan[]=array('priority'=>(int)$r['priority'],'type'=>(string)$r['item_type'],'order_id'=>(int)$r['order_id'],'title'=>(string)$r['title'],'details'=>(string)$r['details']);foreach($ready as $o)if($o instanceof \WC_Order)$plan[]=array('priority'=>60,'type'=>'ready_to_ship','order_id'=>$o->get_id(),'title'=>'آماده ارسال #'.$o->get_order_number(),'details'=>'سفارش بسته‌بندی شده و آماده عملیات ارسال است.');usort($plan,static fn($a,$b)=>$b['priority']<=>$a['priority']);return array_slice($plan,0,Config::int('daily_plan_limit',50,10,500));}
	public static function morningBrief(): array {$m=\HoseinMomeni\MahexWoo\V2\DailyMetrics::range(2);$y=$m?end($m):array();$pack=Intelligence::packagingForecast();return array('open_inbox'=>count(self::inbox(500)),'ready_to_ship'=>count(\HoseinMomeni\MahexWoo\V1\Operations::readyOrders(500)),'yesterday_orders'=>(int)($y['orders_count']??0),'yesterday_profit'=>(float)($y['profit']??0),'low_packaging'=>count(array_filter($pack,static fn($p)=>!empty($p['reorder']))),'high_sla_risk'=>count(array_filter(self::slaPredictions(200),static fn($p)=>$p['risk']==='high')));}
	public static function endOfDay(): array {$m=\HoseinMomeni\MahexWoo\V2\DailyMetrics::rebuildDate(gmdate('Y-m-d'));$perf=\HoseinMomeni\MahexWoo\V2\ShiftManager::performance(1);return array('metrics'=>$m,'operators'=>$perf,'open_inbox'=>count(self::inbox(500)),'completed_workflows'=>count(array_filter(WorkflowManager::recent('',200),static fn($w)=>in_array($w['status'],array('completed','closed'),true))));}
	public static function slaPredictions(int $limit=100): array {$sla=Config::int('sla_hours',48,1,720);$orders=wc_get_orders(array('limit'=>max(1,min(500,$limit)),'status'=>array('processing','on-hold'),'orderby'=>'date','order'=>'ASC'));$out=array();foreach($orders as $o){if(!$o instanceof \WC_Order)continue;$age=Stats::orderAgeHours($o);$packing=(string)$o->get_meta('_hm_mahex_packing_status',true);$remaining=max(0,$sla-$age);$risk=$age>=$sla?'high':($remaining<max(4,$sla*.25)?'medium':'low');if(in_array($packing,array('packed','ready_to_ship'),true)&&$risk==='medium')$risk='low';$due=$o->get_date_created()?gmdate('Y-m-d H:i:s',$o->get_date_created()->getTimestamp()+$sla*HOUR_IN_SECONDS):null;$out[]=array('order_id'=>$o->get_id(),'age_hours'=>round($age,1),'remaining_hours'=>round($remaining,1),'risk'=>$risk,'due_at'=>$due,'message'=>sprintf('سفارش %.1f ساعت از زمان ثبت گذشته و وضعیت بسته‌بندی «%s» است.',$age,$packing?:'نامشخص'));}return $out;}
	public static function operatorWorkload(): array {$open=wc_get_orders(array('limit'=>500,'status'=>array('processing','on-hold'),'return'=>'ids'));$users=get_users(array('role__in'=>array('administrator','shop_manager'),'fields'=>array('ID','display_name')));$perf=\HoseinMomeni\MahexWoo\V2\ShiftManager::performance(30);$map=array();foreach($perf as $p)$map[(int)$p['user_id']]=$p;$out=array();foreach($users as $u){$p=$map[(int)$u->ID]??array();$rate=(float)($p['minutes']??0)>0?(float)($p['packed_orders']??0)/((float)$p['minutes']/60):0;$out[]=array('user_id'=>(int)$u->ID,'name'=>(string)$u->display_name,'packed_30d'=>(int)($p['packed_orders']??0),'errors'=>(int)($p['errors']??0),'orders_per_hour'=>round($rate,1),'suggested_share'=>0);}$capacity=array_sum(array_map(static fn($r)=>max(.5,(float)$r['orders_per_hour']),$out));foreach($out as &$r)$r['suggested_share']=$capacity>0?(int)round(count($open)*max(.5,(float)$r['orders_per_hour'])/$capacity):0;unset($r);return $out;}
	public static function shiftPlan(): array {$work=self::operatorWorkload();$brief=self::morningBrief();$needed=max(1,(int)ceil(($brief['ready_to_ship']+$brief['open_inbox'])/40));usort($work,static fn($a,$b)=>$b['orders_per_hour']<=>$a['orders_per_hour']);return array('recommended_operators'=>min($needed,max(1,count($work))),'operators'=>array_slice($work,0,$needed),'workload'=>$brief['ready_to_ship']+$brief['open_inbox']);}
	public static function packingTimeAnalytics(int $days=30): array {global $wpdb;$t=$wpdb->prefix.'hm_mahex_packing_sessions';$rows=$wpdb->get_results($wpdb->prepare("SELECT actor_id,status,COUNT(*) sessions,AVG(TIMESTAMPDIFF(SECOND,created_at,updated_at))/60 avg_minutes,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) errors FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) GROUP BY actor_id,status",max(1,$days)),ARRAY_A)?:array();return $rows;}
	public static function bottlenecks(): array {$brief=self::morningBrief();$pack=self::packingTimeAnalytics(30);$avg=$pack?array_sum(array_map(static fn($r)=>(float)$r['avg_minutes'],$pack))/count($pack):0;$out=array();if($brief['ready_to_ship']>50)$out[]=array('stage'=>'dispatch','severity'=>'high','message'=>'صف آماده ارسال بزرگ است.');if($brief['open_inbox']>30)$out[]=array('stage'=>'exceptions','severity'=>'high','message'=>'تعداد Exceptionهای باز بالاست.');if($avg>20)$out[]=array('stage'=>'packing','severity'=>'medium','message'=>'میانگین زمان ثبت‌شده بسته‌بندی بالاست.');if($brief['low_packaging']>0)$out[]=array('stage'=>'inventory','severity'=>'medium','message'=>'کمبود بسته‌بندی می‌تواند عملیات را متوقف کند.');return $out;}
	private static function priority(string $severity,int $orderId): int {$p=match($severity){'critical','error'=>95,'warning'=>70,default=>40};if($orderId){$o=wc_get_order($orderId);if($o instanceof \WC_Order){$p+=min(5,(int)floor((float)$o->get_total()/10000000));}}return min(100,$p);}
}
