<?php

namespace HoseinMomeni\MahexWoo\V25;

final class ReportCenter {
	public static function definitions(): array {$r=get_option(Config::REPORTS,array());return is_array($r)?$r:array();}
	public static function saveDefinition(array $raw): string {$id=sanitize_key((string)($raw['id']??''))?:'report-'.strtolower(wp_generate_password(8,false,false));$defs=self::definitions();$defs[$id]=array('id'=>$id,'name'=>substr(sanitize_text_field((string)($raw['name']??'گزارش')),0,100),'dimension'=>in_array(($raw['dimension']??''),array('city','customer','status','cost_center','day'),true)?$raw['dimension']:'city','metric'=>in_array(($raw['metric']??''),array('orders','revenue','profit','cost','returns'),true)?$raw['metric']:'profit','days'=>max(1,min(3650,(int)($raw['days']??30))),'limit'=>max(5,min(200,(int)($raw['limit']??30))),'scheduled'=>!empty($raw['scheduled']));update_option(Config::REPORTS,$defs,false);return $id;}
	public static function run(array $def): array {global $wpdb;$days=max(1,(int)($def['days']??30));$limit=max(5,(int)($def['limit']??30));$dim=(string)($def['dimension']??'city');$metric=(string)($def['metric']??'profit');if($dim==='cost_center')return Finance::costCenters($days);$t=$wpdb->prefix.'hm_mahex_order_index';$group=match($dim){'customer'=>'customer_name,phone','status'=>'shipment_status','day'=>'DATE(created_at)',default=>'province,city'};$select=match($dim){'customer'=>'customer_name,phone','status'=>'shipment_status','day'=>'DATE(created_at) label',default=>'province,city'};$metricSql=match($metric){'orders'=>'COUNT(*)','revenue'=>'SUM(shipping_total+packaging_total)','cost'=>'SUM(carrier_cost)','returns'=>"SUM(CASE WHEN shipment_status='returned' THEN 1 ELSE 0 END)",default=>'SUM(profit)'};return $wpdb->get_results($wpdb->prepare("SELECT $select,COUNT(*) orders,SUM(shipping_total+packaging_total) revenue,SUM(carrier_cost) cost,SUM(profit) profit,SUM(CASE WHEN shipment_status='returned' THEN 1 ELSE 0 END) returns,$metricSql metric_value FROM $t WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) GROUP BY $group ORDER BY metric_value DESC LIMIT %d",$days,$limit),ARRAY_A)?:array();}
	public static function snapshotScheduled(): int {if(!Config::bool('scheduled_reports_enabled',true))return 0;global $wpdb;$count=0;foreach(self::definitions() as $id=>$def){if(empty($def['scheduled']))continue;$rows=self::run($def);$wpdb->insert($wpdb->prefix.'hm_mahex_v25_report_snapshots',array('report_key'=>$id,'title'=>(string)$def['name'],'payload'=>wp_json_encode($rows,JSON_UNESCAPED_UNICODE),'created_at'=>current_time('mysql',true)),array('%s','%s','%s','%s'));$count++;}return $count;}
	public static function snapshots(int $limit=50): array {global $wpdb;return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}hm_mahex_v25_report_snapshots ORDER BY id DESC LIMIT %d",max(1,min(500,$limit))),ARRAY_A)?:array();}
	public static function dashboardWidgets(): array {$v=get_option(Config::DASHBOARD,array('brief','profit','inbox','forecast','packaging'));return is_array($v)?array_values(array_unique(array_map('sanitize_key',$v))):array();}
	public static function saveDashboard(mixed $v): void {$allowed=array('brief','profit','inbox','forecast','packaging','operators','returns','bottlenecks','budget','anomalies');$v=is_array($v)?$v:array();update_option(Config::DASHBOARD,array_values(array_intersect($allowed,array_map('sanitize_key',$v))),false);}
}
