<?php

namespace HoseinMomeni\MahexWoo\Enterprise;

final class Admin {
	private const PAGE='hm-mahex-enterprise';
	public static function register(): void {add_action('admin_menu',array(self::class,'menu'),95);add_action('admin_post_hm_mahex_enterprise_save',array(self::class,'save'));add_action('admin_post_hm_mahex_warehouses_save',array(self::class,'saveWarehouses'));add_action('admin_post_hm_mahex_ndr_save',array(self::class,'saveNdr'));add_action('admin_post_hm_mahex_queue_retry',array(self::class,'retry'));add_action('admin_post_hm_mahex_task_save',array(self::class,'saveTask'));}
	public static function menu(): void {add_submenu_page('hm-mahex','لجستیک Enterprise','لجستیک Enterprise',Roles::MANAGE,self::PAGE,array(self::class,'render'));}
	private static function guard(string $nonce,bool $settings=false): void {if($settings?!Roles::canSettings():!Roles::canManage())wp_die('دسترسی غیرمجاز','',array('response'=>403));check_admin_referer($nonce);}
	public static function render(): void {if(!Roles::canManage())wp_die('دسترسی غیرمجاز');$tab=sanitize_key((string)($_GET['tab']??'settings'));$tabs=array('settings'=>'تنظیمات','warehouses'=>'انبارها','ndr'=>'NDR/تماس','queue'=>'صف','tasks'=>'کارها','audit'=>'Audit Log','health'=>'سلامت');if(!Roles::canSettings()){unset($tabs['settings'],$tabs['warehouses'],$tabs['audit']);if(in_array($tab,array('settings','warehouses','audit'),true))$tab='ndr';}echo '<div class="wrap" dir="rtl"><h1>Mahex Enterprise Logistics</h1><nav class="nav-tab-wrapper">';foreach($tabs as $k=>$v)echo '<a class="nav-tab '.($tab===$k?'nav-tab-active':'').'" href="'.esc_url(admin_url('admin.php?page='.self::PAGE.'&tab='.$k)).'">'.esc_html($v).'</a>';echo '</nav>';self::notice();match($tab){'warehouses'=>self::warehouses(),'ndr'=>self::ndr(),'queue'=>self::queue(),'tasks'=>self::tasks(),'audit'=>self::audit(),'health'=>self::health(),default=>self::settings()};echo '</div>';}
	private static function settings(): void {$s=Config::all();echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_enterprise_save">';wp_nonce_field('hm_mahex_enterprise_save');echo '<table class="form-table">';self::check('enabled','فعال‌سازی لایه Enterprise',$s);self::check('multi_warehouse','Multi-Warehouse و تقسیم بسته‌ها',$s);self::select('service_policy','سیاست انتخاب سرویس',$s,array('balanced'=>'متعادل','cheapest'=>'ارزان‌ترین','fastest'=>'سریع‌ترین'));self::check('service_choices','نمایش سطح‌های سرویس به مشتری',$s);self::area('local_services','سطح‌های سرویس: id|label|SLA days|max weight g|surcharge IRR',$s);self::area('excluded_provinces','استان‌های خارج پوشش',$s);self::area('excluded_cities','شهرهای خارج پوشش',$s);self::num('max_service_weight_g','حداکثر وزن سرویس (گرم)',$s);self::check('fallback_enabled','نمایش نرخ جایگزین اگر ماهکس در دسترس نبود',$s);self::text('fallback_label','عنوان نرخ جایگزین',$s);self::num('fallback_cost_irr','هزینه نرخ جایگزین (ریال)',$s);self::num('sla_default_days','SLA پیش‌فرض (روز کاری)',$s);self::area('sla_rules','SLA: استان|شهر|روز',$s);self::area('holidays','تعطیلات YYYY-MM-DD',$s);self::text('weekend_days','روزهای تعطیل هفته (ISO 1..7)',$s);self::text('cutoff_time','Cut-off HH:MM',$s);self::check('require_postcode','کدپستی الزامی',$s);self::check('validate_postcode','اعتبارسنجی ساختار کدپستی',$s);self::check('require_phone','موبایل معتبر الزامی',$s);self::check('require_address2','جزئیات آدرس/واحد الزامی',$s);self::check('require_plate','وجود پلاک/عدد در نشانی الزامی',$s);self::area('city_aliases','نام مستعار شهر: ورودی|نام استاندارد',$s);self::area('city_province_rules','تطابق شهر/استان: شهر|استان',$s);self::area('blacklist_phones','Blacklist موبایل',$s);self::area('blacklist_postcodes','Blacklist پیشوند کدپستی',$s);self::area('whitelist_phones','Whitelist موبایل',$s);self::num('risk_hold_threshold','آستانه ریسک برای بازبینی',$s);self::check('queue_enabled','صف پایدار فعال',$s);self::num('queue_max_attempts','حداکثر Retry',$s);self::check('health_email_enabled','ارسال هشدار سلامت با ایمیل',$s);self::text('health_email','ایمیل هشدار',$s,'email');self::check('operator_role_enabled','نقش اپراتور ماهکس فعال',$s);echo '</table>';submit_button('ذخیره تنظیمات لجستیک محلی');echo '</form><p class="description">نسخه 1.0.0 همه عملیات حمل را به‌صورت محلی داخل وردپرس و ووکامرس مدیریت می‌کند.</p>';}
	private static function warehouses(): void {$rows=WarehouseRepository::all();echo '<p>هر انبار می‌تواند پوشش استان/شهر، مختصات و زمان آماده‌سازی مستقل داشته باشد. نزدیک‌ترین انبار واجد شرایط خودکار انتخاب می‌شود.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_warehouses_save">';wp_nonce_field('hm_mahex_warehouses_save');echo '<table class="widefat striped"><thead><tr><th>فعال</th><th>ID / نام</th><th>استان / شهر</th><th>نشانی / کدپستی</th><th>مختصات</th><th>Prep</th><th>پوشش</th></tr></thead><tbody>';for($i=0;$i<max(5,count($rows)+2);$i++){$r=array_values($rows)[$i]??array();echo '<tr><td><input type="checkbox" name="warehouses['.$i.'][enabled]" value="1" '.checked(!empty($r['enabled']),true,false).'></td><td><input name="warehouses['.$i.'][id]" value="'.esc_attr((string)($r['id']??'')).'" placeholder="tehran"><br><input name="warehouses['.$i.'][name]" value="'.esc_attr((string)($r['name']??'')).'" placeholder="انبار تهران"></td><td><input name="warehouses['.$i.'][province]" value="'.esc_attr((string)($r['province']??'')).'"><br><input name="warehouses['.$i.'][city]" value="'.esc_attr((string)($r['city']??'')).'"></td><td><textarea name="warehouses['.$i.'][address]" placeholder="نشانی انبار">'.esc_textarea((string)($r['address']??'')).'</textarea><br><input name="warehouses['.$i.'][postcode]" value="'.esc_attr((string)($r['postcode']??'')).'" placeholder="کدپستی"></td><td><input size="8" name="warehouses['.$i.'][lat]" value="'.esc_attr((string)($r['lat']??'')).'"> <input size="8" name="warehouses['.$i.'][lng]" value="'.esc_attr((string)($r['lng']??'')).'"></td><td><input type="number" min="0" max="30" name="warehouses['.$i.'][prep_days]" value="'.esc_attr((string)($r['prep_days']??0)).'" style="width:70px"></td><td><textarea name="warehouses['.$i.'][coverage_provinces]" placeholder="استان‌ها">'.esc_textarea(implode(',',(array)($r['coverage_provinces']??array()))).'</textarea><br><textarea name="warehouses['.$i.'][coverage_cities]" placeholder="شهرها">'.esc_textarea(implode(',',(array)($r['coverage_cities']??array()))).'</textarea></td></tr>';}echo '</tbody></table>';submit_button('ذخیره انبارها');echo '</form>';}
	private static function ndr(): void {$orders=NdrManager::orders();echo '<table class="widefat striped"><thead><tr><th>سفارش</th><th>مشتری</th><th>ریسک</th><th>NDR</th><th>پیگیری</th></tr></thead><tbody>';foreach($orders as $o){$n=$o->get_meta('_hm_mahex_ndr',true);$n=is_array($n)?$n:array();echo '<tr><td><a href="'.esc_url($o->get_edit_order_url()).'">#'.esc_html($o->get_order_number()).'</a></td><td>'.esc_html($o->get_formatted_billing_full_name()).'</td><td>'.esc_html((string)$o->get_meta('_hm_mahex_risk_score',true)).'</td><td>'.esc_html((string)($n['reason']??'unknown')).'<br><small>'.esc_html((string)($n['suggestion']??'')).'</small></td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="hm_mahex_ndr_save"><input type="hidden" name="order_id" value="'.$o->get_id().'">';wp_nonce_field('hm_mahex_ndr_save_'.$o->get_id());echo '<select name="reason"><option value="recipient_absent">گیرنده حاضر نبود</option><option value="bad_address">آدرس مشکل‌دار</option><option value="phone_unreachable">عدم پاسخ تلفن</option><option value="refused">عدم پذیرش</option><option value="damaged">خسارت</option><option value="payment_issue">پرداخت</option><option value="carrier_issue">حمل‌کننده</option><option value="other">سایر</option></select><input name="contact_outcome" placeholder="نتیجه تماس"><input type="date" name="follow_up_date"><select name="status"><option value="open">باز</option><option value="retry">ارسال مجدد</option><option value="resolved">حل شد</option><option value="returned">بازگشت</option></select><button class="button">ثبت</button></form></td></tr>';}echo '</tbody></table>';}
	private static function queue(): void {$counts=QueueStore::counts();echo '<p>Pending: '.(int)($counts['pending']??0).' | Running: '.(int)($counts['running']??0).' | Failed/Dead: '.(int)($counts['dead']??0).' | Completed: '.(int)($counts['completed']??0).'</p><table class="widefat striped"><thead><tr><th>ID</th><th>نوع</th><th>اولویت</th><th>وضعیت</th><th>تلاش</th><th>خطا</th><th></th></tr></thead><tbody>';foreach(QueueStore::recent(150) as $r){echo '<tr><td>'.(int)$r['id'].'</td><td>'.esc_html($r['type']).'</td><td>'.(int)$r['priority'].'</td><td>'.esc_html($r['status']).'</td><td>'.(int)$r['attempts'].'/'.(int)$r['max_attempts'].'</td><td>'.esc_html((string)$r['last_error']).'</td><td>';if('dead'===$r['status'])echo '<a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hm_mahex_queue_retry&job_id='.(int)$r['id']),'hm_mahex_queue_retry_'.(int)$r['id'])).'">Retry</a>';echo '</td></tr>';}echo '</tbody></table>';}
	private static function tasks(): void {echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="margin:16px 0"><input type="hidden" name="action" value="hm_mahex_task_save">';wp_nonce_field('hm_mahex_task_save');echo '<input type="number" name="order_id" placeholder="Order ID"> <input name="title" placeholder="عنوان کار" required> <input type="date" name="due"> <button class="button button-primary">ساخت Task</button></form><table class="widefat striped"><thead><tr><th>ID</th><th>سفارش</th><th>عنوان</th><th>وضعیت</th><th>موعد</th></tr></thead><tbody>';foreach(TaskManager::recent(150) as $r)echo '<tr><td>'.(int)$r['id'].'</td><td>'.(int)$r['order_id'].'</td><td>'.esc_html($r['title']).'</td><td>'.esc_html($r['status']).'</td><td>'.esc_html((string)$r['due_at']).'</td></tr>';echo '</tbody></table>';}
	private static function audit(): void {echo '<table class="widefat striped"><thead><tr><th>زمان</th><th>کاربر</th><th>عمل</th><th>شیء</th><th>نتیجه</th><th>Context</th></tr></thead><tbody>';foreach(AuditLog::recent(150) as $r){$u=get_userdata((int)$r['actor_id']);echo '<tr><td>'.esc_html($r['created_at']).'</td><td>'.esc_html($u?$u->display_name:'سیستم').'</td><td>'.esc_html($r['action']).'</td><td>'.esc_html($r['object_type'].':'.$r['object_id']).'</td><td>'.esc_html($r['outcome']).'</td><td><code>'.esc_html((string)$r['context']).'</code></td></tr>';}echo '</tbody></table>';}
	private static function health(): void {$issues=HealthMonitor::issues();echo '<h2>سلامت سیستم</h2>';if(!$issues)echo '<div class="notice notice-success inline"><p>مشکل شناخته‌شده‌ای دیده نشد.</p></div>';else echo '<ul><li>'.implode('</li><li>',array_map('esc_html',$issues)).'</li></ul><p>نسخه 1.0.0 در حالت محلی اجرا می‌شود.</p>';}
	public static function save(): void {self::guard('hm_mahex_enterprise_save',true);$in=isset($_POST['settings'])&&is_array($_POST['settings'])?wp_unslash($_POST['settings']):array();update_option(Config::OPTION,Config::sanitize($in),false);Roles::install();self::redirect('settings','saved');}
	public static function saveWarehouses(): void {self::guard('hm_mahex_warehouses_save',true);$rows=isset($_POST['warehouses'])&&is_array($_POST['warehouses'])?wp_unslash($_POST['warehouses']):array();update_option(Config::WAREHOUSES,WarehouseRepository::sanitizeRows($rows),false);self::redirect('warehouses','saved');}
	public static function saveNdr(): void {$id=absint($_POST['order_id']??0);self::guard('hm_mahex_ndr_save_'.$id);$o=wc_get_order($id);if($o)NdrManager::update($o,wp_unslash($_POST));self::redirect('ndr','saved');}
	public static function retry(): void {$id=absint($_GET['job_id']??0);self::guard('hm_mahex_queue_retry_'.$id);QueueStore::retry($id);AuditLog::write('queue.retry','job',$id);self::redirect('queue','saved');}
	public static function saveTask(): void {self::guard('hm_mahex_task_save');$date=(string)($_POST['due']??'');$due=preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)?$date.' 09:00:00':null;TaskManager::create(absint($_POST['order_id']??0),sanitize_text_field((string)($_POST['title']??'')),'',$due,get_current_user_id());self::redirect('tasks','saved');}
	private static function redirect(string $tab,string $n): never {wp_safe_redirect(add_query_arg(array('page'=>self::PAGE,'tab'=>$tab,'hm_notice'=>$n),admin_url('admin.php')));exit;}
	private static function notice(): void {if('saved'===sanitize_key((string)($_GET['hm_notice']??'')))echo '<div class="notice notice-success inline"><p>ذخیره شد.</p></div>';}
	private static function row(string $html): void {echo '<tr><th scope="row">'.$html.'</th></tr>';}
	private static function check(string $k,string $l,array $s): void {echo '<tr><th>'.esc_html($l).'</th><td><label><input type="checkbox" name="settings['.esc_attr($k).']" value="1" '.checked(!empty($s[$k]),true,false).'> فعال</label></td></tr>';}
	private static function text(string $k,string $l,array $s,string $type='text'): void {echo '<tr><th>'.esc_html($l).'</th><td><input class="regular-text" type="'.esc_attr($type).'" name="settings['.esc_attr($k).']" value="'.esc_attr((string)($s[$k]??'')).'"></td></tr>';}
	private static function password(string $k,string $l,array $s): void {echo '<tr><th>'.esc_html($l).'</th><td><input class="regular-text" type="password" name="settings['.esc_attr($k).']" value="'.(!empty($s[$k])?'********':'').'" autocomplete="new-password"></td></tr>';}
	private static function num(string $k,string $l,array $s): void {echo '<tr><th>'.esc_html($l).'</th><td><input type="number" min="0" name="settings['.esc_attr($k).']" value="'.esc_attr((string)($s[$k]??0)).'"></td></tr>';}
	private static function area(string $k,string $l,array $s): void {echo '<tr><th>'.esc_html($l).'</th><td><textarea class="large-text code" rows="4" name="settings['.esc_attr($k).']">'.esc_textarea((string)($s[$k]??'')).'</textarea></td></tr>';}
	private static function select(string $k,string $l,array $s,array $opts): void {echo '<tr><th>'.esc_html($l).'</th><td><select name="settings['.esc_attr($k).']">';foreach($opts as $v=>$t)echo '<option value="'.esc_attr($v).'" '.selected((string)($s[$k]??''),$v,false).'>'.esc_html($t).'</option>';echo '</select></td></tr>';}
}
