<?php

namespace HoseinMomeni\MahexWoo\Enterprise;

use HoseinMomeni\MahexWoo\Shipments\Shipment;

final class NdrManager {
	public static function register(): void {add_action('hm_mahex_shipment_saved',array(self::class,'shipmentSaved'),10,3);}
	public static function shipmentSaved(\WC_Order $order,Shipment $shipment,string $action): void {if(!in_array($shipment->status,array('failed','returned'),true))return;$current=$order->get_meta('_hm_mahex_ndr',true);if(is_array($current)&&!empty($current['opened_at']))return;$ndr=array('status'=>'open','reason'=>'unknown','suggestion'=>'تماس با مشتری و بررسی آدرس/زمان تحویل','opened_at'=>gmdate(DATE_ATOM),'last_contact_at'=>'','contact_outcome'=>'','follow_up_date'=>'','notes'=>'');$order->update_meta_data('_hm_mahex_ndr',$ndr);$order->save_meta_data();TaskManager::create($order->get_id(),'پیگیری مرسوله تحویل‌نشده','وضعیت مرسوله: '.$shipment->status,gmdate('Y-m-d H:i:s',time()+86400));AuditLog::write('ndr.open','order',$order->get_id());}
	public static function update(\WC_Order $order,array $input): void {$ndr=$order->get_meta('_hm_mahex_ndr',true);$ndr=is_array($ndr)?$ndr:array();$reason=sanitize_key((string)($input['reason']??'unknown'));$allowed=array('unknown','recipient_absent','bad_address','phone_unreachable','refused','damaged','payment_issue','carrier_issue','other');if(!in_array($reason,$allowed,true))$reason='unknown';$ndr['status']=in_array((string)($input['status']??''),array('open','retry','resolved','returned'),true)?(string)$input['status']:'open';$ndr['reason']=$reason;$ndr['suggestion']=self::suggestion($reason);$ndr['last_contact_at']=gmdate(DATE_ATOM);$ndr['contact_outcome']=sanitize_text_field((string)($input['contact_outcome']??''));$date=(string)($input['follow_up_date']??'');$ndr['follow_up_date']=preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)?$date:'';$ndr['notes']=sanitize_textarea_field((string)($input['notes']??''));$order->update_meta_data('_hm_mahex_ndr',$ndr);$order->save_meta_data();if(''!==$ndr['follow_up_date']&&'resolved'!==$ndr['status'])TaskManager::create($order->get_id(),'پیگیری مجدد NDR',$ndr['contact_outcome'],$ndr['follow_up_date'].' 09:00:00',get_current_user_id());AuditLog::write('ndr.update','order',$order->get_id());}
	public static function suggestion(string $r): string {return match($r){'recipient_absent'=>'هماهنگی زمان تحویل مجدد با گیرنده','bad_address'=>'اصلاح آدرس و درخواست ارسال مجدد','phone_unreachable'=>'تماس از کانال جایگزین و تأیید شماره','refused'=>'بررسی دلیل عدم پذیرش و تصمیم بازگشت/ارسال مجدد','damaged'=>'ثبت خسارت و بررسی بیمه/جایگزینی','payment_issue'=>'تعیین روش پرداخت جایگزین','carrier_issue'=>'پیگیری با اپراتور حمل و زمان‌بندی مجدد',default=>'تماس با مشتری و بررسی آدرس/زمان تحویل'};}
	public static function orders(int $limit=100): array {$orders=wc_get_orders(array('limit'=>max(1,min(200,$limit)),'orderby'=>'date','order'=>'DESC','status'=>array_keys(wc_get_order_statuses()),'meta_query'=>array(array('key'=>'_hm_mahex_ndr','compare'=>'EXISTS'))));return array_values(array_filter($orders,static fn($o)=>$o instanceof \WC_Order));}
}
